<script lang="ts">
 import {getContext,onDestroy} from 'svelte';
 import * as Card from '$lib/components/ui/card';
 import {Button} from '$lib/components/ui/button';
 import {Checkbox} from '$lib/components/ui/checkbox';
 import {Input} from '$lib/components/ui/input';
 import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
 import DatePicker from '$lib/components/forms/date-picker.svelte';
 import ScrollRegion from '$lib/components/shared/scroll-region.svelte';
 import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';
 import {PRIVACY_CONTEXT,type PrivacyState} from '$lib/privacy';
 import {formatDate} from '$lib/dates';
 import {formatExactAmount} from '$lib/ux/amount';
 let {workspaceId,kind,currency,timezone='Asia/Jakarta'}:{workspaceId:string;kind:string;currency:string;timezone?:string}=$props();
 const ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),privacy=getContext<PrivacyState>(PRIVACY_CONTEXT);
 const t=(en:string,id:string)=>ui.locale==='id'?id:en;
 let reportType=$state('analytics'),preset=$state('this_month'),basis=$state('cash'),comparison=$state('none'),groupBy=$state('day'),sort=$state('date');
 let from=$state(''),through=$state(''),reportName=$state(''),accountIds:string[]=$state([]),categoryIds:string[]=$state([]),accounts:any[]=$state([]),categories:any[]=$state([]),tags:any[]=$state([]),tagIds:string[]=$state([]);
 let definitions:any[]=$state([]),schedules:any[]=$state([]),deliveries:any[]=$state([]),selected=$state(''),selectedVersion=$state(0),run:any=$state(null),rows:any[]=$state([]),section=$state('grouped'),cursor:number|null=$state(null);
 let busy=$state(false),error=$state(''),notice=$state(''),cadence=$state('monthly'),sendTime=$state('09:00'),format=$state('pdf'),consent=$state(false),download=$state('');
 let editingSchedule=$state(''),editingVersion=$state(0);
 let controller=new AbortController(),generation=0;
 const uid=$props.id();
 const types=$derived([{value:'analytics',label:t('Transaction analytics','Analitik transaksi')},{value:'cashflow',label:t('Cashflow statement','Laporan arus kas')},{value:'budget_actual',label:t('Budget vs actual','Anggaran vs aktual')},...(kind==='business'?[{value:'profit_loss',label:t('Profit and loss','Laba rugi')},{value:'balance_sheet',label:t('Balance sheet','Neraca')},{value:'tax',label:t('Tax evidence','Bukti pajak')}]:[])]);
 const business=$derived(['profit_loss','balance_sheet','tax'].includes(reportType));
 const sections=$derived(reportType==='analytics'?['grouped','activity','comparison']:reportType==='cashflow'?['cashflow']:reportType==='budget_actual'?['budget_actual']:reportType==='tax'?['tax_sales','tax_purchases','comparison']:['ledger','comparison']);
 function definition(){if(preset==='custom'&&(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(through)))throw new Error(t('Choose both start and end dates.','Pilih tanggal mulai dan akhir.'));const end=new Date(through+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+1);return {version:1,reportType,preset,currency,basis:reportType==='tax'?'accrual':basis,comparison:['cashflow','budget_actual'].includes(reportType)?'none':comparison,groupBy,sort,accountIds:reportType==='analytics'?accountIds:[],categoryIds:reportType==='analytics'?categoryIds:[],tagIds:reportType==='analytics'?tagIds:[],...(preset==='custom'?{from,toExclusive:end.toISOString().slice(0,10)}:{})};}
 async function api(path:string,method='GET',body?:unknown){const response=await fetch(`/api/workspaces/${workspaceId}/reports/${path}`,{method,signal:controller.signal,headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.message??t('Request failed. Try again.','Permintaan gagal. Coba lagi.'));return result;}
 async function perform(action:()=>Promise<void>){if(busy)return;busy=true;error='';notice='';try{await action();}catch(e){if((e as Error).name!=='AbortError')error=(e as Error).message;}finally{busy=false;}}
 async function refresh(){const [saved,scheduled]=await Promise.all([api('definitions'),api('schedules')]);definitions=saved.items;schedules=scheduled.items;deliveries=scheduled.deliveries;}
 $effect(()=>{const ws=workspaceId;controller.abort();controller=new AbortController();generation++;run=null;rows=[];selected='';definitions=[];schedules=[];deliveries=[];download='';accountIds=[];categoryIds=[];tagIds=[];busy=false;reportType='analytics';editingSchedule='';if(ws){void refresh().catch(e=>{if(e.name!=='AbortError')error=e.message;});const signal=controller.signal;void Promise.all([fetch(`/api/workspaces/${ws}/accounts`,{signal}),fetch(`/api/workspaces/${ws}/categories`,{signal}),fetch(`/api/workspaces/${ws}/tags`,{signal})]).then(async([a,c,g])=>{if(signal.aborted)return;const av=await a.json(),cv=await c.json(),gv=await g.json();if(!signal.aborted){accounts=av.items??av.accounts??[];categories=cv.items??cv.categories??[];tags=gv.items??[];}}).catch(()=>{});}});
 onDestroy(()=>controller.abort());
 async function pause(){await new Promise<void>((resolve,reject)=>{const signal=controller.signal;const abort=()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));};const timer=setTimeout(()=>{signal.removeEventListener('abort',abort);resolve();},1200);signal.addEventListener('abort',abort,{once:true});});}
 async function preview(){await perform(async()=>{download='';const requestGeneration=generation;const created=await api('builder/runs','POST',{definition:definition(),idempotencyKey:crypto.randomUUID()});const id=created.run.id;notice=t('Preparing your report…','Menyiapkan laporan Anda…');for(let i=0;i<100;i++){if(requestGeneration!==generation)return;const result=await api(`runs/${id}`);run=result.run;if(run.status==='failed')throw new Error(t('Report could not be generated: ','Laporan gagal dibuat: ')+(run.failureCode??''));if(run.status==='ready'){notice=t('Report snapshot ready. Downloads expire after 7 days.','Snapshot laporan siap. Unduhan berlaku 7 hari.');section=sections[0];await loadRows();return;}await pause();}throw new Error(t('Still preparing. Open recent reports to check later.','Masih diproses. Periksa laporan terbaru nanti.'));});}
 async function loadRows(append=false){if(!run)return;const result=await api(`runs/${run.id}/rows?section=${section}&cursor=${append?cursor??0:0}&limit=50`);rows=append?[...rows,...result.items.map((item:any)=>item.data)]:result.items.map((item:any)=>item.data);cursor=result.nextCursor;}
 async function save(){await perform(async()=>{const payload={name:reportName,definition:definition(),version:selectedVersion};const result=await api(selected?`definitions/${selected}`:'definitions',selected?'PATCH':'POST',payload);selected=result.item.id;selectedVersion=result.item.version;await refresh();notice=t('Report saved.','Laporan disimpan.');});}
 function choose(value:string){const saved=definitions.find(item=>item.id===value);selected=value;if(!saved){selectedVersion=0;reportName='';run=null;rows=[];return;}selectedVersion=saved.version;reportName=saved.name;const d=saved.definition;reportType=d.reportType;preset=d.preset;basis=d.basis;comparison=d.comparison;groupBy=d.groupBy;sort=d.sort;accountIds=d.accountIds;categoryIds=d.categoryIds;tagIds=d.tagIds??[];from=d.from??'';if(d.toExclusive){const end=new Date(d.toExclusive);end.setUTCDate(end.getUTCDate()-1);through=end.toISOString().slice(0,10);}run=null;rows=[];}
 async function exportFile(value:string){await perform(async()=>{const result=await api(`runs/${run.id}/exports`,'POST',{format:value,idempotencyKey:crypto.randomUUID()});for(let i=0;i<100;i++){const state=await api(`exports/${result.export.id}`);if(state.export.status==='ready'){download=`/api/workspaces/${workspaceId}/reports/exports/${result.export.id}/download`;notice=t('Download ready.','Unduhan siap.');return;}if(['failed','expired'].includes(state.export.status))throw new Error(state.export.failureCode??'Export failed');await pause();}throw new Error(t('Export is still processing. Try again later.','Ekspor masih diproses. Coba lagi nanti.'));});}
 const display=(value:any,key=''):string=>{if(value===null||value===undefined)return '—';if(privacy.hidden&&/amount|balance|net|tax|total|income|expense|profit|planned|actual|equity|assets|liabilit|credit|debit|remaining|saved/i.test(key))return '••••••';if(typeof value==='object')return Object.entries(value).map(([k,v])=>`${k}: ${display(v,k)}`).join(' · ');if(/^\d{4}-\d{2}-\d{2}$/.test(String(value)))return formatDate(value);if(typeof value==='string'&&/^-?\d+\.\d+$/.test(value))return privacy.hidden?'••••••':formatExactAmount(value,ui.locale);const descriptions:Record<string,string>={recorded_transactions:t('Recorded transactions','Transaksi tercatat'),historical_budget_revision:t('Historical budget limits','Batas anggaran historis'),issued_document_evidence:t('Issued document evidence','Bukti dokumen terbit'),needs_qualified_review:t('Needs qualified review','Perlu tinjauan profesional'),cash:t('Cash basis','Dasar kas'),accrual:t('Accrual basis','Dasar akrual')};return descriptions[String(value)]??String(value);};
 const sectionLabel=(key:string)=>({grouped:t('Grouped totals','Total kelompok'),activity:t('Transactions','Transaksi'),comparison:t('Comparison period','Periode pembanding'),ledger:t('Ledger detail','Rincian buku besar'),cashflow:t('Cashflow evidence','Bukti arus kas'),budget_actual:t('Budget periods','Periode anggaran'),tax_sales:t('Sales tax evidence','Bukti pajak penjualan'),tax_purchases:t('Purchase tax evidence','Bukti pajak pembelian')}[key]??key);
 const columnLabel=(key:string)=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ');
 const headings:Record<string,string>={income:t('Income','Pemasukan'),expense:t('Expenses','Pengeluaran'),netActivity:t('Net activity','Aktivitas bersih'),profitAndLoss:t('Profit and loss','Laba rugi'),balanceSheet:t('Balance sheet','Neraca'),basis:t('Accounting basis','Dasar akuntansi'),coverage:t('Coverage','Cakupan'),reconciliation:t('Ledger reconciliation','Rekonsiliasi buku besar'),totals:t('Tax totals by currency','Total pajak per mata uang'),reviewStatus:t('Review status','Status peninjauan')};
</script>

<Card.Root class="mb-8">
 <Card.Header><Card.Title>{t('Your report, your view','Laporan sesuai kebutuhan Anda')}</Card.Title><Card.Description>{t('Choose a period, compare results and save a reusable report. Business statements use your recorded ledger.','Pilih periode, bandingkan hasil, dan simpan pengaturan laporan. Laporan bisnis menggunakan buku besar yang tercatat.')}</Card.Description></Card.Header>
 <Card.Content class="space-y-6">
  <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
   <label for={uid+'saved'}>{t('Saved report','Laporan tersimpan')}<ChoiceSelect id={uid+'saved'} value={selected} onValueChange={(value)=>choose(value)} items={[{value:'',label:t('New report','Laporan baru')},...definitions.map(item=>({value:item.id,label:item.name}))]} /></label>
   <label for={uid+'type'}>{t('Report type','Jenis laporan')}<ChoiceSelect id={uid+'type'} bind:value={reportType} items={types}/></label>
   <label for={uid+'period'}>{t('Period','Periode')}<ChoiceSelect id={uid+'period'} bind:value={preset} items={[{value:'this_month',label:t('This month','Bulan ini')},{value:'last_month',label:t('Last month','Bulan lalu')},{value:'this_week',label:t('This week','Minggu ini')},{value:'last_week',label:t('Last week','Minggu lalu')},{value:'year_to_date',label:t('Year to date','Tahun ini')},{value:'custom',label:t('Custom dates','Tanggal khusus')}]}/></label>
   {#if preset==='custom'}<label for={uid+'from'}>{t('Start date','Tanggal mulai')}<DatePicker id={uid+'from'} bind:value={from} required/></label><label for={uid+'through'}>{t('End date (included)','Tanggal akhir (termasuk)')}<DatePicker id={uid+'through'} bind:value={through} min={from} required/></label>{/if}
   {#if business&&reportType!=='tax'}<label for={uid+'basis'}>{t('Accounting basis','Dasar akuntansi')}<ChoiceSelect id={uid+'basis'} bind:value={basis} items={[{value:'cash',label:t('Cash: recorded payments','Kas: pembayaran tercatat')},{value:'accrual',label:t('Accrual: reviewed ledger','Akrual: buku besar ditinjau')}]}/></label>{/if}
   {#if !['cashflow','budget_actual'].includes(reportType)}<label for={uid+'comparison'}>{t('Compare with','Bandingkan dengan')}<ChoiceSelect id={uid+'comparison'} bind:value={comparison} items={[{value:'none',label:t('No comparison','Tanpa perbandingan')},{value:'previous_period',label:t('Previous equal-length period','Periode sebelumnya, durasi sama')},{value:'previous_year',label:t('Same dates last year','Tanggal sama tahun lalu')}]}/></label>{/if}
   {#if reportType==='analytics'}
    <label for={uid+'group'}>{t('Group by','Kelompokkan berdasarkan')}<ChoiceSelect id={uid+'group'} bind:value={groupBy} items={[{value:'day',label:t('Day','Hari')},{value:'month',label:t('Month','Bulan')},{value:'category',label:t('Category','Kategori')},{value:'account',label:t('Account','Akun')}]}/></label>
    <label for={uid+'sort'}>{t('Sort','Urutan')}<ChoiceSelect id={uid+'sort'} bind:value={sort} items={[{value:'date',label:t('Date / name','Tanggal / nama')},{value:'amount_desc',label:t('Largest amount first','Nominal terbesar dahulu')}]}/></label>
    <label for={uid+'accounts'}>{t('Accounts (empty means all)','Akun (kosong berarti semua)')}<ChoiceSelect id={uid+'accounts'} multiple bind:value={accountIds} items={accounts.map(item=>({value:item.id,label:item.name}))}/></label>
    <label for={uid+'categories'}>{t('Primary categories (empty means all)','Kategori utama (kosong berarti semua)')}<ChoiceSelect id={uid+'categories'} multiple bind:value={categoryIds} items={categories.map(item=>({value:item.id,label:item.name}))}/></label>
    <label for={uid+'tags'}>{t('Tags (matches any selected tag)','Tag (cocok salah satu tag)')}<ChoiceSelect id={uid+'tags'} multiple bind:value={tagIds} items={tags.map(item=>({value:item.id,label:item.name}))}/></label>
   {/if}
  </div>
  {#if reportType==='tax'}<p class="text-muted-foreground">{t('Indonesia · issued-document evidence. Purchase tax needs supporting tax invoices and qualified review; this is not a tax return.','Indonesia · bukti dokumen terbit. Pajak pembelian membutuhkan faktur pajak dan tinjauan profesional; ini bukan SPT.')}</p>{/if}
  <div class="flex flex-wrap items-end gap-4"><label for={uid+'name'} class="min-w-0 basis-full flex-1 md:basis-auto">{t('Report name','Nama laporan')}<Input id={uid+'name'} bind:value={reportName} maxlength={120}/></label><Button disabled={busy} onclick={preview}>{busy?t('Working…','Memproses…'):t('Preview report','Pratinjau laporan')}</Button><Button variant="outline" disabled={busy||!reportName.trim()} onclick={save}>{selected?t('Update saved report','Perbarui laporan'):t('Save report','Simpan laporan')}</Button>{#if selected}<Button variant="outline" disabled={busy} onclick={()=>perform(async()=>{if(!confirm(t('Delete this saved report and its email schedules?','Hapus laporan dan jadwal emailnya?')))return;await api(`definitions/${selected}`,'DELETE');selected='';await refresh();})}>{t('Delete saved report','Hapus laporan')}</Button>{/if}</div>
  <p role="status" aria-live="polite">{notice}</p>{#if error}<p role="alert" class="text-destructive">{error}</p>{/if}
  {#if run?.status==='ready'}
   <div class="rounded-[var(--radius)] border-2 border-border p-4 space-y-4">
    <h3 class="font-heading text-lg">{t('Snapshot','Snapshot')} · {formatDate(run.periodFrom)} – {formatDate(new Date(Date.parse(run.periodToExclusive)-86400000).toISOString().slice(0,10))}</h3>
    <dl class="grid gap-4 md:grid-cols-2">{#each Object.entries(run.summary??{}).filter(([key])=>headings[key]) as [key,value]}<div><dt class="text-sm text-muted-foreground">{headings[key]}</dt><dd class="font-semibold break-words">{display(value,key)}</dd></div>{/each}</dl>
    {#if run.qualityFlags?.length}<p class="text-muted-foreground">{run.qualityFlags.map((flag:string)=>flag.replaceAll('_',' ')).join(' · ')}</p>{/if}
    {#if run.summary?.limitations}<ul class="list-disc pl-6">{#each run.summary.limitations as limitation}<li>{limitation}</li>{/each}</ul>{/if}
    <div class="flex flex-wrap gap-3"><Button variant="outline" disabled={busy} onclick={()=>exportFile('pdf')}>PDF</Button><Button variant="outline" disabled={busy} onclick={()=>exportFile('xlsx')}>Excel</Button><Button variant="outline" disabled={busy} onclick={()=>exportFile('csv')}>CSV</Button>{#if download}<a class="inline-flex min-h-11 items-center rounded-full border-2 border-border px-4 focus-visible:outline-2" href={download}>{t('Download file','Unduh berkas')}</a>{/if}</div>
    <label for={uid+'section'}>{t('Report detail','Rincian laporan')}<ChoiceSelect id={uid+'section'} bind:value={section} onValueChange={()=>perform(()=>loadRows())} items={sections.map(value=>({value,label:sectionLabel(value)}))}/></label>
    <ScrollRegion label={t('Report detail rows','Baris rincian laporan')}>
     {#if rows.length}<table class="w-full text-sm"><caption class="sr-only">{t('Report evidence','Bukti laporan')}</caption><thead><tr>{#each Object.keys(rows[0]) as key}<th class="p-3 text-left whitespace-nowrap" scope="col">{columnLabel(key)}</th>{/each}</tr></thead><tbody>{#each rows as row}<tr class="border-t border-border">{#each Object.keys(rows[0]) as key}<td class="p-3 align-top max-w-80 break-words tabular-nums">{display(row[key],key)}</td>{/each}</tr>{/each}</tbody></table>{:else}<p class="p-4 text-muted-foreground">{t('No records for this selection.','Tidak ada data untuk pilihan ini.')}</p>{/if}
    </ScrollRegion>{#if cursor!==null}<Button variant="outline" disabled={busy} onclick={()=>perform(()=>loadRows(true))}>{t('Load more','Muat lagi')}</Button>{/if}
   </div>
  {/if}
 </Card.Content>
</Card.Root>
<Card.Root class="mb-8">
 <Card.Header><Card.Title>{t('Reports in your inbox','Laporan ke kotak masuk')}</Card.Title><Card.Description>{t('Send the previous complete week or month to your own verified email. An attachment is sent after your access is checked again.','Kirim laporan minggu atau bulan lengkap sebelumnya ke email terverifikasi Anda. Lampiran dikirim setelah izin akses diperiksa kembali.')}</Card.Description></Card.Header>
 <Card.Content class="space-y-6">
  <div class="grid gap-4 md:grid-cols-3"><label for={uid+'cadence'}>{t('Frequency','Frekuensi')}<ChoiceSelect id={uid+'cadence'} bind:value={cadence} items={[{value:'monthly',label:t('Monthly · 1st day','Bulanan · tanggal 1')},{value:'weekly',label:t('Weekly · Monday','Mingguan · Senin')}]}/></label><label for={uid+'time'}>{t('Send time','Waktu kirim')}<Input id={uid+'time'} type="time" bind:value={sendTime}/><span class="text-sm text-muted-foreground">{timezone}</span></label><label for={uid+'format'}>{t('Attachment','Lampiran')}<ChoiceSelect id={uid+'format'} bind:value={format} items={[{value:'pdf',label:'PDF'},{value:'xlsx',label:'Excel'},{value:'csv',label:'CSV'}]}/></label></div>
  <label for={uid+"consent"} class="flex min-h-11 items-center gap-3"><Checkbox id={uid+"consent"} bind:checked={consent} class="size-5"/>{t('I agree to receive these reports at my verified email.','Saya setuju menerima laporan ke email terverifikasi saya.')}</label>
  <Button disabled={busy||!selected||preset==='custom'||!consent} onclick={()=>perform(async()=>{await api(editingSchedule?`schedules/${editingSchedule}`:'schedules',editingSchedule?'PATCH':'POST',{definitionId:selected,cadence,localTime:sendTime,timezone,format,locale:ui.locale,consent,enabled:true,version:editingVersion});editingSchedule='';await refresh();notice=t('Email schedule created.','Jadwal email dibuat.');})}>{editingSchedule?t('Save schedule changes','Simpan perubahan jadwal'):t('Schedule selected saved report','Jadwalkan laporan tersimpan')}</Button>
  {#if !selected||preset==='custom'}<p class="text-sm text-muted-foreground">{t('Select a saved report with a relative period before scheduling.','Pilih laporan tersimpan dengan periode relatif untuk membuat jadwal.')}</p>{/if}
  {#each schedules as schedule}<div class="flex flex-wrap items-center justify-between gap-4 rounded-[var(--radius)] border-2 border-border p-4"><div><h3 class="font-semibold">{schedule.name}</h3><p class="text-sm text-muted-foreground">{schedule.cadence} · {schedule.local_time} · {schedule.timezone} · {schedule.format.toUpperCase()} · {schedule.enabled?t('Active','Aktif'):t('Paused','Dijeda')}</p></div><div class="flex flex-wrap gap-3"><Button variant="outline" disabled={busy} onclick={()=>{choose(schedule.definition_id);editingSchedule=schedule.id;editingVersion=schedule.version;cadence=schedule.cadence;sendTime=schedule.local_time;format=schedule.format;consent=true;notice=t("Editing this schedule. Save changes above.","Mengedit jadwal ini. Simpan perubahan di atas.");}}>{t("Edit","Edit")}</Button><Button variant="outline" disabled={busy} onclick={()=>perform(async()=>{await api(`schedules/${schedule.id}`,'PATCH',{enabled:!schedule.enabled,version:schedule.version});await refresh();})}>{schedule.enabled?t('Pause','Jeda'):t('Resume','Lanjutkan')}</Button><Button variant="outline" disabled={busy} onclick={()=>perform(async()=>{if(!confirm(t('Delete this email schedule?','Hapus jadwal email ini?')))return;await api(`schedules/${schedule.id}`,'DELETE');await refresh();})}>{t('Delete','Hapus')}</Button></div></div>{/each}
  {#if deliveries.length}<h3 class="font-semibold">{t('Recent email attempts','Upaya kirim terbaru')}</h3>{#each deliveries as delivery}<p class="text-sm">{formatDate(delivery.occurrence)} · {delivery.state==='accepted'?t('Accepted by mail server (not a read receipt)','Diterima server email (bukan tanda dibaca)'):delivery.state==='unknown'?t('Outcome uncertain; no automatic resend','Hasil tidak pasti; tidak dikirim ulang otomatis'):delivery.state}{delivery.failure_code?' · '+delivery.failure_code:''}</p>{/each}{/if}
 </Card.Content>
</Card.Root>
