<script lang="ts">
  import {getContext as privacyContext} from 'svelte';
  import {concealed,PRIVACY_CONTEXT,type PrivacyState} from '$lib/privacy';
  const privacy=privacyContext<PrivacyState>(PRIVACY_CONTEXT);
  import { getContext } from 'svelte';
  import { Button } from '$lib/components/ui/button';
  import * as Card from '$lib/components/ui/card';
  import { AUTH_UI_CONTEXT, type AuthUiState } from '$lib/i18n/auth';
  import { trackingText } from '$lib/i18n/tracking';
  import { assistantText } from '$lib/i18n/assistant';
  type State={selectedId:string;ready:boolean};
  type Summary={balance:string;income:string;expense:string;netChange:string};
  type Row={id:string;type:string;amount:string;currency:string;date:string;accountName:string;categoryName?:string;merchant?:string;notes?:string};
  type AssistantSummary={asOfDate:string;currency:string;horizonDays:number;safeToSpend:string|null;safeToSpendReason:string;minimumBalance:string;firstShortfallDate:string|null;firstLowBalanceDate:string|null;qualityFlags:string[]};
  type ReportDashboard={summary:{currency:string;income:string;expense:string};budgetActual:{name:string;planned:string;actual:string;usedPercent:number|null}[];goals:{id:string;name:string;saved:string;target:string;progressPercent:number|null}[];bills:{id:string;name:string;amount:string;dueOn:string}[]};
  const workspace=getContext<State>('capybudget-workspaces');
  const authUi=getContext<AuthUiState>(AUTH_UI_CONTEXT);const t=(key:Parameters<typeof trackingText>[1])=>trackingText(authUi.locale,key);
  let summary:Summary=$state({balance:'0.0000',income:'0.0000',expense:'0.0000',netChange:'0.0000'}),recent:Row[]=$state([]),assistant:AssistantSummary|null=$state(null),assistantSuggestion:any=$state(null),reports:ReportDashboard|null=$state(null),loading=$state(true),error=$state(''),requestSequence=0,horizon=$state(30);
  $effect(()=>{void (workspace as {revision?:number}).revision;const id=workspace.selectedId;if(id)void load(id);});
  async function load(id:string){
    const sequence=++requestSequence;loading=true;error='';
    try{const [s,t,a,r]=await Promise.all([fetch('/api/workspaces/'+id+'/summary').then(r=>r.json()),fetch('/api/workspaces/'+id+'/transactions?limit=6').then(r=>r.json()),fetch(`/api/workspaces/${id}/assistant/forecast?horizon=${horizon}`).then(async r=>r.ok?await r.json():null).catch(()=>null),fetch(`/api/workspaces/${id}/reports/dashboard?preset=this_month`).then(async r=>r.ok?await r.json():null).catch(()=>null)]);if(sequence!==requestSequence)return;summary=s;recent=t.items;assistant=a?.forecast??null;assistantSuggestion=a?.suggestions?.[0]??null;reports=r;}
    catch(e){if(sequence===requestSequence)error=e instanceof Error?e.message:'Unable to load your money summary.';}
    finally{if(sequence===requestSequence)loading=false;}
  }
  function netChange(){return concealed(summary.netChange,privacy.hidden);}
function assistantMoney(value:string|null){if(privacy.hidden)return '••••••';return value===null?assistantText(authUi.locale,'unavailable'):`${assistant?.currency??''} ${value}`;}
  function reportMoney(value:string){if(privacy.hidden)return '••••••';return `${reports?.summary.currency??''} ${value}`;}
  function suggestionTitle(value:string){return assistantText(authUi.locale,value==='shortfall'?'shortfall':value==='low_balance'?'lowBalance':value==='savings'?'savingsOpportunity':'invoiceFollowup');}
  function monthDay(value:string){return new Intl.DateTimeFormat(authUi.locale==='id'?'id-ID':'en',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));}
  function changeHorizon(value:string){horizon=Number(value);if(workspace.selectedId)void load(workspace.selectedId);}
</script>

<div class="welcome"><div><p class="eyebrow">A LITTLE MORE CLARITY</p><h1>{t('dashboardHeading')}</h1><p class="muted">{t('dashboardSubtitle')}</p></div><Button href="/transactions">{t('addTransaction')}</Button></div>
{#if !workspace.ready||loading}<p role="status">{t('loading')}</p>
{:else if error}<p class="error" role="alert">{error}</p>
{:else}
  <div class="stats">
    <Card.Root><Card.Header><Card.Description>{t('balance')}</Card.Description><Card.Title class="money">{concealed(summary.balance,privacy.hidden)}</Card.Title></Card.Header></Card.Root>
    <Card.Root><Card.Header><Card.Description>Income</Card.Description><Card.Title class="money income">{concealed(summary.income,privacy.hidden)}</Card.Title></Card.Header></Card.Root>
    <Card.Root><Card.Header><Card.Description>Expenses</Card.Description><Card.Title class="money expense">{concealed(summary.expense,privacy.hidden)}</Card.Title></Card.Header></Card.Root>
    <Card.Root><Card.Header><Card.Description>{t('netChange')}</Card.Description><Card.Title class="money">{netChange()}</Card.Title></Card.Header></Card.Root>
  </div>
  {#if reports}<Card.Root class="reports-summary"><Card.Header><div class="report-heading"><div><Card.Title>{authUi.locale==='id'?'Ringkasan bulan ini':'This month at a glance'}</Card.Title><Card.Description>{reportMoney(reports.summary.income)} {authUi.locale==='id'?'pemasukan':'income'} · {reportMoney(reports.summary.expense)} {authUi.locale==='id'?'pengeluaran':'expenses'}</Card.Description></div><Button variant="outline" href="/reports">{authUi.locale==='id'?'Lihat laporan':'View reports'} →</Button></div></Card.Header><Card.Content><div class="report-grid"><div><strong>{authUi.locale==='id'?'Anggaran':'Budgets'}</strong>{#each reports.budgetActual.slice(0,3) as budget}<p>{budget.name}<small>{reportMoney(budget.actual)} / {reportMoney(budget.planned)}{privacy.hidden||budget.usedPercent===null?'':` · ${budget.usedPercent}%`}</small></p>{:else}<p class="report-empty">{authUi.locale==='id'?'Belum ada anggaran aktif.':'No active budgets.'}</p>{/each}</div><div><strong>{authUi.locale==='id'?'Tagihan mendatang':'Upcoming bills'}</strong>{#each reports.bills.slice(0,3) as bill}<p>{bill.name}<small>{bill.dueOn} · {reportMoney(bill.amount)}</small></p>{:else}<p class="report-empty">{authUi.locale==='id'?'Tidak ada tagihan dalam 30 hari.':'No bills due in 30 days.'}</p>{/each}</div><div><strong>{authUi.locale==='id'?'Target tabungan':'Savings goals'}</strong>{#each reports.goals.slice(0,3) as goal}<p>{goal.name}<small>{reportMoney(goal.saved)} / {reportMoney(goal.target)}{privacy.hidden||goal.progressPercent===null?'':` · ${goal.progressPercent}%`}</small></p>{:else}<p class="report-empty">{authUi.locale==='id'?'Belum ada target tabungan.':'No active savings goals.'}</p>{/each}</div></div></Card.Content></Card.Root>{/if}
  {#if assistant}<Card.Root class="assistant-summary"><Card.Header><div class="assistant-head"><div><Card.Description>{assistantText(authUi.locale,'safeToSpend')}</Card.Description><Card.Title class="money">{assistantMoney(assistant.safeToSpend)}</Card.Title><Card.Description>{assistant.safeToSpendReason==='incomplete_data'?assistantText(authUi.locale,'excluded'):assistantText(authUi.locale,'afterReserves')}</Card.Description><Card.Description>{assistantText(authUi.locale,'asOf')} {monthDay(assistant.asOfDate)} · {assistantText(authUi.locale,'assistantDisclaimer')}</Card.Description></div><div class="assistant-actions"><label for="dashboard-horizon">{assistantText(authUi.locale,'forecast')} <select id="dashboard-horizon" value={horizon} onchange={(event)=>changeHorizon(event.currentTarget.value)}><option value={30}>30 {assistantText(authUi.locale,'days')}</option><option value={60}>{60} {assistantText(authUi.locale,'days')}</option><option value={90}>{90} {assistantText(authUi.locale,'days')}</option></select></label><Button variant="outline" href="/assistant">{assistantText(authUi.locale,'forecast')} →</Button></div></div>{#if assistant.firstShortfallDate||assistant.firstLowBalanceDate}<p class="assistant-alert">{assistant.firstShortfallDate?assistantText(authUi.locale,'shortfallOn'):assistantText(authUi.locale,'lowOn')} {monthDay(assistant.firstShortfallDate??assistant.firstLowBalanceDate!)}</p>{/if}{#if assistantSuggestion}<p class="assistant-insight"><strong>{suggestionTitle(assistantSuggestion.kind)}</strong><span>{assistantSuggestion.facts?.date?monthDay(assistantSuggestion.facts.date):assistantSuggestion.facts?.dueDate?monthDay(assistantSuggestion.facts.dueDate):''}{assistantSuggestion.facts?.amount?` · ${assistant?.currency??''} ${concealed(assistantSuggestion.facts.amount,privacy.hidden)}`:''}</span></p>{/if}</Card.Header></Card.Root>{/if}
  <Card.Root class="history"><Card.Header><Card.Title>{t('recentTransactions')}</Card.Title><Card.Description>{t('latestActivity')}</Card.Description></Card.Header><Card.Content>
    {#if recent.length===0}<div class="empty"><span>◌</span><strong>{t('nap')}</strong><p>{t('firstTransaction')}</p><Button variant="outline" href="/transactions">{t('addTransaction')}</Button></div>
    {:else}<div class="rows">{#each recent as row (row.id)}<a class="row" href="/transactions"><span class="symbol" class:income={row.type==='income'} class:expense={row.type==='expense'}>{row.type==='income'?'↗':row.type==='expense'?'↘':'↔'}</span><span class="desc"><strong>{row.merchant||row.notes||row.type}</strong><small>{row.categoryName??row.accountName} · {row.date}</small></span><strong class="amount">{row.currency} {row.type==='expense'?'-':''}{concealed(row.amount,privacy.hidden)}</strong></a>{/each}</div><div class="footer"><a href="/transactions">{t('viewHistory')}</a></div>{/if}
  </Card.Content></Card.Root>
{/if}

<style>
  .welcome{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:24px}.eyebrow{font-size:11px;letter-spacing:1px;font-weight:700;color:var(--muted-foreground);margin:0 0 6px}h1{font:500 clamp(26px,4vw,36px) 'Fredoka Variable',sans-serif;margin:0}.muted{color:var(--muted-foreground);margin:7px 0 0}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}:global(.money){font:500 clamp(18px,2.2vw,26px) 'Nunito Sans Variable',sans-serif;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.income{color:#2F7A2A}.expense{color:#C7473A}:global(.history){margin-top:18px}:global(.assistant-summary),:global(.reports-summary){margin-top:14px}.report-heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.report-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.report-grid p{display:grid;gap:4px;margin:10px 0;font-size:13px}.report-grid small,.report-empty{color:var(--muted-foreground)}.assistant-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.assistant-alert{margin:12px 0 0;padding:10px;border-radius:10px;background:var(--muted);font-size:13px}.assistant-insight{display:grid;gap:3px;margin:10px 0 0;font-size:13px}.assistant-insight span{color:var(--muted-foreground)}.rows{display:grid}.row{display:grid;grid-template-columns:40px minmax(0,1fr) auto;align-items:center;gap:10px;padding:13px 2px;text-decoration:none;color:var(--foreground);border-bottom:1px solid var(--border)}.row:last-child{border:0}.symbol{display:grid;place-items:center;width:38px;height:38px;border-radius:13px;background:var(--secondary);color:var(--secondary-foreground);font-size:19px}.desc{display:grid;gap:3px}.desc small{color:var(--muted-foreground)}.amount{font-variant-numeric:tabular-nums;white-space:nowrap}.empty{text-align:center;padding:35px 8px}.empty span{font-size:32px;color:var(--muted-foreground)}.empty strong{display:block;margin-top:8px}.empty p{color:var(--muted-foreground)}.footer{text-align:right;padding:14px 0 3px}.footer a{color:var(--primary);text-decoration:none;font-weight:600}.error{color:var(--destructive)}@media(max-width:800px){.stats{grid-template-columns:repeat(2,minmax(0,1fr))}.report-grid{grid-template-columns:1fr}}@media(max-width:480px){.welcome{align-items:flex-start;flex-direction:column}.assistant-head,.report-heading{align-items:flex-start;flex-direction:column}.stats{gap:8px}:global(.money){font-size:18px}}
  :global(.app-shell[data-mode='business'] .stats){gap:10px}
  :global(.app-shell[data-mode='business'] .assistant-alert){border-radius:7px}
</style>
