<script lang="ts">
  import {getContext as privacyContext} from 'svelte';
  import {concealed,PRIVACY_CONTEXT,type PrivacyState} from '$lib/privacy';
  const privacy=privacyContext<PrivacyState>(PRIVACY_CONTEXT);
 import {getContext} from 'svelte';import {page} from '$app/state';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {businessText} from '$lib/i18n/business';import {trackingText} from '$lib/i18n/tracking';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';
 type Workspace={selectedId:string;ready:boolean;items:{id:string;kind:string;timezone?:string}[]};type Line={description:string;quantity:string;unitPrice:string;discountAmount:string;taxRate:string;netAmount?:string;taxAmount?:string;totalAmount?:string};
 const workspace=getContext<Workspace>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof businessText>[1])=>businessText(ui.locale,key),tt=(key:Parameters<typeof trackingText>[1])=>trackingText(ui.locale,key);
 let invoice:any=$state(null),accounts:any[]=$state([]),categories:any[]=$state([]),loading=$state(true),busy=$state(false),error=$state(''),notice=$state(''),amount=$state(''),paidOn=$state(''),accountId=$state(''),forecastAccountId=$state(''),forecastDate=$state(''),categoryId=$state(''),reference=$state(''),requestId=0;
 const id=$derived(page.params.invoiceId);
 function dateToday(){const timezone=workspace.items.find(x=>x.id===workspace.selectedId)?.timezone??'Asia/Jakarta',parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=(n:string)=>parts.find(p=>p.type===n)?.value;return get('year')+'-'+get('month')+'-'+get('day');}
 const label=(value:string)=>t(value as Parameters<typeof businessText>[1]);
 async function load(){if(!workspace.ready||!workspace.selectedId||!id)return;const current=++requestId;loading=true;error='';try{const [inv,ac,cat]=await Promise.all([fetch('/api/workspaces/'+workspace.selectedId+'/invoices/'+id),fetch('/api/workspaces/'+workspace.selectedId+'/accounts'),fetch('/api/workspaces/'+workspace.selectedId+'/categories')]);const [idata,adata,cdata]=await Promise.all([inv.json(),ac.json(),cat.json()]);if(!inv.ok)throw new Error(idata.message??t('error'));if(current!==requestId)return;invoice=idata.invoice;accounts=adata.items??[];forecastAccountId=idata.invoice.expectedAccountId??'';forecastDate=idata.invoice.expectedPaymentOn??idata.invoice.dueDate;categories=(cdata.items??[]).filter((x:any)=>x.type==='income');paidOn=dateToday();accountId=accounts.find((x:any)=>x.currency===invoice.currency)?.id??'';categoryId=categories[0]?.id??'';}catch(e){if(current===requestId)error=e instanceof Error?e.message:t('error');}finally{if(current===requestId)loading=false;}}
 $effect(()=>{void (workspace as {revision?:number}).revision;if(workspace.ready&&workspace.selectedId&&id)void load();});
 async function call(url:string,method='POST',body?:unknown){const response=await fetch(url,{method,headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),data=response.status===204?null:await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.message??t('error'));return data;}
 async function saveDraft(){if(busy)return;busy=true;error='';notice='';try{const body={version:invoice.version,recipient:invoice.recipientSnapshot,issueDate:invoice.issue_date,dueDate:invoice.due_date,notes:invoice.notes,paymentInstructions:invoice.payment_instructions,lines:invoice.lines};const data=await call('/api/workspaces/'+workspace.selectedId+'/invoices/'+id,'PATCH',body);invoice=data.invoice;notice=t('saved');}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
 function addLine(){invoice.lines=[...invoice.lines,{description:'',quantity:'1',unitPrice:'',discountAmount:'0',taxRate:'0'}];}
 function removeLine(index:number){if(invoice.lines.length>1)invoice.lines=invoice.lines.filter((_:Line,i:number)=>i!==index);}
 async function issueInvoice(){if(busy)return;busy=true;error='';try{const data=await call('/api/workspaces/'+workspace.selectedId+'/invoices/'+id+'/issue','POST',{version:invoice.version});invoice=data.invoice;}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
 async function saveCollectionForecast(){if(busy||invoice.state!=='issued')return;busy=true;error='';try{const data=await call('/api/workspaces/'+workspace.selectedId+'/invoices/'+id+'/collection-forecast','PATCH',{version:invoice.version,expectedPaymentOn:forecastDate||null,expectedAccountId:forecastAccountId||null});invoice={...invoice,...data};notice=ui.locale==='id'?'Asumsi penerimaan tersimpan.':'Collection estimate saved.';}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
 async function sendInvoice(){if(busy)return;busy=true;error='';try{await call('/api/workspaces/'+workspace.selectedId+'/invoices/'+id+'/send','POST',{version:invoice.version});notice=t('sending');await load();}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
 async function downloadPdf(){if(busy)return;busy=true;error='';try{const response=await fetch('/api/workspaces/'+workspace.selectedId+'/invoices/'+id+'/pdf',{method:'POST'});if(!response.ok){const data=await response.json();throw new Error(data.message??t('error'));}const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download=(invoice.number??'invoice-draft')+'.pdf';anchor.click();URL.revokeObjectURL(url);}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
 async function voidInvoice(){const reason=prompt(t('reason'));if(!reason)return;busy=true;try{const data=await call('/api/workspaces/'+workspace.selectedId+'/invoices/'+id+'/void','POST',{reason,effectiveOn:dateToday(),version:invoice.version});invoice=data.invoice;}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
 async function recordPayment(event:SubmitEvent){event.preventDefault();if(busy)return;busy=true;error='';try{await call('/api/workspaces/'+workspace.selectedId+'/invoices/'+id+'/payments','POST',{amount,paidOn,accountId,categoryId,reference,idempotencyKey:crypto.randomUUID()});amount='';reference='';await load();}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
 async function reversePayment(payment:any){const reason=prompt(t('reason'));if(!reason)return;busy=true;try{await call('/api/workspaces/'+workspace.selectedId+'/invoices/'+id+'/payments/'+payment.id+'/reverse','POST',{reason,effectiveOn:dateToday()});await load();}catch(e){error=e instanceof Error?e.message:t('error');}finally{busy=false;}}
</script>
<svelte:head><title>CapyBudget · {invoice?.number??t('invoice')}</title></svelte:head>
{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p role="status">{notice}</p>{/if}
{#if loading}<p>{t('loading')}</p>{:else if invoice}<div class="head"><div><p><a href="/invoices">{t('invoices')}</a></p><h1>{invoice.number??t('draft')}</h1><span class="state">{label(invoice.status)}</span></div><div class="actions">{#if invoice.state==='draft'}<Button variant="outline" onclick={saveDraft} disabled={busy}>{t('saveDraft')}</Button><Button onclick={issueInvoice} disabled={busy}>{t('issueInvoice')}</Button>{:else if invoice.state==='issued'}<Button variant="outline" onclick={downloadPdf} disabled={busy}>{t('downloadPdf')}</Button><Button onclick={sendInvoice} disabled={busy}>{t('sendInvoice')}</Button>{#if invoice.status!=='paid'}<Button variant="destructive" onclick={voidInvoice} disabled={busy}>{t('voidInvoice')}</Button>{/if}{/if}</div></div>
<div class="grid"><Card.Root><Card.Header><Card.Title>{t('customer')}</Card.Title><Card.Description>{invoice.currency} · {invoice.issueDate} → {invoice.dueDate}</Card.Description></Card.Header><Card.Content><Field.FieldGroup class="fields">
<Field.Field><Field.FieldLabel for="customer">{t('customer')}</Field.FieldLabel><Input id="customer" bind:value={invoice.recipientSnapshot.name} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="customer-email">{t('email')}</Field.FieldLabel><Input id="customer-email" type="email" bind:value={invoice.recipientSnapshot.email} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="customer-phone">{t('phone')}</Field.FieldLabel><Input id="customer-phone" bind:value={invoice.recipientSnapshot.phone} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="customer-street">{t('street')}</Field.FieldLabel><Input id="customer-street" bind:value={invoice.recipientSnapshot.address.street} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="customer-city">{t('city')}</Field.FieldLabel><Input id="customer-city" bind:value={invoice.recipientSnapshot.address.city} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="customer-region">{t('region')}</Field.FieldLabel><Input id="customer-region" bind:value={invoice.recipientSnapshot.address.region} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="customer-postal">{t('postalCode')}</Field.FieldLabel><Input id="customer-postal" bind:value={invoice.recipientSnapshot.address.postalCode} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="customer-country">{t('country')}</Field.FieldLabel><Input id="customer-country" bind:value={invoice.recipientSnapshot.address.country} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="issue-date">{t('issueDate')}</Field.FieldLabel><Input id="issue-date" type="date" bind:value={invoice.issue_date} disabled={invoice.state!=='draft'} /></Field.Field>
<Field.Field><Field.FieldLabel for="due-date">{t('dueDate')}</Field.FieldLabel><Input id="due-date" type="date" bind:value={invoice.due_date} disabled={invoice.state!=='draft'} /></Field.Field>
</Field.FieldGroup><div class="summary"><span>{t('paid')}: {invoice.currency} {concealed(invoice.paidAmount,privacy.hidden)}</span><strong>{t('outstanding')}: {invoice.currency} {concealed(invoice.outstanding,privacy.hidden)}</strong></div></Card.Content></Card.Root>
{#if invoice.state==='issued'}<Card.Root class="collection-card"><Card.Header><Card.Title>{ui.locale==='id'?'Perkiraan penerimaan':'Collection estimate'}</Card.Title><Card.Description>{ui.locale==='id'?'Asumsi ini hanya untuk prakiraan dan tidak mengubah jatuh tempo faktur.':'Forecasting assumption only; it does not change the invoice due date.'}</Card.Description></Card.Header><Card.Content><Field.FieldGroup class="fields"><Field.Field><Field.FieldLabel for="collection-date">{ui.locale==='id'?'Tanggal penerimaan yang diperkirakan':'Expected collection date'}</Field.FieldLabel><Input id="collection-date" type="date" bind:value={forecastDate}/></Field.Field><Field.Field><Field.FieldLabel for="collection-account">{ui.locale==='id'?'Akun penerimaan':'Receiving account'}</Field.FieldLabel><select id="collection-account" bind:value={forecastAccountId}><option value="">{ui.locale==='id'?'Belum ditentukan':'Unassigned'}</option>{#each accounts.filter((x:any)=>x.currency===invoice.currency&&['cash','bank','e_wallet','savings'].includes(x.kind)) as account (account.id)}<option value={account.id}>{account.name}</option>{/each}</select></Field.Field></Field.FieldGroup><Button class="save-collection" variant="outline" onclick={saveCollectionForecast} disabled={busy}>{ui.locale==='id'?'Simpan asumsi':'Save estimate'}</Button></Card.Content></Card.Root>{/if}
<Card.Root><Card.Header><Card.Title>{t('invoice')}</Card.Title></Card.Header><Card.Content>{#if invoice.state==='draft'}<div class="lines">{#each invoice.lines as line,i (line.id??i)}<div class="line"><Field.Field><Field.FieldLabel for={'line-description-'+i}>{t('description')}</Field.FieldLabel><Input id={'line-description-'+i} bind:value={line.description} maxlength={500} /></Field.Field><Field.Field><Field.FieldLabel for={'line-quantity-'+i}>{t('quantity')}</Field.FieldLabel><Input id={'line-quantity-'+i} bind:value={line.quantity} inputmode="decimal" /></Field.Field><Field.Field><Field.FieldLabel for={'line-price-'+i}>{t('unitPrice')}</Field.FieldLabel><Input id={'line-price-'+i}  type={privacy.hidden?'password':'text'} bind:value={line.unitPrice} inputmode="decimal" /></Field.Field><Field.Field><Field.FieldLabel for={'line-discount-'+i}>{t('discount')}</Field.FieldLabel><Input id={'line-discount-'+i}  type={privacy.hidden?'password':'text'} bind:value={line.discountAmount} inputmode="decimal" /></Field.Field><Field.Field><Field.FieldLabel for={'line-tax-'+i}>{t('taxRate')}</Field.FieldLabel><Input id={'line-tax-'+i} bind:value={line.taxRate} inputmode="decimal" /></Field.Field>{#if invoice.lines.length>1}<Button type="button" variant="ghost" onclick={()=>removeLine(i)}>{t('removeLine')}</Button>{/if}</div>{/each}</div><Button type="button" variant="outline" onclick={addLine} disabled={invoice.lines.length>=100}>{t('addLine')}</Button>{:else}<div class="rows">{#each invoice.lines as line (line.id)}<article><div><strong>{line.description}</strong><p>{line.quantity} × {invoice.currency} {concealed(line.unitPrice,privacy.hidden)}</p></div><strong>{invoice.currency} {concealed(line.totalAmount,privacy.hidden)}</strong></article>{/each}</div>{/if}<div class="totals"><p>{t('subtotal')} <strong>{invoice.currency} {concealed(invoice.subtotal,privacy.hidden)}</strong></p><p>{t('discount')} <strong>−{invoice.currency} {concealed(invoice.discountTotal,privacy.hidden)}</strong></p><p>{t('tax')} <strong>{invoice.currency} {concealed(invoice.taxTotal,privacy.hidden)}</strong></p><p class="total">{t('total')} <strong>{invoice.currency} {concealed(invoice.total,privacy.hidden)}</strong></p></div>{#if invoice.state==='draft'}<Field.FieldGroup class="fields extra"><Field.Field><Field.FieldLabel for="invoice-notes">{t('notes')}</Field.FieldLabel><Input id="invoice-notes" bind:value={invoice.notes} maxlength={4000} /></Field.Field><Field.Field><Field.FieldLabel for="payment-instructions">{t('paymentInstructions')}</Field.FieldLabel><Input id="payment-instructions" bind:value={invoice.payment_instructions} maxlength={2000} /></Field.Field></Field.FieldGroup>{:else if invoice.notes}<p class="hint">{t('notes')}: {invoice.notes}</p>{/if}</Card.Content></Card.Root></div>
{#if invoice.state==='issued'&&invoice.outstanding!=='0'}<Card.Root class="payment-card"><Card.Header><Card.Title>{t('recordPayment')}</Card.Title><Card.Description>This records a new income transaction in the selected receiving account.</Card.Description></Card.Header><Card.Content><form onsubmit={recordPayment}><Field.FieldGroup class="fields"><Field.Field><Field.FieldLabel for="payment-amount">{t('total')}</Field.FieldLabel><Input id="payment-amount"  type={privacy.hidden?'password':'text'} bind:value={amount} inputmode="decimal" required /></Field.Field><Field.Field><Field.FieldLabel for="payment-date">{t('paymentDate')}</Field.FieldLabel><Input id="payment-date" type="date" bind:value={paidOn} required /></Field.Field><Field.Field><Field.FieldLabel for="payment-account">{t('receivingAccount')}</Field.FieldLabel><select id="payment-account" bind:value={accountId} required>{#each accounts.filter((x:any)=>x.currency===invoice.currency) as account (account.id)}<option value={account.id}>{account.name}</option>{/each}</select></Field.Field><Field.Field><Field.FieldLabel for="payment-category">{t('incomeCategory')}</Field.FieldLabel><select id="payment-category" bind:value={categoryId} required>{#each categories as category (category.id)}<option value={category.id}>{category.name}</option>{/each}</select></Field.Field><Field.Field><Field.FieldLabel for="payment-reference">{t('reference')}</Field.FieldLabel><Input id="payment-reference" bind:value={reference} maxlength={300} /></Field.Field></Field.FieldGroup><Button type="submit" disabled={busy||!accountId||!categoryId}>{busy?'…':t('recordPayment')}</Button></form></Card.Content></Card.Root>{/if}
{#if invoice.payments.length}<Card.Root class="payment-card"><Card.Header><Card.Title>{t('paid')}</Card.Title></Card.Header><Card.Content><div class="rows">{#each invoice.payments as payment (payment.id)}<article><div><strong>{invoice.currency} {concealed(payment.amount,privacy.hidden)}</strong><p>{payment.paidOn} · {payment.reference??'—'}{payment.reversedAt?' · '+t('reversePayment'):''}</p></div>{#if !payment.reversedAt&&invoice.state==='issued'}<Button size="sm" variant="outline" onclick={()=>reversePayment(payment)}>{t('reversePayment')}</Button>{/if}</article>{/each}</div></Card.Content></Card.Root>{/if}
{#if invoice.deliveries.length}<Card.Root class="payment-card"><Card.Header><Card.Title>{t('sendInvoice')}</Card.Title><Card.Description>{t('sending')} and accepted messages</Card.Description></Card.Header><Card.Content>{#each invoice.deliveries as delivery (delivery.id)}<p>{delivery.state}{delivery.errorCode?' · '+t('sendFailed'):''}{delivery.acceptedAt?' · '+delivery.acceptedAt:''}</p>{/each}</Card.Content></Card.Root>{/if}
{/if}
<style>.head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:22px}.head>div:first-child p{margin:0}.head a{color:var(--muted-foreground)}.head h1{font:500 clamp(26px,4vw,36px) 'Fredoka Variable',sans-serif;margin:4px 0}.state{display:inline-block;padding:4px 10px;border-radius:99px;background:var(--secondary);font-size:12px}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px}.grid{display:grid;grid-template-columns:1fr 1fr;align-items:start;gap:16px}:global(.fields){display:grid;grid-template-columns:1fr 1fr;gap:12px}.summary,.totals{display:grid;gap:10px;margin-top:20px}.summary{border-top:1px solid var(--border);padding-top:14px}.summary strong{text-align:right}.totals{max-width:330px;margin-left:auto}.totals p{display:flex;justify-content:space-between;margin:0}.total{border-top:2px solid var(--border);padding-top:10px;font-size:18px}.rows{display:grid;gap:10px}.rows article{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:10px 0;border-bottom:1px solid var(--border)}.rows p,.hint{color:var(--muted-foreground);font-size:13px;margin:4px 0}:global(.payment-card){margin-top:16px}:global(.collection-card){margin-top:16px}:global(.collection-card select){height:40px;border:1px solid var(--input);border-radius:var(--radius);padding:8px;background:var(--background);color:var(--foreground)}:global(.save-collection){margin-top:14px}:global(.payment-card form){display:grid;gap:16px}:global(.payment-card select){height:40px;border:1px solid var(--input);border-radius:var(--radius);padding:8px;background:var(--background);color:var(--foreground)}.lines{display:grid;gap:14px;margin-bottom:14px}.line{display:grid;grid-template-columns:2fr repeat(4,minmax(70px,1fr)) auto;gap:8px;align-items:end;border-bottom:1px solid var(--border);padding-bottom:12px}:global(.extra){margin-top:20px}.error{color:var(--destructive)}@media(max-width:780px){.head{align-items:flex-start;flex-direction:column}.actions{justify-content:flex-start}.grid{grid-template-columns:1fr}}@media(max-width:650px){.line{grid-template-columns:repeat(2,minmax(0,1fr))}:global(.line)>:first-child{grid-column:1/-1}:global(.fields){grid-template-columns:1fr}}</style>
