<script lang="ts">
 import {getContext} from 'svelte';
 import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';
 import * as Card from '$lib/components/ui/card';
 import {Button} from '$lib/components/ui/button';
 import {Input} from '$lib/components/ui/input';
 import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
 import DatePicker from '$lib/components/forms/date-picker.svelte';
 import AmountInput from '$lib/components/forms/amount-input.svelte';
 import MoneyDisplay from '$lib/components/shared/money-display.svelte';
 import PageHeader from '$lib/components/shared/page-header.svelte';
 import LoadingScope from '$lib/components/shared/loading-scope.svelte';
 import ErrorState from '$lib/components/shared/error-state.svelte';
 import {formatDate} from '$lib/dates';
 const ws=getContext<{ready:boolean;selectedId:string;revision?:number}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(a:string,b:string)=>ui.locale==='id'?b:a;
 let items:any[]=$state([]),candidates:any[]=$state([]),accounts:any[]=$state([]),bills:any[]=$state([]),busy=$state(false),error=$state(''),name=$state(''),amount=$state(''),accountId=$state(''),cadence=$state('month'),nextCharge=$state(''),billId=$state(''),edit:any=$state(null),message=$state('');let seq=0;
 async function load(){const id=ws.selectedId,n=++seq;if(!id)return;busy=true;try{const r=await Promise.all(['subscriptions','accounts','bills'].map(p=>fetch(`/api/workspaces/${id}/${p}`))),b=await Promise.all(r.map(a=>a.json()));if(r.some(a=>!a.ok))throw new Error(b.find(a=>a.message)?.message);if(n===seq&&id===ws.selectedId){items=b[0].items;candidates=b[0].candidates;accounts=b[1].items;bills=(b[2].items??[]).filter((x:any,i:number,a:any[])=>a.findIndex(y=>y.billId===x.billId)===i).map((x:any)=>({id:x.billId,name:x.name}));}}catch(e){if(n===seq)error=e instanceof Error?e.message:String(e);}finally{if(n===seq)busy=false;}}
 $effect(()=>{void ws.revision;if(ws.ready&&ws.selectedId){edit=null;void load();}});
 async function send(path:string,body:unknown,method='POST'){const activeId=ws.selectedId;if(busy)return;busy=true;error='';try{const r=await fetch(`/api/workspaces/${activeId}/${path}`,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)}),b=await r.json();if(activeId!==ws.selectedId)return;if(!r.ok)throw new Error(b.message);if(b.algorithm)message=t('Recurring-charge review complete. Check any suggestions below; repeated charges do not prove that a service is unused.','Tinjauan biaya berulang selesai. Periksa saran di bawah; biaya berulang tidak membuktikan layanan tidak digunakan.');edit=null;await load();}catch(e){error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 function statusLabel(value:string){return ({active:t('Active tracking','Pelacakan aktif'),paused:t('Tracking paused','Pelacakan dijeda'),cancelled:t('Marked cancelled','Ditandai dibatalkan')} as Record<string,string>)[value]??value;}
 function cadenceLabel(value:string){return ({week:t('Weekly','Mingguan'),month:t('Monthly','Bulanan'),year:t('Yearly','Tahunan')} as Record<string,string>)[value]??value;}
 const cadences=$derived([{value:'week',label:t('Weekly','Mingguan')},{value:'month',label:t('Monthly','Bulanan')},{value:'year',label:t('Yearly','Tahunan')}]);
</script>
<svelte:head><title>CapyBudget · {t('Subscriptions','Langganan')}</title></svelte:head>
<LoadingScope active={busy}/><PageHeader title={t('Recurring costs, in one place','Biaya rutin, di satu tempat')} description={t('Review subscriptions and possible recurring charges. Changes here do not cancel a service with its provider.','Tinjau langganan dan kemungkinan biaya berulang. Perubahan di sini tidak membatalkan layanan dari penyedianya.')}/>
{#if error}<ErrorState title={t('Please check the details','Periksa detail')} message={error} onRetry={load}/>{/if}
<Card.Root><Card.Header><Card.Title>{t('Add subscription','Tambah langganan')}</Card.Title></Card.Header><Card.Content><form onsubmit={(e)=>{e.preventDefault();void send('subscriptions',{name,amount,accountId,cadence,nextCharge,billId});}}><div class="fields"><label for="sub-name">{t('Merchant / service','Merchant / layanan')}<Input id="sub-name" bind:value={name} required/></label><label for="sub-account">{t('Payment account','Akun pembayaran')}<ChoiceSelect id="sub-account" bind:value={accountId} required items={accounts.map(a=>({value:a.id,label:`${a.name} · ${a.currency}`}))}/></label><label for="sub-amount">{t('Amount per charge','Jumlah per tagihan')}<AmountInput id="sub-amount" bind:value={amount} currency={accounts.find(a=>a.id===accountId)?.currency} required/></label><label for="sub-cadence">{t('Schedule','Jadwal')}<ChoiceSelect id="sub-cadence" bind:value={cadence} items={cadences}/></label><label for="sub-date">{t('Next charge','Tagihan berikutnya')}<DatePicker id="sub-date" bind:value={nextCharge} required/></label><label for="sub-bill">{t('Link existing bill (optional)','Hubungkan tagihan (opsional)')}<ChoiceSelect id="sub-bill" bind:value={billId} items={[{value:'',label:'—'},...bills.map(b=>({value:b.id,label:b.name}))]}/></label></div><p>{t('Create reminders on Bills, then link the existing bill here to avoid duplicate reminders.','Buat pengingat di Tagihan, lalu hubungkan di sini untuk menghindari pengingat ganda.')}</p><Button type="submit" disabled={busy}>{t('Add subscription','Tambah langganan')}</Button></form></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{t('Review recurring charges','Tinjau biaya berulang')}</Card.Title><Card.Description>{t('Suggestions need at least three comparable expenses. You choose what to track.','Saran membutuhkan setidaknya tiga pengeluaran sebanding. Anda memilih apa yang dilacak.')}</Card.Description></Card.Header><Card.Content><Button disabled={busy} onclick={()=>send('subscriptions/detect',{})}>{t('Find recurring charges','Cari biaya berulang')}</Button>{#if message}<p role="status">{message}</p>{/if}
{#if !candidates.length}<p>{t('No suggestions waiting for review.','Tidak ada saran yang menunggu ditinjau.')}</p>{/if}
{#each candidates as c(c.id)}<section class="item"><h2>{c.merchant}</h2><MoneyDisplay amount={c.amount} currency={c.currency}/><p>{cadenceLabel(c.cadence)} · {t('Pattern match','Kesesuaian pola')}: {c.confidence==='high'?t('Strong','Kuat'):t('Moderate','Sedang')}</p><details><summary>{t('Why this was suggested','Alasan saran ini')}</summary><p>{t('Repeated charges with similar amounts and regular dates; this does not prove the service is unused.','Tagihan berulang dengan jumlah serupa dan tanggal rutin; ini tidak membuktikan layanan tidak digunakan.')}</p><ul>{#each c.evidence as e}<li>{formatDate(e.date)} · <MoneyDisplay amount={e.amount} currency={c.currency}/></li>{/each}</ul></details><div class="actions"><Button disabled={busy} onclick={()=>send(`subscription-candidates/${c.id}`,{action:'accept'})}>{t('Confirm subscription','Konfirmasi langganan')}</Button><Button disabled={busy} variant="outline" onclick={()=>send(`subscription-candidates/${c.id}`,{action:'dismiss'})}>{t('Dismiss','Abaikan')}</Button></div></section>{/each}</Card.Content></Card.Root>
<div class="list">{#each items as s(s.id)}<Card.Root><Card.Header><Card.Title>{s.name}</Card.Title><Card.Description>{statusLabel(s.status)} · {cadenceLabel(s.cadence)} · {t('Next charge: ','Tagihan berikutnya: ')}{formatDate(s.nextCharge)}</Card.Description></Card.Header><Card.Content><MoneyDisplay amount={s.amount} currency={s.currency} size="lg"/><p>{t('Estimated monthly','Estimasi bulanan')}: <MoneyDisplay amount={s.monthlyEstimate} currency={s.currency}/> · {t('Estimated yearly','Estimasi tahunan')}: <MoneyDisplay amount={s.annualEstimate} currency={s.currency}/></p>
{#if s.needsReview}<p>{t('It has been a while since your last review. Still worth keeping?','Sudah lama sejak tinjauan terakhir. Masih perlu disimpan?')}</p>{/if}{#if s.overlap}<p>{t('Another active subscription has the same merchant. Check for overlap.','Langganan aktif lain memiliki merchant sama. Periksa kemungkinan tumpang tindih.')}</p>{/if}{#if s.chargedAfterCancellation}<p>{t('A charge appeared after you marked this cancelled. Check with your provider.','Ada tagihan setelah ditandai dibatalkan. Periksa dengan penyedia layanan.')}</p>{/if}
<div class="actions"><Button variant="outline" onclick={()=>edit={...s}}>{t('Edit','Ubah')}</Button><Button variant="ghost" disabled={busy} onclick={()=>send(`subscriptions/${s.id}`,{status:s.status},'PATCH')}>{t('Mark reviewed','Tandai ditinjau')}</Button>{#if s.status!=='cancelled'}<Button variant="ghost" disabled={busy} onclick={()=>send(`subscriptions/${s.id}`,{status:'cancelled'},'PATCH')}>{t('Mark cancelled','Tandai dibatalkan')}</Button>{:else}<Button variant="ghost" onclick={()=>send(`subscriptions/${s.id}`,{status:'active'},'PATCH')}>{t('Reactivate tracking','Aktifkan pelacakan')}</Button>{/if}</div>
{#if edit?.id===s.id}<form onsubmit={(e)=>{e.preventDefault();void send(`subscriptions/${s.id}`,edit,'PATCH');}}><div class="fields"><label for="edit-sub-name">{t('Name','Nama')}<Input id="edit-sub-name" bind:value={edit.name} required/></label><label for="edit-sub-amount">{t('Amount','Jumlah')}<AmountInput id="edit-sub-amount" bind:value={edit.amount} currency={s.currency} required/></label><label for="edit-sub-date">{t('Next charge','Tagihan berikutnya')}<DatePicker id="edit-sub-date" bind:value={edit.nextCharge} required/></label><label for="edit-sub-cadence">{t('Schedule','Jadwal')}<ChoiceSelect id="edit-sub-cadence" bind:value={edit.cadence} items={cadences}/></label><label for="edit-sub-status">Status<ChoiceSelect id="edit-sub-status" bind:value={edit.status} items={[{value:'active',label:t('Active','Aktif')},{value:'paused',label:t('Paused','Dijeda')},{value:'cancelled',label:t('Cancelled','Dibatalkan')}]}/></label></div><Button type="submit" disabled={busy}>{t('Save','Simpan')}</Button><Button variant="ghost" onclick={()=>edit=null}>{t('Cancel','Batal')}</Button></form>{/if}
</Card.Content></Card.Root>{/each}</div>
<style>.fields,.list{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:16px;margin:16px 0}label{display:grid;gap:8px;font-size:14px}label :global([data-slot=select-trigger]){width:100%}.actions{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.item{margin-top:24px;padding-top:16px;border-top:2px solid var(--border)}h2{font-size:20px}summary{min-height:44px;display:flex;align-items:center;cursor:pointer}p{font-size:14px;color:var(--muted-foreground)}:global(main [data-slot=card]){margin-bottom:24px}</style>
