<script lang="ts">
  import { getContext, onMount } from 'svelte';
  import { AUTH_UI_CONTEXT, type AuthUiState } from '$lib/i18n/auth';
  import { notificationTitle, notificationMessage } from '$lib/i18n/notifications';
  import { readPrivacyMode, writePrivacyMode } from '$lib/privacy';
  import { Button } from '$lib/components/ui/button';
  type WorkspaceState={selectedId:string;ready:boolean};
  type Notice={evidence:Record<string,string|number|boolean>;resolutionReason:string|null;deliveries?:{channel:string;status:string;attempts:number}[];id:string;kind:string;sourceType:string;sourceId:string;actionType:string|null;title:string;message:string;messageKey:string;messageParams:Record<string,string|number>;severity:string;readAt:string|null;resolvedAt:string|null;dismissedAt:string|null;snoozedUntil:string|null;createdAt:string};
  const workspace=getContext<WorkspaceState>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT);
  let items:Notice[]=$state([]),filterState=$state('all'),filterType=$state(''),loading=$state(false),error=$state(''),cursor:string|null=null,more=$state(false),privacyMode=$state(false);
  const isId=$derived(ui.locale==='id');
  function sourceHref(n:Notice){if(!n.sourceId)return null;if(n.sourceType==='assistant_suggestion')return '/assistant';if(n.sourceType==='invoice')return `/invoices/${encodeURIComponent(n.sourceId)}`;if(n.sourceType==='transaction')return `/transactions?highlight=${encodeURIComponent(n.sourceId)}`;if(n.sourceType==='budget')return '/budgets';if(n.sourceType==='account')return '/accounts';if(n.sourceType==='bill_occurrence')return '/bills';if(n.sourceType==='recurring_occurrence')return '/recurring';return null;}
  let requestVersion=0;
  async function load(reset=true){const workspaceId=workspace.selectedId;if(!workspaceId)return;const version=++requestVersion;if(reset){items=[];cursor=null;}loading=true;error='';try{const params=new URLSearchParams({state:filterState,type:filterType,limit:'50'});if(cursor)params.set('cursor',cursor);const response=await fetch(`/api/workspaces/${workspaceId}/notifications?${params}`);if(!response.ok)throw new Error();const data=await response.json();if(version!==requestVersion||workspaceId!==workspace.selectedId)return;items=reset?data.items:[...items,...data.items];cursor=data.nextCursor;more=Boolean(cursor);}catch{if(version===requestVersion)error=isId?'Notifikasi gagal dimuat.':'Could not load notifications.';}finally{if(version===requestVersion)loading=false;}}
  $effect(()=>{if(workspace.ready&&workspace.selectedId)void load();});
  async function mutate(path:string,options:RequestInit){const workspaceId=workspace.selectedId;error='';try{const response=await fetch(`/api/workspaces/${workspaceId}/notifications/${path}`,options);if(!response.ok)throw new Error();if(workspaceId===workspace.selectedId)await load();}catch{if(workspaceId===workspace.selectedId)error=isId?'Perubahan gagal disimpan. Coba lagi.':'Could not save the change. Try again.';}}
  async function act(item:Notice,action:'read'|'dismiss'|'snooze'){const body=action==='snooze'?JSON.stringify({until:new Date(Date.now()+60*60*1000).toISOString()}):undefined;await mutate(`${item.id}/${action}`,{method:'PATCH',headers:body?{'content-type':'application/json'}:undefined,body});}
  async function readAll(){await mutate('read-all',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});}
  function togglePrivacy(){privacyMode=!privacyMode;writePrivacyMode(privacyMode);}
  onMount(()=>{privacyMode=readPrivacyMode();const update=()=>privacyMode=readPrivacyMode();window.addEventListener('capybudget-privacy-change',update);return()=>window.removeEventListener('capybudget-privacy-change',update);});
</script>
<svelte:head><title>{isId?'Pemberitahuan':'Notifications'} · CapyBudget</title></svelte:head>
<section class="page">
  <header><div><p class="eyebrow">{isId?'PUSAT AKTIVITAS':'ACTIVITY CENTER'}</p><h1>{isId?'Pemberitahuan':'Notifications'}</h1><p>{isId?'Pengingat tagihan, faktur, anggaran, dan saldo.':'Bill, invoice, budget, and balance reminders.'}</p></div><div class="header-actions"><Button variant="outline" aria-pressed={privacyMode} onclick={togglePrivacy}>{privacyMode?(isId?'Tampilkan jumlah':'Show amounts'):(isId?'Sembunyikan jumlah':'Hide amounts')}</Button><Button variant="outline" onclick={readAll}>{isId?'Tandai semua dibaca':'Mark all read'}</Button></div></header>
  {#if privacyMode}<p class="privacy-status" role="status">{isId?'Detail keuangan disembunyikan di kotak masuk ini.':'Financial details are hidden in this inbox.'}</p>{/if}
  <nav aria-label={isId?'Filter':'Filters'}>{#each [['all',isId?'Semua':'All'],['unread',isId?'Belum dibaca':'Unread'],['read',isId?'Dibaca':'Read'],['resolved',isId?'Selesai':'Resolved']] as [value,label]}<button aria-pressed={filterState===value} class:active={filterState===value} onclick={()=>{filterState=value;void load();}}>{label}</button>{/each}</nav>
  <label class="type-filter">{isId?'Jenis pemberitahuan':'Notification type'}<select bind:value={filterType} onchange={()=>void load()}><option value="">{isId?'Semua jenis':'All types'}</option>{#each [['bill-reminder',isId?'Tagihan':'Bills'],['invoice-due',isId?'Faktur':'Invoices'],['payment-due',isId?'Pembayaran':'Payments'],['budget-alert',isId?'Anggaran':'Budgets'],['recorded-low-balance',isId?'Saldo tercatat':'Recorded balance'],['unusual-spending',isId?'Pengeluaran tidak biasa':'Unusual spending'],['cashflow-shortfall',isId?'Proyeksi kekurangan':'Projected shortfall'],['cashflow-low-balance',isId?'Proyeksi saldo rendah':'Projected low balance'],['assistant-invoice-followup',isId?'Tindak lanjut faktur':'Invoice follow-up']] as [value,label]}<option {value}>{label}</option>{/each}</select></label>
  {#if error}<div role="alert"><p>{error}</p><Button variant="outline" onclick={()=>void load()}>{isId?'Coba lagi':'Retry'}</Button></div>{/if}{#if loading&&!items.length}<p role="status">{isId?'Memuat…':'Loading…'}</p>{:else if !items.length}<p class="empty">{isId?'Belum ada pemberitahuan di sini.':'No notifications here yet.'}</p>{:else}<div class="list">{#each items as item (item.id)}<article aria-labelledby={`notice-${item.id}`} class:unread={!item.readAt&&!item.resolvedAt}><div class="top"><span class="kind">{item.kind.replaceAll('-',' ')}</span><time datetime={item.createdAt}>{new Date(item.createdAt).toLocaleString(isId?'id-ID':'en-US')}</time></div><h2 id={`notice-${item.id}`}>{notificationTitle(item,ui.locale)}</h2><p>{privacyMode?(isId?'Detail keuangan disembunyikan.':'Financial details are hidden.'):notificationMessage(item,ui.locale)}</p>{#if item.resolvedAt}<p class="resolution">{isId?'Selesai: sumber atau kondisi telah berubah.':'Resolved: the source or condition has changed.'}</p>{/if}{#if !privacyMode&&item.kind==='unusual-spending'}<details><summary>{isId?'Mengapa pemberitahuan ini muncul?':'Why did this appear?'}</summary><p>{isId?'Riwayat':'History'}: {item.evidence.sampleCount} · {isId?'Median':'Median'}: {item.evidence.median} {item.messageParams.currency} · {isId?'Batas':'Threshold'}: {item.evidence.threshold} {item.messageParams.currency}</p></details>{/if}{#each item.deliveries??[] as delivery}{#if ['unknown','failed','retryable'].includes(delivery.status)}<p role="status" class="delivery">{delivery.channel==='email'?'Email':'Push'}: {delivery.status==='unknown'?(isId?'Hasil pengiriman belum diketahui. Tidak dikirim ulang otomatis.':'Delivery is uncertain. Automatic resend is paused.'):delivery.status==='failed'?(isId?'Pengiriman gagal. Periksa pengaturan notifikasi.':'Delivery failed. Check notification settings.'):(isId?'Pengiriman akan dicoba kembali.':'Delivery will be retried.')}</p>{/if}{/each}<div class="actions">{#if sourceHref(item)}<a class="source" href={sourceHref(item)!}>{isId?'Buka sumber':'Open source'}</a>{/if}{#if !item.readAt}<Button variant="ghost" size="sm" onclick={()=>act(item,'read')}>{isId?'Tandai dibaca':'Mark read'}</Button>{/if}{#if !item.resolvedAt}<Button variant="ghost" size="sm" onclick={()=>act(item,'snooze')}>{isId?'Tunda 1 jam':'Snooze 1 hour'}</Button><Button variant="ghost" size="sm" onclick={()=>act(item,'dismiss')}>{isId?'Selesaikan':'Dismiss'}</Button>{/if}</div></article>{/each}</div>{/if}
  {#if more}<Button variant="outline" onclick={()=>void load(false)} disabled={loading}>{isId?'Muat lainnya':'Load more'}</Button>{/if}
</section>
<style>
.page{display:grid;gap:22px}.page header{display:flex;align-items:center;justify-content:space-between;gap:16px}.page h1{margin:0;font-size:30px}.page header p{margin:6px 0;color:var(--muted-foreground)}.header-actions{display:flex;gap:8px;flex-wrap:wrap}.privacy-status{margin:0;color:var(--muted-foreground);font-size:13px}.eyebrow{font-size:11px;letter-spacing:.13em;font-weight:700;color:var(--primary)!important}nav{display:flex;gap:8px;border-bottom:1px solid var(--border)}.type-filter{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.type-filter select{background:var(--card);color:var(--foreground);border:1px solid var(--border);border-radius:8px;padding:10px;min-height:44px}nav button{min-height:44px;border:0;border-bottom:2px solid transparent;background:none;color:var(--muted-foreground);padding:10px 12px;cursor:pointer}nav button.active{border-color:var(--primary);color:var(--foreground)}.list{display:grid;gap:12px}article{padding:18px;border:1px solid var(--border);border-radius:16px;background:var(--card)}article.unread{border-inline-start:4px solid var(--primary)}article h2{font-size:17px;margin:10px 0 4px}article p{margin:4px 0;color:var(--muted-foreground)}.top,.actions{display:flex;align-items:center;gap:8px}.top{justify-content:space-between;font-size:12px;color:var(--muted-foreground)}.kind{text-transform:capitalize}.actions{justify-content:flex-end;margin-top:10px;flex-wrap:wrap}.source{min-height:44px;display:inline-flex;align-items:center;margin-right:auto;color:var(--primary);padding:8px}.empty{padding:28px;text-align:center;color:var(--muted-foreground)}@media(max-width:600px){.page header{align-items:flex-start;flex-direction:column}.top{align-items:flex-start;flex-direction:column}}
</style>
