<script lang="ts">
  import { formatDateTime } from '$lib/dates';
  import Disclosure from '$lib/components/shared/disclosure.svelte';
  import LoadingScope from '$lib/components/shared/loading-scope.svelte';
  import { cn } from '$lib/utils';
  import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
  import { getContext, onMount } from 'svelte';
  import { AUTH_UI_CONTEXT, type AuthUiState } from '$lib/i18n/auth';
  import { notificationTitle, notificationMessage } from '$lib/i18n/notifications';
  import { PRIVACY_CONTEXT,type PrivacyState,readPrivacyMode } from '$lib/privacy';
  import { Button } from '$lib/components/ui/button';
  import PageHeader from '$lib/components/shared/page-header.svelte';
  import EmptyState from '$lib/components/shared/empty-state.svelte';
  import ErrorState from '$lib/components/shared/error-state.svelte';
  import LoadingSkeleton from '$lib/components/shared/loading-skeleton.svelte';
  import StatusBadge from '$lib/components/shared/status-badge.svelte';
  type WorkspaceState={selectedId:string;ready:boolean};
  type Notice={evidence:Record<string,string|number|boolean>;resolutionReason:string|null;deliveries?:{channel:string;status:string;attempts:number}[];id:string;kind:string;sourceType:string;sourceId:string;actionType:string|null;title:string;message:string;messageKey:string;messageParams:Record<string,string|number>;severity:string;readAt:string|null;resolvedAt:string|null;dismissedAt:string|null;snoozedUntil:string|null;createdAt:string};
  const privacy=getContext<PrivacyState>(PRIVACY_CONTEXT);
  $effect(()=>{privacyMode=privacy.hidden;});
  const workspace=getContext<WorkspaceState>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT);
  let items:Notice[]=$state([]),filterState=$state('all'),filterType=$state(''),loading=$state(false),error=$state(''),cursor:string|null=null,more=$state(false),privacyMode=$state(true);
  const isId=$derived(ui.locale==='id');
  const severityTone=(s:string)=>s==='urgent'||s==='critical'?'expense':s==='warning'?'warning':'neutral';
  function sourceHref(n:Notice){if(!n.sourceId)return null;if(n.sourceType==='assistant_suggestion')return '/assistant';if(n.sourceType==='invoice')return `/invoices/${encodeURIComponent(n.sourceId)}`;if(n.sourceType==='transaction')return `/transactions?highlight=${encodeURIComponent(n.sourceId)}`;if(n.sourceType==='budget')return '/budgets';if(n.sourceType==='account')return '/accounts';if(n.sourceType==='bill_occurrence')return '/bills';if(n.sourceType==='recurring_occurrence')return '/recurring';return null;}
  let requestVersion=0;
  async function load(reset=true){const workspaceId=workspace.selectedId;if(!workspaceId)return;const version=++requestVersion;if(reset){items=[];cursor=null;}loading=true;error='';try{const params=new URLSearchParams({state:filterState,type:filterType,limit:'50'});if(cursor)params.set('cursor',cursor);const response=await fetch(`/api/workspaces/${workspaceId}/notifications?${params}`);if(!response.ok)throw new Error();const data=await response.json();if(version!==requestVersion||workspaceId!==workspace.selectedId)return;items=reset?data.items:[...items,...data.items];cursor=data.nextCursor;more=Boolean(cursor);}catch{if(version===requestVersion)error=isId?'Notifikasi gagal dimuat.':'Could not load notifications.';}finally{if(version===requestVersion)loading=false;}}
  $effect(()=>{void (workspace as {revision?:number}).revision;if(workspace.ready&&workspace.selectedId)void load();});
  async function mutate(path:string,options:RequestInit){const workspaceId=workspace.selectedId;error='';try{const response=await fetch(`/api/workspaces/${workspaceId}/notifications/${path}`,options);if(!response.ok)throw new Error();if(workspaceId===workspace.selectedId)await load();}catch{if(workspaceId===workspace.selectedId)error=isId?'Perubahan gagal disimpan. Coba lagi.':'Could not save the change. Try again.';}}
  async function act(item:Notice,action:'read'|'dismiss'|'snooze'){const body=action==='snooze'?JSON.stringify({until:new Date(Date.now()+60*60*1000).toISOString()}):undefined;await mutate(`${item.id}/${action}`,{method:'PATCH',headers:body?{'content-type':'application/json'}:undefined,body});}
  async function readAll(){await mutate('read-all',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});}
  onMount(()=>{privacyMode=readPrivacyMode();const update=()=>privacyMode=readPrivacyMode();window.addEventListener('capybudget-privacy-change',update);return()=>window.removeEventListener('capybudget-privacy-change',update);});
</script>
<LoadingScope active={!!loading} />
<svelte:head><title>{isId?'Pemberitahuan':'Notifications'} · CapyBudget</title></svelte:head>
<PageHeader eyebrow={isId?'PUSAT AKTIVITAS':'ACTIVITY CENTER'} title={isId?'Pemberitahuan':'Notifications'} description={isId?'Pengingat tagihan, faktur, anggaran, dan saldo.':'Bill, invoice, budget, and balance reminders.'}>
  {#snippet actions()}<Button variant="outline" onclick={readAll}>{isId?'Tandai semua dibaca':'Mark all read'}</Button>{/snippet}
</PageHeader>
<section class="page" aria-label={isId?'Pemberitahuan':'Notifications'}>
  {#if privacyMode}<p class="privacy-status" role="status">{isId?'Detail keuangan disembunyikan di kotak masuk ini.':'Financial details are hidden in this inbox.'}</p>{/if}
  <nav aria-label={isId?'Filter':'Filters'}>{#each [['all',isId?'Semua':'All'],['unread',isId?'Belum dibaca':'Unread'],['read',isId?'Dibaca':'Read'],['resolved',isId?'Selesai':'Resolved']] as [value,label]}<Button variant="ghost" aria-pressed={filterState===value} class={cn('', {"active": filterState===value})} onclick={()=>{filterState=value;void load();}}>{label}</Button>{/each}</nav>
  <label class="type-filter">{isId?'Jenis pemberitahuan':'Notification type'}<ChoiceSelect bind:value={filterType} onValueChange={()=>void load()} items={[{value: '', label: String(isId?'Semua jenis':'All types')}, ...([['bill-reminder',isId?'Tagihan':'Bills'],['invoice-due',isId?'Faktur':'Invoices'],['payment-due',isId?'Pembayaran':'Payments'],['budget-alert',isId?'Anggaran':'Budgets'],['recorded-low-balance',isId?'Saldo tercatat':'Recorded balance'],['unusual-spending',isId?'Pengeluaran tidak biasa':'Unusual spending'],['cashflow-shortfall',isId?'Proyeksi kekurangan':'Projected shortfall'],['cashflow-low-balance',isId?'Proyeksi saldo rendah':'Projected low balance'],['assistant-invoice-followup',isId?'Tindak lanjut faktur':'Invoice follow-up']]).flatMap(([value,label]) => [{value: value, label: String(label)}])]} /></label>
  {#if error}<ErrorState title={isId?'Terjadi kesalahan':'Something went wrong'} message={error} retryLabel={isId?'Coba lagi':'Retry'} onRetry={()=>void load()} />{/if}
  {#if loading&&!items.length}<LoadingSkeleton rows={4} label={isId?'Memuat…':'Loading…'} />
  {:else if !items.length}<EmptyState title={isId?'Pemberitahuan':'Notifications'} body={isId?'Belum ada pemberitahuan di sini.':'No notifications here yet.'} actionLabel={isId?'Atur pengingat':'Reminder settings'} actionHref="/settings/notifications" />
  {:else}<div class="list">{#each items as item (item.id)}<article aria-labelledby={`notice-${item.id}`} class:unread={!item.readAt&&!item.resolvedAt}><div class="top"><span class="kind"><StatusBadge tone={severityTone(item.severity)}>{item.kind.replaceAll('-',' ')}</StatusBadge></span><time datetime={item.createdAt}>{formatDateTime(item.createdAt, isId?'id-ID':'en-US')}</time></div><h2 id={`notice-${item.id}`}>{notificationTitle(item,ui.locale)} <span class="sr-only">{item.readAt||item.resolvedAt?(isId?'(dibaca)':'(read)'):(isId?'(belum dibaca)':'(unread)')}</span></h2><p>{privacyMode?(isId?'Detail keuangan disembunyikan.':'Financial details are hidden.'):notificationMessage(item,ui.locale)}</p>{#if item.resolvedAt}<p class="resolution">{isId?'Selesai: sumber atau kondisi telah berubah.':'Resolved: the source or condition has changed.'}</p>{/if}{#if !privacyMode&&item.kind==='unusual-spending'}<Disclosure>{#snippet title()}{isId?'Mengapa pemberitahuan ini muncul?':'Why did this appear?'}{/snippet}<p>{isId?'Riwayat':'History'}: {item.evidence.sampleCount} · {isId?'Median':'Median'}: {item.evidence.median} {item.messageParams.currency} · {isId?'Batas':'Threshold'}: {item.evidence.threshold} {item.messageParams.currency}</p></Disclosure>{/if}{#each item.deliveries??[] as delivery}{#if ['unknown','failed','retryable'].includes(delivery.status)}<p role="status" class="delivery">{delivery.channel==='email'?'Email':'Push'}: {delivery.status==='unknown'?(isId?'Hasil pengiriman belum diketahui. Tidak dikirim ulang otomatis.':'Delivery is uncertain. Automatic resend is paused.'):delivery.status==='failed'?(isId?'Pengiriman gagal. Periksa pengaturan notifikasi.':'Delivery failed. Check notification settings.'):(isId?'Pengiriman akan dicoba kembali.':'Delivery will be retried.')}</p>{/if}{/each}<div class="actions">{#if sourceHref(item)}<a class="source" href={sourceHref(item)!}>{isId?'Buka sumber':'Open source'}</a>{/if}{#if !item.readAt}<Button variant="ghost" size="sm" onclick={()=>act(item,'read')}>{isId?'Tandai dibaca':'Mark read'}</Button>{/if}{#if !item.resolvedAt}<Button variant="ghost" size="sm" onclick={()=>act(item,'snooze')}>{isId?'Tunda 1 jam':'Snooze 1 hour'}</Button><Button variant="ghost" size="sm" onclick={()=>act(item,'dismiss')}>{isId?'Selesaikan':'Dismiss'}</Button>{/if}</div></article>{/each}</div>{/if}
  {#if more}<Button variant="outline" onclick={()=>void load(false)} disabled={loading}>{isId?'Muat lainnya':'Load more'}</Button>{/if}
</section>
<style>
.page{display:grid;gap:16px}.privacy-status{margin:0;color:var(--muted-foreground);font-size:13px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}nav{display:flex;gap:8px;border-bottom:1px solid var(--border);overflow-x:auto}.type-filter{display:flex;align-items:center;gap:12px;flex-wrap:wrap}nav :global([data-slot="button"]){min-height:44px;border:0;border-bottom:2px solid transparent;background:none;color:var(--muted-foreground);padding:8px 12px;cursor:pointer;white-space:nowrap}nav :global([data-slot="button"].active){border-color:var(--primary);color:var(--foreground)}.list{display:grid;gap:12px}article{padding:16px;border:1px solid var(--border);border-radius:16px;background:var(--card)}article.unread{border-inline-start:4px solid var(--primary)}article h2{font-size:17px;margin:8px 0 4px}article p{margin:4px 0;color:var(--muted-foreground)}.top,.actions{display:flex;align-items:center;gap:8px}.top{justify-content:space-between;font-size:12px;color:var(--muted-foreground)}.kind{text-transform:capitalize}.actions{justify-content:flex-end;margin-top:8px;flex-wrap:wrap}.source{min-height:44px;display:inline-flex;align-items:center;margin-right:auto;color:var(--brand-ink);padding:8px}@media(max-width:600px){.top{align-items:flex-start;flex-direction:column}}
</style>
