import { Elysia } from 'elysia';
import type { TransactionSql } from 'postgres';
import { auth } from '../auth';
import { client } from '../db';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const amount=/^(?:0|[1-9]\d{0,14})(?:\.\d{1,4})?$/;
const balanceAmount=/^-?(?:0|[1-9]\d{0,14})(?:\.\d{1,4})?$/;
type Row=Record<string,any>;
const q=(tx:TransactionSql,sql:string,values:unknown[]=[])=>(tx.unsafe(sql,values as never[]));
const fail=(status:number,code:string,message:string)=>Response.json({code,message},{status,headers:{'Cache-Control':'private, no-store'}});

async function scope<T>(request:Request,workspaceId:string,run:(tx:TransactionSql,userId:string)=>Promise<T>):Promise<T|Response>{
 if(!uuid.test(workspaceId))return fail(400,'INVALID_WORKSPACE_ID','Workspace ID is invalid.');
 const session=await auth.api.getSession({headers:request.headers});if(!session)return fail(401,'AUTH_REQUIRED','Sign in to continue.');if(!session.user.emailVerified)return fail(403,'EMAIL_VERIFICATION_REQUIRED','Verify your email to continue.');
 try{return await client.begin(async tx=>{await q(tx,"select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[session.user.id,workspaceId]);const [member]=await q(tx,'select 1 from workspace_memberships where workspace_id=$1 and user_id=$2',[workspaceId,session.user.id]);if(!member)return fail(404,'WORKSPACE_NOT_FOUND','Workspace not found.');return run(tx,session.user.id);}) as T|Response;}
 catch(error){const e=error as {code?:string};console.error('Notification request failed',{sqlState:e.code??'unknown'});return fail(500,'NOTIFICATION_FAILED','The request could not be completed.');}
}

function isResponse(value:unknown):value is Response{return value instanceof Response;}
function validateSnooze(value:unknown){if(typeof value!=='string')return false;const date=new Date(value);return Number.isFinite(date.valueOf())&&date.valueOf()>Date.now()&&date.valueOf()<=Date.now()+30*86400000;}
async function queueUnusualReview(tx:TransactionSql,workspaceId:string,userId:string,scopeKey:string){
 await q(tx,"insert into finance_notification_evaluation_state(workspace_id,user_id,rule_key,scope_key,period_key,state,dirty_version,processed_version) select $1,$2,'unusual_spending',$3,'dirty',jsonb_build_object('fromDate',((now() at time zone w.timezone)::date-180)::text,'throughDate',(now() at time zone w.timezone)::date::text,'lastId',null),1,0 from workspaces w where w.id=$1 on conflict(workspace_id,user_id,rule_key,scope_key,period_key) do update set state=jsonb_build_object('fromDate',least(coalesce(nullif(finance_notification_evaluation_state.state->>'fromDate','')::date,(excluded.state->>'fromDate')::date),(excluded.state->>'fromDate')::date)::text,'throughDate',greatest(coalesce(nullif(finance_notification_evaluation_state.state->>'throughDate','')::date,(excluded.state->>'throughDate')::date),(excluded.state->>'throughDate')::date)::text,'lastId',null),dirty_version=finance_notification_evaluation_state.dirty_version+1,next_evaluation_at=now(),updated_at=now()",[workspaceId,userId,scopeKey]);
}

export const notificationRoutes=new Elysia({name:'notification-routes'})
 .onBeforeHandle(({set})=>{set.headers['Cache-Control']='private, no-store';})
 .get('/api/workspaces/:workspaceId/notification-delivery-health',({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  const rows=await q(tx,"select status,count(*)::int as count from finance_notification_deliveries where workspace_id=$1 and user_id=$2 group by status",[params.workspaceId,userId]);
  const [pending]=await q(tx,"select min(created_at) as oldest from finance_notification_deliveries where workspace_id=$1 and user_id=$2 and status in ('pending','retryable')",[params.workspaceId,userId]);
  return {counts:Object.fromEntries(rows.map(row=>[row.status,Number(row.count)])),oldestPendingAt:pending?.oldest??null};
 }))
 .get('/api/workspaces/:workspaceId/notifications/unread-count',({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  const [row]=await q(tx,"select count(*)::int as count from finance_notifications where workspace_id=$1 and user_id=$2 and read_at is null and resolved_at is null and dismissed_at is null and expires_at>now() and (snoozed_until is null or snoozed_until<=now())",[params.workspaceId,userId]);return {count:Number(row.count)};
 }))
 .get('/api/workspaces/:workspaceId/notifications',({request,params,query})=>scope(request,params.workspaceId,async(tx,userId)=>{
  const limit=Math.min(100,Math.max(1,Number(query.limit??25)||25)),state=String(query.state??'all'),type=String(query.type??'');
  if(!['all','unread','read','resolved'].includes(state))return fail(422,'INVALID_NOTIFICATION_FILTER','Choose a supported notification filter.');
  if(type.length>60)return fail(422,'INVALID_NOTIFICATION_TYPE','Notification type is too long.');
  const values:unknown[]=[params.workspaceId,userId],where=['workspace_id=$1','user_id=$2','expires_at>now()'];
  if(state==='unread')where.push('read_at is null','resolved_at is null','dismissed_at is null','(snoozed_until is null or snoozed_until<=now())');
  if(state==='read')where.push('read_at is not null','dismissed_at is null');
  if(state==='resolved')where.push('(resolved_at is not null or dismissed_at is not null)');
  if(type){values.push(type);where.push('kind=$'+values.length);}
  if(query.cursor){const [created,id]=String(query.cursor).split('|');if(!created||!uuid.test(id??'')||!Number.isFinite(Date.parse(created)))return fail(422,'INVALID_CURSOR','Notification cursor is invalid.');values.push(created,id);where.push('(created_at,id)<($'+(values.length-1)+'::timestamptz,$'+values.length+'::uuid)');}
  values.push(limit+1);const items=await q(tx,'select id,kind,source_type as "sourceType",source_id as "sourceId",title,message,message_key as "messageKey",message_params as "messageParams",evidence,severity,action_type as "actionType",read_at as "readAt",dismissed_at as "dismissedAt",snoozed_until as "snoozedUntil",resolved_at as "resolvedAt",resolution_reason as "resolutionReason",created_at as "createdAt",(select coalesce(jsonb_agg(jsonb_build_object(\'channel\',d.channel,\'status\',d.status,\'attempts\',d.attempts)),\'[]\'::jsonb) from finance_notification_deliveries d where d.workspace_id=finance_notifications.workspace_id and d.user_id=finance_notifications.user_id and d.notification_id=finance_notifications.id) as deliveries from finance_notifications where '+where.join(' and ')+' order by created_at desc,id desc limit $'+values.length,values);
  const page=items.slice(0,limit),last=page.at(-1);return {items:page,nextCursor:items.length>limit&&last?String(last.createdAt)+'|'+String(last.id):null};
 }))
 .patch('/api/workspaces/:workspaceId/notifications/:id/read',({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  if(!uuid.test(params.id))return fail(400,'INVALID_NOTIFICATION_ID','Notification ID is invalid.');
  const [row]=await q(tx,'update finance_notifications set read_at=coalesce(read_at,now()),updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 returning id,read_at as "readAt"',[params.workspaceId,userId,params.id]);return row??fail(404,'NOTIFICATION_NOT_FOUND','Notification not found.');
 }))
 .post('/api/workspaces/:workspaceId/notifications/read-all',async({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  const body=await request.json().catch(()=>({})) as {before?:unknown};let before:string|undefined;
  if(body.before!==undefined){if(typeof body.before!=='string'||!Number.isFinite(Date.parse(body.before)))return fail(422,'INVALID_CUTOFF','Choose a valid read-all cutoff.');before=body.before;}
  await q(tx,'update finance_notifications set read_at=coalesce(read_at,now()),updated_at=now() where workspace_id=$1 and user_id=$2 and read_at is null and resolved_at is null and dismissed_at is null and ($3::timestamptz is null or created_at<=$3::timestamptz)',[params.workspaceId,userId,before??null]);return {ok:true};
 }))
 .patch('/api/workspaces/:workspaceId/notifications/:id/dismiss',({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  if(!uuid.test(params.id))return fail(400,'INVALID_NOTIFICATION_ID','Notification ID is invalid.');
  const [row]=await q(tx,'update finance_notifications set dismissed_at=coalesce(dismissed_at,now()),read_at=coalesce(read_at,now()),updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and resolved_at is null returning id,dismissed_at as "dismissedAt"',[params.workspaceId,userId,params.id]);if(!row)return fail(404,'NOTIFICATION_NOT_FOUND','Notification not found.');
  await q(tx,"update finance_notification_deliveries set status='cancelled',updated_at=now() where workspace_id=$1 and user_id=$2 and notification_id=$3 and status in ('pending','retryable')",[params.workspaceId,userId,params.id]);return row;
 }))
 .patch('/api/workspaces/:workspaceId/notifications/:id/snooze',async({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  if(!uuid.test(params.id))return fail(400,'INVALID_NOTIFICATION_ID','Notification ID is invalid.');const body=await request.json().catch(()=>null) as {until?:unknown}|null;if(!body||!validateSnooze(body.until))return fail(422,'INVALID_SNOOZE','Choose a future time within 30 days.');
  const [row]=await q(tx,'update finance_notifications set snoozed_until=$4::timestamptz,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and resolved_at is null and expires_at>$4::timestamptz returning id,snoozed_until as "snoozedUntil"',[params.workspaceId,userId,params.id,body.until]);if(row)await q(tx,"update finance_notification_deliveries set available_at=greatest(available_at,$4::timestamptz),updated_at=now() where workspace_id=$1 and user_id=$2 and notification_id=$3 and status in ('pending','retryable')",[params.workspaceId,userId,params.id,body.until]);return row??fail(404,'NOTIFICATION_NOT_FOUND','Notification not found.');
 }))
 .get('/api/workspaces/:workspaceId/notification-rules',({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>({items:await q(tx,'select r.id,r.rule_type as "ruleType",r.scope_key as "scopeKey",r.account_id as "accountId",r.category_id as "categoryId",r.currency,r.enabled,r.parameters,r.version,a.name as "accountName",c.name as "categoryName" from finance_notification_rules r left join accounts a on a.workspace_id=r.workspace_id and a.id=r.account_id left join categories c on c.workspace_id=r.workspace_id and c.id=r.category_id where r.workspace_id=$1 and r.user_id=$2 order by r.rule_type,r.scope_key',[params.workspaceId,userId])})))
 .put('/api/workspaces/:workspaceId/notification-rules',async({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body||!['low_balance','unusual_spending'].includes(String(body.ruleType))||typeof body.enabled!=='boolean')return fail(422,'INVALID_NOTIFICATION_RULE','Provide a rule type and enabled state.');
  if(body.ruleType==='low_balance'){
   if(!uuid.test(String(body.accountId))||typeof body.threshold!=='string'||!balanceAmount.test(body.threshold))return fail(422,'INVALID_NOTIFICATION_RULE','Provide an account and valid balance threshold.');
   const [account]=await q(tx,"select id from accounts where workspace_id=$1 and id=$2 and kind in ('cash','bank','e_wallet','savings') and archived_at is null and deleted_at is null",[params.workspaceId,body.accountId]);if(!account)return fail(404,'ACCOUNT_NOT_FOUND','Liquid account not found.');
   const cfg=JSON.stringify({threshold:body.threshold}),key='account:'+String(body.accountId),[existing]=await q(tx,"select version from finance_notification_rules where workspace_id=$1 and user_id=$2 and rule_type='low_balance' and scope_key=$3 for update",[params.workspaceId,userId,key]);let row:Row|undefined;
   if(existing){if(!Number.isInteger(body.version)||Number(body.version)!==Number(existing.version))return fail(409,'STALE_NOTIFICATION_RULE','Reload notification settings before saving this rule.');[row]=await q(tx,"update finance_notification_rules set enabled=$4,parameters=$5::jsonb,version=version+1,updated_at=now() where workspace_id=$1 and user_id=$2 and rule_type='low_balance' and scope_key=$3 and version=$6 returning id,rule_type as \"ruleType\",scope_key as \"scopeKey\",account_id as \"accountId\",enabled,parameters,version",[params.workspaceId,userId,key,body.enabled,cfg,body.version]);}
   else{[row]=await q(tx,"insert into finance_notification_rules(workspace_id,user_id,rule_type,scope_key,account_id,enabled,parameters) values($1,$2,'low_balance',$3,$4,$5,$6::jsonb) on conflict(workspace_id,user_id,rule_type,scope_key) do nothing returning id,rule_type as \"ruleType\",scope_key as \"scopeKey\",account_id as \"accountId\",enabled,parameters,version",[params.workspaceId,userId,key,body.accountId,body.enabled,cfg]);}
   if(!row)return fail(409,'STALE_NOTIFICATION_RULE','Reload notification settings before saving this rule.');return {rule:row};
  }
  if(typeof body.currency!=='string'||! /^[A-Z]{3}$/.test(body.currency)||typeof body.minimumAmount!=='string'||!amount.test(body.minimumAmount)||!/[1-9]/.test(body.minimumAmount)||(body.categoryId!==null&&body.categoryId!==undefined&&!uuid.test(String(body.categoryId))))return fail(422,'INVALID_NOTIFICATION_RULE','Provide a currency, positive minimum amount, and optional category.');
  const categoryId=body.categoryId?String(body.categoryId):null;if(categoryId){const [category]=await q(tx,"select id from categories where workspace_id=$1 and id=$2 and type='expense' and archived_at is null",[params.workspaceId,categoryId]);if(!category)return fail(404,'CATEGORY_NOT_FOUND','Expense category not found.');}
  const key=(categoryId??'uncategorized')+':'+String(body.currency),cfg=JSON.stringify({minimumAmount:body.minimumAmount}),[existing]=await q(tx,"select version from finance_notification_rules where workspace_id=$1 and user_id=$2 and rule_type='unusual_spending' and scope_key=$3 for update",[params.workspaceId,userId,key]);let row:Row|undefined;
  if(existing){if(!Number.isInteger(body.version)||Number(body.version)!==Number(existing.version))return fail(409,'STALE_NOTIFICATION_RULE','Reload notification settings before saving this rule.');[row]=await q(tx,"update finance_notification_rules set enabled=$4,parameters=$5::jsonb,version=version+1,updated_at=now() where workspace_id=$1 and user_id=$2 and rule_type='unusual_spending' and scope_key=$3 and version=$6 returning id,rule_type as \"ruleType\",scope_key as \"scopeKey\",category_id as \"categoryId\",currency,enabled,parameters,version",[params.workspaceId,userId,key,body.enabled,cfg,body.version]);}
  else{[row]=await q(tx,"insert into finance_notification_rules(workspace_id,user_id,rule_type,scope_key,category_id,currency,enabled,parameters) values($1,$2,'unusual_spending',$3,$4,$5,$6,$7::jsonb) on conflict(workspace_id,user_id,rule_type,scope_key) do nothing returning id,rule_type as \"ruleType\",scope_key as \"scopeKey\",category_id as \"categoryId\",currency,enabled,parameters,version",[params.workspaceId,userId,key,categoryId,body.currency,body.enabled,cfg]);}
  if(!row)return fail(409,'STALE_NOTIFICATION_RULE','Reload notification settings before saving this rule.');if(body.enabled)await queueUnusualReview(tx,params.workspaceId,userId,key);return {rule:row};
 }))
 .get('/api/workspaces/:workspaceId/notification-preferences',({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  const prefs=await q(tx,'select event_type as "eventType",channel,enabled,version from finance_notification_preferences where workspace_id=$1 and user_id=$2',[params.workspaceId,userId]);const get=(event:string,channel:string,fallback:boolean)=>prefs.find((p:any)=>p.eventType===event&&p.channel===channel)?.enabled??fallback;
  const channels:Record<string,Record<string,boolean>>={};for(const row of prefs){channels[row.eventType]??={};channels[row.eventType]![row.channel]=row.enabled;}
  return {channels,version:Math.max(1,...prefs.map((p:any)=>Number(p.version))),emailBillReminders:get('bill-reminder','email',true),pushBillReminders:get('bill-reminder','push',false),emailAssistantAlerts:get('assistant-alert','email',false),pushAssistantAlerts:get('assistant-alert','push',false)};
 }))
 .put('/api/workspaces/:workspaceId/notification-preferences',async({request,params})=>scope(request,params.workspaceId,async(tx,userId)=>{
  const body=await request.json().catch(()=>null) as Record<string,any>|null;if(!body)return fail(422,'INVALID_PREFERENCES','Provide notification preferences.');
  await q(tx,"select pg_advisory_xact_lock(hashtextextended('capybudget:notification-preferences:'||$1||':'||$2,0))",[params.workspaceId,userId]);
  if(body.version!==undefined&&(!Number.isInteger(body.version)||body.version<1))return fail(422,'INVALID_PREFERENCES','Preference version is invalid.');const [currentPreferenceVersion]=await q(tx,'select coalesce(max(version),1)::int as version from finance_notification_preferences where workspace_id=$1 and user_id=$2',[params.workspaceId,userId]),preferenceVersion=Number(currentPreferenceVersion.version);if(body.version!==undefined&&preferenceVersion!==body.version)return fail(409,'STALE_NOTIFICATION_PREFERENCES','Reload notification settings before saving preferences.');
  const legacy:[string,string,string][]=[['emailBillReminders','bill-reminder','email'],['pushBillReminders','bill-reminder','push'],['emailAssistantAlerts','assistant-alert','email'],['pushAssistantAlerts','assistant-alert','push']];
  const updates:{event:string;channel:string;enabled:boolean}[]=[];for(const [field,event,channel] of legacy)if(body[field]!==undefined){if(typeof body[field]!=='boolean')return fail(422,'INVALID_PREFERENCES','Preference values must be boolean.');updates.push({event,channel,enabled:body[field]});}
  if(body.channels!==undefined){if(!body.channels||typeof body.channels!=='object'||Array.isArray(body.channels))return fail(422,'INVALID_PREFERENCES','Provide event channel preferences.');for(const [event,channels] of Object.entries(body.channels)){if(!/^[a-z][a-z0-9-]{1,59}$/.test(event)||!channels||typeof channels!=='object'||Array.isArray(channels))return fail(422,'INVALID_PREFERENCES','An event preference is invalid.');for(const [channel,value] of Object.entries(channels as Record<string,unknown>)){if(!['in_app','email','push'].includes(channel)||typeof value!=='boolean')return fail(422,'INVALID_PREFERENCES','Supported channels are in-app, email, and push.');updates.push({event,channel,enabled:value});}}}
  if(!updates.length)return fail(422,'INVALID_PREFERENCES','Choose at least one preference.');
  if(updates.some(p=>p.channel==='push'&&p.enabled)){const [sub]=await q(tx,'select id from push_subscriptions where workspace_id=$1 and user_id=$2 limit 1',[params.workspaceId,userId]);if(!sub)return fail(422,'PUSH_DEVICE_REQUIRED','Enable browser notifications on this device first.');}
  const nextPreferenceVersion=preferenceVersion+1;for(const item of updates){await q(tx,'insert into finance_notification_preferences(workspace_id,user_id,event_type,channel,enabled,version,updated_at) values($1,$2,$3,$4,$5,$6,now()) on conflict(workspace_id,user_id,event_type,channel) do update set enabled=excluded.enabled,version=excluded.version,updated_at=now()',[params.workspaceId,userId,item.event,item.channel,item.enabled,nextPreferenceVersion]);if(item.channel==='in_app'&&!item.enabled){const changed=await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='preference_disabled',updated_at=now() where workspace_id=$1 and user_id=$2 and kind=$3 and resolved_at is null returning id",[params.workspaceId,userId,item.event]);if(changed.length)await q(tx,"update finance_notification_deliveries set status='cancelled',updated_at=now() where workspace_id=$1 and user_id=$2 and notification_id=any($3::uuid[]) and status in ('pending','retryable')",[params.workspaceId,userId,changed.map((row:any)=>row.id)]);}if(!item.enabled&&item.channel!=='in_app')await q(tx,"update finance_notification_deliveries d set status='cancelled',updated_at=now() from finance_notifications n where d.workspace_id=$1 and d.user_id=$2 and d.notification_id=n.id and n.workspace_id=d.workspace_id and n.user_id=d.user_id and n.kind=$3 and d.channel=$4 and d.status in ('pending','retryable')",[params.workspaceId,userId,item.event,item.channel]);}
  const prefs=await q(tx,'select event_type as "eventType",channel,enabled,version from finance_notification_preferences where workspace_id=$1 and user_id=$2',[params.workspaceId,userId]);const channels:Record<string,Record<string,boolean>>={};for(const row of prefs){channels[row.eventType]??={};channels[row.eventType]![row.channel]=row.enabled;}return {channels,version:Math.max(1,...prefs.map((p:any)=>Number(p.version)))};
 }));
