import { client } from '../db';
import type { TransactionSql } from 'postgres';
import { toUnits, fromUnits } from '../assistant/money';
import { workspaceHour, workspaceToday } from '../tracking/recurrence';
import { exceedsUnusualThreshold, unusualThreshold } from './math';

type Tx=TransactionSql;
type Row=Record<string,any>;
const q=(tx:Tx,sql:string,values:unknown[]=[])=>(tx.unsafe(sql,values as never[]));
const shift=(day:string,n:number)=>{const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};

async function notify(tx:Tx,ws:string,user:string,n:{kind:string;source:string;sourceType:string;key:string;title:string;message:string;messageKey:string;params?:any;evidence?:any;action:string;severity?:string;ruleVersion?:string}){
 const [pref]=await q(tx,"select enabled from finance_notification_preferences where workspace_id=$1 and user_id=$2 and event_type=$3 and channel='in_app'",[ws,user,n.kind]);if(pref?.enabled===false)return;
 const [cutover]=await q(tx,"select state->>'cutoverAt' as at from finance_notification_evaluation_state where workspace_id=$1 and user_id=$2 and rule_key='rollout' and scope_key='workspace' and period_key='notifications-mvp'",[ws,user]);
 if(cutover?.at){
  const [existing]=await q(tx,'select id from finance_notifications where workspace_id=$1 and user_id=$2 and dedupe_key=$3',[ws,user,n.key]);
  const sourceTables:Record<string,string>={tax_reminder:'business_tax_reminders',vendor_bill:'vendor_bills',invoice:'invoices',bill_occurrence:'bill_occurrences',recurring_occurrence:'recurring_occurrences',budget:'budgets',transaction:'transactions'};
  const table=sourceTables[n.sourceType];
  if(!existing&&table){const [source]=await q(tx,`select ${['transactions','budgets','invoices'].includes(table)?'updated_at':'created_at'} as created_at from ${table} where workspace_id=$1 and id=$2`,[ws,n.source]);
   if(source&&new Date(source.created_at)<new Date(cutover.at)){
    if(n.messageKey.endsWith('.overdue')||n.kind==='unusual-spending')return;
    if(n.kind==='budget-alert'){const [changed]=await q(tx,'with recursive descendants(id) as (select category_id from budgets where workspace_id=$1 and id=$3 union all select c.id from categories c join descendants d on c.parent_id=d.id where c.workspace_id=$1) select 1 from tracking_allocations where workspace_id=$1 and updated_at>$2::timestamptz and category_id in(select id from descendants) and currency=$4 and occurred_at >= $5::date and occurred_at < $6::date limit 1',[ws,cutover.at,n.source,n.params?.currency,n.evidence?.periodStart,n.evidence?.periodEnd]);if(!changed)return;}
   }
  }
 }
 await q(tx,"insert into finance_notifications(workspace_id,user_id,kind,source_id,source_type,dedupe_key,title,message,message_key,message_params,evidence,action_type,severity,rule_version) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12,$13,$14) on conflict(workspace_id,user_id,dedupe_key) do update set source_type=excluded.source_type,title=excluded.title,message=excluded.message,message_key=excluded.message_key,message_params=excluded.message_params,evidence=excluded.evidence,action_type=excluded.action_type,severity=excluded.severity,updated_at=now(),resolved_at=null,resolution_reason=null",[ws,user,n.kind,n.source,n.sourceType,n.key,n.title,n.message,n.messageKey,JSON.stringify(n.params??{}),JSON.stringify(n.evidence??{}),n.action,n.severity??'attention',n.ruleVersion??null]);
}
async function resolve(tx:Tx,ws:string,user:string,kind:string,sourceType:string,source:string,reason:string){await q(tx,'update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason=$6,updated_at=now() where workspace_id=$1 and user_id=$2 and kind=$3 and source_type=$4 and source_id=$5 and resolved_at is null',[ws,user,kind,sourceType,source,reason]);}

async function evaluateUnusualCandidate(tx:Tx,ws:string,user:string,scopeKey:string,categoryId:string|null,currency:string,item:Row,minimum:bigint,today:string){
 const day=String(item.occurred_at).slice(0,10),baseline:Row[]=await q(tx,"select amount::text,occurred_at from transactions where workspace_id=$1 and deleted_at is null and type='expense' and currency=$2 and occurred_at >= $3::date and occurred_at < $4::date and (($5::uuid is null and category_id is null) or category_id=$5) order by amount",[ws,currency,shift(day,-90),day,categoryId]);
 if(baseline.length<10||new Set(baseline.map(x=>String(x.occurred_at).slice(0,10))).size<4){await resolve(tx,ws,user,'unusual-spending','transaction',String(item.id),'insufficient_history');return;}
 const amounts=baseline.map(x=>toUnits(String(x.amount))),{median:med,mad,threshold:cutoff}=unusualThreshold(amounts,minimum);
 if(!exceedsUnusualThreshold(toUnits(String(item.amount)),cutoff)){await resolve(tx,ws,user,'unusual-spending','transaction',String(item.id),'no_longer_unusual');return;}
 const key='unusual-expense-v1:'+item.id;
 if(day<shift(today,-7)){const [existing]=await q(tx,'select id from finance_notifications where workspace_id=$1 and user_id=$2 and dedupe_key=$3 and resolved_at is null',[ws,user,key]);if(!existing)return;}
 await notify(tx,ws,user,{kind:'unusual-spending',source:String(item.id),sourceType:'transaction',key,title:'This expense is higher than usual',message:(item.merchant||'This expense')+' is above your usual spending. Review the transaction.',messageKey:'spending.unusual',params:{amount:String(item.amount),currency:String(item.currency),merchant:String(item.merchant??'')},evidence:{scopeKey,ruleVersion:'unusual-expense-v1',sampleCount:baseline.length,windowDays:90,median:fromUnits(med),medianAbsoluteDeviation:fromUnits(mad),threshold:fromUnits(cutoff),candidateAmount:String(item.amount),currency:String(item.currency),candidateDate:day},action:'open_transaction',ruleVersion:'unusual-expense-v1'});
}

export async function evaluateWorkspaceNotifications(ws:Row,now:Date){
 const workspaceId=String(ws.id),userId=String(ws.owner_user_id),today=workspaceToday(String(ws.timezone),now),remindersReleased=workspaceHour(String(ws.timezone),now)>=9,horizon=shift(today,90),catchup=shift(today,-7);
 await client.begin(async tx=>{
  const [eligible]=await q(tx,"select w.id from workspaces w join workspace_memberships m on m.workspace_id=w.id and m.user_id=w.owner_user_id and m.role='owner' join \"user\" u on u.id=w.owner_user_id and u.account_status='active' and u.email_verified=true where w.id=$1 and w.owner_user_id=$2 and w.archived_at is null for share of w,m",[workspaceId,userId]);if(!eligible)return;
  const [lease]=await q(tx,"select pg_try_advisory_xact_lock(hashtextextended('capybudget:notification-sweep:'||$1,0)) as acquired",[workspaceId]);if(!lease?.acquired)return;
  await q(tx,"select set_config('app.notification_worker','true',true),set_config('app.workspace_id',$1,true),set_config('app.user_id',$2,true)",[workspaceId,userId]);
  await q(tx,'delete from finance_notifications where workspace_id=$1 and user_id=$2 and expires_at<=now()',[workspaceId,userId]);
  if(ws.kind==='business'){
   const taxes=await q(tx,'select id,name,due_on from business_tax_reminders where workspace_id=$1 and completed_at is null and due_on between $2::date and $3::date order by due_on limit 1000',[workspaceId,catchup,horizon]);
   if(remindersReleased)for(const row of taxes){const due=String(row.due_on).slice(0,10),days=Math.round((Date.parse(due)-Date.parse(today))/86400000),stage=days<0?'overdue':days===0?'today':days===3?'upcoming':null;if(!stage)continue;const key='tax:'+row.id+':'+due+':'+stage;await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='reminder_stage_changed' where workspace_id=$1 and user_id=$2 and source_type='tax_reminder' and source_id=$3 and dedupe_key<>$4 and resolved_at is null",[workspaceId,userId,row.id,key]);await notify(tx,workspaceId,userId,{kind:'tax-reminder',source:row.id,sourceType:'tax_reminder',key,title:'A tax reminder is due',message:row.name+' · '+due,messageKey:'tax.'+stage,params:{name:row.name,dueDate:due},action:'open_tax'});}
   await q(tx,"update finance_notifications n set resolved_at=coalesce(n.resolved_at,now()),resolution_reason='tax_reminder_completed' where n.workspace_id=$1 and n.user_id=$2 and n.source_type='tax_reminder' and n.resolved_at is null and not exists(select 1 from business_tax_reminders r where r.workspace_id=n.workspace_id and r.id=n.source_id and r.completed_at is null)",[workspaceId,userId]);
  }
  const invoices:Row[]=await q(tx,"select i.id,i.number,i.due_date,i.currency,i.total::text as total,i.currency_scale,coalesce(sum(p.amount-p.refunded_amount) filter(where p.reversed_at is null),0)::text as paid from invoices i left join invoice_payments p on p.workspace_id=i.workspace_id and p.invoice_id=i.id where i.workspace_id=$1 and i.state='issued' and i.archived_at is null and i.due_date<=$2::date and i.due_date >= $3::date group by i.id having i.total>coalesce(sum(p.amount-p.refunded_amount) filter(where p.reversed_at is null),0) order by i.due_date limit 1000",[workspaceId,horizon,catchup]);
  for(const row of invoices){const due=String(row.due_date).slice(0,10),days=Math.round((Date.parse(due+'T00:00:00Z')-Date.parse(today+'T00:00:00Z'))/86400000),stage=days<0?'overdue':days===0?'today':days===3?'upcoming':null;if(!stage||!remindersReleased)continue;const key='invoice:'+row.id+':'+due+':'+stage;await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='reminder_stage_changed',updated_at=now() where workspace_id=$1 and user_id=$2 and kind='invoice-due' and source_id=$3 and resolved_at is null and dedupe_key<>$4",[workspaceId,userId,row.id,key]);const outstanding=fromUnits(toUnits(String(row.total))-toUnits(String(row.paid)));await notify(tx,workspaceId,userId,{kind:'invoice-due',source:String(row.id),sourceType:'invoice',key,title:stage==='overdue'?'Invoice is overdue':stage==='today'?'Invoice due today':'Invoice due soon',message:String(row.number)+' · '+row.currency+' '+outstanding+' · '+due,messageKey:'invoice.'+stage,params:{number:String(row.number),amount:outstanding,currency:String(row.currency),dueDate:due},evidence:{outstanding,currency:String(row.currency),dueDate:due,daysUntilDue:days},action:'open_invoice',severity:stage==='overdue'?'urgent':'attention'});}
  const stale=await q(tx,"select distinct n.source_id from finance_notifications n where n.workspace_id=$1 and n.user_id=$2 and n.kind='invoice-due' and n.resolved_at is null and not exists(select 1 from invoices i left join invoice_payments p on p.workspace_id=i.workspace_id and p.invoice_id=i.id where i.workspace_id=n.workspace_id and i.id=n.source_id and i.state='issued' and i.archived_at is null and i.due_date<=$3::date and i.due_date >= $4::date group by i.id having i.total>coalesce(sum(p.amount-p.refunded_amount) filter(where p.reversed_at is null),0))",[workspaceId,userId,horizon,catchup]);for(const row of stale)await resolve(tx,workspaceId,userId,'invoice-due','invoice',String(row.source_id),'invoice_paid_or_changed');
  const bills:Row[]=await q(tx,"select o.id,o.name,o.amount::text,o.currency,o.due_on,b.reminder_days from bill_occurrences o join bills b on b.workspace_id=o.workspace_id and b.id=o.bill_id where o.workspace_id=$1 and o.status='unpaid' and (b.enabled or b.frequency='once') and b.archived_at is null and o.due_on<$2::date and o.due_on >= $3::date order by o.due_on limit 1000",[workspaceId,today,shift(today,-7)]);
  if(remindersReleased)for(const row of bills){const dueOn=String(row.due_on).slice(0,10),key='bill:'+row.id+':'+dueOn+':due-in:overdue';const stale=await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='reminder_stage_changed',updated_at=now() where workspace_id=$1 and user_id=$2 and kind='bill-reminder' and source_type='bill_occurrence' and source_id=$3 and resolved_at is null and dedupe_key<>$4 returning id",[workspaceId,userId,row.id,key]);if(stale.length)await q(tx,"update finance_notification_deliveries set status='cancelled',updated_at=now() where workspace_id=$1 and user_id=$2 and notification_id=any($3::uuid[]) and status in ('pending','retryable')",[workspaceId,userId,stale.map((notice)=>notice.id)]);await notify(tx,workspaceId,userId,{kind:'bill-reminder',source:String(row.id),sourceType:'bill_occurrence',key,title:'Bill is overdue',message:row.name+' · '+row.currency+' '+row.amount+' · '+row.due_on,messageKey:'bill.overdue',params:{name:String(row.name),amount:String(row.amount),currency:String(row.currency),dueDate:dueOn},evidence:{amount:String(row.amount),currency:String(row.currency),dueDate:dueOn},action:'open_bill',severity:'urgent'});}
  const recurrences:Row[]=await q(tx,"select o.id,o.rule_id,o.scheduled_date,o.template_snapshot,r.notes from recurring_occurrences o join recurring_rules r on r.workspace_id=o.workspace_id and r.id=o.rule_id where o.workspace_id=$1 and o.status='pending' and o.scheduled_date between $2::date and $3::date and r.status='active' order by o.scheduled_date limit 1000",[workspaceId,catchup,horizon]);
  for(const row of recurrences){const data=typeof row.template_snapshot==='string'?JSON.parse(row.template_snapshot):row.template_snapshot;if(data?.type!=='expense')continue;const [bill]=await q(tx,'select 1 from bills where workspace_id=$1 and recurring_rule_id=$2 and archived_at is null limit 1',[workspaceId,row.rule_id]);if(bill)continue;const day=String(row.scheduled_date).slice(0,10),days=Math.round((Date.parse(day+'T00:00:00Z')-Date.parse(today+'T00:00:00Z'))/86400000),stage=days<0?'overdue':days===0?'today':days===3?'upcoming':null;if(!stage||!remindersReleased)continue;const name=String(data.notes||row.notes||'Scheduled payment'),key='recurring:'+row.id+':due:'+stage;await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='reminder_stage_changed',updated_at=now() where workspace_id=$1 and user_id=$2 and kind='payment-due' and source_id=$3 and resolved_at is null and dedupe_key<>$4",[workspaceId,userId,row.id,key]);await notify(tx,workspaceId,userId,{kind:'payment-due',source:String(row.id),sourceType:'recurring_occurrence',key,title:stage==='today'?'Payment due today':stage==='overdue'?'Payment is overdue':'Payment due soon',message:name+' · '+data.currency+' '+data.amount+' · '+day,messageKey:stage==='today'?'payment.today':stage==='overdue'?'payment.overdue':'payment.upcoming',params:{name,amount:String(data.amount),currency:String(data.currency),dueDate:day},evidence:{amount:String(data.amount),currency:String(data.currency),dueDate:day},action:'open_recurring',severity:stage==='overdue'?'urgent':'attention'});}
  const stalePayments=await q(tx,"select distinct n.source_id from finance_notifications n where n.workspace_id=$1 and n.user_id=$2 and n.kind='payment-due' and n.source_type='recurring_occurrence' and n.resolved_at is null and not exists(select 1 from recurring_occurrences o join recurring_rules r on r.workspace_id=o.workspace_id and r.id=o.rule_id where o.workspace_id=n.workspace_id and o.id=n.source_id and o.status='pending' and r.status='active' and o.scheduled_date >= $3::date and not exists(select 1 from bills b where b.workspace_id=o.workspace_id and b.recurring_rule_id=o.rule_id and b.archived_at is null))",[workspaceId,userId,catchup]);for(const row of stalePayments)await resolve(tx,workspaceId,userId,'payment-due','recurring_occurrence',String(row.source_id),'payment_no_longer_pending_or_expired');
  const budgets:Row[]=await q(tx,"select b.id,b.category_id,b.name,b.amount::text,b.currency,b.cadence,b.alert_thresholds,b.alert_revision,b.starts_on,c.name as category_name,case when b.cadence='weekly' then date_trunc('week',$2::date)::date else date_trunc('month',$2::date)::date end as period_start,case when b.cadence='weekly' then (date_trunc('week',$2::date)+interval '7 days')::date else (date_trunc('month',$2::date)+interval '1 month')::date end as period_end from budgets b join categories c on c.workspace_id=b.workspace_id and c.id=b.category_id where b.workspace_id=$1 and b.archived_at is null and b.starts_on<=$2::date",[workspaceId,today]);
  for(const budget of budgets){const periodStart=String(budget.period_start).slice(0,10),periodEnd=String(budget.period_end).slice(0,10);if(periodStart<String(budget.starts_on).slice(0,10))continue;await q(tx,"delete from finance_notification_evaluation_state where workspace_id=$1 and user_id=$2 and rule_key='budget_threshold' and scope_key=$3 and period_key not like $4",[workspaceId,userId,String(budget.id),periodStart+':r'+budget.alert_revision+':%']);const [actual]=await q(tx,"with recursive descendants(id) as (select $2::uuid union all select c.id from categories c join descendants d on c.parent_id=d.id where c.workspace_id=$1) select coalesce(sum(amount),0)::text as spent from tracking_allocations where workspace_id=$1 and deleted_at is null and type='expense' and currency=$5 and occurred_at >= $3::date and occurred_at < $4::date and category_id in(select id from descendants)",[workspaceId,budget.category_id,periodStart,periodEnd,budget.currency]);const thresholds:number[]=Array.isArray(budget.alert_thresholds)?budget.alert_thresholds:[];let crossed:number|null=null;const budgetAmount=toUnits(String(budget.amount));if(budgetAmount===0n){if(toUnits(String(actual.spent))>0n)crossed=0;}else for(const threshold of [...thresholds].sort((a,b)=>b-a)){const [result]=await q(tx,'select $1::numeric*100 >= $2::numeric*$3::numeric as crossed',[actual.spent,budget.amount,threshold]);if(result.crossed){crossed=threshold;break;}}
   const prefix=`budget:${budget.id}:${periodStart}:r${budget.alert_revision}:`,stageKey=crossed===0?'zero-budget':String(crossed);if(crossed!==null){let firstCrossing=false;const reached= crossed===0?[0]:thresholds.filter(x=>x<=crossed);for(const threshold of reached){const marker=await q(tx,"insert into finance_notification_evaluation_state(workspace_id,user_id,rule_key,scope_key,period_key,state,dirty_version,processed_version) values($1,$2,'budget_threshold',$3,$4,$5::jsonb,1,1) on conflict(workspace_id,user_id,rule_key,scope_key,period_key) do nothing returning id",[workspaceId,userId,String(budget.id),periodStart+':r'+budget.alert_revision+':'+(threshold===0?'zero':threshold),JSON.stringify({crossedAt:now.toISOString(),threshold})]);if(threshold===crossed&&marker.length)firstCrossing=true;}if(firstCrossing)await notify(tx,workspaceId,userId,{kind:'budget-alert',source:String(budget.id),sourceType:'budget',key:prefix+stageKey,title:crossed===0?String(budget.category_name)+' has spending against a zero budget':String(budget.category_name)+' budget at '+crossed+'%',message:budget.currency+' '+actual.spent+' spent against '+(crossed===0?'a zero budget':budget.currency+' '+budget.amount+' in the current period.'),messageKey:crossed===0?'budget.zero':'budget.threshold',params:{category:String(budget.category_name),threshold:crossed===0?null:crossed,spent:String(actual.spent),amount:String(budget.amount),currency:String(budget.currency)},evidence:{periodStart,periodEnd,spent:String(actual.spent),budgetAmount:String(budget.amount),threshold:crossed===0?'zero':crossed,currency:String(budget.currency)},action:'open_budget'});}
   const revisionlessPrefix=`budget:${budget.id}:${periodStart}:`;await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='threshold_no_longer_crossed',updated_at=now() where workspace_id=$1 and user_id=$2 and kind='budget-alert' and source_id=$3 and dedupe_key like $4 and dedupe_key<>$5 and resolved_at is null",[workspaceId,userId,budget.id,revisionlessPrefix+'%',crossed===null?'':prefix+stageKey]);
  }
  const endedBudgetNotices=await q(tx,"update finance_notifications n set resolved_at=coalesce(resolved_at,now()),resolution_reason='budget_period_or_source_ended',updated_at=now() where n.workspace_id=$1 and n.user_id=$2 and n.kind='budget-alert' and n.resolved_at is null and ((n.evidence->>'periodEnd')::date <= $3::date or not exists(select 1 from budgets b where b.workspace_id=n.workspace_id and b.id=n.source_id and b.archived_at is null)) returning n.id",[workspaceId,userId,today]);if(endedBudgetNotices.length)await q(tx,"update finance_notification_deliveries set status='cancelled',updated_at=now() where workspace_id=$1 and user_id=$2 and notification_id=any($3::uuid[]) and status in ('pending','retryable')",[workspaceId,userId,endedBudgetNotices.map((notice)=>notice.id)]);
  const rules:Row[]=await q(tx,"select id,rule_type,scope_key,account_id,category_id,currency,parameters,version,enabled from finance_notification_rules where workspace_id=$1 and user_id=$2 order by rule_type,scope_key limit 1000",[workspaceId,userId]);
  for(const rule of rules){const cfg=typeof rule.parameters==='string'?JSON.parse(rule.parameters):rule.parameters;
   if(!rule.enabled){if(rule.rule_type==='low_balance'){await q(tx,"update finance_notification_evaluation_state set state=jsonb_set(state,'{active}','false'::jsonb,true),processed_version=dirty_version,updated_at=now() where workspace_id=$1 and user_id=$2 and rule_key='low_balance' and scope_key=$3 and period_key='episode'",[workspaceId,userId,rule.scope_key]);await resolve(tx,workspaceId,userId,'recorded-low-balance','account',String(rule.account_id),'rule_disabled');}else await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='rule_disabled',updated_at=now() where workspace_id=$1 and user_id=$2 and kind='unusual-spending' and resolved_at is null and evidence->>'scopeKey'=$3",[workspaceId,userId,rule.scope_key]);continue;}
   if(rule.rule_type==='low_balance'){const [account]=await q(tx,"select id,name,kind,currency,ledger_account_id from accounts where workspace_id=$1 and id=$2 and archived_at is null and deleted_at is null and kind in ('cash','bank','e_wallet','savings')",[workspaceId,rule.account_id]);if(!account){await resolve(tx,workspaceId,userId,'recorded-low-balance','account',String(rule.account_id),'account_unavailable');continue;}const [balance]=await q(tx,'select coalesce(sum(l.debit-l.credit),0)::text as amount from journal_lines l join journal_entries e on e.workspace_id=l.workspace_id and e.id=l.entry_id where l.workspace_id=$1 and l.ledger_account_id=$2 and e.effective_date<=$3::date',[workspaceId,account.ledger_account_id,today]),current=toUnits(String(balance.amount),true),threshold=toUnits(String(cfg.threshold??'0'),true),[saved]=await q(tx,"select state from finance_notification_evaluation_state where workspace_id=$1 and user_id=$2 and rule_key='low_balance' and scope_key=$3 and period_key='episode' for update",[workspaceId,userId,rule.scope_key]),state=saved?(typeof saved.state==='string'?JSON.parse(saved.state):saved.state):{episode:0,active:false};let episode=Number(state.episode??0),active=Boolean(state.active);if(Number(state.ruleVersion??0)!==Number(rule.version)){if(active)await resolve(tx,workspaceId,userId,'recorded-low-balance','account',String(account.id),'rule_changed');active=false;}
    if(current<threshold&&!active){episode++;active=true;await q(tx,"insert into finance_notification_evaluation_state(workspace_id,user_id,rule_key,scope_key,period_key,state,dirty_version,processed_version) values($1,$2,'low_balance',$3,'episode',$4::jsonb,1,1) on conflict(workspace_id,user_id,rule_key,scope_key,period_key) do update set state=excluded.state,processed_version=finance_notification_evaluation_state.dirty_version,updated_at=now()",[workspaceId,userId,rule.scope_key,JSON.stringify({episode,active,ruleVersion:Number(rule.version)})]);await notify(tx,workspaceId,userId,{kind:'recorded-low-balance',source:String(account.id),sourceType:'account',key:'low-balance:'+account.id+':'+episode,title:account.name+' is below your balance limit',message:'Recorded balance: '+account.currency+' '+balance.amount+'; limit: '+account.currency+' '+cfg.threshold+'.',messageKey:'balance.low',params:{name:String(account.name),balance:String(balance.amount),threshold:String(cfg.threshold),currency:String(account.currency)},evidence:{balance:String(balance.amount),threshold:String(cfg.threshold),currency:String(account.currency),asOf:today},action:'open_account'});}
    if(current>=threshold&&active){const reset=threshold+(threshold<0n?-threshold:threshold)/20n;if(current>=reset){await q(tx,"update finance_notification_evaluation_state set state=jsonb_build_object('episode',$4::int,'active',false,'ruleVersion',$5::int),processed_version=dirty_version,updated_at=now() where workspace_id=$1 and user_id=$2 and rule_key='low_balance' and scope_key=$3 and period_key='episode'",[workspaceId,userId,rule.scope_key,episode,rule.version]);await resolve(tx,workspaceId,userId,'recorded-low-balance','account',String(account.id),'balance_recovered');}}continue;}
   if(rule.rule_type!=='unusual_spending'||!rule.currency)continue;const minimum=toUnits(String(cfg.minimumAmount??'0'));if(minimum<=0n)continue;
   const [dirtyRow]=await q(tx,"select state,dirty_version,processed_version from finance_notification_evaluation_state where workspace_id=$1 and user_id=$2 and rule_key='unusual_spending' and scope_key=$3 and period_key='dirty' for update",[workspaceId,userId,rule.scope_key]);const dirty=dirtyRow?.state?(typeof dirtyRow.state==='string'?JSON.parse(dirtyRow.state):dirtyRow.state):null;
   if(dirty&&Number(dirtyRow.dirty_version)>Number(dirtyRow.processed_version)&&dirty.fromDate&&dirty.throughDate){
    const dirtyCandidates:Row[]=await q(tx,"select id,amount::text,currency,occurred_at,merchant from transactions where workspace_id=$1 and deleted_at is null and type='expense' and currency=$2 and occurred_at >= $3::date and occurred_at < ($4::date+1) and (($5::uuid is null and category_id is null) or category_id=$5) and ($6::uuid is null or id>$6::uuid) order by id limit 100",[workspaceId,rule.currency,dirty.fromDate,dirty.throughDate,rule.category_id,dirty.lastId??null]);
    for(const item of dirtyCandidates)await evaluateUnusualCandidate(tx,workspaceId,userId,String(rule.scope_key),rule.category_id?String(rule.category_id):null,String(rule.currency),item,minimum,today);
    const staleDirtyAlerts=await q(tx,"update finance_notifications n set resolved_at=coalesce(n.resolved_at,now()),resolution_reason='transaction_no_longer_matches_rule',updated_at=now() where n.workspace_id=$1 and n.user_id=$2 and n.kind='unusual-spending' and n.resolved_at is null and n.evidence->>'scopeKey'=$3 and (n.evidence->>'candidateDate')::date between $4::date and $5::date and not exists(select 1 from transactions t where t.workspace_id=n.workspace_id and t.id=n.source_id and t.deleted_at is null and t.type='expense' and t.currency=$6 and (($7::uuid is null and t.category_id is null) or t.category_id=$7) and t.occurred_at::date=(n.evidence->>'candidateDate')::date) returning n.id",[workspaceId,userId,rule.scope_key,dirty.fromDate,dirty.throughDate,rule.currency,rule.category_id]);if(staleDirtyAlerts.length)await q(tx,"update finance_notification_deliveries set status='cancelled',updated_at=now() where workspace_id=$1 and user_id=$2 and notification_id=any($3::uuid[]) and status in ('pending','retryable')",[workspaceId,userId,staleDirtyAlerts.map((notice)=>notice.id)]);
    if(dirtyCandidates.length===100){dirty.lastId=String(dirtyCandidates[dirtyCandidates.length-1]!.id);await q(tx,"update finance_notification_evaluation_state set state=$4::jsonb,updated_at=now() where workspace_id=$1 and user_id=$2 and rule_key='unusual_spending' and scope_key=$3 and period_key='dirty'",[workspaceId,userId,rule.scope_key,JSON.stringify(dirty)]);}
    else await q(tx,"update finance_notification_evaluation_state set state=jsonb_build_object('fromDate',null,'throughDate',null,'lastId',null),processed_version=dirty_version,updated_at=now() where workspace_id=$1 and user_id=$2 and rule_key='unusual_spending' and scope_key=$3 and period_key='dirty'",[workspaceId,userId,rule.scope_key]);
   }
   const [cursorRow]=await q(tx,"select cursor from finance_notification_evaluation_state where workspace_id=$1 and user_id=$2 and rule_key='unusual_spending' and scope_key=$3 and period_key='recent' for update",[workspaceId,userId,rule.scope_key]);const savedCursor=cursorRow?.cursor?(typeof cursorRow.cursor==='string'?JSON.parse(cursorRow.cursor):cursorRow.cursor):null,lastId=typeof savedCursor?.lastId==='string'?savedCursor.lastId:null;
   const candidates:Row[]=await q(tx,"select id,amount::text,currency,occurred_at,merchant from transactions where workspace_id=$1 and deleted_at is null and type='expense' and currency=$2 and occurred_at < $3::date and occurred_at >= $4::date and updated_at >= now()-interval '7 days' and (($5::uuid is null and category_id is null) or category_id=$5) and ($6::uuid is null or id>$6::uuid) order by id limit 100",[workspaceId,rule.currency,shift(today,1),shift(today,-180),rule.category_id,lastId]);
   for(const item of candidates)await evaluateUnusualCandidate(tx,workspaceId,userId,String(rule.scope_key),rule.category_id?String(rule.category_id):null,String(rule.currency),item,minimum,today);
   const nextCursor=candidates.length===100?{lastId:String(candidates[candidates.length-1]!.id)}:null;await q(tx,"insert into finance_notification_evaluation_state(workspace_id,user_id,rule_key,scope_key,period_key,cursor,dirty_version,processed_version) values($1,$2,'unusual_spending',$3,'recent',$4::jsonb,1,1) on conflict(workspace_id,user_id,rule_key,scope_key,period_key) do update set cursor=excluded.cursor,processed_version=finance_notification_evaluation_state.dirty_version,updated_at=now()",[workspaceId,userId,rule.scope_key,JSON.stringify(nextCursor)]);
   }
  await q(tx,"update finance_notifications n set resolved_at=coalesce(n.resolved_at,now()),resolution_reason='rule_removed',updated_at=now() where n.workspace_id=$1 and n.user_id=$2 and n.resolved_at is null and ((n.kind='recorded-low-balance' and not exists(select 1 from finance_notification_rules r where r.workspace_id=n.workspace_id and r.user_id=n.user_id and r.rule_type='low_balance' and r.account_id=n.source_id and r.enabled)) or (n.kind='unusual-spending' and not exists(select 1 from finance_notification_rules r where r.workspace_id=n.workspace_id and r.user_id=n.user_id and r.rule_type='unusual_spending' and r.enabled and r.scope_key=n.evidence->>'scopeKey'))) ",[workspaceId,userId]);
  await q(tx,"delete from finance_notification_evaluation_state s where s.workspace_id=$1 and s.user_id=$2 and ((s.rule_key='unusual_spending' and not exists(select 1 from finance_notification_rules r where r.workspace_id=s.workspace_id and r.user_id=s.user_id and r.rule_type='unusual_spending' and r.scope_key=s.scope_key)) or (s.rule_key='low_balance' and not exists(select 1 from finance_notification_rules r where r.workspace_id=s.workspace_id and r.user_id=s.user_id and r.rule_type='low_balance' and r.scope_key=s.scope_key)) or (s.rule_key='budget_threshold' and not exists(select 1 from budgets b where b.workspace_id=s.workspace_id and b.id::text=s.scope_key and b.archived_at is null)))",[workspaceId,userId]);
 });
}
let running=false;
export async function sweepNotifications(now=new Date()){if(running)return;running=true;try{const rows=await client.unsafe('select id,owner_user_id,timezone,kind from workspaces where archived_at is null');for(const workspace of rows){try{await evaluateWorkspaceNotifications(workspace,now);}catch(error){console.error('Notification sweep failed',{workspaceId:workspace.id,errorCode:(error as {code?:string}).code??'unknown'});}}}finally{running=false;}}
export function startNotificationScheduler(){void sweepNotifications();const timer=setInterval(()=>void sweepNotifications(),60_000);timer.unref?.();}
