<script lang="ts">
 import {getContext} from 'svelte';
 import {PRIVACY_CONTEXT,type PrivacyState} from '$lib/privacy';
 const privacy=getContext<PrivacyState>(PRIVACY_CONTEXT);
 import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';
 import * as Card from '$lib/components/ui/card';
 import {Button} from '$lib/components/ui/button';
 import {Input} from '$lib/components/ui/input';
 import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
 import CurrencySelect from '$lib/components/forms/currency-select.svelte';
 import DatePicker from '$lib/components/forms/date-picker.svelte';
 import AmountInput from '$lib/components/forms/amount-input.svelte';
 import MoneyDisplay from '$lib/components/shared/money-display.svelte';
 import PageHeader from '$lib/components/shared/page-header.svelte';
 import LoadingScope from '$lib/components/shared/loading-scope.svelte';
 import ErrorState from '$lib/components/shared/error-state.svelte';
 import * as AlertDialog from '$lib/components/ui/alert-dialog';
 import {formatDate} from '$lib/dates';
 const ws=getContext<{ready:boolean;selectedId:string;currency?:string;revision?:number}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(a:string,b:string)=>ui.locale==='id'?b:a;
 let items:any[]=$state([]),snapshots:any[]=$state([]),lines:Record<string,any[]>=$state({}),busy=$state(false),error=$state(''),name=$state(''),kind=$state('asset'),currency=$state('IDR'),amount=$state(''),date=$state(new Date().toISOString().slice(0,10)),ownership=$state('100'),updateId=$state(''),updateAmount=$state(''),archive:any=$state(null);let seq=0;
 async function load(){const id=ws.selectedId,n=++seq;if(!id)return;busy=true;try{const r=await fetch(`/api/workspaces/${id}/net-worth`),b=await r.json();if(!r.ok)throw new Error(b.message);if(n===seq&&id===ws.selectedId){items=b.items;snapshots=b.snapshots;}}catch(e){if(n===seq)error=e instanceof Error?e.message:String(e);}finally{if(n===seq)busy=false;}}
 $effect(()=>{void ws.revision;if(ws.ready&&ws.selectedId){lines={};void load();}});
 async function send(path:string,body:unknown,method='POST'){const activeId=ws.selectedId;if(busy)return;busy=true;error='';try{const r=await fetch(`/api/workspaces/${activeId}/net-worth/${path}`,{method,headers:{'content-type':'application/json'},body:body===null?undefined:JSON.stringify(body)}),b=await r.json();if(activeId!==ws.selectedId)return;if(!r.ok)throw new Error(b.message);await load();}catch(e){error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 async function explain(id:string){try{const r=await fetch(`/api/workspaces/${ws.selectedId}/net-worth/snapshots/${id}`),b=await r.json();if(!r.ok)throw new Error(b.message);lines[id]=b.lines;}catch(e){error=e instanceof Error?e.message:String(e);}}
 const history=$derived(snapshots.filter((s,i,a)=>s.status==='complete'&&a.findIndex(x=>x.date===s.date)===i).slice(0,12).reverse());
 const values=$derived(history.map(s=>Number(s.netWorth))),min=$derived(Math.min(0,...values)),max=$derived(Math.max(1,...values));
 const points=$derived(values.map((v,i)=>`${40+i*(520/Math.max(1,values.length-1))},${180-(v-min)/(max-min)*140}`).join(' '));
</script>
<svelte:head><title>CapyBudget · {t('Net worth','Kekayaan bersih')}</title></svelte:head>
<LoadingScope active={busy}/><PageHeader title={t('Your bigger picture','Gambaran keuangan Anda')} description={t('Assets minus liabilities, with traceable snapshots over time. Accounts and linked debts are counted once.','Aset dikurangi liabilitas, dengan snapshot yang dapat ditelusuri. Akun dan utang terkait dihitung satu kali.')}/>
{#if error}<ErrorState title={t('Please check the details','Periksa detail')} message={error} onRetry={load}/>{/if}
<Card.Root><Card.Header><Card.Title>{t('Net-worth history','Riwayat kekayaan bersih')}</Card.Title><Card.Description>{t('Each recalculation creates a new revision. Missing rates or valuations older than 90 days produce an incomplete snapshot.','Setiap perhitungan ulang membuat revisi baru. Kurs hilang atau valuasi berusia lebih dari 90 hari menghasilkan snapshot belum lengkap.')}</Card.Description></Card.Header><Card.Content><form onsubmit={(e)=>{e.preventDefault();void send('snapshots',{date});}}><div class="fields"><label for="snapshot-date">{t('As of date','Per tanggal')}<DatePicker id="snapshot-date" bind:value={date} required max={new Date().toISOString().slice(0,10)}/></label></div><Button type="submit" disabled={busy}>{t('Calculate snapshot','Hitung snapshot')}</Button></form>
{#if history.length&&!privacy.hidden}<svg viewBox="0 0 600 220" role="img" aria-label={t('Net-worth trend. Exact values are in the table below.','Tren kekayaan bersih. Nilai tepat pada tabel di bawah.')}><title>{t('Net-worth trend','Tren kekayaan bersih')}</title><path d="M40 180H560" stroke="var(--border)" fill="none"/><polyline points={points} stroke="var(--pond-blue)" stroke-width="3" fill="none"/>{#each values as v,i}<circle cx={40+i*(520/Math.max(1,values.length-1))} cy={180-(v-min)/(max-min)*140} r="4" fill="var(--pond-blue)"/>{/each}</svg>{/if}
<div class="scroll"><table><caption>{t('Snapshot history and revisions','Riwayat snapshot dan revisi')}</caption><thead><tr><th>{t('Date','Tanggal')}</th><th>{t('Revision','Revisi')}</th><th>{t('Net worth','Kekayaan bersih')}</th><th>Status</th><th>{t('Details','Detail')}</th></tr></thead><tbody>{#each snapshots as s}<tr><td>{formatDate(s.date)}</td><td>{s.revision}</td><td>{#if s.netWorth!==null}<MoneyDisplay amount={s.netWorth} currency={s.currency}/>{:else}—{/if}</td><td>{s.status==='complete'?t('Complete','Lengkap'):t('Incomplete','Belum lengkap')}</td><td><Button variant="ghost" onclick={()=>explain(s.id)}>{t('View sources','Lihat sumber')}</Button></td></tr>{#if lines[s.id]}<tr><td colspan="5"><ul>{#each lines[s.id] as l}<li><strong>{l.name}</strong> · {l.kind} · {#if l.amount!==null}<MoneyDisplay amount={l.amount} currency={l.currency}/>{:else}—{/if} · {formatDate(l.sourceDate)} · {l.status}{#if l.rate} · {t('Rate','Kurs')} {l.rate} ({formatDate(l.rateDate)}){/if}</li>{/each}</ul></td></tr>{/if}{/each}</tbody></table></div>
{#if !snapshots.length}<p>{t('Create your first snapshot to start your history.','Buat snapshot pertama untuk memulai riwayat.')}</p>{/if}
</Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{t('Add an asset or liability','Tambahkan aset atau liabilitas')}</Card.Title><Card.Description>{t('Only add items not already represented by a wallet, credit-card account, or linked debt. For example: property or a loan outside your tracked accounts.','Hanya tambahkan yang belum tercatat sebagai dompet, kartu kredit, atau utang terkait. Contoh: properti atau pinjaman di luar akun terlacak.')}</Card.Description></Card.Header><Card.Content><form onsubmit={(e)=>{e.preventDefault();void send('items',{name,kind,currency,amount,date,ownership});}}><div class="fields"><label for="worth-name">{t('Name','Nama')}<Input id="worth-name" bind:value={name} required/></label><label for="worth-kind">{t('Type','Jenis')}<ChoiceSelect id="worth-kind" bind:value={kind} items={[{value:'asset',label:t('Asset','Aset')},{value:'liability',label:t('Liability','Liabilitas')}]}/></label><label for="worth-currency">{t('Currency','Mata uang')}<CurrencySelect id="worth-currency" bind:value={currency}/></label><label for="worth-amount">{t('Value','Nilai')}<AmountInput id="worth-amount" bind:value={amount} {currency} required/></label><label for="worth-ownership">{t('Ownership (%)','Kepemilikan (%)')}<Input id="worth-ownership" bind:value={ownership} inputmode="decimal" required/></label><label for="worth-date">{t('Valuation date','Tanggal valuasi')}<DatePicker id="worth-date" bind:value={date} required/></label></div><Button type="submit" disabled={busy}>{t('Add item','Tambah item')}</Button></form></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{t('Manual valuations','Valuasi manual')}</Card.Title></Card.Header><Card.Content>{#each items as i}<div class="row"><span>{i.name} · {i.kind} · {i.currency} · {i.ownership}%</span><Button variant="outline" onclick={()=>{updateId=i.id;updateAmount='';}}>{t('Update valuation','Perbarui valuasi')}</Button><Button variant="ghost" onclick={()=>archive=i}>{t('Archive','Arsipkan')}</Button></div>{#if updateId===i.id}<form onsubmit={(e)=>{e.preventDefault();void send(`items/${i.id}/valuations`,{amount:updateAmount,date});}}><div class="fields"><label for="valuation-amount">{t('Value','Nilai')}<AmountInput id="valuation-amount" bind:value={updateAmount} currency={i.currency} required/></label><label for="valuation-date">{t('As of','Per tanggal')}<DatePicker id="valuation-date" bind:value={date} required/></label></div><Button type="submit" disabled={busy}>{t('Save valuation','Simpan valuasi')}</Button></form>{/if}{/each}</Card.Content></Card.Root>
<AlertDialog.Root open={!!archive} onOpenChange={(v)=>{if(!v)archive=null;}}><AlertDialog.Content><AlertDialog.Header><AlertDialog.Title>{t('Archive this item?','Arsipkan item ini?')}</AlertDialog.Title><AlertDialog.Description>{t('Existing snapshots keep their source history. Future calculations exclude this item.','Snapshot yang ada mempertahankan riwayat sumber. Perhitungan berikutnya mengecualikan item ini.')}</AlertDialog.Description></AlertDialog.Header><AlertDialog.Footer><AlertDialog.Cancel>{t('Cancel','Batal')}</AlertDialog.Cancel><AlertDialog.Action onclick={async()=>{if(archive){await send(`items/${archive.id}`,null,'DELETE');archive=null;}}}>{t('Archive','Arsipkan')}</AlertDialog.Action></AlertDialog.Footer></AlertDialog.Content></AlertDialog.Root>
<style>.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:16px;margin:16px 0}label{display:grid;gap:8px;font-size:14px}label :global([data-slot=select-trigger]){width:100%}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap;padding:16px 0;border-bottom:1px solid var(--border)}.row span{flex:1;min-width:180px}.scroll{overflow:auto}svg{display:block;width:100%;max-height:240px;margin-top:24px}table{width:100%;font-size:14px}th,td{padding:12px;text-align:left;border-bottom:1px solid var(--border)}p,li{font-size:14px;color:var(--muted-foreground)}:global(main [data-slot=card]){margin-bottom:24px}</style>
