<script lang="ts">
  import { formatDate } from '$lib/dates';
  import LoadingScope from '$lib/components/shared/loading-scope.svelte';
  import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
 import {getContext} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {businessText} from '$lib/i18n/business';import {uxText} from '$lib/i18n/ux';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';
 import PageHeader from '$lib/components/shared/page-header.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import EmptyState from '$lib/components/shared/empty-state.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';import LoadingSkeleton from '$lib/components/shared/loading-skeleton.svelte';import StatusBadge from '$lib/components/shared/status-badge.svelte';
 type Workspace={selectedId:string;ready:boolean;items:{id:string;kind:string;role?:string}[]};type Invoice={id:string;number:string|null;status:string;dueDate:string;currency:string;total:string;outstanding:string;recipientSnapshot:{name:string};paidAmount:string};
 const workspace=getContext<Workspace>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof businessText>[1])=>businessText(ui.locale,key);
 const canCreate=$derived(workspace.items.find(w=>w.id===workspace.selectedId)?.role!=='viewer');
 const ux=(key:Parameters<typeof uxText>[1])=>uxText(ui.locale,key);
 let items:Invoice[]=$state([]),loading=$state(true),error=$state(''),search=$state(''),status=$state('all'),requestId=0;
 async function load(){if(!workspace.ready||!workspace.selectedId)return;const current=++requestId;loading=true;error='';try{const query=new URLSearchParams({limit:'100',q:search,status}),response=await fetch('/api/workspaces/'+workspace.selectedId+'/invoices?'+query);const data=await response.json();if(!response.ok)throw new Error(data.message??t('error'));if(current===requestId&&workspace.selectedId)items=data.items;}catch(e){if(current===requestId)error=e instanceof Error?e.message:t('error');}finally{if(current===requestId)loading=false;}}
 $effect(()=>{void (workspace as {revision?:number}).revision;if(workspace.ready&&workspace.selectedId)void load();});
 function label(value:string){return t(value as Parameters<typeof businessText>[1]);}
 const statusTone=(s:string):'income'|'expense'|'transfer'|'warning'|'info'|'neutral'=>s==='paid'?'income':s==='overdue'?'expense':s==='void'?'neutral':s==='draft'?'neutral':'info';
</script>
<LoadingScope active={!!loading} />
<svelte:head><title>CapyBudget · {t('invoices')}</title></svelte:head>
<PageHeader eyebrow={t('studioMode').toUpperCase()} title={t('invoices')} description={t('invoiceListIntro')}>
  {#snippet actions()}{#if canCreate}<Button href="/invoices/new">{t('newInvoice')}</Button>{/if}{/snippet}
</PageHeader>
{#if error}<ErrorState title={ux('errorTitle')} message={error} retryLabel={ux('retry')} onRetry={load} />{/if}
<Card.Root><Card.Content><div class="filters"><Field.Field><Field.FieldLabel for="invoice-search">{t('search')}</Field.FieldLabel><Input id="invoice-search" bind:value={search} oninput={load}/></Field.Field><Field.Field><Field.FieldLabel for="invoice-status">{t('allStatuses')}</Field.FieldLabel><ChoiceSelect id="invoice-status" bind:value={status} onValueChange={load} items={[{value: "all", label: String(t('allStatuses'))}, ...(['draft','issued','sent','partially_paid','paid','overdue','void']).flatMap((key) => [{value: key, label: String(label(key))}])]} /></Field.Field></div>
{#if loading}<LoadingSkeleton rows={4} label={t('loading')} />{:else if !items.length}<EmptyState title={t('invoices')} body={t('empty')} actionLabel={canCreate?t('newInvoice'):undefined} actionHref={canCreate?'/invoices/new':undefined} />{:else}<div class="table-wrap" role="region" aria-label={t('invoices')}><table><thead><tr><th>{t('invoiceNumber')}</th><th>{t('customer')}</th><th>{t('dueDate')}</th><th>{t('total')}</th><th>{t('outstanding')}</th><th>{t('statusCol')}</th></tr></thead><tbody>{#each items as invoice (invoice.id)}<tr><td><a href={'/invoices/'+invoice.id}>{invoice.number??t('draft')}</a></td><td>{invoice.recipientSnapshot?.name||'—'}</td><td>{formatDate(invoice.dueDate)}</td><td><MoneyDisplay amount={invoice.total} currency={invoice.currency} /></td><td><MoneyDisplay amount={invoice.outstanding} currency={invoice.currency} type={invoice.status==='overdue'?'expense':null} /></td><td><StatusBadge tone={statusTone(invoice.status)}>{label(invoice.status)}</StatusBadge></td></tr>{/each}</tbody></table></div>{/if}</Card.Content></Card.Root>
<style>.filters{display:grid;grid-template-columns:2fr 1fr;gap:12px;margin-bottom:16px}.table-wrap{overflow:auto;border-radius:var(--radius-input)}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--border);white-space:nowrap}th{font-size:12px;color:var(--muted-foreground)}td a{color:var(--brand-ink);font-weight:600}@media(max-width:600px){.filters{grid-template-columns:1fr}}</style>
