<script lang="ts">
  import {getContext as privacyContext} from 'svelte';
  import {concealed,PRIVACY_CONTEXT,type PrivacyState} from '$lib/privacy';
  const privacy=privacyContext<PrivacyState>(PRIVACY_CONTEXT);
 import {getContext} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {businessText} from '$lib/i18n/business';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';
 type Workspace={selectedId:string;ready:boolean;items:{id:string;kind:string}[]};type Invoice={id:string;number:string|null;status:string;dueDate:string;currency:string;total:string;outstanding:string;recipientSnapshot:{name:string};paidAmount:string};
 const workspace=getContext<Workspace>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof businessText>[1])=>businessText(ui.locale,key);
 let items:Invoice[]=$state([]),loading=$state(true),error=$state(''),search=$state(''),status=$state('all'),requestId=0;
 async function load(){if(!workspace.ready||!workspace.selectedId)return;const current=++requestId;loading=true;error='';try{const query=new URLSearchParams({limit:'100',q:search,status}),response=await fetch('/api/workspaces/'+workspace.selectedId+'/invoices?'+query);const data=await response.json();if(!response.ok)throw new Error(data.message??t('error'));if(current===requestId&&workspace.selectedId)items=data.items;}catch(e){if(current===requestId)error=e instanceof Error?e.message:t('error');}finally{if(current===requestId)loading=false;}}
 $effect(()=>{void (workspace as {revision?:number}).revision;if(workspace.ready&&workspace.selectedId)void load();});
 function label(value:string){return t(value as Parameters<typeof businessText>[1]);}
</script>
<svelte:head><title>CapyBudget · {t('invoices')}</title></svelte:head>
<div class="heading"><div><p>Studio mode</p><h1>{t('invoices')}</h1><span>Draft, send, and track business invoices.</span></div><Button href="/invoices/new">{t('newInvoice')}</Button></div>
{#if error}<p class="error" role="alert">{error}</p>{/if}
<Card.Root><Card.Content><div class="filters"><Field.Field><Field.FieldLabel for="invoice-search">{t('search')}</Field.FieldLabel><Input id="invoice-search" bind:value={search} oninput={load}/></Field.Field><Field.Field><Field.FieldLabel for="invoice-status">{t('allStatuses')}</Field.FieldLabel><select id="invoice-status" bind:value={status} onchange={load}><option value="all">{t('allStatuses')}</option>{#each ['draft','issued','sent','partially_paid','paid','overdue','void'] as key}<option value={key}>{label(key)}</option>{/each}</select></Field.Field></div>
{#if loading}<p>{t('loading')}</p>{:else if !items.length}<p class="empty">{t('empty')}</p>{:else}<div class="table-wrap"><table><thead><tr><th>{t('invoiceNumber')}</th><th>{t('customer')}</th><th>{t('dueDate')}</th><th>{t('total')}</th><th>{t('outstanding')}</th><th>Status</th></tr></thead><tbody>{#each items as invoice (invoice.id)}<tr><td><a href={'/invoices/'+invoice.id}>{invoice.number??t('draft')}</a></td><td>{invoice.recipientSnapshot?.name||'—'}</td><td>{invoice.dueDate}</td><td>{invoice.currency} {concealed(invoice.total,privacy.hidden)}</td><td>{invoice.currency} {concealed(invoice.outstanding,privacy.hidden)}</td><td><span class="status" data-status={invoice.status}>{label(invoice.status)}</span></td></tr>{/each}</tbody></table></div>{/if}</Card.Content></Card.Root>
<style>.heading{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:24px}.heading p{margin:0 0 4px;color:var(--muted-foreground);font-size:13px}.heading h1{font:500 clamp(28px,4vw,38px) 'Fredoka Variable',sans-serif;margin:0}.heading span{display:block;color:var(--muted-foreground);margin-top:6px}.filters{display:grid;grid-template-columns:2fr 1fr;gap:14px;margin-bottom:18px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--border);white-space:nowrap}th{font-size:12px;color:var(--muted-foreground)}td a{color:var(--primary);font-weight:600}.status{display:inline-flex;padding:4px 9px;border-radius:999px;background:var(--secondary);font-size:12px}.status[data-status=overdue]{color:var(--destructive)}.status[data-status=paid]{color:var(--text-green)}.empty{padding:20px;color:var(--muted-foreground)}.error{color:var(--destructive)}select{height:40px;border:1px solid var(--input);border-radius:var(--radius);background:var(--background);color:var(--foreground);padding:8px}@media(max-width:600px){.heading{align-items:flex-start;flex-direction:column}.filters{grid-template-columns:1fr}}</style>
