<script lang="ts">
 import {getContext,untrack} from 'svelte';import {parseDate} from '@internationalized/date';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import DatePicker from '$lib/components/forms/date-picker.svelte';import PageHeader from '$lib/components/shared/page-header.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';import {formatDate} from '$lib/dates';
 const workspace=getContext<{selectedId:string;ready:boolean;revision?:number}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 let rows:any[]=$state([]),invoices:any[]=$state([]),occurrences:any[]=$state([]),expanded=$state(''),name=$state(''),invoiceId=$state(''),anchor=$state(''),frequency=$state('month'),interval=$state('1'),dueDays=$state('14'),end=$state(''),delivery=$state('draft'),canWrite=$state(false),loading=$state(false),busy=$state(false),error=$state(''),sequence=0,occurrenceSequence=0;
 let notice=$state(''),formError=$state('');
 const endpoint=(ws:string)=>'/api/workspaces/'+ws;
 async function call(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.message??copy('The request could not be completed.','Permintaan tidak dapat diselesaikan.'));return result;}
 async function load(ws:string){const current=++sequence;loading=true;try{const [templates,source,access]=await Promise.all([call(endpoint(ws)+'/recurring-invoices'),call(endpoint(ws)+'/invoices?limit=100'),call(endpoint(ws)+'/business-access')]);if(current===sequence&&ws===workspace.selectedId){rows=templates.items;invoices=source.items.filter((i:any)=>i.state!=='void');canWrite=['owner','accountant'].includes(access.role);}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{void workspace.revision;if(workspace.ready&&workspace.selectedId){const ws=workspace.selectedId;untrack(()=>{name='';invoiceId='';anchor='';end='';rows=[];invoices=[];expanded='';occurrences=[];canWrite=false;error='';notice='';formError='';occurrenceSequence++;void load(ws);});}});
 async function mutate(path:string,method:string,body?:unknown){if(busy||loading)return false;const ws=workspace.selectedId;busy=true;error='';try{await call(endpoint(ws)+path,method,body);if(ws===workspace.selectedId)await load(ws);return ws===workspace.selectedId;}catch(e){if(ws===workspace.selectedId)error=e instanceof Error?e.message:String(e);return false;}finally{busy=false;}}
 function validDate(value:string){try{return !!value&&parseDate(value).toString()===value;}catch{return false;}}
 function invalid(form:HTMLFormElement,id:string,message:string){formError=message;form.querySelector<HTMLElement>('#'+id)?.focus();}
 async function create(event:SubmitEvent){
  event.preventDefault();if(busy||loading||!canWrite)return;
  const form=event.currentTarget as HTMLFormElement;formError='';notice='';
  if(!name.trim()||name.trim().length>200)return invalid(form,'template-name',copy('Enter a template name (up to 200 characters).','Masukkan nama templat (maksimal 200 karakter).'));
  if(!invoiceId||!invoices.some(invoice=>invoice.id===invoiceId))return invalid(form,'source-invoice',copy('Choose a saved source invoice. If none are listed, save an invoice first.','Pilih faktur sumber tersimpan. Jika belum ada, simpan faktur terlebih dahulu.'));
  if(!validDate(anchor))return invalid(form,'anchor',copy('Choose a valid first invoice date, or enter DD-MM-YYYY.','Pilih tanggal faktur pertama yang valid, atau masukkan DD-MM-YYYY.'));
  if(!/^\d+$/.test(interval)||Number(interval)<1||Number(interval)>120)return invalid(form,'template-interval',copy('Enter a whole-number interval from 1 to 120.','Masukkan interval bilangan bulat dari 1 sampai 120.'));
  if(!/^\d+$/.test(dueDays)||Number(dueDays)>365)return invalid(form,'due-days',copy('Enter payment due days from 0 to 365.','Masukkan hari jatuh tempo dari 0 sampai 365.'));
  if(end&&(!validDate(end)||end<anchor))return invalid(form,'template-end',copy('Choose a last date on or after the first invoice date, or leave it empty.','Pilih tanggal terakhir pada atau setelah tanggal faktur pertama, atau biarkan kosong.'));
  if(delivery==='send'&&!confirm(copy('Allow this template to issue invoices and email the saved recipient automatically?','Izinkan templat menerbitkan faktur dan mengirim email otomatis kepada penerima tersimpan?')))return;
  if(await mutate('/recurring-invoices','POST',{name:name.trim(),invoiceId,anchorDate:anchor,frequency,interval:Number(interval),dueDays:Number(dueDays),endDate:end||null,autoIssue:delivery!=='draft',autoSend:delivery==='send'})){name='';invoiceId='';notice=copy('Template saved. It appears in the templates list below.','Templat disimpan. Templat tampil di daftar di bawah.');}
 }

 async function show(id:string){const ws=workspace.selectedId,current=++occurrenceSequence;expanded=id;occurrences=[];try{const result=await call(endpoint(ws)+'/recurring-invoices/'+id+'/occurrences');if(current===occurrenceSequence&&ws===workspace.selectedId)occurrences=result.items;}catch(e){error=e instanceof Error?e.message:String(e);}}
</script>
<svelte:head><title>CapyBudget · {copy('Recurring invoices','Faktur berulang')}</title></svelte:head><LoadingScope active={loading||busy}/><PageHeader title={copy('Recurring invoices','Faktur berulang')} description={copy('Copy a saved invoice on an anchored schedule. Drafts are the default.','Salin faktur tersimpan sesuai jadwal tetap. Draf menjadi pilihan bawaan.')}/>
{#if error}<ErrorState title={copy('Could not update recurring invoices','Faktur berulang gagal diperbarui')} message={error} onRetry={()=>load(workspace.selectedId)} retryLabel={copy('Retry','Coba lagi')}/>{/if}
<div role="status" aria-live="polite">{#if notice}<p class="mb-6 rounded-[14px] border-2 border-border bg-muted p-4 text-sm">{notice}</p>{/if}</div>
<div class="space-y-6">{#if canWrite}<Card.Root><Card.Header><Card.Title>{copy('New template','Templat baru')}</Card.Title><Card.Description>{copy('Save an invoice first, then choose it here. The template copies its customer, items, and prices for future invoices.','Simpan faktur terlebih dahulu, lalu pilih di sini. Templat menyalin pelanggan, item, dan harga untuk faktur berikutnya.')}</Card.Description></Card.Header><Card.Content><form onsubmit={create} class="space-y-4" novalidate>{#if formError}<p role="alert" class="rounded-[14px] border-2 border-border bg-muted p-4 text-sm text-destructive">{formError}</p>{/if}<div class="grid gap-4 sm:grid-cols-2">
<Field.Field><Field.FieldLabel for="template-name">{copy('Name','Nama')}</Field.FieldLabel><Input id="template-name" bind:value={name} maxlength={200} required/></Field.Field>
<Field.Field><Field.FieldLabel for="source-invoice">{copy('Saved source invoice (latest 100)','Faktur sumber tersimpan (100 terbaru)')}</Field.FieldLabel><ChoiceSelect id="source-invoice" bind:value={invoiceId} required aria-describedby="source-invoice-help" items={[{value:'',label:copy('Select','Pilih')},...invoices.map(i=>({value:i.id,label:(i.number??copy('Draft','Draf'))+' · '+(i.recipientSnapshot?.name??'—')}))]}/><p id="source-invoice-help" class="text-sm leading-relaxed text-muted-foreground">{copy('Required: choose the invoice whose customer, items, and prices you want to repeat. A saved draft works too.','Wajib: pilih faktur dengan pelanggan, item, dan harga yang ingin diulang. Draf tersimpan juga bisa digunakan.')}</p><a href="/invoices/new" class="inline-flex min-h-11 items-center rounded-[14px] text-sm font-semibold text-brand-ink underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-ring">{copy('Create a source invoice','Buat faktur sumber')}</a></Field.Field>
<Field.Field><Field.FieldLabel for="anchor">{copy('First invoice date','Tanggal faktur pertama')}</Field.FieldLabel><DatePicker id="anchor" bind:value={anchor} required/></Field.Field>
<Field.Field><Field.FieldLabel for="frequency">{copy('Frequency','Frekuensi')}</Field.FieldLabel><ChoiceSelect id="frequency" bind:value={frequency} items={[{value:'day',label:copy('Daily','Harian')},{value:'week',label:copy('Weekly','Mingguan')},{value:'month',label:copy('Monthly','Bulanan')},{value:'year',label:copy('Yearly','Tahunan')}]}/></Field.Field>
<Field.Field><Field.FieldLabel for="template-interval">{copy('Every how many periods?','Setiap berapa periode?')}</Field.FieldLabel><Input id="template-interval" bind:value={interval} inputmode="numeric" maxlength={3} required aria-describedby="template-interval-help"/><p id="template-interval-help" class="text-sm text-muted-foreground">{copy('1–120. For example, monthly with 2 creates an invoice every two months.','1–120. Contoh: bulanan dengan 2 membuat faktur setiap dua bulan.')}</p></Field.Field>
<Field.Field><Field.FieldLabel for="due-days">{copy('Payment due after (days)','Jatuh tempo setelah (hari)')}</Field.FieldLabel><Input id="due-days" bind:value={dueDays} inputmode="numeric" maxlength={3} required aria-describedby="due-days-help"/><p id="due-days-help" class="text-sm text-muted-foreground">{copy('0–365 days after each invoice date. Use 0 for payment due the same day.','0–365 hari setelah tanggal setiap faktur. Gunakan 0 untuk jatuh tempo pada hari yang sama.')}</p></Field.Field>
<Field.Field><Field.FieldLabel for="template-end">{copy('Last date (optional)','Tanggal terakhir (opsional)')}</Field.FieldLabel><DatePicker id="template-end" bind:value={end} min={anchor||undefined}/></Field.Field>
<Field.Field><Field.FieldLabel for="template-delivery">{copy('On each occurrence','Pada setiap jadwal')}</Field.FieldLabel><ChoiceSelect id="template-delivery" bind:value={delivery} items={[{value:'draft',label:copy('Create draft for review','Buat draf untuk ditinjau')},{value:'issue',label:copy('Issue automatically','Terbitkan otomatis')},{value:'send',label:copy('Issue and email automatically','Terbitkan dan kirim email otomatis')}]}/></Field.Field></div>
<p class="text-sm text-muted-foreground">{copy('The 31st uses the last day of a shorter month and returns to the 31st afterward. Past dates are processed in bounded batches. To change prices or customer details, pause the old template and create a new one from an updated saved invoice.','Tanggal 31 memakai hari terakhir pada bulan yang lebih pendek, lalu kembali ke tanggal 31. Jadwal lampau diproses bertahap. Untuk mengubah harga atau pelanggan, jeda templat lama lalu buat templat baru dari faktur yang telah diperbarui.')}</p><Button type="submit" disabled={busy||loading}>{busy?copy('Saving…','Menyimpan…'):copy('Save template','Simpan templat')}</Button></form></Card.Content></Card.Root>{/if}
<Card.Root><Card.Header><Card.Title>{copy('Templates','Templat')}</Card.Title></Card.Header><Card.Content><ul class="divide-y divide-border">{#each rows as row(row.id)}<li class="space-y-4 py-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-base font-semibold">{row.name}</h2><p class="text-sm text-muted-foreground">{formatDate(row.anchorDate)} · {row.frequency} × {row.interval} · {row.active?copy('Active','Aktif'):copy('Paused','Dijeda')}</p></div><div class="flex gap-2"><Button variant="outline" onclick={()=>show(row.id)}>{copy('View occurrences','Lihat jadwal')}</Button>{#if canWrite}<Button variant="outline" disabled={busy} onclick={()=>mutate('/recurring-invoices/'+row.id,'PATCH',{active:!row.active,version:row.version})}>{row.active?copy('Pause','Jeda'):copy('Resume','Lanjutkan')}</Button>{/if}</div></div>{#if expanded===row.id}<ul class="space-y-2 rounded-[14px] border-2 border-border p-4">{#each occurrences as item(item.id)}<li class="flex flex-wrap items-center justify-between gap-2"><span>{formatDate(item.scheduledOn)} · {item.state} · v{item.templateVersion}</span>{#if item.invoiceId}<Button href={'/invoices/'+item.invoiceId} variant="outline">{copy('Open invoice','Buka faktur')}</Button>{/if}{#if canWrite&&item.state==='failed'}<Button variant="outline" disabled={busy} onclick={async()=>{await mutate('/recurring-invoice-occurrences/'+item.id+'/retry','POST');await show(row.id);}}>{copy('Retry after review','Coba lagi setelah ditinjau')}</Button>{/if}</li>{/each}{#if !occurrences.length}<li>{copy('No occurrences yet. The scheduler checks every minute.','Belum ada jadwal. Penjadwal memeriksa setiap menit.')}</li>{/if}</ul>{/if}</li>{/each}</ul>{#if !rows.length&&!loading}<p>{copy('Create a template from a saved invoice to begin.','Buat templat dari faktur tersimpan untuk mulai.')}</p>{/if}</Card.Content></Card.Root></div>
