<script lang="ts">
  import { goto } from '$app/navigation'; import { invalidateAll } from '$app/navigation'; import type { PageData } from './$types';
  import { Button } from '$lib/components/ui/button'; import { authClient } from '$lib/auth-client'; import AuthPreferences from '$lib/components/auth/auth-preferences.svelte'; import { getContext } from 'svelte'; import { AUTH_UI_CONTEXT, messages, type AuthUiState } from '$lib/i18n/auth';
  let { data }: { data: PageData } = $props(); let busy = $state(false);
  const authUi = getContext<AuthUiState>(AUTH_UI_CONTEXT);
  const t = $derived(messages[authUi.locale]);
  async function signOut() { if (busy) return; busy = true; try { await authClient.signOut(); await invalidateAll(); await goto('/login'); } finally { busy = false; } }
</script>
<svelte:head><title>{t.brand} · {t.dashboard}</title></svelte:head>
<main class="dashboard"><header><a class="brand" href="/" aria-label={t.brand}><span class="brand-mark">c</span><span>capy<span>budget</span></span></a><AuthPreferences /></header><section><span class="success">✓</span><h1>{t.dashboard}{data.user.name ? `, ${data.user.name}` : ''}</h1><p>{data.user.email}</p><Button onclick={signOut} disabled={busy}>{busy ? '…' : t.signOut}</Button></section></main>
<style>.dashboard{min-height:100svh;padding:28px clamp(20px,6vw,80px);background:#f8f7f3;color:#28342e;transition:background-color .35s ease,color .35s ease}:global(.dark) .dashboard{background:#171c19;color:#e7eee8}.dashboard header{display:flex;justify-content:space-between;align-items:center}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:inherit;font:600 23px 'Fredoka Variable',sans-serif}.brand>span:last-child>span{color:#6e9e7f;font-weight:400}.brand-mark{display:grid;place-items:center;background:#4d8966;color:white;border-radius:11px;width:34px;height:34px;font-size:22px}.dashboard section{min-height:75svh;display:flex;flex-direction:column;align-items:center;justify-content:center}.success{display:grid;place-items:center;background:#e7f2e8;color:#47815d;width:58px;height:58px;border-radius:18px;font-size:29px}.dashboard h1{font:500 clamp(25px,4vw,36px) 'Fredoka Variable',sans-serif;margin:22px 0 5px}.dashboard p{color:#78847b;margin:0 0 25px}</style>
