<script lang="ts">
 import {getContext} from 'svelte';
 import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';
 import * as Card from '$lib/components/ui/card';
 import {Button} from '$lib/components/ui/button';
 import {Input} from '$lib/components/ui/input';
 import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
 import DatePicker from '$lib/components/forms/date-picker.svelte';
 import AmountInput from '$lib/components/forms/amount-input.svelte';
 import MoneyDisplay from '$lib/components/shared/money-display.svelte';
 import PageHeader from '$lib/components/shared/page-header.svelte';
 import LoadingScope from '$lib/components/shared/loading-scope.svelte';
 import ErrorState from '$lib/components/shared/error-state.svelte';
 import * as AlertDialog from '$lib/components/ui/alert-dialog';
 import {formatDate} from '$lib/dates';
 const ws=getContext<{ready:boolean;selectedId:string;revision?:number}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(a:string,b:string)=>ui.locale==='id'?b:a;
 type Debt={id:string;name:string;currency:string;balance:string;apr:string;minimum:string;dueDay:number};
 let items:Debt[]=$state([]),accounts:{id:string;name:string;kind:string;currency:string}[]=$state([]),categories:{id:string;name:string}[]=$state([]),busy=$state(false),error=$state(''),name=$state(''),linked=$state(''),apr=$state('0'),minimum=$state(''),due=$state('1'),debtStartDate=$state(new Date().toISOString().slice(0,10)),payoffStartDate=$state(new Date().toISOString().slice(0,10)),extra=$state('0'),comparisons:any[]=$state([]),histories:Record<string,any[]>=$state({});
 let target:Debt|null=$state(null),paymentAccount=$state(''),principal=$state(''),interest=$state('0'),fees=$state('0'),category=$state(''),date=$state(new Date().toISOString().slice(0,10)),confirm=$state(false),edit:Debt|null=$state(null),archive:Debt|null=$state(null);
 let seq=0;
 async function load(){const id=ws.selectedId,n=++seq;if(!id)return;busy=true;try{const r=await Promise.all(['debts','accounts','categories'].map(p=>fetch(`/api/workspaces/${id}/${p}`)));const b=await Promise.all(r.map(a=>a.json()));if(r.some(a=>!a.ok))throw new Error(b.find(a=>a.message)?.message);if(n===seq&&id===ws.selectedId){items=b[0].items;accounts=b[1].items;categories=b[2].items.filter((c:{type:string})=>c.type==='expense');}}catch(e){if(n===seq)error=e instanceof Error?e.message:String(e);}finally{if(n===seq)busy=false;}}
 $effect(()=>{void ws.revision;if(ws.ready&&ws.selectedId){comparisons=[];histories={};target=null;void load();}});
 async function send(path:string,body:unknown,method='POST'){const activeId=ws.selectedId;if(busy)return null;busy=true;error='';try{const r=await fetch(`/api/workspaces/${activeId}/${path}`,{method,headers:{'content-type':'application/json'},body:body===null?undefined:JSON.stringify(body)}),b=await r.json();if(activeId!==ws.selectedId)return null;if(!r.ok)throw new Error(b.message);return b;}catch(e){error=e instanceof Error?e.message:String(e);return null;}finally{busy=false;}}
 async function create(e:SubmitEvent){e.preventDefault();if(await send('debts',{name,linkedAccountId:linked,apr,minimum,dueDay:Number(due),startsOn:debtStartDate})){name='';await load();}}
 async function history(id:string){try{const r=await fetch(`/api/workspaces/${ws.selectedId}/debts/${id}/payments`),b=await r.json();if(!r.ok)throw new Error(b.message);histories[id]=b.items;}catch(e){error=e instanceof Error?e.message:String(e);}}
 async function pay(){const d=target;if(!d)return;confirm=false;if(await send(`debts/${d.id}/payments`,{accountId:paymentAccount,categoryId:category,principal,interest,fees,date,confirm:true,idempotencyKey:crypto.randomUUID()})){target=null;await load();await history(d.id);}}
</script>
<svelte:head><title>CapyBudget · {t('Debts','Utang')}</title></svelte:head>
<LoadingScope active={busy}/><PageHeader title={t('A clearer path to debt-free','Rencana pelunasan yang jelas')} description={t('Track principal and interest separately. Compare estimates before recording a payment.','Catat pokok dan bunga terpisah. Bandingkan estimasi sebelum mencatat pembayaran.')}/>
{#if error}<ErrorState title={t('Please check the details','Periksa detail')} message={error} onRetry={load}/>{/if}
<div class="grid"><Card.Root><Card.Header><Card.Title>{t('Add debt','Tambah utang')}</Card.Title><Card.Description>{t('Link an existing credit-card/liability account. Its negative balance is the debt; no duplicate opening balance is added. Create the account first if needed.','Hubungkan akun kartu kredit/liabilitas. Saldo negatif adalah utang; saldo awal tidak digandakan. Buat akun terlebih dahulu bila perlu.')}</Card.Description></Card.Header><Card.Content><form onsubmit={create}><div class="fields">
<label for="debt-name">{t('Name','Nama')}<Input id="debt-name" bind:value={name} required/></label><label for="debt-account">{t('Liability account','Akun liabilitas')}<ChoiceSelect id="debt-account" bind:value={linked} required items={accounts.filter(a=>a.kind==='credit_card').map(a=>({value:a.id,label:a.name}))}/></label>
<label for="debt-apr">{t('Annual interest (%)','Bunga tahunan (%)')}<Input id="debt-apr" inputmode="decimal" bind:value={apr} required/></label><label for="debt-min">{t('Minimum monthly payment','Minimum pembayaran bulanan')}<AmountInput id="debt-min" bind:value={minimum} required/></label><label for="debt-day">{t('Due day (1–31)','Hari jatuh tempo (1–31)')}<Input id="debt-day" inputmode="numeric" bind:value={due} required/></label><label for="debt-start">{t('Start date','Tanggal mulai')}<DatePicker id="debt-start" bind:value={debtStartDate} required/></label>
</div><Button type="submit" disabled={busy}>{t('Add debt','Tambah utang')}</Button> <Button href="/accounts" variant="outline">{t('Manage accounts','Kelola akun')}</Button></form></Card.Content></Card.Root>
<section class="list" aria-label={t('Your debts','Utang Anda')}>
{#if !busy&&!items.length}<p>{t('No debts tracked yet. Add a liability account to get started.','Belum ada utang. Tambahkan akun liabilitas untuk memulai.')}</p>{/if}
{#each items as d(d.id)}<Card.Root><Card.Header><Card.Title>{d.name}</Card.Title><Card.Description>{d.apr}% APR · {t('Due day','Jatuh tempo hari')} {d.dueDay}</Card.Description></Card.Header><Card.Content><MoneyDisplay amount={d.balance} currency={d.currency} size="lg"/><p>{t('Minimum','Minimum')}: <MoneyDisplay amount={d.minimum} currency={d.currency}/></p><div class="actions"><Button onclick={()=>{target=d;principal='';interest='0';fees='0';}}>{t('Record payment','Catat pembayaran')}</Button><Button variant="outline" onclick={()=>history(d.id)}>{t('Payment history','Riwayat pembayaran')}</Button><Button variant="ghost" onclick={()=>edit={...d}}>{t('Edit','Ubah')}</Button><Button variant="ghost" onclick={()=>archive=d}>{t('Archive','Arsipkan')}</Button></div>
{#if histories[d.id]}<ul>{#each histories[d.id] as p}<li>{formatDate(p.occurredOn)} · {t('Principal','Pokok')}: <MoneyDisplay amount={p.principal} currency={d.currency}/> · {t('Interest','Bunga')}: <MoneyDisplay amount={p.interest} currency={d.currency}/> · {t('Fees','Biaya')}: <MoneyDisplay amount={p.fees} currency={d.currency}/></li>{/each}</ul>{/if}
{#if edit?.id===d.id}<form onsubmit={async(e)=>{e.preventDefault();if(edit&&await send(`debts/${edit.id}`,edit,'PATCH')){edit=null;await load();}}}><div class="fields"><label for="edit-debt-name">{t('Name','Nama')}<Input id="edit-debt-name" bind:value={edit.name}/></label><label for="edit-debt-apr">APR (%)<Input id="edit-debt-apr" bind:value={edit.apr} inputmode="decimal"/></label><label for="edit-debt-min">{t('Minimum payment','Minimum pembayaran')}<AmountInput id="edit-debt-min" bind:value={edit.minimum} currency={d.currency}/></label><label for="edit-debt-day">{t('Due day','Hari jatuh tempo')}<Input id="edit-debt-day" type="number" min={1} max={31} bind:value={edit.dueDay}/></label></div><Button type="submit" disabled={busy}>{t('Save','Simpan')}</Button><Button variant="ghost" onclick={()=>edit=null}>{t('Cancel','Batal')}</Button></form>{/if}
</Card.Content></Card.Root>{/each}</section></div>
{#if target}<Card.Root><Card.Header><Card.Title>{t('Payment for','Pembayaran untuk')} {target.name}</Card.Title></Card.Header><Card.Content><form onsubmit={(e)=>{e.preventDefault();confirm=true;}}><div class="fields"><label for="payment-account">{t('Pay from','Bayar dari')}<ChoiceSelect id="payment-account" bind:value={paymentAccount} required items={accounts.filter(a=>a.kind!=='credit_card'&&a.currency===target?.currency).map(a=>({value:a.id,label:a.name}))}/></label><label for="payment-principal">{t('Principal','Pokok')}<AmountInput id="payment-principal" bind:value={principal} currency={target.currency} required/></label><label for="payment-interest">{t('Interest','Bunga')}<AmountInput id="payment-interest" bind:value={interest} currency={target.currency}/></label><label for="payment-fees">{t('Fees','Biaya')}<AmountInput id="payment-fees" bind:value={fees} currency={target.currency}/></label><label for="payment-category">{t('Interest/fee expense category','Kategori pengeluaran bunga/biaya')}<ChoiceSelect id="payment-category" bind:value={category} items={categories.map(c=>({value:c.id,label:c.name}))} required={Number(interest)+Number(fees)>0}/></label><label for="payment-date">{t('Payment date','Tanggal pembayaran')}<DatePicker id="payment-date" bind:value={date} required/></label></div><Button type="submit" disabled={busy}>{t('Review payment','Tinjau pembayaran')}</Button><Button variant="ghost" onclick={()=>target=null}>{t('Cancel','Batal')}</Button></form></Card.Content></Card.Root>{/if}
<Card.Root><Card.Header><Card.Title>{t('Compare payoff strategies','Bandingkan strategi pelunasan')}</Card.Title><Card.Description>{t('Snowball targets the smallest balance; avalanche targets the highest interest. Monthly APR/12 estimates, rounded half-up, maximum 600 months. Actual lender terms may differ.','Snowball mendahulukan saldo terkecil; avalanche mendahulukan bunga tertinggi. Estimasi APR/12 bulanan, pembulatan half-up, maksimal 600 bulan. Ketentuan pemberi pinjaman bisa berbeda.')}</Card.Description></Card.Header><Card.Content><form onsubmit={async(e)=>{e.preventDefault();const b=await send('debt-comparison',{extra,startsOn:payoffStartDate});if(b)comparisons=b.items.map((i:any)=>({...i,currency:b.currency}));}}><div class="fields"><label for="payoff-extra">{t('Extra monthly payment','Tambahan pembayaran bulanan')}<AmountInput id="payoff-extra" bind:value={extra}/></label><label for="payoff-start">{t('First payment month','Bulan pembayaran pertama')}<DatePicker id="payoff-start" bind:value={payoffStartDate} required/></label></div><Button type="submit" disabled={busy||!items.length}>{t('Compare estimates','Bandingkan estimasi')}</Button></form><div class="fields">{#each comparisons as c}<section><h2>{c.strategy}</h2><p>{t('Monthly budget','Anggaran bulanan')}: <MoneyDisplay amount={c.monthlyBudget} currency={c.currency}/></p><p>{t('Estimated interest','Estimasi bunga')}: <MoneyDisplay amount={c.totalInterest} currency={c.currency}/></p><p>{c.paidOff?`${t('Payoff date','Tanggal lunas')}: ${formatDate(c.payoffDate)}`:c.reason}</p><ul>{#each c.warnings??[] as warning}<li>{items.find(d=>d.id===warning.debtId)?.name}: {t('The minimum payment alone does not reduce principal. Extra payments may be needed.','Pembayaran minimum saja tidak mengurangi pokok. Pembayaran tambahan mungkin diperlukan.')}</li>{/each}</ul><details><summary>{t('Payment schedule','Jadwal pembayaran')}</summary><div class="scroll"><table><caption>{t('Estimated payments, not recorded transactions','Estimasi pembayaran, bukan transaksi tercatat')}</caption><thead><tr><th>{t('Date','Tanggal')}</th><th>{t('Debt','Utang')}</th><th>{t('Interest','Bunga')}</th><th>{t('Payment','Pembayaran')}</th><th>{t('Remaining','Sisa')}</th></tr></thead><tbody>{#each c.rows as row}<tr><td>{formatDate(row.date)}</td><td>{items.find(d=>d.id===row.debtId)?.name}</td><td><MoneyDisplay amount={row.interest} currency={c.currency}/></td><td><MoneyDisplay amount={row.payment} currency={c.currency}/></td><td><MoneyDisplay amount={row.closing} currency={c.currency}/></td></tr>{/each}</tbody></table></div></details></section>{/each}</div></Card.Content></Card.Root>
<AlertDialog.Root bind:open={confirm}><AlertDialog.Content><AlertDialog.Header><AlertDialog.Title>{t('Record this payment?','Catat pembayaran ini?')}</AlertDialog.Title><AlertDialog.Description>{t('This will post a principal transfer and any interest/fee expense. It does not send money to your lender. Recorded debt payment transactions are protected from edits and deletion.','Ini mencatat transfer pokok serta pengeluaran bunga/biaya. Uang tidak dikirim ke pemberi pinjaman. Transaksi pembayaran terlindungi dari perubahan dan penghapusan.')}</AlertDialog.Description></AlertDialog.Header><AlertDialog.Footer><AlertDialog.Cancel>{t('Cancel','Batal')}</AlertDialog.Cancel><AlertDialog.Action onclick={pay}>{t('Confirm recording','Konfirmasi pencatatan')}</AlertDialog.Action></AlertDialog.Footer></AlertDialog.Content></AlertDialog.Root>
<AlertDialog.Root open={!!archive} onOpenChange={(v)=>{if(!v)archive=null;}}><AlertDialog.Content><AlertDialog.Header><AlertDialog.Title>{t('Archive debt?','Arsipkan utang?')}</AlertDialog.Title><AlertDialog.Description>{t('The linked account and payment history will be kept.','Akun terkait dan riwayat pembayaran tetap disimpan.')}</AlertDialog.Description></AlertDialog.Header><AlertDialog.Footer><AlertDialog.Cancel>{t('Cancel','Batal')}</AlertDialog.Cancel><AlertDialog.Action onclick={async()=>{if(archive&&await send(`debts/${archive.id}`,null,'DELETE')){archive=null;await load();}}}>{t('Archive','Arsipkan')}</AlertDialog.Action></AlertDialog.Footer></AlertDialog.Content></AlertDialog.Root>
<style>.grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px;align-items:start}.list{display:grid;gap:16px}.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));gap:16px;margin:16px 0}label{display:grid;gap:8px;font-size:14px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.scroll{overflow:auto;max-height:400px}table{width:100%;font-size:14px}th,td{padding:12px;text-align:left;border-bottom:1px solid var(--border);white-space:nowrap}summary{cursor:pointer;min-height:44px;display:flex;align-items:center}label :global([data-slot=select-trigger]){width:100%}.grid :global([data-slot=card]){margin-bottom:24px}@media(max-width:760px){.grid{grid-template-columns:minmax(0,1fr)}}</style>
