<script lang="ts">
 import {getContext,untrack} from 'svelte';import {env} from '$env/dynamic/public';
 import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import * as AlertDialog from '$lib/components/ui/alert-dialog';
 import {Input} from '$lib/components/ui/input';import PasswordInput from '$lib/components/forms/password-input.svelte';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import PageHeader from '$lib/components/shared/page-header.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';import {formatDateTime} from '$lib/dates';
 const workspace=getContext<{selectedId:string;ready:boolean;revision?:number}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 type Connection={id:string;provider:string;sandbox:boolean;clientId:string;accountId:string;categoryId:string;disabledAt:string|null;createdAt:string};
 type Verification={checkedAt:string;sandbox:boolean;status:string;providerVerified:boolean;callbackReceivedAt:string|null;complete:boolean};
 let verification:Record<string,Verification>=$state({}),checkErrors:Record<string,string>=$state({}),disableTarget:Connection|null=$state(null),notice=$state('');
 let items:Connection[]=$state([]),accounts:any[]=$state([]),categories:any[]=$state([]),loading=$state(false),saving=$state(false),error=$state(''),projectSlug=$state(''),apiKey=$state(''),webhookSecret=$state(''),environment=$state('sandbox'),accountId=$state(''),categoryId=$state(''),sequence=0;
 const endpoint=(ws:string)=>'/api/workspaces/'+ws;
 function mode(sandbox:boolean){return sandbox?copy('Test mode · no real payments','Mode uji coba · bukan pembayaran nyata'):copy('Live mode · real payments','Mode langsung · pembayaran nyata');}
 function paymentStatus(status:string){return status==='SUCCESS'?copy('Payment successful','Pembayaran berhasil'):status==='PENDING'?copy('Waiting for payment','Menunggu pembayaran'):status==='FAILED'?copy('Payment failed','Pembayaran gagal'):status==='EXPIRED'?copy('Payment expired','Pembayaran kedaluwarsa'):status==='CANCELLED'?copy('Payment cancelled','Pembayaran dibatalkan'):copy('Status not recognized','Status tidak dikenal');}
 function callbackPath(item:Connection){return '/api/payments/'+item.provider+'/'+item.id;}
 function notificationUrl(item:Connection){try{const url=new URL(env.PUBLIC_API_URL??'');return ['https:','http:'].includes(url.protocol)?url.origin+callbackPath(item):callbackPath(item);}catch{return callbackPath(item);}}
 async function call(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.message??copy('Request failed.','Permintaan gagal.'));return result;}
 async function load(ws:string){const current=++sequence;loading=true;error='';try{const [connections,wallets,cats]=await Promise.all([call(endpoint(ws)+'/payment-connections'),call(endpoint(ws)+'/accounts'),call(endpoint(ws)+'/categories')]);if(current===sequence&&ws===workspace.selectedId){items=connections.items;accounts=wallets.items.filter((a:any)=>a.currency==='IDR');categories=cats.items.filter((c:any)=>c.type==='income');}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{void workspace.revision;if(workspace.ready&&workspace.selectedId){const ws=workspace.selectedId;untrack(()=>{items=[];verification={};checkErrors={};disableTarget=null;notice='';accounts=[];categories=[];apiKey='';webhookSecret='';projectSlug='';accountId='';categoryId='';environment='sandbox';void load(ws);});}});
 async function save(event:SubmitEvent){event.preventDefault();if(saving||loading)return;const ws=workspace.selectedId;saving=true;error='';notice='';try{await call(endpoint(ws)+'/payment-connections','POST',{projectSlug,apiKey,webhookSecret,sandbox:environment==='sandbox',accountId,categoryId});if(ws===workspace.selectedId){apiKey='';webhookSecret='';await load(ws);if(ws===workspace.selectedId)notice=copy('Connection saved. Set its notification URL in Pakasir, then check it using an invoice payment. Saving alone does not verify the connection.','Koneksi tersimpan. Atur URL notifikasinya di Pakasir, lalu periksa menggunakan pembayaran invoice. Menyimpan saja belum memverifikasi koneksi.');}}catch(e){if(ws===workspace.selectedId)error=e instanceof Error?e.message:String(e);}finally{saving=false;}}
 async function verify(id:string){if(saving||loading)return;const ws=workspace.selectedId;saving=true;checkErrors[id]='';delete verification[id];try{const result=await call(endpoint(ws)+'/payment-connections/'+id+'/verify','POST',{});if(ws===workspace.selectedId)verification[id]=result;}catch(e){if(ws===workspace.selectedId)checkErrors[id]=e instanceof Error?e.message:String(e);}finally{saving=false;}}
 async function disable(){const target=disableTarget;if(saving||loading||!target)return;const ws=workspace.selectedId;disableTarget=null;saving=true;error='';notice='';try{await call(endpoint(ws)+'/payment-connections/'+target.id,'DELETE');if(ws===workspace.selectedId){delete verification[target.id];await load(ws);if(ws===workspace.selectedId)notice=copy('Connection disabled for new payments. Existing payment requests will still be checked.','Koneksi dinonaktifkan untuk pembayaran baru. Permintaan pembayaran yang sudah ada tetap diperiksa.');}}catch(e){if(ws===workspace.selectedId)error=e instanceof Error?e.message:String(e);}finally{saving=false;}}
 async function copyNotification(item:Connection){const ws=workspace.selectedId;try{await navigator.clipboard.writeText(notificationUrl(item));if(ws===workspace.selectedId)notice=notificationUrl(item)===callbackPath(item)?copy('Notification path copied. Add your public API address before this path.','Jalur notifikasi disalin. Tambahkan alamat API publik di depan jalur ini.'):copy('Notification URL copied. Paste it into this project’s Pakasir settings.','URL notifikasi disalin. Tempelkan ke pengaturan proyek ini di Pakasir.');}catch{if(ws===workspace.selectedId)notice=copy('Select the notification address and copy it manually.','Pilih alamat notifikasi dan salin secara manual.');}}
</script>
<svelte:head><title>CapyBudget · Pakasir</title></svelte:head><LoadingScope active={loading||saving}/><PageHeader title={copy('Payment connections','Koneksi pembayaran')} description={copy('Connect Pakasir for your own QRIS invoice payment pages.','Hubungkan Pakasir untuk halaman pembayaran faktur QRIS Anda sendiri.')}/>
{#if error}<ErrorState title={copy('Could not update connection','Koneksi gagal diperbarui')} message={error} onRetry={()=>load(workspace.selectedId)} retryLabel={copy('Retry','Coba lagi')}/>{/if}
<div role="status" aria-live="polite" aria-atomic="true">{#if notice}<p class="mb-6 rounded-[14px] border border-border bg-muted p-4 text-sm leading-relaxed">{notice}</p>{/if}</div>
<div class="space-y-6"><Card.Root><Card.Header><Card.Title>{copy('Add a Pakasir connection','Tambahkan koneksi Pakasir')}</Card.Title><Card.Description>{copy('Choose an IDR account and income category for confirmed invoice payments. Start in test mode. Only the business owner can set this up; saved keys are encrypted and stay hidden.','Pilih akun IDR dan kategori pemasukan untuk pembayaran invoice yang dikonfirmasi. Mulai dalam mode uji coba. Hanya pemilik bisnis yang dapat mengatur ini; kunci tersimpan dienkripsi dan tetap disembunyikan.')}</Card.Description></Card.Header><Card.Content><form onsubmit={save} class="space-y-4"><div class="grid gap-4 sm:grid-cols-2">
<Field.Field><Field.FieldLabel for="pakasir-environment">{copy('Payment mode','Mode pembayaran')}</Field.FieldLabel><ChoiceSelect id="pakasir-environment" disabled={loading||saving} bind:value={environment} items={[{value:'sandbox',label:copy('Test mode (sandbox)','Mode uji coba (sandbox)')},{value:'production',label:copy('Live mode — real payments','Mode langsung — pembayaran nyata')}]}/></Field.Field>
<Field.Field><Field.FieldLabel for="pakasir-client">{copy('Pakasir project code (slug)','Kode proyek Pakasir (slug)')}</Field.FieldLabel><Input id="pakasir-client" disabled={loading||saving} bind:value={projectSlug} maxlength={128} required autocomplete="off"/></Field.Field>
<Field.Field><Field.FieldLabel for="pakasir-secret">API key</Field.FieldLabel><PasswordInput id="pakasir-secret" disabled={loading||saving} bind:value={apiKey} required autocomplete="new-password"/></Field.Field>
<Field.Field><Field.FieldLabel for="pakasir-webhook-secret">{copy('Notification verification key (webhook secret)','Kunci verifikasi notifikasi (webhook secret)')}</Field.FieldLabel><PasswordInput id="pakasir-webhook-secret" disabled={loading||saving} bind:value={webhookSecret} required autocomplete="new-password"/></Field.Field>
<Field.Field><Field.FieldLabel for="pakasir-account">{copy('Record payments in (IDR account)','Catat pembayaran di (akun IDR)')}</Field.FieldLabel><ChoiceSelect id="pakasir-account" disabled={loading||saving} bind:value={accountId} aria-describedby="pakasir-account-help" required items={[{value:'',label:copy('Select','Pilih')},...accounts.map(a=>({value:a.id,label:a.name}))]}/><p id="pakasir-account-help" class="text-sm leading-relaxed text-muted-foreground">{copy('Used for recording payments in CapyBudget. This does not change your payout bank account in Pakasir.','Dipakai untuk mencatat pembayaran di CapyBudget. Ini tidak mengubah rekening pencairan dana Anda di Pakasir.')}</p></Field.Field>
<Field.Field><Field.FieldLabel for="pakasir-category">{copy('Income category','Kategori pemasukan')}</Field.FieldLabel><ChoiceSelect id="pakasir-category" disabled={loading||saving} bind:value={categoryId} required items={[{value:'',label:copy('Select','Pilih')},...categories.map(c=>({value:c.id,label:c.name}))]}/></Field.Field></div>
<p class="text-sm text-muted-foreground">{copy('Copy the project slug, API key, and webhook secret from Pakasir. Choose the same environment as the project’s sandbox setting; this form does not change its mode. Your API key and notification key stay hidden after saving.','Salin slug proyek, API key, dan webhook secret dari Pakasir. Pilih lingkungan sesuai pengaturan sandbox proyek; formulir ini tidak mengubah mode proyek. API key dan kunci notifikasi tetap disembunyikan setelah disimpan.')}</p><Button type="submit" disabled={loading||saving||!accountId||!categoryId}>{copy('Save connection','Simpan koneksi')}</Button></form></Card.Content></Card.Root>
<Card.Root><Card.Header><div class="flex flex-wrap items-center justify-between gap-4"><Card.Title>{copy('Saved connections','Koneksi tersimpan')}</Card.Title><Button variant="outline" disabled={loading||saving} onclick={()=>load(workspace.selectedId)}>{copy('Refresh connections','Muat ulang koneksi')}</Button></div><Card.Description>{copy('An enabled Pakasir connection can create new payment requests. A working notification URL lets payment updates reach CapyBudget.','Koneksi Pakasir yang diaktifkan dapat membuat permintaan pembayaran baru. URL notifikasi yang berfungsi memungkinkan kabar pembayaran diterima CapyBudget.')}</Card.Description></Card.Header>
<Card.Content class="space-y-6">
 {#if !loading&&!items.length}<div class="space-y-2 rounded-[20px] border-2 border-border bg-muted/40 p-6"><p class="font-semibold">{copy('No payment connections yet','Belum ada koneksi pembayaran')}</p><p class="text-sm text-muted-foreground">{copy('Add a Pakasir test connection using the form above. Then create a QRIS payment from an invoice.','Tambahkan koneksi uji coba Pakasir melalui formulir di atas. Lalu buat pembayaran QRIS dari invoice.')}</p></div>{/if}
 {#each items as item(item.id)}
  <article class="space-y-6 rounded-[20px] border-2 border-border p-4 sm:p-6" aria-labelledby={'connection-title-'+item.id}>
   <div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0 space-y-2"><h2 id={'connection-title-'+item.id} class="break-all text-base font-semibold">{item.provider==='doku'?copy('DOKU · previous provider','DOKU · penyedia sebelumnya'):'Pakasir'} · {item.clientId}</h2><div class="flex flex-wrap gap-2"><span class="rounded-full border border-border bg-muted px-3 py-1 text-sm">{mode(item.sandbox)}</span><span class="rounded-full border border-border bg-muted px-3 py-1 text-sm font-semibold">{item.disabledAt?copy('Disabled for new payments','Nonaktif untuk pembayaran baru'):copy('Enabled for new payments','Aktif untuk pembayaran baru')}</span></div></div></div>
   <dl class="grid gap-4 sm:grid-cols-2"><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Record received payments in','Catat pembayaran masuk di')}</dt><dd class="break-words text-sm text-muted-foreground">{accounts.find(a=>a.id===item.accountId)?.name??copy('Account unavailable or archived','Akun tidak tersedia atau diarsipkan')}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Income category','Kategori pemasukan')}</dt><dd class="break-words text-sm text-muted-foreground">{categories.find(c=>c.id===item.categoryId)?.name??copy('Category unavailable or archived','Kategori tidak tersedia atau diarsipkan')}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Saved on','Disimpan pada')}</dt><dd class="text-sm text-muted-foreground">{formatDateTime(item.createdAt,ui.locale)}</dd></div>{#if item.disabledAt}<div class="space-y-1"><dt class="text-sm font-semibold">{copy('Disabled on','Dinonaktifkan pada')}</dt><dd class="text-sm text-muted-foreground">{formatDateTime(item.disabledAt,ui.locale)}</dd></div>{/if}</dl>
   {#if item.provider==='doku'}<p class="text-sm leading-relaxed text-muted-foreground">{copy('This older connection is kept for existing payment history. New QRIS payment requests use Pakasir.','Koneksi lama ini dipertahankan untuk riwayat pembayaran yang sudah ada. Permintaan pembayaran QRIS baru menggunakan Pakasir.')}</p>{/if}
   {#if !item.disabledAt}
    <div class="space-y-3 rounded-[14px] border border-border bg-muted/40 p-4"><h3 class="text-sm font-semibold">{copy('Where payment updates are sent','Alamat penerima kabar pembayaran')}</h3><p class="text-sm leading-relaxed text-muted-foreground">{copy('Set this as the notification / webhook URL in this project’s provider dashboard. It lets CapyBudget receive payment confirmations automatically.','Atur alamat ini sebagai URL notifikasi / webhook pada dasbor penyedia proyek ini. CapyBudget dapat menerima konfirmasi pembayaran secara otomatis.')}</p><Field.Field><Field.FieldLabel for={'notification-'+item.id}>{notificationUrl(item)===callbackPath(item)?copy('Notification path','Jalur notifikasi'):copy('Notification URL','URL notifikasi')}</Field.FieldLabel><Input id={'notification-'+item.id} readonly value={notificationUrl(item)} onclick={event=>event.currentTarget.select()} aria-describedby={'notification-help-'+item.id}/></Field.Field><p id={'notification-help-'+item.id} class="text-sm leading-relaxed text-muted-foreground">{notificationUrl(item)===callbackPath(item)?copy('Add your public API address before this exact path. Your notification URL must be reachable from the internet.','Tambahkan alamat API publik sebelum jalur persis ini. URL notifikasi harus dapat diakses dari internet.'):copy('This address uses the app’s configured API URL. For local testing, replace localhost with your public HTTPS tunnel address. Copying it does not update Pakasir settings.','Alamat ini memakai URL API yang dikonfigurasi pada aplikasi. Untuk pengujian lokal, ganti localhost dengan alamat tunnel HTTPS publik. Menyalinnya tidak mengubah pengaturan Pakasir.')}</p><Button variant="outline" onclick={()=>copyNotification(item)}>{notificationUrl(item)===callbackPath(item)?copy('Copy notification path','Salin jalur notifikasi'):copy('Copy notification URL','Salin URL notifikasi')}</Button></div>
    {#if item.provider==='pakasir'}<div class="space-y-3"><h3 class="text-sm font-semibold">{copy('Check this connection','Periksa koneksi ini')}</h3><p class="text-sm leading-relaxed text-muted-foreground">{copy('Checks the most recent existing payment and whether its payment notification was received. Create a QRIS payment from an invoice first. This check does not create or simulate a payment.','Memeriksa pembayaran terbaru yang sudah ada dan apakah notifikasinya diterima. Buat pembayaran QRIS dari invoice terlebih dahulu. Pemeriksaan ini tidak membuat atau menyimulasikan pembayaran.')}</p><Button variant="outline" disabled={saving||loading} aria-label={copy('Check Pakasir connection ','Periksa koneksi Pakasir ')+item.clientId} onclick={()=>verify(item.id)}>{copy('Check payment connection','Periksa koneksi pembayaran')}</Button>
     {#if checkErrors[item.id]}<div role="alert" class="space-y-2 rounded-[14px] border border-border bg-muted p-4"><p class="text-sm font-semibold">{copy('Check could not be completed','Pemeriksaan belum dapat diselesaikan')}</p><p class="text-sm leading-relaxed">{checkErrors[item.id]}</p><p class="text-sm text-muted-foreground">{copy('Make sure this connection has an existing QRIS payment and its project mode matches Pakasir.','Pastikan koneksi ini sudah memiliki pembayaran QRIS dan mode proyeknya sesuai dengan Pakasir.')}</p></div>{/if}
     {#if verification[item.id]}{@const result=verification[item.id]}<div role="status" class="space-y-4 rounded-[20px] border-2 border-border bg-muted/40 p-4"><h4 class="text-sm font-semibold">{result.complete?copy('Payment and notification confirmed','Pembayaran dan notifikasi dikonfirmasi'):copy('Connection check needs follow-up','Pemeriksaan koneksi perlu ditindaklanjuti')}</h4><dl class="grid gap-4 sm:grid-cols-2"><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Payment provider check','Pemeriksaan penyedia pembayaran')}</dt><dd class="text-sm">{result.providerVerified?copy('Payment details verified','Detail pembayaran terverifikasi'):copy('Not confirmed','Belum dikonfirmasi')}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Latest payment status','Status pembayaran terbaru')}</dt><dd class="text-sm">{paymentStatus(result.status)}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Payment notification','Notifikasi pembayaran')}</dt><dd class="text-sm">{result.callbackReceivedAt?copy('Received on ','Diterima pada ')+formatDateTime(result.callbackReceivedAt,ui.locale):copy('No matching notification recorded','Belum ada notifikasi yang cocok tercatat')}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Last checked this visit','Terakhir diperiksa dalam kunjungan ini')}</dt><dd class="text-sm">{formatDateTime(result.checkedAt,ui.locale)}</dd></div></dl><p class="text-sm leading-relaxed text-muted-foreground">{!result.callbackReceivedAt?(result.sandbox?copy('Check the notification URL in Pakasir. Complete a sandbox payment and check again after its notification arrives.','Periksa URL notifikasi di Pakasir. Selesaikan pembayaran sandbox lalu periksa kembali setelah notifikasinya diterima.'):copy('Check this project’s notification URL in Pakasir and ensure it is publicly reachable. Check again after the notification for this payment arrives.','Periksa URL notifikasi proyek ini di Pakasir dan pastikan dapat diakses publik. Periksa kembali setelah notifikasi pembayaran ini diterima.')):result.status!=='SUCCESS'?copy('A matching notification was received, but this payment is not successful yet. Check the invoice’s payment status.','Notifikasi yang cocok telah diterima, tetapi pembayaran ini belum berhasil. Periksa status pembayaran invoice.'):copy('These results apply to the payment checked at this time; they do not guarantee every future payment will succeed.','Hasil ini berlaku untuk pembayaran yang diperiksa pada saat ini; bukan jaminan semua pembayaran berikutnya akan berhasil.')}</p></div>{/if}
    </div>{/if}
    <details class="rounded-[14px] border border-border"><summary class="min-h-11 cursor-pointer rounded-[14px] px-4 py-3 text-sm text-muted-foreground focus-visible:outline-2 focus-visible:outline-ring">{copy('Disable or replace this connection','Nonaktifkan atau ganti koneksi ini')}</summary><div class="space-y-3 px-4 pb-4"><p class="text-sm leading-relaxed text-muted-foreground">{copy('Disable this connection before saving a replacement in the same mode. New payment requests stop using it; existing payment requests continue to be checked.','Nonaktifkan koneksi ini sebelum menyimpan pengganti dalam mode yang sama. Permintaan pembayaran baru berhenti memakai koneksi ini; permintaan yang sudah ada tetap diperiksa.')}</p><Button variant="outline" disabled={saving||loading} onclick={()=>disableTarget=item}>{copy('Disable connection','Nonaktifkan koneksi')}</Button></div></details>
   {:else}<p class="text-sm leading-relaxed text-muted-foreground">{copy('This connection cannot create new payment requests. Existing requests still get checked. To accept new payments, add a new connection using the form above.','Koneksi ini tidak dapat membuat permintaan pembayaran baru. Permintaan yang sudah ada tetap diperiksa. Untuk menerima pembayaran baru, tambahkan koneksi baru melalui formulir di atas.')}</p>{/if}
  </article>
 {/each}
</Card.Content></Card.Root></div>
<AlertDialog.Root open={!!disableTarget} onOpenChange={open=>{if(!open&&!saving)disableTarget=null;}}><AlertDialog.Content><AlertDialog.Header><AlertDialog.Title>{copy('Disable this payment connection?','Nonaktifkan koneksi pembayaran ini?')}</AlertDialog.Title><AlertDialog.Description>{disableTarget?.clientId} · {mode(disableTarget?.sandbox??true)}. {copy('New payment requests can no longer use this connection. Existing payments will still be checked. This does not cancel invoices or delete payment history. To use this mode again, save a new connection.','Permintaan pembayaran baru tidak dapat lagi menggunakan koneksi ini. Pembayaran yang sudah ada tetap diperiksa. Ini tidak membatalkan invoice atau menghapus riwayat pembayaran. Untuk memakai mode ini lagi, simpan koneksi baru.')}</AlertDialog.Description></AlertDialog.Header><AlertDialog.Footer><AlertDialog.Cancel disabled={saving} onclick={()=>disableTarget=null}>{copy('Keep enabled','Tetap aktifkan')}</AlertDialog.Cancel><Button disabled={saving||loading} onclick={disable}>{copy('Disable connection','Nonaktifkan koneksi')}</Button></AlertDialog.Footer></AlertDialog.Content></AlertDialog.Root>
