import {saveFeedbackTargets} from './feedback';
import {hasLanguageConsent} from './providers';
import {opportunityFindings} from './opportunities';
import type {TransactionSql} from 'postgres';
import { buildForecastSources } from '../sources';
import { fromUnits,toUnits } from '../money';
import { revealRow,protectedJson } from '../../security/business-fields';
import { ANALYTICS_VERSION,businessBurn,customerMetrics,detectFindings,goalCoaching,shiftDate,spendingComparison,type SpendingRow } from './calculations';
import {randomUUID} from 'node:crypto';
export const v2q=async(tx:TransactionSql,s:string,v:unknown[]=[]) => (await tx.unsafe(s,v as never[])).map(r=>revealRow(r,String(v[0]??'')));
export function v2Reject(code:string,message:string,status=422):never{throw Object.assign(new Error(message),{status,code});}
export async function v2Context(tx:TransactionSql,ws:string,user:string,workspace:{currency:string;timezone:string;kind:string}){
 const [prefs]=await v2q(tx,'select * from assistant_settings where workspace_id=$1 and user_id=$2',[ws,user]);if(!prefs||!prefs.local_forecast_enabled)v2Reject('FORECAST_DISABLED','Enable local forecasts in Assistant settings.',403);
 const built=await buildForecastSources(tx,ws,user,workspace,prefs,Number(prefs.default_horizon_days),null);
 return {prefs,built,accountIds:built.accounts.map(a=>a.id)};
}
export async function spendingRows(tx:TransactionSql,ws:string,actor:string,accountIds:string[],since:string,through:string,merchant:boolean):Promise<SpendingRow[]>{
 const rows=await v2q(tx,`select t.id,t.occurred_at::text as date,t.amount::text,t.currency,t.type,t.account_id as "accountId",ac.name as "accountName",t.category_id as "categoryId",coalesce(c.name,'Uncategorized') as "categoryName",la.class as "ledgerClass",coalesce(o.exclude_from_baseline,false) as "oneOff",${merchant?"coalesce(t.merchant,'')":"''"} as merchant,
 exists(select 1 from recurring_occurrences r where r.workspace_id=t.workspace_id and r.transaction_id=t.id) as "recurringRuleId",
 exists(select 1 from invoice_payments p where p.workspace_id=t.workspace_id and p.transaction_id=t.id) as "invoiceLinked",
 (exists(select 1 from bill_occurrences b where b.workspace_id=t.workspace_id and b.transaction_id=t.id) or exists(select 1 from vendor_bill_payments p where p.workspace_id=t.workspace_id and p.transaction_id=t.id)) as "billLinked",
 exists(select 1 from subscription_transaction_links l where l.workspace_id=t.workspace_id and l.transaction_id=t.id) as "subscriptionLinked"
 from transactions t join accounts ac on ac.workspace_id=t.workspace_id and ac.id=t.account_id left join categories c on c.workspace_id=t.workspace_id and c.id=t.category_id left join ledger_accounts la on la.workspace_id=c.workspace_id and la.id=c.ledger_account_id left join forecast_transaction_overrides o on o.workspace_id=t.workspace_id and o.transaction_id=t.id and o.user_id=$5
 where t.workspace_id=$1 and t.account_id=any($2::uuid[]) and t.deleted_at is null and t.occurred_at between $3::date and $4::date and t.type in ('income','expense') order by t.occurred_at,t.id limit 5001`,[ws,accountIds,since,through,actor]);
 if(rows.length>5000)v2Reject('ANALYTICS_LIMIT','This window contains over 5,000 transactions. Narrow the account or period before analyzing.',422);return rows as SpendingRow[];
}
export async function goalsData(tx:TransactionSql,ws:string,ids:string[],currency:string,today:string,safe:string|null){
 return (await v2q(tx,`select g.id,g.name,g.target_amount::text as target,g.target_date::text as deadline,g.currency,coalesce(sum(case when c.direction='withdraw' then -c.amount else c.amount end) filter(where c.occurred_on <= $4::date),0)::text as allocated from savings_goals g left join goal_contributions c on c.workspace_id=g.workspace_id and c.goal_id=g.id where g.workspace_id=$1 and g.archived_at is null and g.currency=$2 and (g.linked_account_id is null or g.linked_account_id=any($3::uuid[])) group by g.id order by g.created_at limit 50`,[ws,currency,ids,today])).map(g=>({id:String(g.id),name:String(g.name),target:String(g.target),deadline:g.deadline as string|null,currency:String(g.currency),allocated:String(g.allocated),coaching:goalCoaching(g.target,g.allocated,g.deadline,today,safe,String(g.currency))}));
}
type Receivable={id:string;number:string;customerId:string|null;customerName:string;dueDate:string;total:string;paid:string;settledOn:string|null};
export async function receivablesData(tx:TransactionSql,ws:string,ids:string[],currency:string,today:string){
 const rows=await v2q(tx,`select i.id,i.number,i.contact_id as "customerId",coalesce(c.name,'Customer not linked') as "customerName",i.due_date::text as "dueDate",i.total::text,coalesce(sum(p.amount-p.refunded_amount) filter(where p.reversed_at is null and p.paid_on<=$4::date),0)::text as paid,max(p.paid_on) filter(where p.reversed_at is null and p.paid_on<=$4::date and p.amount>p.refunded_amount)::text as "settledOn" from invoices i left join business_contacts c on c.workspace_id=i.workspace_id and c.id=i.contact_id left join invoice_payments p on p.workspace_id=i.workspace_id and p.invoice_id=i.id where i.workspace_id=$1 and i.state='issued' and i.archived_at is null and i.currency=$2 and i.expected_account_id=any($3::uuid[]) group by i.id,c.name order by i.due_date limit 501`,[ws,currency,ids,today]);if(rows.length>500)v2Reject('RECEIVABLES_LIMIT','More than 500 invoices are in this account scope. Narrow the permitted accounts before analyzing.',422);return (rows as Receivable[]).map(invoice=>{const balance=toUnits(invoice.total)-toUnits(invoice.paid);return {...invoice,hasUnpaid:balance>0n,outstanding:fromUnits(balance>0n?balance:0n)};});
}
export async function analyticsData(tx:TransactionSql,ws:string,user:string,workspace:{currency:string;timezone:string;kind:string},dimension:'category'|'merchant'|'account'='category'){
 const {prefs,built,accountIds}=await v2Context(tx,ws,user,workspace),today=built.today;
 const rows=built.allowed.history?await spendingRows(tx,ws,user,accountIds,shiftDate(today,-90),today,Boolean(built.allowed.merchant)):[];
 if(dimension==='merchant'&&!built.allowed.merchant)v2Reject('SOURCE_DISABLED','Allow merchant data to compare merchant spending.',403);
 const comparisonRows=dimension==='category'&&built.allowed.history?await allocationRows(tx,ws,user,accountIds,shiftDate(today,-90),today):rows;
 const comparison=built.allowed.history?spendingComparison(comparisonRows,today,workspace.currency,dimension):null;
 const findings=[...(built.allowed.history?detectFindings(rows,workspace.currency):[]),...await opportunityFindings(tx,ws,accountIds,workspace.currency,today,built.allowed)];
 for(const f of findings){const [old]=await v2q(tx,'select id from insight_findings where workspace_id=$1 and user_id=$2 and fingerprint=$3',[ws,user,f.fingerprint]);const id=old?.id??randomUUID();await v2q(tx,`insert into insight_findings(id,workspace_id,user_id,consent_version,kind,fingerprint,detector_version,evidence,facts) values($3,$1,$2,$4,$5,$6,$7,$8::jsonb,$9::jsonb) on conflict(workspace_id,user_id,fingerprint) do update set consent_version=excluded.consent_version,detector_version=excluded.detector_version,state=case when insight_findings.state='obsolete' then 'active' else insight_findings.state end,evidence=excluded.evidence,facts=excluded.facts,expires_at=now()+interval '30 days'`,[ws,user,id,prefs.consent_version,f.kind,f.fingerprint,f.detectorVersion,JSON.stringify(f.evidence),protectedJson(f.facts,ws,id,'facts')]);}
 // Do not retain stale findings whose evidence was removed or whose threshold no longer holds.
 await v2q(tx,"update insight_findings set state='obsolete' where workspace_id=$1 and user_id=$2 and state in ('active','legitimate') and kind not in ('goal_coaching','savings') and fingerprint<>all($3::text[])",[ws,user,findings.map(f=>f.fingerprint)]);
 const saved=await v2q(tx,"select i.*,(select f.vote from assistant_feedback f where f.workspace_id=i.workspace_id and f.user_id=i.user_id and f.source_type='finding' and f.source_id=i.id and f.expires_at>now() order by f.updated_at desc limit 1) as feedback from insight_findings i where i.workspace_id=$1 and i.user_id=$2 and i.consent_version=$3 and i.kind not in ('goal_coaching','savings') and i.state not in ('obsolete','dismissed') and i.expires_at>now() order by i.created_at desc limit 100",[ws,user,prefs.consent_version]);
 let burn=null;const customers=[];
 if(workspace.kind==='business'){
  const operatingRows=rows.filter(r=>r.date>=shiftDate(today,-90)&&r.date<today&&r.currency===workspace.currency&&!(r as any).oneOff&&['income','expense'].includes((r as any).ledgerClass)),complete=built.result.qualityFlags.length===0&&Boolean(built.allowed.history)&&built.history.every((h:any)=>h.eligibleDays===90);
  burn={...businessBurn({inflows:fromUnits(operatingRows.filter(r=>r.type==='income').reduce((n,r)=>n+toUnits(r.amount),0n)),outflows:fromUnits(operatingRows.filter(r=>r.type==='expense').reduce((n,r)=>n+toUnits(r.amount),0n)),availableCash:fromUnits(built.accounts.reduce((n,a)=>n+toUnits(a.balance,true),0n)),protectedCash:fromUnits(built.accounts.reduce((n,a)=>n+toUnits(a.protectedAmount),toUnits(String(prefs.safety_buffer)))),days:90,complete,currency:workspace.currency}),windowStart:shiftDate(today,-90),windowEnd:shiftDate(today,-1),forecast:{horizonDays:Number(prefs.default_horizon_days),minimumBalance:built.result.minimumBalance,firstShortfallDate:built.result.firstShortfallDate,safeToSpend:built.result.safeToSpend}};
  if(built.allowed.invoices){const invoices=await receivablesData(tx,ws,accountIds,workspace.currency,today),ids=[...new Set(invoices.map(i=>i.customerId).filter(Boolean))];for(const customerId of ids){const metrics=customerMetrics(invoices.filter(i=>i.customerId===customerId) as any,today);const [old]=await v2q(tx,'select id from customer_payment_metrics where workspace_id=$1 and user_id=$2 and customer_id=$3',[ws,user,customerId]);const id=old?.id??randomUUID();await v2q(tx,'insert into customer_payment_metrics(id,workspace_id,user_id,consent_version,customer_id,as_of_date,metrics,algorithm_version) values($3,$1,$2,$4,$5,$6,$7::jsonb,$8) on conflict(workspace_id,user_id,customer_id) do update set metrics=excluded.metrics,as_of_date=excluded.as_of_date,expires_at=now()+interval \'30 days\'',[ws,user,id,prefs.consent_version,customerId,today,protectedJson(metrics,ws,id,'metrics'),ANALYTICS_VERSION]);customers.push({customerId,name:invoices.find(i=>i.customerId===customerId)?.customerName??'Customer',...metrics});}}
 }
 const rawGoals=built.allowed.goals?await goalsData(tx,ws,accountIds,workspace.currency,today,built.result.safeToSpend):[];
 const savingsFingerprint='savings:'+today.slice(0,7),targets=await saveFeedbackTargets(tx,ws,user,Number(prefs.consent_version),[...rawGoals.map(goal=>({kind:'goal_coaching',fingerprint:'goal:'+goal.id})),...(built.result.safeToSpend===null?[]:[{kind:'savings',fingerprint:savingsFingerprint}])]);
 const goals=rawGoals.map(goal=>({...goal,feedbackTarget:targets.get('goal:'+goal.id)!})).filter(goal=>!goal.feedbackTarget.dismissed),savingsFeedback=targets.get(savingsFingerprint)??null;

 const subscriptions=built.allowed.recurring?await v2q(tx,"select id,name,amount::text,currency,cadence,next_charge::text as \"nextCharge\" from subscriptions where workspace_id=$1 and account_id=any($2::uuid[]) and currency=$3 and status='active' order by next_charge limit 50",[ws,accountIds,workspace.currency]):[];
 return {asOfDate:today,currency:workspace.currency,algorithmVersion:ANALYTICS_VERSION,coverage:built.result.qualityFlags,comparison,findings:saved,burn,customers,goals,subscriptions,savingsOpportunity:built.result.safeToSpend===null||savingsFeedback?.dismissed?null:{feedbackTarget:savingsFeedback,maximumAllocation:built.result.safeToSpend,reason:'Only conservative headroom after obligations and protected reserves is available for review. No transfer is made.'},subscriptionReview:'Review confirmed subscriptions for overlapping services or price changes. Charges do not show whether a service is unused; no savings amount is invented.'};
}
export async function allocationRows(tx:TransactionSql,ws:string,actor:string,ids:string[],start:string,end:string):Promise<SpendingRow[]>{
 const rows=await v2q(tx,`select a.id,a.occurred_at::text as date,a.amount::text,a.currency,a.type,t.account_id as "accountId",ac.name as "accountName",a.category_id as "categoryId",coalesce(c.name,'Uncategorized') as "categoryName",'' as merchant from tracking_allocations a join transactions t on t.workspace_id=a.workspace_id and t.id=a.id join accounts ac on ac.workspace_id=t.workspace_id and ac.id=t.account_id left join categories c on c.workspace_id=a.workspace_id and c.id=a.category_id where a.workspace_id=$1 and t.account_id=any($2::uuid[]) and a.currency=t.currency and a.deleted_at is null and a.type in ('income','expense') and a.occurred_at between $3::date and $4::date order by a.occurred_at,a.id limit 5001`,[ws,ids,start,end]);if(rows.length>5000)v2Reject('ANALYTICS_LIMIT','This window contains over 5,000 category allocations. Narrow the account scope.',422);return rows as SpendingRow[];
}
/** Language entry uses explicit answer permissions, independently of forecast opt-in. */
export async function languageContext(tx:TransactionSql,ws:string,user:string){
 const [prefs]=await v2q(tx,'select * from assistant_settings where workspace_id=$1 and user_id=$2',[ws,user]);if(!hasLanguageConsent(prefs))v2Reject('AI_CONSENT_REQUIRED','Enable external language processing in Assistant settings.',403);
 const accounts=await v2q(tx,'select a.id,a.name,a.currency,a.kind from accounts a join assistant_account_settings s on s.workspace_id=a.workspace_id and s.account_id=a.id and s.user_id=$2 where a.workspace_id=$1 and s.allow_external_ai=true and a.archived_at is null and a.deleted_at is null order by a.created_at',[ws,user]);if(!accounts.length)v2Reject('ACCOUNT_CONSENT_REQUIRED','Allow at least one account in Capy answers in Assistant settings.',403);
 return {prefs,accounts,accountIds:accounts.map(a=>a.id),allowed:prefs.source_permissions as Record<string,boolean>};
}
