import type {TransactionSql} from 'postgres';
import {v2q as q} from './data';
import {ANALYTICS_VERSION,shiftDate} from './calculations';
import {fromUnits,toUnits} from '../money';
export async function opportunityFindings(tx:TransactionSql,ws:string,accountIds:string[],currency:string,today:string,permissions:Record<string,boolean>){
 const findings:Array<{kind:string;fingerprint:string;evidence:string[];facts:Record<string,unknown>;detectorVersion:string}>=[];
 if(permissions.recurring){
  const subscriptions=await q(tx,"select id,name,normalized_merchant,cadence,account_id,currency,amount::text from subscriptions where workspace_id=$1 and account_id=any($2::uuid[]) and currency=$3 and status='active' order by id limit 100",[ws,accountIds,currency]);
  for(const subscription of subscriptions){const overlap=subscriptions.filter(s=>s.id!==subscription.id&&s.normalized_merchant===subscription.normalized_merchant&&s.cadence===subscription.cadence&&s.account_id===subscription.account_id);if(permissions.merchant&&overlap.length){const ids=[subscription.id,...overlap.map(s=>s.id)].sort();if(subscription.id===ids[0])findings.push({kind:'subscription_overlap',fingerprint:'subscription-overlap:'+ids.join(':'),evidence:ids,facts:{amount:subscription.amount,currency,name:subscription.name,reason:'More than one confirmed active subscription has the same merchant, account and billing cadence. Check whether both are intentional; no cancellation or savings estimate is made.'},detectorVersion:ANALYTICS_VERSION});}
   if(permissions.history){const charges=await q(tx,"select t.id,t.amount::text,t.occurred_at::text from subscription_transaction_links l join transactions t on t.workspace_id=l.workspace_id and t.id=l.transaction_id where l.workspace_id=$1 and l.subscription_id=$2 and t.account_id=any($3::uuid[]) and t.deleted_at is null and t.type='expense' and t.currency=$4 and t.occurred_at<=$5::date order by t.occurred_at desc,t.id desc limit 2",[ws,subscription.id,accountIds,currency,today]);if(charges.length===2&&toUnits(charges[0]!.amount)>toUnits(charges[1]!.amount)*105n/100n)findings.push({kind:'subscription_charge_increase',fingerprint:'subscription-increase:'+subscription.id+':'+charges[0]!.id,evidence:charges.map(c=>c.id),facts:{amount:charges[0]!.amount,previousAmount:charges[1]!.amount,currency,name:subscription.name,reason:'The latest linked charge exceeds the previous charge by more than 5%. Review the billed period, fees and terms before treating this as a price increase.'},detectorVersion:ANALYTICS_VERSION});}
  }
 }
 if(permissions.budgets&&permissions.history){
  const budgets=await q(tx,`select b.id,b.name,b.amount::text,b.category_id,b.cadence from budgets b where b.workspace_id=$1 and b.currency=$2 and b.archived_at is null and b.starts_on<=$3::date order by b.id limit 100`,[ws,currency,today]);
  for(const budget of budgets){const day=new Date(today+'T00:00:00Z').getUTCDay(),start=budget.cadence==='weekly'?shiftDate(today,-((day+6)%7)):today.slice(0,8)+'01';const [totals]=await q(tx,`with recursive descendants(id) as (select $3::uuid union all select c.id from categories c join descendants d on c.parent_id=d.id where c.workspace_id=$1)
 select coalesce(sum(a.amount),0)::text as spent,array_agg(distinct a.id) as evidence from tracking_allocations a join transactions t on t.workspace_id=a.workspace_id and t.id=a.id where a.workspace_id=$1 and t.account_id=any($2::uuid[]) and a.category_id in (select id from descendants) and a.currency=$4 and a.type='expense' and a.deleted_at is null and a.occurred_at between $5::date and $6::date`,[ws,accountIds,budget.category_id,currency,start,today]);if(toUnits(totals!.spent)>toUnits(budget.amount))findings.push({kind:'budget_overspend',fingerprint:'budget-overspend:'+budget.id+':'+start,evidence:(totals!.evidence??[]).slice(0,50),facts:{amount:totals!.spent,budget:budget.amount,overBy:fromUnits(toUnits(totals!.spent)-toUnits(budget.amount)),currency,name:budget.name,reason:'Recorded expenses in permitted accounts are above this budget. Review future purchases or the target; the budget has not changed.'},detectorVersion:ANALYTICS_VERSION});}
 }
 return findings;
}
