<script lang="ts">
  import { getContext } from 'svelte'; import { AUTH_UI_CONTEXT,type AuthUiState } from '$lib/i18n/auth'; import { financeText } from '$lib/i18n/finance';
  import { Button } from '$lib/components/ui/button'; import * as Card from '$lib/components/ui/card'; import * as Field from '$lib/components/ui/field'; import { Input } from '$lib/components/ui/input';
  type WorkspaceState={selectedId:string;ready:boolean};type Goal={id:string;name:string;targetAmount:string;currency:string;targetDate:string|null;linkedAccountId:string|null;saved:string;remaining:string;progressPercent:string};type Account={id:string;name:string;currency:string};type Contribution={id:string;direction:'add'|'withdraw';amount:string;occurredOn:string;note:string|null};
  const workspace=getContext<WorkspaceState>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof financeText>[1])=>financeText(ui.locale,key);
  let items:Goal[]=$state([]),accounts:Account[]=$state([]),history:Record<string,Contribution[]>=$state({}),loading=$state(true),error=$state(''),name=$state(''),targetAmount=$state(''),targetDate=$state(''),linkedAccountId=$state(''),contributions:Record<string,string>=$state({}),directions:Record<string,'add'|'withdraw'>=$state({}),saving=$state(false);
  async function load(){if(!workspace.ready||!workspace.selectedId)return;loading=true;try{const [r,a]=await Promise.all([fetch(`/api/workspaces/${workspace.selectedId}/goals`),fetch(`/api/workspaces/${workspace.selectedId}/accounts`)]);if(!r.ok||!a.ok)throw new Error(t('error'));items=(await r.json()).items;accounts=(await a.json()).items;for(const goal of items){const h=await fetch(`/api/workspaces/${workspace.selectedId}/goals/${goal.id}/contributions`);if(h.ok)history[goal.id]=(await h.json()).items;}}catch(e){error=e instanceof Error?e.message:t('error');}finally{loading=false;}}
  $effect(()=>{if(workspace.ready&&workspace.selectedId)void load();});
  async function create(event:SubmitEvent){event.preventDefault();if(saving)return;saving=true;error='';try{const r=await fetch(`/api/workspaces/${workspace.selectedId}/goals`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,targetAmount,targetDate:targetDate||null,linkedAccountId:linkedAccountId||null})});const b=await r.json();if(!r.ok)throw new Error(b.message);name='';targetAmount='';targetDate='';linkedAccountId='';await load();}catch(e){error=e instanceof Error?e.message:t('error');}finally{saving=false;}}
  async function add(event:SubmitEvent,id:string){event.preventDefault();const amount=contributions[id];if(!amount)return;error='';try{const r=await fetch(`/api/workspaces/${workspace.selectedId}/goals/${id}/contributions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,direction:directions[id]??'add'})});const b=await r.json();if(!r.ok)throw new Error(b.message);contributions[id]='';await load();}catch(e){error=e instanceof Error?e.message:t('error');}}
  async function archive(id:string){await fetch(`/api/workspaces/${workspace.selectedId}/goals/${id}`,{method:'DELETE'});await load();}
  function percent(goal:Goal){return Number(goal.progressPercent);}
</script>
<svelte:head><title>CapyBudget · {t('goals')}</title></svelte:head>
<div class="page-head"><div><p class="eyebrow">Personal finance</p><h1>{t('goals')}</h1><p>A small steady contribution fills the pool over time.</p></div></div>{#if error}<p class="error" role="alert">{error}</p>{/if}
<div class="grid"><Card.Root><Card.Header><Card.Title>{t('addGoal')}</Card.Title><Card.Description>Track your savings progress without changing account balances.</Card.Description></Card.Header><Card.Content><form onsubmit={create}><Field.FieldGroup><Field.Field><Field.FieldLabel for="goal-name">{t('name')}</Field.FieldLabel><Input id="goal-name" bind:value={name} maxlength={100} required /></Field.Field><Field.Field><Field.FieldLabel for="goal-target">{t('target')}</Field.FieldLabel><Input id="goal-target" type="text" inputmode="decimal" bind:value={targetAmount} required /></Field.Field><Field.Field><Field.FieldLabel for="goal-date">{t('targetDate')}</Field.FieldLabel><Input id="goal-date" type="date" bind:value={targetDate} /></Field.Field><Field.Field><Field.FieldLabel for="goal-account">{t('linkedAccount')}</Field.FieldLabel><select id="goal-account" bind:value={linkedAccountId}><option value="">{t('allAccounts')}</option>{#each accounts as account}<option value={account.id}>{account.name} · {account.currency}</option>{/each}</select></Field.Field></Field.FieldGroup><Button class="submit" type="submit" disabled={saving||!workspace.selectedId}>{saving?'…':t('addGoal')}</Button></form></Card.Content></Card.Root>
<section class="list">{#if loading}<p>{t('loading')}</p>{:else if !items.length}<Card.Root><Card.Content><p>{t('emptyGoals')}</p></Card.Content></Card.Root>{:else}{#each items as goal (goal.id)}{@const pct=percent(goal)}<Card.Root><Card.Header><div class="title-row"><div><Card.Title>{goal.name}</Card.Title><Card.Description>{goal.targetDate?`${t('targetDate')}: ${goal.targetDate}`:t('progress')}</Card.Description></div><Button variant="ghost" size="sm" onclick={()=>archive(goal.id)}>{t('archive')}</Button></div></Card.Header><Card.Content><div class="amounts"><strong>{goal.currency} {goal.saved}</strong><span>of {goal.currency} {goal.targetAmount}</span></div><progress aria-label={`${goal.name}: ${Math.min(100,pct).toFixed(0)}% saved`} max="100" value={Math.min(100,pct)}></progress><p class="caption">{Math.min(100,pct).toFixed(1)}% · {goal.currency} {goal.remaining} {t('remaining')}</p><form class="contribution" onsubmit={(event)=>add(event,goal.id)}><Field.Field><Field.FieldLabel for={`contribution-direction-${goal.id}`}>{t('direction')}</Field.FieldLabel><select id={`contribution-direction-${goal.id}`} bind:value={directions[goal.id]}><option value="add">{t('contribute')}</option><option value="withdraw">{t('withdraw')}</option></select></Field.Field><Field.Field><Field.FieldLabel for={`contribution-${goal.id}`}>{t('contribution')}</Field.FieldLabel><Input id={`contribution-${goal.id}`} type="text" inputmode="decimal" bind:value={contributions[goal.id]} required /></Field.Field><Button type="submit">{t('save')}</Button></form><details class="history"><summary>{t('transactionHistory')}</summary>{#if history[goal.id]?.length}{#each history[goal.id] as entry (entry.id)}<p>{entry.occurredOn} · {entry.direction==='add'?'+':'−'}{goal.currency} {entry.amount}{entry.note?` · ${entry.note}`:''}</p>{/each}{:else}<p>{t('emptyGoals')}</p>{/if}</details></Card.Content></Card.Root>{/each}{/if}</section></div>
<style>.page-head{margin-bottom:24px}.eyebrow{color:var(--muted-foreground);font-size:13px;margin:0 0 5px}h1{font:500 clamp(28px,4vw,38px) 'Fredoka Variable',sans-serif;margin:0}.page-head p:last-child{color:var(--muted-foreground);margin:8px 0 0}.grid{display:grid;grid-template-columns:minmax(250px,350px) minmax(0,1fr);gap:20px;align-items:start}.list{display:grid;gap:14px}.title-row,.amounts{display:flex;justify-content:space-between;gap:12px;align-items:center}.amounts{justify-content:flex-start;align-items:baseline;margin-bottom:12px;flex-wrap:wrap}.amounts strong{font-size:24px;font-variant-numeric:tabular-nums}.amounts span,.caption{color:var(--muted-foreground);font-size:13px}.caption{font-size:12px;font-variant-numeric:tabular-nums}progress{width:100%;height:13px;accent-color:#5BB8D4}.contribution{display:flex;align-items:end;gap:10px;margin-top:18px}.contribution :global([data-slot=field]){flex:1}:global(.submit){margin-top:18px;width:100%}.error{color:var(--destructive)}.grid :global([data-slot=field-group]){gap:14px}@media(max-width:760px){.grid{grid-template-columns:1fr}}
</style>
