<script lang="ts">
  import { formatDate } from '$lib/dates';
  import SavingsPool from '$lib/components/shared/savings-pool.svelte';
  import AmountInput from '$lib/components/forms/amount-input.svelte';
  import Disclosure from '$lib/components/shared/disclosure.svelte';
  import LoadingScope from '$lib/components/shared/loading-scope.svelte';
  import DatePicker from '$lib/components/forms/date-picker.svelte';
  import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
 import CapyMascot from '$lib/components/shared/capy-mascot.svelte';
  import {getContext as privacyContext} from 'svelte';
  import {concealed,PRIVACY_CONTEXT,type PrivacyState} from '$lib/privacy';
  const privacy=privacyContext<PrivacyState>(PRIVACY_CONTEXT);
  import { getContext } from 'svelte'; import { AUTH_UI_CONTEXT,type AuthUiState } from '$lib/i18n/auth'; import { financeText } from '$lib/i18n/finance'; import { uxText } from '$lib/i18n/ux';
  import { Button } from '$lib/components/ui/button'; import * as Card from '$lib/components/ui/card'; import * as Field from '$lib/components/ui/field'; import { Input } from '$lib/components/ui/input'; import * as AlertDialog from '$lib/components/ui/alert-dialog';
  import PageHeader from '$lib/components/shared/page-header.svelte'; import MoneyDisplay from '$lib/components/shared/money-display.svelte'; import EmptyState from '$lib/components/shared/empty-state.svelte'; import ErrorState from '$lib/components/shared/error-state.svelte'; import LoadingSkeleton from '$lib/components/shared/loading-skeleton.svelte';
  type WorkspaceState={selectedId:string;ready:boolean};type Goal={id:string;name:string;targetAmount:string;currency:string;targetDate:string|null;linkedAccountId:string|null;saved:string;remaining:string;progressPercent:string};type Account={id:string;name:string;currency:string};type Contribution={id:string;direction:'add'|'withdraw';amount:string;occurredOn:string;note:string|null};
  const workspace=getContext<WorkspaceState>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof financeText>[1])=>financeText(ui.locale,key);
  const ux=(key:Parameters<typeof uxText>[1])=>uxText(ui.locale,key);
  let items:Goal[]=$state([]),accounts:Account[]=$state([]),history:Record<string,Contribution[]>=$state({}),loading=$state(true),error=$state(''),name=$state(''),targetAmount=$state(''),targetDate=$state(''),linkedAccountId=$state(''),contributions:Record<string,string>=$state({}),directions:Record<string,'add'|'withdraw'>=$state({}),saving=$state(false),archiveTarget=$state<Goal|null>(null);
  async function load(){if(!workspace.ready||!workspace.selectedId)return;loading=true;try{const [r,a]=await Promise.all([fetch(`/api/workspaces/${workspace.selectedId}/goals`),fetch(`/api/workspaces/${workspace.selectedId}/accounts`)]);if(!r.ok||!a.ok)throw new Error(t('error'));items=(await r.json()).items;accounts=(await a.json()).items;for(const goal of items){const h=await fetch(`/api/workspaces/${workspace.selectedId}/goals/${goal.id}/contributions`);if(h.ok)history[goal.id]=(await h.json()).items;}}catch(e){error=e instanceof Error?e.message:t('error');}finally{loading=false;}}
  $effect(()=>{void (workspace as {revision?:number}).revision;if(workspace.ready&&workspace.selectedId)void load();});
  async function create(event:SubmitEvent){event.preventDefault();if(saving)return;saving=true;error='';try{const r=await fetch(`/api/workspaces/${workspace.selectedId}/goals`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,targetAmount,targetDate:targetDate||null,linkedAccountId:linkedAccountId||null})});const b=await r.json();if(!r.ok)throw new Error(b.message);name='';targetAmount='';targetDate='';linkedAccountId='';await load();}catch(e){error=e instanceof Error?e.message:t('error');}finally{saving=false;}}
  async function add(event:SubmitEvent,id:string){event.preventDefault();const amount=contributions[id];if(!amount)return;error='';try{const r=await fetch(`/api/workspaces/${workspace.selectedId}/goals/${id}/contributions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,direction:directions[id]??'add'})});const b=await r.json();if(!r.ok)throw new Error(b.message);contributions[id]='';await load();}catch(e){error=e instanceof Error?e.message:t('error');}}
  async function confirmArchive(){const target=archiveTarget;if(!target)return;archiveTarget=null;await fetch(`/api/workspaces/${workspace.selectedId}/goals/${target.id}`,{method:'DELETE'});await load();}
  function percent(goal:Goal){return Number(goal.progressPercent);}
</script>
<LoadingScope active={!!loading || !!saving} />
<svelte:head><title>CapyBudget · {t('goals')}</title></svelte:head>
<PageHeader eyebrow={t('financeEyebrow').toUpperCase()} title={t('goals')} description={t('goalIntro')} />
{#if error}<ErrorState title={ux('errorTitle')} message={error} retryLabel={ux('retry')} onRetry={load} />{/if}
<div class="grid"><Card.Root><Card.Header><Card.Title>{t('addGoal')}</Card.Title><Card.Description>{t('goalFormHint')}</Card.Description></Card.Header><Card.Content><form onsubmit={create}><Field.FieldGroup><Field.Field><Field.FieldLabel for="goal-name">{t('name')}</Field.FieldLabel><Input id="goal-name" bind:value={name} maxlength={100} required /></Field.Field><Field.Field><Field.FieldLabel for="goal-target">{t('target')}</Field.FieldLabel><AmountInput id="goal-target" inputmode="decimal"  type={privacy.hidden?'password':'text'} bind:value={targetAmount} required /></Field.Field><Field.Field><Field.FieldLabel for="goal-date">{t('targetDate')}</Field.FieldLabel><DatePicker id="goal-date" bind:value={targetDate} /></Field.Field><Field.Field><Field.FieldLabel for="goal-account">{t('linkedAccount')}</Field.FieldLabel><ChoiceSelect id="goal-account" bind:value={linkedAccountId} items={[{value: '', label: String(t('allAccounts'))}, ...(accounts).flatMap((account) => [{value: account.id, label: String(account.name) + " · " + String(account.currency)}])]} /></Field.Field></Field.FieldGroup><Button class="submit" type="submit" disabled={saving||!workspace.selectedId}>{saving?'…':t('addGoal')}</Button></form></Card.Content></Card.Root>
<section class="list" aria-label={t('goals')}>{#if loading}<LoadingSkeleton rows={3} label={t('loading')} />{:else if !items.length}<Card.Root><Card.Content><EmptyState title={t('goals')} body={t('emptyGoals')} actionLabel={t('addGoal')} actionHref="#goal-name" /></Card.Content></Card.Root>{:else}{#each items as goal (goal.id)}{@const pct=percent(goal)}<Card.Root><Card.Header><div class="title-row"><div><Card.Title><span class="goal-title">{goal.name}{#if !privacy.hidden && pct>=100}<CapyMascot size={32} state="celebrating" />{/if}</span></Card.Title><Card.Description>{goal.targetDate?`${t('targetDate')}: ${formatDate(goal.targetDate)}`:t('progress')}</Card.Description></div><Button variant="ghost" size="sm" onclick={()=>archiveTarget=goal}>{t('archive')}</Button></div></Card.Header><Card.Content><div class="amounts"><MoneyDisplay amount={goal.saved} currency={goal.currency} size="lg" /><span>{t('ofLabel')} <MoneyDisplay amount={goal.targetAmount} currency={goal.currency} /></span></div><SavingsPool name={goal.name} percent={goal.progressPercent===null ? null : pct} /><p class="caption"><MoneyDisplay amount={goal.remaining} currency={goal.currency} /> {t('remaining')}</p><form class="contribution" onsubmit={(event)=>add(event,goal.id)}><Field.Field><Field.FieldLabel for={`contribution-direction-${goal.id}`}>{t('direction')}</Field.FieldLabel><ChoiceSelect id={`contribution-direction-${goal.id}`} bind:value={directions[goal.id]} items={[{value: "add", label: String(t('contribute'))}, {value: "withdraw", label: String(t('withdraw'))}]} /></Field.Field><Field.Field><Field.FieldLabel for={`contribution-${goal.id}`}>{t('contribution')}</Field.FieldLabel><AmountInput currency={goal.currency} id={`contribution-${goal.id}`} type={privacy.hidden?'password':'text'} inputmode="decimal" bind:value={contributions[goal.id]} required /></Field.Field><Button type="submit">{t('save')}</Button></form><Disclosure class="history">{#snippet title()}{t('transactionHistory')}{/snippet}{#if history[goal.id]?.length}{#each history[goal.id] as entry (entry.id)}<p>{formatDate(entry.occurredOn)} · {entry.direction==='add'?'+':'−'}{goal.currency} {concealed(entry.amount,privacy.hidden)}{entry.note?` · ${entry.note}`:''}</p>{/each}{:else}<p>{t('emptyGoals')}</p>{/if}</Disclosure></Card.Content></Card.Root>{/each}{/if}</section></div>
<AlertDialog.Root open={!!archiveTarget} onOpenChange={(v)=>{if(!v)archiveTarget=null;}}>
  <AlertDialog.Content>
    <AlertDialog.Header><AlertDialog.Title>{t('archiveGoalTitle')}</AlertDialog.Title><AlertDialog.Description>{t('archiveBody')}</AlertDialog.Description></AlertDialog.Header>
    <AlertDialog.Footer><AlertDialog.Cancel onclick={()=>archiveTarget=null}>{t('cancel')}</AlertDialog.Cancel><AlertDialog.Action onclick={confirmArchive}>{t('archive')}</AlertDialog.Action></AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>
<style>.grid{display:grid;grid-template-columns:minmax(250px,350px) minmax(0,1fr);gap:16px;align-items:start}.list{display:grid;gap:16px;min-width:0}.title-row,.amounts{display:flex;justify-content:space-between;gap:12px;align-items:center}.amounts{justify-content:flex-start;align-items:baseline;margin-bottom:12px;flex-wrap:wrap}.amounts span{color:var(--muted-foreground);font-size:13px}.caption{color:var(--muted-foreground);font-size:12px;font-variant-numeric:tabular-nums}.contribution{display:flex;align-items:end;gap:8px;margin-top:16px;flex-wrap:wrap}.contribution :global([data-slot=field]){flex:1;min-width:140px}:global(.submit){margin-top:16px;width:100%}.grid :global([data-slot=field-group]){gap:12px}:global(.history) :global([data-slot="disclosure-trigger"]){cursor:pointer;min-height:44px}@media(max-width:760px){.grid{grid-template-columns:minmax(0,1fr)}}.amounts :global(.money){color:var(--text-blue)}
.goal-title{display:flex;align-items:center;gap:8px}
</style>
