<script lang="ts">
  import AmountInput from '$lib/components/forms/amount-input.svelte';
  import LoadingScope from '$lib/components/shared/loading-scope.svelte';
  import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
  import { getContext } from 'svelte';
  import { AUTH_UI_CONTEXT, type AuthUiState } from '$lib/i18n/auth';
  import { Button } from '$lib/components/ui/button';
  import * as Card from '$lib/components/ui/card';
  import * as Field from '$lib/components/ui/field';
  import { Input } from '$lib/components/ui/input';
  import PageHeader from '$lib/components/shared/page-header.svelte';
  import EmptyState from '$lib/components/shared/empty-state.svelte';
  import ErrorState from '$lib/components/shared/error-state.svelte';
  import LoadingSkeleton from '$lib/components/shared/loading-skeleton.svelte';
  type Workspace={selectedId:string;ready:boolean;items?:{id:string;kind:string}[]};type Account={id:string;name:string;currency:string;kind:string};type Category={id:string;name:string};type Rule={id:string;ruleType:'low_balance'|'unusual_spending';scopeKey:string;accountId:string|null;categoryId:string|null;currency:string|null;enabled:boolean;version:number;parameters:Record<string,string>;accountName?:string;categoryName?:string};
  const workspace=getContext<Workspace>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),isId=$derived(ui.locale==='id');
  let accounts:Account[]=$state([]),categories:Category[]=$state([]),rules:Rule[]=$state([]),inApp:Record<string,boolean>=$state({}),preferenceVersion=$state(1),accountId=$state(''),threshold=$state(''),categoryId=$state(''),currency=$state('IDR'),minimumAmount=$state(''),loading=$state(true),saving=$state(false),error=$state(''),success=$state('');
  const eventTypes=$derived(['bill-reminder','invoice-due','payment-due','budget-alert','recorded-low-balance','unusual-spending',...(workspace.items?.find(w=>w.id===workspace.selectedId)?.kind==='business'?['tax-reminder']:[])]);
  async function load(){if(!workspace.ready||!workspace.selectedId)return;loading=true;try{const [ar,cr,rr,pr]=await Promise.all([fetch(`/api/workspaces/${workspace.selectedId}/accounts`),fetch(`/api/workspaces/${workspace.selectedId}/categories`),fetch(`/api/workspaces/${workspace.selectedId}/notification-rules`),fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`)]);if(!ar.ok||!cr.ok||!rr.ok||!pr.ok)throw new Error();accounts=(await ar.json()).items.filter((x:Account)=>['cash','bank','e_wallet','savings'].includes(x.kind));categories=(await cr.json()).items.filter((x:Category&{type:string})=>x.type==='expense');rules=(await rr.json()).items;const prefs=await pr.json();preferenceVersion=prefs.version??1;inApp=Object.fromEntries(eventTypes.map((event)=>[event,prefs.channels?.[event]?.in_app??true]));accountId=accounts[0]?.id??'';currency=accounts[0]?.currency??'IDR';}catch{error=isId?'Pengaturan gagal dimuat.':'Could not load notification settings.';}finally{loading=false;}}
  $effect(()=>{void (workspace as {revision?:number}).revision;if(workspace.ready&&workspace.selectedId)void load();});
  async function save(payload:Record<string,unknown>){saving=true;error='';success='';try{const existing=rules.find((rule)=>rule.ruleType===payload.ruleType&&(rule.ruleType==='low_balance'?rule.accountId===payload.accountId:rule.categoryId===(payload.categoryId||null)&&rule.currency===payload.currency));const versioned=existing?{...payload,version:existing.version}:payload;const response=await fetch(`/api/workspaces/${workspace.selectedId}/notification-rules`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(versioned)});const body=await response.json();if(!response.ok)throw new Error(body.message??'Could not save rule.');success=isId?'Aturan tersimpan.':'Rule saved.';await load();}catch(e){error=e instanceof Error?e.message:'Could not save rule.';}finally{saving=false;}}
  async function toggle(rule:Rule){const enabled=!rule.enabled;if(rule.ruleType==='low_balance')await save({ruleType:rule.ruleType,accountId:rule.accountId,threshold:rule.parameters.threshold,enabled});else await save({ruleType:rule.ruleType,categoryId:rule.categoryId,currency:rule.currency,minimumAmount:rule.parameters.minimumAmount,enabled});}
  async function toggleInApp(event:string){saving=true;try{const response=await fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({version:preferenceVersion,channels:{[event]:{in_app:!inApp[event]}}})});if(!response.ok)throw new Error();const saved=await response.json();preferenceVersion=saved.version;inApp={...inApp,[event]:!inApp[event]};}catch{error=isId?'Preferensi tidak dapat disimpan. Muat ulang pengaturan.':'Could not save preference. Reload settings.';}finally{saving=false;}}
  function addLow(event:SubmitEvent){event.preventDefault();if(accountId&&threshold)void save({ruleType:'low_balance',accountId,threshold,enabled:true});}
  function addUnusual(event:SubmitEvent){event.preventDefault();if(minimumAmount)void save({ruleType:'unusual_spending',categoryId:categoryId||null,currency,minimumAmount,enabled:true});}
  function eventLabel(event:string,id:boolean){const labels:Record<string,[string,string]>={'tax-reminder':['Tax deadlines','Tenggat pajak'],'bill-reminder':['Bill reminders','Pengingat tagihan'],'invoice-due':['Invoice due dates','Jatuh tempo faktur'],'payment-due':['Scheduled payments','Pembayaran terjadwal'],'budget-alert':['Budget thresholds','Batas anggaran'],'recorded-low-balance':['Low recorded balance','Saldo tercatat rendah'],'unusual-spending':['Unusual spending','Pengeluaran tidak biasa']};return labels[event]?.[id?1:0]??event;}
</script>
<LoadingScope active={!!loading || !!saving} />
<svelte:head><title>{isId?'Pengaturan pemberitahuan':'Notification settings'} · CapyBudget</title></svelte:head>
<PageHeader eyebrow={isId?'PREFERENSI':'PREFERENCES'} title={isId?'Pengaturan pemberitahuan':'Notification settings'} description={isId?'Atur batas saldo rendah dan deteksi pengeluaran yang tidak biasa.':'Set low-balance limits and deterministic unusual-spending detection.'} />
<section class="page">
  {#if error}<ErrorState title={isId?'Terjadi kesalahan':'Something went wrong'} message={error} retryLabel={isId?'Coba lagi':'Retry'} onRetry={load} />{/if}{#if success}<p class="success" role="status">{success}</p>{/if}
  <div class="grid"><Card.Root><Card.Header><Card.Title>{isId?'Peringatan saldo rendah':'Low-balance alerts'}</Card.Title><Card.Description>{isId?'Diberi tahu saat saldo tercatat turun di bawah batas.':'Alert when a recorded account balance drops below your limit.'}</Card.Description></Card.Header><Card.Content><form onsubmit={addLow}><Field.FieldGroup><Field.Field><Field.FieldLabel for="low-account">{isId?'Akun':'Account'}</Field.FieldLabel><ChoiceSelect id="low-account" bind:value={accountId} items={[...(accounts).flatMap((account) => [{value: account.id, label: String(account.name) + " · " + String(account.currency)}])]} /></Field.Field><Field.Field><Field.FieldLabel for="low-threshold">{isId?'Batas saldo':'Balance threshold'}</Field.FieldLabel><AmountInput currency={accounts.find(account => account.id === accountId)?.currency} id="low-threshold" bind:value={threshold} required inputmode="decimal" placeholder="0.00" /></Field.Field></Field.FieldGroup><Button type="submit" disabled={saving||!accountId}>{isId?'Tambah aturan':'Add rule'}</Button></form></Card.Content></Card.Root>
  <Card.Root><Card.Header><Card.Title>{isId?'Pengeluaran tidak biasa':'Unusual-spending alerts'}</Card.Title><Card.Description>{isId?'Membandingkan transaksi dengan 90 hari sebelumnya setelah tersedia cukup riwayat.':'Compares expenses with the previous 90 days once enough history is available.'}</Card.Description></Card.Header><Card.Content><form onsubmit={addUnusual}><Field.FieldGroup><Field.Field><Field.FieldLabel for="spending-category">{isId?'Kategori (opsional)':'Category (optional)'}</Field.FieldLabel><ChoiceSelect id="spending-category" bind:value={categoryId} items={[{value: '', label: String(isId?'Semua kategori':'All categories')}, ...(categories).flatMap((category) => [{value: category.id, label: String(category.name)}])]} /></Field.Field><Field.Field><Field.FieldLabel for="spending-currency">{isId?'Mata uang':'Currency'}</Field.FieldLabel><Input id="spending-currency" bind:value={currency} maxlength={3} required /></Field.Field><Field.Field><Field.FieldLabel for="spending-minimum">{isId?'Jumlah minimum':'Minimum amount'}</Field.FieldLabel><AmountInput {currency} id="spending-minimum" bind:value={minimumAmount} required inputmode="decimal" placeholder="100000" /></Field.Field></Field.FieldGroup><Button type="submit" disabled={saving}>{isId?'Tambah aturan':'Add rule'}</Button></form></Card.Content></Card.Root></div>
  <Card.Root><Card.Header><Card.Title>{isId?'Aturan aktif':'Configured rules'}</Card.Title></Card.Header><Card.Content>{#if loading}<LoadingSkeleton rows={2} label={isId?'Memuat…':'Loading…'} />{:else if !rules.length}<EmptyState title={isId?'Aturan aktif':'Configured rules'} body={isId?'Belum ada aturan.':'No rules configured yet.'} />{:else}<div class="rules">{#each rules as rule (rule.id)}<div class="rule"><span><strong>{rule.ruleType==='low_balance'?(isId?'Saldo rendah':'Low balance'):(isId?'Pengeluaran tidak biasa':'Unusual spending')}</strong><small>{rule.ruleType==='low_balance'?`${rule.accountName} · ${rule.parameters.threshold}`:`${rule.categoryName??(isId?'Semua kategori':'All categories')} · ${rule.currency} ${rule.parameters.minimumAmount}`}</small></span><Button variant="outline" size="sm" disabled={saving} onclick={()=>toggle(rule)}>{rule.enabled?(isId?'Nonaktifkan':'Disable'):(isId?'Aktifkan':'Enable')}</Button></div>{/each}</div>{/if}</Card.Content></Card.Root>
  <Card.Root><Card.Header><Card.Title>{isId?'Pemberitahuan dalam aplikasi':'In-app notifications'}</Card.Title><Card.Description>{isId?'Kelola jenis peringatan yang muncul di kotak masuk.':'Choose which alert types appear in your inbox.'}</Card.Description></Card.Header><Card.Content><div class="rules">{#each eventTypes as event}<div class="rule"><strong>{eventLabel(event,isId)}</strong><Button variant="outline" size="sm" disabled={saving} onclick={()=>toggleInApp(event)}>{inApp[event]?(isId?'Aktif':'On'):(isId?'Nonaktif':'Off')}</Button></div>{/each}</div></Card.Content></Card.Root>
</section>
<style>
.page{display:grid;gap:16px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.grid form{display:grid;gap:15px}.rules{display:grid}.rule{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid var(--border)}.rule:last-child{border:0}.rule span{display:grid;gap:3px}.rule small{color:var(--muted-foreground)}:global([data-slot="select-trigger"]){width:100%}.success{color:var(--income-ink)}@media(max-width:700px){.grid{grid-template-columns:1fr}}
</style>
