<script lang="ts">
  import { getContext } from 'svelte';
  import { AUTH_UI_CONTEXT, type AuthUiState } from '$lib/i18n/auth';
  import { Button } from '$lib/components/ui/button';
  import * as Card from '$lib/components/ui/card';
  import * as Field from '$lib/components/ui/field';
  import { Input } from '$lib/components/ui/input';
  type Workspace={selectedId:string;ready:boolean};type Account={id:string;name:string;currency:string;kind:string};type Category={id:string;name:string};type Rule={id:string;ruleType:'low_balance'|'unusual_spending';scopeKey:string;accountId:string|null;categoryId:string|null;currency:string|null;enabled:boolean;version:number;parameters:Record<string,string>;accountName?:string;categoryName?:string};
  const workspace=getContext<Workspace>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),isId=$derived(ui.locale==='id');
  let accounts:Account[]=$state([]),categories:Category[]=$state([]),rules:Rule[]=$state([]),inApp:Record<string,boolean>=$state({}),preferenceVersion=$state(1),accountId=$state(''),threshold=$state(''),categoryId=$state(''),currency=$state('IDR'),minimumAmount=$state(''),loading=$state(true),saving=$state(false),error=$state(''),success=$state('');
  const eventTypes=['bill-reminder','invoice-due','payment-due','budget-alert','recorded-low-balance','unusual-spending'];
  async function load(){if(!workspace.ready||!workspace.selectedId)return;loading=true;try{const [ar,cr,rr,pr]=await Promise.all([fetch(`/api/workspaces/${workspace.selectedId}/accounts`),fetch(`/api/workspaces/${workspace.selectedId}/categories`),fetch(`/api/workspaces/${workspace.selectedId}/notification-rules`),fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`)]);if(!ar.ok||!cr.ok||!rr.ok||!pr.ok)throw new Error();accounts=(await ar.json()).items.filter((x:Account)=>['cash','bank','e_wallet','savings'].includes(x.kind));categories=(await cr.json()).items.filter((x:Category&{type:string})=>x.type==='expense');rules=(await rr.json()).items;const prefs=await pr.json();preferenceVersion=prefs.version??1;inApp=Object.fromEntries(eventTypes.map((event)=>[event,prefs.channels?.[event]?.in_app??true]));accountId=accounts[0]?.id??'';currency=accounts[0]?.currency??'IDR';}catch{error=isId?'Pengaturan gagal dimuat.':'Could not load notification settings.';}finally{loading=false;}}
  $effect(()=>{if(workspace.ready&&workspace.selectedId)void load();});
  async function save(payload:Record<string,unknown>){saving=true;error='';success='';try{const existing=rules.find((rule)=>rule.ruleType===payload.ruleType&&(rule.ruleType==='low_balance'?rule.accountId===payload.accountId:rule.categoryId===(payload.categoryId||null)&&rule.currency===payload.currency));const versioned=existing?{...payload,version:existing.version}:payload;const response=await fetch(`/api/workspaces/${workspace.selectedId}/notification-rules`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(versioned)});const body=await response.json();if(!response.ok)throw new Error(body.message??'Could not save rule.');success=isId?'Aturan tersimpan.':'Rule saved.';await load();}catch(e){error=e instanceof Error?e.message:'Could not save rule.';}finally{saving=false;}}
  async function toggle(rule:Rule){const enabled=!rule.enabled;if(rule.ruleType==='low_balance')await save({ruleType:rule.ruleType,accountId:rule.accountId,threshold:rule.parameters.threshold,enabled});else await save({ruleType:rule.ruleType,categoryId:rule.categoryId,currency:rule.currency,minimumAmount:rule.parameters.minimumAmount,enabled});}
  async function toggleInApp(event:string){saving=true;try{const response=await fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({version:preferenceVersion,channels:{[event]:{in_app:!inApp[event]}}})});if(!response.ok)throw new Error();const saved=await response.json();preferenceVersion=saved.version;inApp={...inApp,[event]:!inApp[event]};}catch{error=isId?'Preferensi tidak dapat disimpan. Muat ulang pengaturan.':'Could not save preference. Reload settings.';}finally{saving=false;}}
  function addLow(event:SubmitEvent){event.preventDefault();if(accountId&&threshold)void save({ruleType:'low_balance',accountId,threshold,enabled:true});}
  function addUnusual(event:SubmitEvent){event.preventDefault();if(minimumAmount)void save({ruleType:'unusual_spending',categoryId:categoryId||null,currency,minimumAmount,enabled:true});}
  function eventLabel(event:string,id:boolean){const labels:Record<string,[string,string]>={'bill-reminder':['Bill reminders','Pengingat tagihan'],'invoice-due':['Invoice due dates','Jatuh tempo faktur'],'payment-due':['Scheduled payments','Pembayaran terjadwal'],'budget-alert':['Budget thresholds','Batas anggaran'],'recorded-low-balance':['Low recorded balance','Saldo tercatat rendah'],'unusual-spending':['Unusual spending','Pengeluaran tidak biasa']};return labels[event]?.[id?1:0]??event;}
</script>
<svelte:head><title>{isId?'Pengaturan pemberitahuan':'Notification settings'} · CapyBudget</title></svelte:head>
<section class="page"><header><p class="eyebrow">{isId?'PREFERENSI':'PREFERENCES'}</p><h1>{isId?'Pengaturan pemberitahuan':'Notification settings'}</h1><p>{isId?'Atur batas saldo rendah dan deteksi pengeluaran yang tidak biasa.':'Set low-balance limits and deterministic unusual-spending detection.'}</p></header>
  {#if error}<p class="error" role="alert">{error}</p>{/if}{#if success}<p class="success" role="status">{success}</p>{/if}
  <div class="grid"><Card.Root><Card.Header><Card.Title>{isId?'Peringatan saldo rendah':'Low-balance alerts'}</Card.Title><Card.Description>{isId?'Diberi tahu saat saldo tercatat turun di bawah batas.':'Alert when a recorded account balance drops below your limit.'}</Card.Description></Card.Header><Card.Content><form onsubmit={addLow}><Field.FieldGroup><Field.Field><Field.FieldLabel for="low-account">{isId?'Akun':'Account'}</Field.FieldLabel><select id="low-account" bind:value={accountId}>{#each accounts as account}<option value={account.id}>{account.name} · {account.currency}</option>{/each}</select></Field.Field><Field.Field><Field.FieldLabel for="low-threshold">{isId?'Batas saldo':'Balance threshold'}</Field.FieldLabel><Input id="low-threshold" bind:value={threshold} required inputmode="decimal" placeholder="0.00" /></Field.Field></Field.FieldGroup><Button type="submit" disabled={saving||!accountId}>{isId?'Tambah aturan':'Add rule'}</Button></form></Card.Content></Card.Root>
  <Card.Root><Card.Header><Card.Title>{isId?'Pengeluaran tidak biasa':'Unusual-spending alerts'}</Card.Title><Card.Description>{isId?'Membandingkan transaksi dengan 90 hari sebelumnya setelah tersedia cukup riwayat.':'Compares expenses with the previous 90 days once enough history is available.'}</Card.Description></Card.Header><Card.Content><form onsubmit={addUnusual}><Field.FieldGroup><Field.Field><Field.FieldLabel for="spending-category">{isId?'Kategori (opsional)':'Category (optional)'}</Field.FieldLabel><select id="spending-category" bind:value={categoryId}><option value="">{isId?'Semua kategori':'All categories'}</option>{#each categories as category}<option value={category.id}>{category.name}</option>{/each}</select></Field.Field><Field.Field><Field.FieldLabel for="spending-currency">{isId?'Mata uang':'Currency'}</Field.FieldLabel><Input id="spending-currency" bind:value={currency} maxlength={3} required /></Field.Field><Field.Field><Field.FieldLabel for="spending-minimum">{isId?'Jumlah minimum':'Minimum amount'}</Field.FieldLabel><Input id="spending-minimum" bind:value={minimumAmount} required inputmode="decimal" placeholder="100000" /></Field.Field></Field.FieldGroup><Button type="submit" disabled={saving}>{isId?'Tambah aturan':'Add rule'}</Button></form></Card.Content></Card.Root></div>
  <Card.Root><Card.Header><Card.Title>{isId?'Aturan aktif':'Configured rules'}</Card.Title></Card.Header><Card.Content>{#if loading}<p>{isId?'Memuat…':'Loading…'}</p>{:else if !rules.length}<p>{isId?'Belum ada aturan.':'No rules configured yet.'}</p>{:else}<div class="rules">{#each rules as rule (rule.id)}<div class="rule"><span><strong>{rule.ruleType==='low_balance'?(isId?'Saldo rendah':'Low balance'):(isId?'Pengeluaran tidak biasa':'Unusual spending')}</strong><small>{rule.ruleType==='low_balance'?`${rule.accountName} · ${rule.parameters.threshold}`:`${rule.categoryName??(isId?'Semua kategori':'All categories')} · ${rule.currency} ${rule.parameters.minimumAmount}`}</small></span><Button variant="outline" size="sm" disabled={saving} onclick={()=>toggle(rule)}>{rule.enabled?(isId?'Nonaktifkan':'Disable'):(isId?'Aktifkan':'Enable')}</Button></div>{/each}</div>{/if}</Card.Content></Card.Root>
  <Card.Root><Card.Header><Card.Title>{isId?'Pemberitahuan dalam aplikasi':'In-app notifications'}</Card.Title><Card.Description>{isId?'Kelola jenis peringatan yang muncul di kotak masuk.':'Choose which alert types appear in your inbox.'}</Card.Description></Card.Header><Card.Content><div class="rules">{#each eventTypes as event}<div class="rule"><strong>{eventLabel(event,isId)}</strong><Button variant="outline" size="sm" disabled={saving} onclick={()=>toggleInApp(event)}>{inApp[event]?(isId?'Aktif':'On'):(isId?'Nonaktif':'Off')}</Button></div>{/each}</div></Card.Content></Card.Root>
</section>
<style>
.page{display:grid;gap:18px}.page header p{color:var(--muted-foreground);margin:5px 0}.page h1{font-size:30px;margin:0}.eyebrow{font-size:11px;letter-spacing:.12em;color:var(--primary)!important;font-weight:700}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.grid form{display:grid;gap:15px}.rules{display:grid}.rule{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid var(--border)}.rule:last-child{border:0}.rule span{display:grid;gap:3px}.rule small{color:var(--muted-foreground)}select{height:40px;width:100%;border:1px solid var(--input);border-radius:var(--radius);background:var(--background);color:var(--foreground);padding:8px}.error{color:var(--destructive)}.success{color:var(--primary)}@media(max-width:700px){.grid{grid-template-columns:1fr}}
</style>
