<script lang="ts">
  import ChatEntryReview from './chat-entry-review.svelte';
  import ChatLoading from './chat-loading.svelte';
  import {getContext,onMount,onDestroy,tick} from 'svelte';
  import Mic from '@lucide/svelte/icons/mic';
  import Send from '@lucide/svelte/icons/send';
  import Square from '@lucide/svelte/icons/square';
  import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';
  import {PRIVACY_CONTEXT,type PrivacyState,concealed} from '$lib/privacy';
  import {formatExactAmount} from '$lib/ux/amount';
  import {formatDate} from '$lib/dates';
  import {recordingToWav} from '$lib/assistant/audio';
  import {Button} from '$lib/components/ui/button';
  import {Textarea} from '$lib/components/ui/textarea';
  import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
  import Disclosure from '$lib/components/shared/disclosure.svelte';
  import CapyMascot from '$lib/components/shared/capy-mascot.svelte';

  let {workspaceId,workspaceName,currency,onNavigate}:{workspaceId:string;workspaceName:string;currency:string;onNavigate:()=>void}=$props();
  type Settings={externalAiEnabled:boolean;externalAiAvailable:boolean;externalAiProviderName:string;voiceAiEnabled:boolean;voiceAiAvailable:boolean;voiceInputFormat:'native'|'wav'};
  type Message={role:'user'|'assistant';text:string;answer?:any};
  const workspace=getContext<{revision:number}>('capybudget-workspaces');
  const ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),privacy=getContext<PrivacyState>(PRIVACY_CONTEXT);
  const L=(en:string,id:string)=>ui.locale==='id'?id:en;
  const money=(amount:unknown)=>amount==null?'—':`${currency} ${concealed(formatExactAmount(String(amount),ui.locale),privacy.hidden)}`;
  let loadingPhase=$state<'settings'|'history'>('settings');
  let settings=$state<Settings|null>(null),loading=$state(true),busy=$state(false),error=$state(''),notice=$state('');
  let draft=$state<any>(null);
  let question=$state(''),conversation=$state(''),conversations=$state<any[]>([]),messages=$state<Message[]>([]),pendingText=$state('');
  let history=$state<HTMLDivElement|undefined>(undefined),composer:HTMLTextAreaElement|null=$state(null),disposed=false;
  const controllers=new Set<AbortController>();let requestKey=crypto.randomUUID();
  let recording=$state(false),starting=$state(false),recorder:MediaRecorder|null=null,stream:MediaStream|null=null,timer:ReturnType<typeof setTimeout>|undefined,generation=0;
  let seconds=$state(0),clock:ReturnType<typeof setInterval>|undefined;
  const allowed=$derived(Boolean(settings?.externalAiEnabled&&settings.externalAiAvailable));
  const voiceAllowed=$derived(Boolean(allowed&&settings?.voiceAiEnabled&&settings.voiceAiAvailable));

  async function api(path:string,method='GET',body?:unknown){const controller=new AbortController();controllers.add(controller);try{const response=await fetch(`/api/workspaces/${workspaceId}/assistant/${path}`,{method,signal:controller.signal,headers:body===undefined?{}:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=await response.json();if(disposed||controller.signal.aborted)throw new DOMException('Chat closed','AbortError');if(!response.ok)throw new Error(result.message??L('This request could not be completed.','Permintaan belum dapat diselesaikan.'));return result;}finally{controllers.delete(controller);}}
  async function scroll(){await tick();if(history)history.scrollTop=history.scrollHeight;}
  async function initialize(){loading=true;loadingPhase='settings';error='';try{settings=(await api('settings')).settings;if(settings?.externalAiEnabled){loadingPhase='history';conversations=(await api('v2/conversations')).items??[];if(conversations.length)await openHistory(conversations[0].id);}await tick();composer?.focus();}catch(e){if(!disposed)error=(e as Error).message;}finally{if(!disposed)loading=false;}}
  async function openHistory(id:string){if(busy||recording||starting)return;busy=true;error='';try{const rows=(await api(`v2/conversations/${id}`)).items??[];messages=rows.map((m:any)=>m.role==='user'?{role:'user',text:m.content}:{role:'assistant',text:'',answer:JSON.parse(m.content)});conversation=id;draft=null;question='';requestKey=crypto.randomUUID();await scroll();}catch(e){if(!disposed)error=(e as Error).message;}finally{if(!disposed)busy=false;}}
  function newConversation(){if(busy||recording||starting)return;messages=[];draft=null;conversation='';question='';error='';notice='';requestKey=crypto.randomUUID();composer?.focus();}
  async function send(){if(!allowed||busy||recording||starting||!question.trim())return;const text=question.trim();busy=true;error='';notice='';pendingText=text;await scroll();try{const answer=await api('v2/chat','POST',{text,locale:ui.locale,conversationId:conversation||null,requestKey});messages=[...messages,{role:'user',text},{role:'assistant',text:'',answer}];conversation=answer.conversationId;if(question.trim()===text)question='';requestKey=crypto.randomUUID();await scroll();try{conversations=(await api('v2/conversations')).items??[];}catch{/* The saved answer remains usable if history refresh fails. */}}catch(e){if(!disposed)error=(e as Error).message;}finally{if(!disposed){busy=false;pendingText='';await scroll();composer?.focus();}}}
  async function prepareEntry(text:string){if(busy||recording||starting)return;busy=true;error='';notice='';try{draft=await api('v2/entry','POST',{text,locale:ui.locale,origin:'text',requestKey:crypto.randomUUID()});await scroll();}catch(e){if(!disposed)error=(e as Error).message;}finally{if(!disposed)busy=false;}}
  async function confirmEntry(){if(!draft||busy)return;busy=true;error='';try{await api(`v2/entry/${draft.id}/confirm`,'POST',{confirmation:'CREATE_TRANSACTION',version:draft.version,fields:draft.fields});workspace.revision++;draft=null;messages=[...messages,{role:'assistant',text:'',answer:{message:L('Transaction saved. You can review it on the Transactions page.','Transaksi tersimpan. Kamu dapat meninjaunya di halaman Transaksi.'),citations:[]}}];notice=L('Transaction saved.','Transaksi tersimpan.');await scroll();}catch(e){if(!disposed)error=(e as Error).message;}finally{if(!disposed)busy=false;}}
  function stop(cancel=false){if(timer)clearTimeout(timer);if(clock)clearInterval(clock);if(cancel)generation++;if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(track=>track.stop());stream=null;recording=false;if(cancel)starting=false;}
  async function record(){if(!voiceAllowed||busy||recording||starting)return;starting=true;error='';notice='';const id=++generation;try{const active=await navigator.mediaDevices.getUserMedia({audio:true});if(disposed||generation!==id){active.getTracks().forEach(track=>track.stop());return;}stream=active;const mime=['audio/webm','audio/ogg','audio/mp4'].find(type=>MediaRecorder.isTypeSupported(type));if(!mime)throw new Error('Unsupported recorder');const device=new MediaRecorder(active,{mimeType:mime}),chunks:Blob[]=[];recorder=device;let size=0;
    device.ondataavailable=e=>{if(disposed||generation!==id)return;size+=e.data.size;if(size>2000000){stop(true);error=L('Try a shorter recording, up to 2 MB.','Coba rekaman lebih singkat, maksimal 2 MB.');}else chunks.push(e.data);};
    device.onstop=()=>{active.getTracks().forEach(track=>track.stop());if(disposed||generation!==id){chunks.length=0;return;}recording=false;void transcribe(chunks,mime,id);};
    device.onerror=()=>{stop(true);error=L('Recording stopped unexpectedly. Please type or try again.','Rekaman terhenti. Silakan ketik atau coba lagi.');};
    device.start(250);recording=true;seconds=0;clock=setInterval(()=>seconds++,1000);timer=setTimeout(()=>stop(),30000);
  }catch{if(generation===id&&!disposed){stop(true);error=L('Microphone unavailable. Allow microphone access over HTTPS, or type your question.','Mikrofon tidak tersedia. Izinkan akses mikrofon melalui HTTPS, atau ketik pertanyaanmu.');}}finally{if(generation===id)starting=false;}}
  async function transcribe(chunks:Blob[],mime:string,id:number){busy=true;const controller=new AbortController();controllers.add(controller);try{const raw=new Blob(chunks,{type:mime}),audio=settings?.voiceInputFormat==='wav'?await recordingToWav(raw):raw;if(disposed||generation!==id||controller.signal.aborted)return;const response=await fetch(`/api/workspaces/${workspaceId}/assistant/v2/voice`,{method:'POST',signal:controller.signal,headers:{'content-type':audio.type,'idempotency-key':crypto.randomUUID()},body:audio});const result=await response.json();if(disposed||generation!==id||controller.signal.aborted)return;if(!response.ok)throw new Error(result.message);question=[question.trim(),result.transcript].filter(Boolean).join(' ').slice(0,2000);requestKey=crypto.randomUUID();notice=L('Transcript ready. Review it, then send your question.','Transkrip siap. Tinjau, lalu kirim pertanyaanmu.');await tick();composer?.focus();}catch(e){if(!disposed&&(e as Error).name!=='AbortError')error=(e as Error).message;}finally{chunks.length=0;controllers.delete(controller);if(!disposed)busy=false;}}
  onMount(()=>void initialize());
  onDestroy(()=>{disposed=true;stop(true);for(const controller of controllers)controller.abort();});
</script>

<div class="room">
  <div class="context-row"><span>{workspaceName}</span><span>{settings?.externalAiProviderName??'Capy'}</span></div>
  {#if loading}<ChatLoading phase={loadingPhase}/>
  {:else if !allowed}<div class="setup"><CapyMascot size={88}/><h3>{L('Let’s get Capy ready','Mari siapkan Capy')}</h3><p>{settings?.externalAiAvailable?L('Enable external text processing and choose permitted accounts in Assistant privacy settings. Voice has its own consent switch.','Aktifkan pemrosesan teks eksternal dan pilih akun yang diizinkan di pengaturan privasi Asisten. Suara memiliki izin terpisah.'):L('The language provider is not configured yet. Local forecasts still work.','Penyedia bahasa belum dikonfigurasi. Proyeksi lokal tetap berfungsi.')}</p><Button href="/assistant#privacy-settings" onclick={onNavigate}>{L('Open Assistant settings','Buka pengaturan Asisten')}</Button>{#if error}<p role="alert">{error}</p><Button variant="outline" onclick={initialize}>{L('Retry','Coba lagi')}</Button>{/if}</div>
  {:else}
    <div class="history-controls"><ChoiceSelect value={conversation} onValueChange={value=>value?void openHistory(value):newConversation()} disabled={busy||recording||starting} items={[{value:'',label:L('New conversation','Percakapan baru')},...conversations.map(c=>({value:c.id,label:privacy.hidden?L('Saved conversation','Percakapan tersimpan'):c.title}))]} aria-label={L('Conversation history','Riwayat percakapan')}/><Button variant="ghost" onclick={newConversation} disabled={busy||recording||starting}>{L('New','Baru')}</Button></div>
    <!-- svelte-ignore a11y_no_noninteractive_tabindex (The conversation must be focusable for keyboard scrolling.) -->
    <div class="messages" bind:this={history} role="log" aria-label={L('Conversation with Capy','Percakapan dengan Capy')} aria-live="polite" aria-relevant="additions text" tabindex="0">
      {#if !messages.length&&!pendingText}<div class="welcome"><CapyMascot size={80}/><h3>{L('What’s on your money mind?','Apa yang ingin kamu tahu?')}</h3><p>{L('Ask about spending, bills, savings goals or your cashflow.','Tanyakan pengeluaran, tagihan, tujuan tabungan, atau arus kasmu.')}</p><div class="prompts">{#each [L('How much did I spend this month?','Berapa pengeluaran bulan ini?'),L('How much is safe to spend?','Berapa yang aman dibelanjakan?'),L('What bills are coming up?','Tagihan apa yang akan datang?')] as prompt}<Button variant="outline" onclick={()=>{question=prompt;requestKey=crypto.randomUUID();composer?.focus();}}>{prompt}</Button>{/each}</div></div>{/if}
      {#each messages as message}<article class:user={message.role==='user'} class="bubble"><span class="speaker">{message.role==='user'?L('You','Kamu'):'Capy'}</span>{#if message.role==='user'}<p>{privacy.hidden?'•••':message.text}</p>{:else}<p>{message.answer.message}</p>{#if message.answer.asOfDate}<small>{L('Records as of','Catatan per')} {formatDate(message.answer.asOfDate)}</small>{/if}{#if message.answer.facts}{#if message.answer.tool==='spending'}<p class="amount">{money(message.answer.facts.amount)}</p><small>{message.answer.facts.category} · {formatDate(message.answer.facts.start)} – {formatDate(message.answer.facts.end)}</small>{:else if message.answer.tool==='forecast'}<p>{L('Safe to spend','Aman dibelanjakan')}: <strong>{money(message.answer.facts.safeToSpend)}</strong></p><p>{L('Lowest projected balance','Saldo proyeksi terendah')}: {money(message.answer.facts.minimumBalance)}</p>{:else if Array.isArray(message.answer.facts)}<ul>{#each message.answer.facts as fact}<li>{privacy.hidden?'•••':fact.name??fact.number??L('Record','Catatan')}{#if message.answer.tool==='receivables'} · {privacy.hidden?'•••':fact.number}{/if} · {money(fact.outstanding??fact.amount??fact.allocated)}{#if fact.dueDate||fact.date} · {formatDate(fact.dueDate??fact.date)}{/if}</li>{/each}</ul>{/if}{/if}{#if !privacy.hidden&&message.answer.citations?.length}<Disclosure>{#snippet title()}{L('Why this answer?','Mengapa jawaban ini?')}{/snippet}<ul>{#each message.answer.citations as citation}<li>{citation.label??L('Source record','Catatan sumber')}{#if citation.date} · {formatDate(citation.date)}{/if}{#if citation.amount} · {money(citation.amount)}{/if}</li>{/each}</ul></Disclosure>{/if}{#if message.answer.proposal?.kind==='review_transaction_entry'}<Button variant="outline" disabled={busy||recording||starting} onclick={()=>prepareEntry(message.answer.proposal.text)}>{L('Review transaction entry','Tinjau entri transaksi')}</Button>{/if}{/if}</article>{/each}
      {#if draft}<ChatEntryReview bind:draft {busy} onConfirm={()=>void confirmEntry()} onCancel={()=>draft=null}/>{/if}
      {#if pendingText}<article class="bubble user"><span class="speaker">{L('You','Kamu')}</span><p>{privacy.hidden?'•••':pendingText}</p></article>{/if}
      {#if busy&&pendingText}<p class="thinking" role="status">{L('Capy is checking your permitted records…','Capy sedang meninjau catatan yang diizinkan…')}</p>{/if}
    </div>
    <form class="composer" onsubmit={e=>{e.preventDefault();void send();}}>
      {#if error}<p class="error" role="alert">{error}</p><Button href="/assistant#privacy-settings" variant="link" onclick={onNavigate}>{L('Review Assistant settings','Tinjau pengaturan Asisten')}</Button>{/if}
      {#if notice}<p class="feedback" role="status">{notice}</p>{/if}
      <label for="capy-widget-question">{L('Your question','Pertanyaanmu')}</label><Textarea id="capy-widget-question" bind:ref={composer} bind:value={question} maxlength={2000} rows={2} disabled={recording||starting} oninput={()=>requestKey=crypto.randomUUID()} onkeydown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();void send();}}}/>
      <div class="compose-actions">{#if recording}<Button variant="outline" type="button" onclick={()=>stop()}><Square aria-hidden="true" size={16}/>{L('Stop','Hentikan')} · {seconds}s</Button><Button variant="ghost" type="button" onclick={()=>stop(true)}>{L('Cancel','Batalkan')}</Button>{:else}<Button variant="outline" type="button" onclick={record} disabled={!voiceAllowed||busy||starting} aria-label={L('Record a voice question','Rekam pertanyaan suara')}><Mic aria-hidden="true" size={18}/>{starting?L('Starting…','Memulai…'):L('Voice','Suara')}</Button>{/if}<Button type="submit" disabled={busy||recording||starting||!question.trim()}><Send aria-hidden="true" size={18}/>{busy?L('Working…','Memproses…'):L('Send','Kirim')}</Button></div>
      <p class="privacy-note">{settings?.externalAiProviderName} · {L('Questions and recordings go to this provider. Retrieved records stay here. Capy never moves money.','Pertanyaan dan rekaman dikirim ke penyedia ini. Catatan hasil pencarian tetap di sini. Capy tidak pernah memindahkan uang.')}</p>
      {#if !voiceAllowed}<a href="/assistant#privacy-settings" onclick={onNavigate}>{L('Enable voice in privacy settings','Aktifkan suara di pengaturan privasi')}</a>{/if}
      <small>{L('Suggestions are not professional financial advice.','Saran bukan nasihat keuangan profesional.')}</small>
    </form>
  {/if}
</div>

<style>
  .room{display:flex;flex-direction:column;flex:1;min-height:0;color:var(--foreground);font-size:14px;line-height:1.5}.context-row{display:flex;gap:12px;justify-content:space-between;padding:12px 20px;color:var(--muted-foreground);border-bottom:1px solid var(--border);font-size:12px}.context-row span{overflow-wrap:anywhere}.setup{display:grid;justify-items:start;align-content:start;gap:16px;padding:24px;overflow:auto}.setup h3,.welcome h3{font:500 20px var(--font-heading)}.history-controls{display:flex;gap:8px;padding:8px 16px;align-items:center;border-bottom:1px solid var(--border)}.history-controls :global(.choice-select){flex:1;min-width:0}.history-controls :global([data-slot="select-trigger"]){flex:1;min-width:0}.messages{flex:1;min-height:0;overflow:auto;overscroll-behavior:contain;padding:20px;display:flex;flex-direction:column;gap:16px;scrollbar-gutter:stable}.welcome{display:grid;gap:12px;justify-items:start}.welcome p,.setup p{color:var(--muted-foreground)}.prompts{display:grid;gap:8px;width:100%}.prompts :global(button){white-space:normal;justify-content:start;text-align:left;padding:12px 16px;min-height:44px;height:auto}.bubble{max-width:95%;align-self:flex-start;background:var(--card);border:2px solid var(--border);border-radius:var(--radius-card);padding:12px 16px;overflow-wrap:anywhere;animation:arrive 180ms ease-out}.bubble.user{align-self:flex-end;background:var(--secondary)}.speaker{display:block;margin-bottom:4px;font-weight:700;color:var(--brand-ink);font-size:12px}.bubble p{white-space:pre-wrap;margin:4px 0}.bubble small{color:var(--muted-foreground)}.bubble ul{padding-left:16px}.amount{font:500 24px var(--font-heading);font-variant-numeric:tabular-nums}.thinking{color:var(--muted-foreground);font-size:12px}.composer{flex-shrink:0;overflow:auto;max-height:70dvh;padding:12px 20px 16px;border-top:2px solid var(--border);background:var(--card);display:grid;gap:8px}.composer label{font-weight:600}.composer :global(textarea){font-size:16px;min-height:64px;max-height:120px;resize:vertical}.compose-actions{display:flex;gap:8px;justify-content:space-between}.compose-actions :global(button){min-height:44px}.privacy-note,.composer small,.composer a{font-size:12px;line-height:1.5;color:var(--muted-foreground)}.composer a{color:var(--info-ink,var(--brand-ink));text-decoration:underline}.error{color:var(--expense-ink)}.feedback{color:var(--muted-foreground);font-size:12px}a:focus-visible,.messages:focus-visible{outline:2px solid var(--ring);outline-offset:2px}
  @keyframes arrive{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){.bubble{animation:none}}@media(max-height:600px){.privacy-note,.composer>small{display:none}.composer{padding:8px 16px}.context-row{padding:8px 16px}}
</style>
