import type { TransactionSql } from 'postgres';
import { fromUnits, toUnits } from './money';
import { projectCashflow, type ForecastEvent } from './forecast';

const q=(tx:TransactionSql,statement:string,values:unknown[]=[])=>(tx.unsafe(statement,values as never[]));
function asJson(value:any){return typeof value==='string'?JSON.parse(value):value;}
function dateMinus(date:string,days:number){const value=new Date(date+'T00:00:00Z');value.setUTCDate(value.getUTCDate()-days);return value.toISOString().slice(0,10);}

export async function createSuggestions(tx:TransactionSql,workspaceId:string,userId:string,runId:string,result:any,events:ForecastEvent[],prefs:any,kind:string,context:{today:string;horizonDays:number;accounts:any[];qualityFlags:string[];workspaceProtectedAmount:string}){
 const expiry=new Date(Date.now()+7*86400000).toISOString(),desired:string[]=[];
 const add=async(kindKey:string,fingerprint:string,template:string,priority:number,facts:any,evidence:any[],reasons:string[])=>{
  if(!prefs.suggestions_enabled)return;desired.push(fingerprint);
  const [suggestion]=await q(tx,"insert into assistant_suggestions(workspace_id,user_id,run_id,kind,fingerprint,template_key,facts,reason_codes,evidence,priority,expires_at) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9::jsonb,$10,$11) on conflict(workspace_id,user_id,fingerprint) do update set run_id=excluded.run_id,facts=excluded.facts,reason_codes=excluded.reason_codes,evidence=excluded.evidence,priority=greatest(assistant_suggestions.priority,excluded.priority),state=case when assistant_suggestions.state in ('dismissed','completed') then assistant_suggestions.state when assistant_suggestions.state='reviewing' and exists(select 1 from assistant_action_proposals p where p.workspace_id=assistant_suggestions.workspace_id and p.user_id=assistant_suggestions.user_id and p.suggestion_id=assistant_suggestions.id and p.state='proposed' and p.expires_at>now()) then 'reviewing' when assistant_suggestions.state='snoozed' and assistant_suggestions.snoozed_until>now() then 'snoozed' else 'active' end,expires_at=excluded.expires_at,version=case when assistant_suggestions.state='reviewing' and exists(select 1 from assistant_action_proposals p where p.workspace_id=assistant_suggestions.workspace_id and p.user_id=assistant_suggestions.user_id and p.suggestion_id=assistant_suggestions.id and p.state='proposed' and p.expires_at>now()) then assistant_suggestions.version else assistant_suggestions.version+1 end,updated_at=now() returning id,state",[workspaceId,userId,runId,kindKey,fingerprint,template,JSON.stringify(facts),JSON.stringify(reasons),JSON.stringify(evidence),priority,expiry]);
  if(suggestion.state==='active'&&!['savings','payment_delay'].includes(kindKey)){
   const id=suggestion.id,locale=prefs.locale==='id',noticeKind=kindKey==='shortfall'?'cashflow-shortfall':kindKey==='low_balance'?'cashflow-low-balance':'assistant-invoice-followup';
   const title=locale?(kindKey==='shortfall'?'Perkiraan kekurangan saldo':kindKey==='low_balance'?'Saldo diperkirakan rendah':'Faktur menunggu pembayaran'):(kindKey==='shortfall'?'Projected cash shortfall':kindKey==='low_balance'?'Projected low balance':'Invoice needs follow-up');
   const message=locale?`Tinjau proyeksi arus kas untuk ${facts.date??facts.dueDate??result.today}.`:`Review the cashflow forecast for ${facts.date??facts.dueDate??result.today}.`;
   // Recorded account alerts already explain today's condition; forecasts describe future conditions.
   const [recorded]=facts.scope==='account' && facts.date<=context.today?await q(tx,"select id from finance_notifications where workspace_id=$1 and user_id=$2 and kind='recorded-low-balance' and source_id=$3 and resolved_at is null",[workspaceId,userId,facts.accountId]):[];
   const [overlap]=facts.scope==='account'?await q(tx,"select n.id from finance_notifications n join assistant_suggestions s on s.workspace_id=n.workspace_id and s.user_id=n.user_id and s.id=n.assistant_suggestion_id where n.workspace_id=$1 and n.user_id=$2 and n.kind=$3 and n.resolved_at is null and s.state='active' and s.facts->>'scope'='workspace' and s.facts->>'date'=$4",[workspaceId,userId,noticeKind,facts.date]):[];
   const [inApp]=await q(tx,"select enabled from finance_notification_preferences where workspace_id=$1 and user_id=$2 and event_type=$3 and channel='in_app'",[workspaceId,userId,noticeKind]);
   if(!recorded&&!overlap&&inApp?.enabled!==false)await q(tx,"insert into finance_notifications(workspace_id,user_id,kind,source_id,dedupe_key,title,message,assistant_suggestion_id,source_type,action_type,message_key,message_params,evidence) values($1,$2,$3,$4,$5,$6,$7,$4,'assistant_suggestion','open_assistant',$8,$9::jsonb,$10::jsonb) on conflict(workspace_id,user_id,dedupe_key) do update set title=excluded.title,message=excluded.message,resolved_at=null,assistant_suggestion_id=excluded.assistant_suggestion_id,source_type=excluded.source_type,action_type=excluded.action_type,message_key=excluded.message_key,message_params=excluded.message_params,evidence=excluded.evidence,expires_at=now()+interval '7 days'",[workspaceId,userId,noticeKind,id,'assistant:'+fingerprint,title,message,'forecast.'+kindKey,JSON.stringify(facts),JSON.stringify({projected:true,reasons,sources:evidence})]);
   else await q(tx,"update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='overlapping_condition_or_preference',updated_at=now() where workspace_id=$1 and user_id=$2 and dedupe_key=$3",[workspaceId,userId,'assistant:'+fingerprint]);
  }
 };
 if(result.firstShortfallDate){const row=result.points.find((x:any)=>x.date===result.firstShortfallDate&&x.scenario==='conservative');await add('shortfall','shortfall:workspace:'+result.firstShortfallDate,'cashflow.shortfall',100,{date:result.firstShortfallDate,amount:row?.minimumBalance??result.minimumBalance,currency:result.currency,scope:'workspace'},events.filter((e)=>e.date<=result.firstShortfallDate).slice(-5).map(e=>({sourceId:e.sourceId,date:e.date,kind:e.kind,amount:e.amount})),['projected_balance_below_zero','outflows_before_income']);}
 else if(result.firstLowBalanceDate){const row=result.points.find((x:any)=>x.date===result.firstLowBalanceDate);await add('low_balance','low-balance:workspace:'+result.firstLowBalanceDate,'cashflow.lowBalance',70,{date:result.firstLowBalanceDate,amount:row?.minimumBalance??result.minimumBalance,currency:result.currency,scope:'workspace'},events.filter((e)=>e.date<=result.firstLowBalanceDate).slice(-5).map(e=>({sourceId:e.sourceId,date:e.date,kind:e.kind,amount:e.amount})),['projected_balance_below_threshold']);}
 for(const alert of result.accountAlerts??[]){const kindKey=alert.kind==='shortfall'?'shortfall':'low_balance';await add(kindKey,kindKey+':account:'+alert.accountId+':'+alert.date,kindKey==='shortfall'?'cashflow.shortfall':'cashflow.lowBalance',alert.kind==='shortfall'?98:68,{date:alert.date,amount:alert.amount,currency:result.currency,scope:'account',accountId:alert.accountId,accountName:alert.accountName},events.filter((event)=>event.accountId===alert.accountId&&event.date<=alert.date).slice(-5).map((event)=>({sourceId:event.sourceId,date:event.date,kind:event.kind,amount:event.amount})),[alert.kind==='shortfall'?'account_below_zero':'account_below_threshold']);}
 if(kind==='business'&&prefs.suggestions_enabled&&prefs.source_permissions?.invoices){const [invoice]=await q(tx,`select i.id,i.number,i.due_date as "dueDate",i.currency,i.total::text,coalesce(sum(p.amount) filter(where p.reversed_at is null),0)::text as paid from invoices i left join invoice_payments p on p.workspace_id=i.workspace_id and p.invoice_id=i.id where i.workspace_id=$1 and i.state='issued' and i.archived_at is null and coalesce(i.expected_payment_on,i.due_date)<$2::date group by i.id having greatest(i.total-coalesce(sum(p.amount) filter(where p.reversed_at is null),0),0)>0 order by i.due_date limit 1`,[workspaceId,context.today]);if(invoice){const outstanding=fromUnits(toUnits(String(invoice.total))-toUnits(String(invoice.paid)));await add('invoice_followup','invoice-followup:'+invoice.id,'invoice.followup',50,{invoiceId:invoice.id,invoiceNumber:String(invoice.number??'').slice(0,80),dueDate:String(invoice.dueDate),currency:invoice.currency,amount:outstanding},[{sourceId:invoice.id,date:String(invoice.dueDate),kind:'invoice',amount:outstanding}],['unpaid_invoice_overdue']);}}
 if(result.firstShortfallDate&&prefs.suggestions_enabled){
  const candidates=events.filter((event)=>event.kind==='bill'&&event.sourceId&&event.date<result.firstShortfallDate).slice(0,20);
  for(const event of candidates){
   const [occurrence]=await q(tx,"select o.id,o.name,o.due_on as \"dueOn\",o.expected_payment_on as \"expectedPaymentOn\",o.deferrable_until as \"deferrableUntil\" from bill_occurrences o where o.workspace_id=$1 and o.id=$2 and o.status='unpaid'",[workspaceId,event.sourceId]);
   if(!occurrence)continue;if(!occurrence.deferrableUntil){await add('payment_delay','payment-terms:'+occurrence.id+':'+result.firstShortfallDate,'bill.checkPaymentTerms',42,{billId:occurrence.id,billName:String(occurrence.name).slice(0,120),amount:event.amount,currency:result.currency,currentDate:event.date,shortfallDate:result.firstShortfallDate,needsTermsConfirmation:true,accountId:event.accountId??null},[{sourceId:occurrence.id,kind:'bill',date:event.date,shortfallDate:result.firstShortfallDate}],['check_payment_terms_before_changing_date']);break;}const newDate=String(occurrence.deferrableUntil);if(newDate<=event.date||newDate>dateMinus(context.today,-context.horizonDays))continue;
   const alternativeEvents=events.map((candidate)=>candidate.id===event.id?{...candidate,date:newDate}:candidate),alternative=projectCashflow({today:context.today,horizonDays:context.horizonDays,accounts:context.accounts,events:alternativeEvents,startingQualityFlags:context.qualityFlags,workspaceProtectedAmount:context.workspaceProtectedAmount});
   if(alternative.firstShortfallDate&&alternative.firstShortfallDate<=result.firstShortfallDate)continue;
   const before=result.firstShortfallDate,after=alternative.firstShortfallDate,daysAfter=after?Math.floor((Date.parse(after+'T00:00:00Z')-Date.parse(before+'T00:00:00Z'))/86400000):null;
   await add('payment_delay','payment-delay:'+occurrence.id+':'+before,'bill.paymentDelay',85,{billId:occurrence.id,billName:String(occurrence.name).slice(0,120),amount:event.amount,currency:result.currency,currentDate:event.date,deferrableUntil:newDate,shortfallDate:before,alternativeShortfallDate:after,daysDeferred:daysAfter,accountId:event.accountId??null},[{sourceId:occurrence.id,kind:'bill',date:event.date,deferrableUntil:newDate,shortfallBefore:before,shortfallAfter:after}],['recorded_deferral_permission','shortfall_recalculated']);break;
  }
 }
 if(prefs.source_permissions?.goals&&prefs.suggestions_enabled&&result.safeToSpend!==null&&toUnits(result.safeToSpend)>0n){const goals=await q(tx,`select g.id,g.name,g.target_date as "targetDate",g.target_amount::text as target,coalesce(sum(case when c.direction='add' then c.amount else -c.amount end),0)::text as saved from savings_goals g left join goal_contributions c on c.workspace_id=g.workspace_id and c.goal_id=g.id where g.workspace_id=$1 and g.archived_at is null and g.currency=$2 group by g.id order by g.target_date nulls last,g.created_at limit 20`,[workspaceId,result.currency]);for(const goal of goals){const remaining=toUnits(String(goal.target))-toUnits(String(goal.saved)),safe=toUnits(result.safeToSpend);if(remaining<=0n)continue;const amount=fromUnits(remaining<safe?remaining:safe);if(toUnits(amount)<=0n)continue;await add('savings','savings-goal:'+goal.id+':'+remaining.toString(),'goal.savingsOpportunity',40,{goalId:goal.id,goalName:String(goal.name).slice(0,100),targetDate:goal.targetDate,amount,currency:result.currency,allocationOnly:true},[{sourceId:goal.id,kind:'savings_goal',remaining:fromUnits(remaining)}],['within_conservative_safe_to_spend','goal_target_remaining']);break;}}
 await q(tx,"update assistant_suggestions set state='obsolete',version=version+1,updated_at=now() where workspace_id=$1 and user_id=$2 and kind in ('shortfall','low_balance','invoice_followup','savings','payment_delay') and state in ('active','reviewing','snoozed') and (cardinality($3::text[])=0 or not(fingerprint=any($3::text[])))",[workspaceId,userId,prefs.suggestions_enabled?desired:[]]);
 await q(tx,"update finance_notifications n set resolved_at=coalesce(n.resolved_at,now()) from assistant_suggestions s where n.workspace_id=$1 and n.user_id=$2 and n.assistant_suggestion_id=s.id and s.workspace_id=$1 and s.user_id=$2 and s.state='obsolete' and n.resolved_at is null",[workspaceId,userId]);
}

