import { formatDate, formatExportDates } from '../../../../shared/dates';
import { Elysia } from 'elysia';
import { createHash } from 'node:crypto';
import type { TransactionSql } from 'postgres';
import { auth } from '../auth';
import { client } from '../db';
import { toUnits, fromUnits } from '../assistant/money';
import { nextOccurrenceDate, workspaceToday } from '../tracking/recurrence';
import { resolveReportPeriod, type ReportPreset } from './periods';
import { enqueueReportExport, enqueueReportRun } from './queue';
import { deleteAttachment, getAttachment, putAttachment } from '../tracking/storage';

type JsonRow=Record<string,any>;
const q=(tx:TransactionSql,text:string,values:unknown[]=[])=>(tx.unsafe(text,values as never[]));
const presets=new Set(['this_week','last_week','this_month','last_month','year_to_date']);
const types=new Set(['analytics','cashflow','budget_actual']);
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const failure=(status:number,code:string,message:string)=>Response.json({code,message},{status,headers:{'Cache-Control':'no-store'}});
function asJson(value:any){return typeof value==='string'?JSON.parse(value):value;}
function amount(value:unknown){return typeof value==='string'?value:String(value??'0');}
function datePlus(date:string,days:number){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}

async function withReportScope<T>(request:Request,workspaceId:string,run:(tx:TransactionSql,actor:{id:string;email:string},workspace:JsonRow)=>Promise<T>):Promise<T|Response>{
 if(!uuid.test(workspaceId))return failure(400,'INVALID_WORKSPACE_ID','Workspace ID is invalid.');
 const session=await auth.api.getSession({headers:request.headers});if(!session)return failure(401,'AUTH_REQUIRED','Sign in to continue.');if(!session.user.emailVerified)return failure(403,'EMAIL_VERIFICATION_REQUIRED','Verify your email to continue.');
 try{return await client.begin(async tx=>{await tx.unsafe('set transaction isolation level repeatable read');await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[session.user.id,workspaceId]);const [workspace]=await q(tx,'select id,currency,timezone,kind from workspaces w join workspace_memberships m on m.workspace_id=w.id and m.user_id=$2 where w.id=$1 and w.archived_at is null',[workspaceId,session.user.id]);if(!workspace)return failure(404,'WORKSPACE_NOT_FOUND','Workspace not found.');return run(tx,{id:session.user.id,email:session.user.email},workspace);}) as T|Response;}catch(error){const e=error as {code?:string;status?:number;message?:string};if(e.status)return failure(e.status,e.code??'REQUEST_FAILED',e.message??'Request failed.');console.error('Report request failed',{sqlState:e.code??'unknown'});return failure(500,'REPORT_FAILED','The report could not be generated.');}
}

function dateSeries(from:string,toExclusive:string){const out:string[]=[];for(let d=new Date(from+'T00:00:00Z'),end=new Date(toExclusive+'T00:00:00Z');d<end;d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));return out;}

async function buildData(tx:TransactionSql,workspaceId:string,workspace:JsonRow,preset:ReportPreset,currency:string,details:boolean){
 const period=resolveReportPeriod(preset,workspace.timezone),flags:string[]=[];
 if(currency!==workspace.currency)flags.push('requested_currency_differs_from_workspace');
 const accountRows:JsonRow[]=await q(tx,`select a.id,a.name,a.kind,a.currency as "nativeCurrency",case when $3=$4 then $3 else a.currency end as currency,a.archived_at as "archivedAt",
 coalesce(sum(case when $3=$4 then coalesce(jl.base_debit,jl.debit)-coalesce(jl.base_credit,jl.credit) else jl.debit-jl.credit end) filter(where je.effective_date<$2::date),0)::text as balance
 from accounts a left join journal_lines jl on jl.workspace_id=a.workspace_id and jl.ledger_account_id=a.ledger_account_id
 left join journal_entries je on je.workspace_id=jl.workspace_id and je.id=jl.entry_id
 where a.workspace_id=$1 and a.deleted_at is null and a.kind in ('cash','bank','e_wallet','savings')
 group by a.id order by a.created_at,a.id`,[workspaceId,period.toExclusive,currency,workspace.currency]);
 const matchingAccounts=accountRows.filter(a=>a.currency===currency),excludedAccounts=accountRows.filter(a=>a.currency!==currency);
 if(excludedAccounts.length)flags.push('other_currency_accounts_excluded');
 const accountTotal=matchingAccounts.reduce((s,a)=>s+toUnits(amount(a.balance),true),0n);
 const cashAccounts=matchingAccounts.filter(a=>!a.archivedAt);
 const liquidBalance=cashAccounts.reduce((s,a)=>s+toUnits(amount(a.balance),true),0n);

 const transactionTotals=await q(tx,`select coalesce(sum(amount) filter(where type='income'),0)::text as income,
 coalesce(sum(amount) filter(where type='expense'),0)::text as expense,count(*)::int as count
 from tracking_valuations where workspace_id=$1 and deleted_at is null and currency=$2 and type in ('income','expense')
 and occurred_at >= $3::date and occurred_at < $4::date`,[workspaceId,currency,period.from,period.toExclusive]);
 const totals=transactionTotals[0]??{income:'0',expense:'0',count:0};
 const categoryRows:JsonRow[]=await q(tx,`select c.id as "categoryId",c.name as "categoryName",coalesce(sum(t.amount),0)::text as amount,count(t.id)::int as count
 from tracking_allocations t left join categories c on c.workspace_id=t.workspace_id and c.id=t.category_id
 where t.workspace_id=$1 and t.deleted_at is null and t.currency=$2 and t.type='expense'
 and t.occurred_at >= $3::date and t.occurred_at < $4::date group by c.id,c.name order by sum(t.amount) desc nulls last,c.name limit 500`,[workspaceId,currency,period.from,period.toExclusive]);
 const dailyRows:JsonRow[]=await q(tx,`select occurred_at as date,coalesce(sum(amount) filter(where type='income'),0)::text as income,
 coalesce(sum(amount) filter(where type='expense'),0)::text as expense from tracking_valuations
 where workspace_id=$1 and deleted_at is null and currency=$2 and type in ('income','expense') and occurred_at >= $3::date and occurred_at < $4::date group by occurred_at order by occurred_at`,[workspaceId,currency,period.from,period.toExclusive]);
 const byDay=new Map(dailyRows.map(r=>[String(r.date),r]));
 let series=dateSeries(period.from,period.toExclusive).map(date=>{const r=byDay.get(date);return {date,income:amount(r?.income),expense:amount(r?.expense),net:fromUnits(toUnits(amount(r?.income))-toUnits(amount(r?.expense))),cashBalance:'0.0000'};});

 const budgets:JsonRow[]=await q(tx,`select b.id,p.name,b.cadence,p.amount::text as planned,b.currency,b.category_id as "categoryId",c.name as "categoryName",
 p.revision,p.legacy_baseline as "legacyBaseline",coalesce((select sum(t.amount) from tracking_allocations t where t.workspace_id=b.workspace_id and t.deleted_at is null and t.type='expense' and t.currency=b.currency and t.occurred_at >= p.period_start and t.occurred_at < p.period_end and t.category_id in (
   with recursive descendants(id) as (select b.category_id union all select child.id from categories child join descendants d on child.parent_id=d.id where child.workspace_id=b.workspace_id) select id from descendants)),0)::text as actual,
 p.period_start as "periodStart",p.period_end as "periodEnd"
 from budgets b join categories c on c.workspace_id=b.workspace_id and c.id=b.category_id
 join lateral(select r.revision,r.legacy_baseline,r.amount,r.name,
   case when b.cadence='weekly' then date_trunc('week',$2::date)::date else date_trunc('month',$2::date)::date end as period_start,
   case when b.cadence='weekly' then (date_trunc('week',$2::date)+interval '7 days')::date else (date_trunc('month',$2::date)+interval '1 month')::date end as period_end
   from budget_revisions r where r.workspace_id=b.workspace_id and r.budget_id=b.id and r.valid_from <= case when b.cadence='weekly' then date_trunc('week',$2::date)::date else date_trunc('month',$2::date)::date end and (r.valid_to is null or r.valid_to > case when b.cadence='weekly' then date_trunc('week',$2::date)::date else date_trunc('month',$2::date)::date end) order by r.revision desc limit 1) p on true
 where b.workspace_id=$1 and b.archived_at is null and b.currency=$3 and p.period_start >= b.starts_on order by c.sort_order,b.name`,[workspaceId,period.through,currency]);
 const budgetActual=budgets.map(b=>{const planned=toUnits(amount(b.planned)),actual=toUnits(amount(b.actual));return {...b,remaining:fromUnits(planned-actual),usedPercent:planned===0n?null:Number((actual*10000n)/planned)/100,period:{from:String(b.periodStart),toExclusive:String(b.periodEnd)}};});
 if(budgets.some((b:JsonRow)=>b.legacyBaseline))flags.push('legacy_budget_terms');

 const goalRows:JsonRow[]=await q(tx,`select g.id,g.name,g.currency,g.target_amount::text as target,g.target_date as "targetDate",
 coalesce(sum(case when c.direction='add' then c.amount else -c.amount end),0)::text as saved
 from savings_goals g left join goal_contributions c on c.workspace_id=g.workspace_id and c.goal_id=g.id and c.occurred_on<$2::date
 where g.workspace_id=$1 and g.archived_at is null group by g.id order by g.target_date nulls last,g.created_at`,[workspaceId,period.toExclusive]);
 const goals=goalRows.map(g=>({...g,remaining:fromUnits(toUnits(amount(g.target))-toUnits(amount(g.saved),true)),progressPercent:toUnits(amount(g.target))>0n?Number((toUnits(amount(g.saved),true)*10000n)/toUnits(amount(g.target)))/100:null}));

 const through30=datePlus(period.today,30);
 const occurrenceRows:JsonRow[]=await q(tx,`select o.id,o.bill_id as "billId",o.name,o.amount::text,o.currency,o.due_on as "dueOn",o.status
 from bill_occurrences o join bills b on b.workspace_id=o.workspace_id and b.id=o.bill_id
 where o.workspace_id=$1 and b.archived_at is null and o.status='unpaid' and o.currency=$2 and o.due_on <= $3::date and o.due_on >= $4::date order by o.due_on,o.name limit 1000`,[workspaceId,currency,through30,period.today]);
 const bills=occurrenceRows.map(b=>({...b,overdue:String(b.dueOn)<period.today}));

 let activity:JsonRow[]=[];
 if(details){const [count]=await q(tx,`select count(*)::int as count from tracking_valuations where workspace_id=$1 and deleted_at is null and currency=$2 and type in ('income','expense','transfer') and occurred_at >= $3::date and occurred_at < $4::date`,[workspaceId,currency,period.from,period.toExclusive]);if(Number(count.count)>50000)throw Object.assign(new Error('This period contains too many transactions for one export. Choose a shorter preset or account scope.'),{status:413,code:'REPORT_TOO_LARGE'});
  activity=await q(tx,`select t.id,t.type,t.occurred_at as date,t.amount::text,t.currency,t.merchant,t.notes,t.account_id as "accountId",a.name as "accountName",c.name as "categoryName"
   from tracking_valuations t join accounts a on a.workspace_id=t.workspace_id and a.id=t.account_id left join categories c on c.workspace_id=t.workspace_id and c.id=t.category_id
   where t.workspace_id=$1 and t.deleted_at is null and t.currency=$2 and t.type in ('income','expense','transfer') and t.occurred_at >= $3::date and t.occurred_at < $4::date order by t.occurred_at,t.id limit 50001`,[workspaceId,currency,period.from,period.toExclusive]);}

 const movementRows:JsonRow[]=await q(tx,`select je.id as "entryId",je.transaction_id as "transactionId",je.effective_date as date,je.reason,
 t.type as "transactionType",t.category_id as "categoryId",c.name as "categoryName",coalesce(m.activity,'unclassified') as activity,
 coalesce(sum(case when $2=(select currency from workspaces where id=$1) then coalesce(jl.base_debit,jl.debit)-coalesce(jl.base_credit,jl.credit) else jl.debit-jl.credit end),0)::text as amount
 from journal_entries je join journal_lines jl on jl.workspace_id=je.workspace_id and jl.entry_id=je.id
 join accounts a on a.workspace_id=jl.workspace_id and a.ledger_account_id=jl.ledger_account_id
 left join transactions t on t.workspace_id=je.workspace_id and t.id=je.transaction_id
 left join categories c on c.workspace_id=t.workspace_id and c.id=t.category_id
 left join cashflow_category_mappings m on m.workspace_id=c.workspace_id and m.category_id=c.id
 where je.workspace_id=$1 and a.kind in ('cash','bank','e_wallet','savings') and (a.currency=$2 or $2=(select currency from workspaces where id=$1)) and je.effective_date >= $3::date and je.effective_date < $4::date
 group by je.id,je.transaction_id,je.effective_date,je.reason,t.type,t.category_id,c.name,m.activity order by je.effective_date,je.id`,[workspaceId,currency,period.from,period.toExclusive]);
 const cashflowRows:JsonRow[]=[];const sums=new Map<string,bigint>();let boundary=0n,openingAdjustments=0n,unclassified=0n;
 for(const row of movementRows){const movement=toUnits(amount(row.amount),true);let activity=String(row.activity);if(row.reason==='opening'){activity='opening_adjustment';openingAdjustments+=movement;}else if(row.transactionType==='transfer'){if(movement===0n)continue;activity='boundary_transfer';boundary+=movement;}else if(!row.transactionId){activity='unclassified';unclassified+=movement;}else if(activity==='unclassified')unclassified+=movement;
   sums.set(activity,(sums.get(activity)??0n)+movement);cashflowRows.push({...row,amount:fromUnits(movement),activity});}
 const openingResult=await q(tx,`select coalesce(sum(case when $2=(select currency from workspaces where id=$1) then coalesce(jl.base_debit,jl.debit)-coalesce(jl.base_credit,jl.credit) else jl.debit-jl.credit end),0)::text as opening from accounts a join journal_lines jl on jl.workspace_id=a.workspace_id and jl.ledger_account_id=a.ledger_account_id join journal_entries je on je.workspace_id=jl.workspace_id and je.id=jl.entry_id where a.workspace_id=$1 and a.kind in ('cash','bank','e_wallet','savings') and (a.currency=$2 or $2=(select currency from workspaces where id=$1)) and je.effective_date<$3::date`,[workspaceId,currency,period.from]);
 const closingResult=await q(tx,`select coalesce(sum(case when $2=(select currency from workspaces where id=$1) then coalesce(jl.base_debit,jl.debit)-coalesce(jl.base_credit,jl.credit) else jl.debit-jl.credit end),0)::text as closing from accounts a join journal_lines jl on jl.workspace_id=a.workspace_id and jl.ledger_account_id=a.ledger_account_id join journal_entries je on je.workspace_id=jl.workspace_id and je.id=jl.entry_id where a.workspace_id=$1 and a.kind in ('cash','bank','e_wallet','savings') and (a.currency=$2 or $2=(select currency from workspaces where id=$1)) and je.effective_date<$3::date`,[workspaceId,currency,period.toExclusive]);
 const opening=toUnits(amount(openingResult[0]?.opening),true),closing=toUnits(amount(closingResult[0]?.closing),true),cashflow=[...sums].map(([activity,value])=>({activity,net:fromUnits(value)}));
 const dailyCashMovement=new Map<string,bigint>();for(const row of movementRows){const date=String(row.date).slice(0,10);dailyCashMovement.set(date,(dailyCashMovement.get(date)??0n)+toUnits(amount(row.amount),true));}let runningCash=opening;series=series.map(row=>{runningCash+=dailyCashMovement.get(row.date)??0n;return {...row,cashBalance:fromUnits(runningCash)};});
 const cashflowNet=[...sums.values()].reduce((s,v)=>s+v,0n);const reconciliation=opening+cashflowNet;
 if(reconciliation!==closing)flags.push('cashflow_reconciliation_mismatch');if(cashflowRows.some(r=>r.activity==='unclassified'))flags.push('unclassified_cashflow');
 const summary={currency,period:{from:period.from,to:period.through,toExclusive:period.toExclusive,preset:period.preset},cashBalance:fromUnits(liquidBalance),trackedAccountNetBalance:fromUnits(accountTotal),income:amount(totals.income),expense:amount(totals.expense),netActivity:fromUnits(toUnits(amount(totals.income))-toUnits(amount(totals.expense))),transactionCount:Number(totals.count),cashflow:{opening:fromUnits(opening),sections:cashflow,openingAdjustments:fromUnits(openingAdjustments),boundaryTransfers:fromUnits(boundary),unclassified:fromUnits(unclassified),closing:fromUnits(closing),reconciled:reconciliation===closing},accountCount:matchingAccounts.length,excludedCurrencyAccounts:excludedAccounts.length,generatedAt:new Date().toISOString(),reportVersion:'reports-v1',basis:'recorded transactions for income/expense; effective-dated journal for cash balances and cashflow'};
 return {period,summary,flags,accounts:matchingAccounts.map(a=>({...a,balance:amount(a.balance)})),series,categories:categoryRows.map(c=>({...c,amount:amount(c.amount)})),budgetActual,goals,bills,cashflowRows,activity};
}

async function saveSnapshot(tx:TransactionSql,workspaceId:string,actorId:string,workspace:JsonRow,reportType:string,preset:ReportPreset,currency:string,key:string,data:Awaited<ReturnType<typeof buildData>>,existingRunId?:string){
 const sections:Record<string,unknown[]>={summary:[data.summary],series:data.series,categories:data.categories,cashflow:data.cashflowRows,budget_actual:data.budgetActual,bills:data.bills,goals:data.goals,accounts:data.accounts,activity:data.activity};
 const count=Object.values(sections).reduce((sum,rows)=>sum+rows.length,0);if(count>50000)throw Object.assign(new Error('The report is too large to save.'),{status:413,code:'REPORT_TOO_LARGE'});
 const content=JSON.stringify({reportType,preset,currency,sections,flags:data.flags}),hash=createHash('sha256').update(content).digest('hex');
 const [run]=existingRunId
  ? await q(tx,`update report_runs set status='ready',attempts=attempts+0,lease_expires_at=null,failure_code=null,generated_at=now(),period_from=$4,period_to_exclusive=$5,timezone=$6,currency=$7,summary=$8::jsonb,quality_flags=$9::jsonb,content_hash=$10,row_count=$11 where workspace_id=$1 and requested_by=$2 and id=$3 returning id,generated_at as "generatedAt",expires_at as "expiresAt"`,[workspaceId,actorId,existingRunId,data.period.from,data.period.toExclusive,workspace.timezone,currency,JSON.stringify(data.summary),JSON.stringify(data.flags),hash,count])
  : await q(tx,`insert into report_runs(workspace_id,requested_by,report_type,preset,parameters,request_key,period_from,period_to_exclusive,timezone,currency,summary,quality_flags,content_hash,row_count)
 values($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13,$14) returning id,generated_at as "generatedAt",expires_at as "expiresAt"`,[workspaceId,actorId,reportType,preset,JSON.stringify({currency}),key,data.period.from,data.period.toExclusive,workspace.timezone,currency,JSON.stringify(data.summary),JSON.stringify(data.flags),hash,count]);
 if(existingRunId)await q(tx,'delete from report_rows where workspace_id=$1 and requested_by=$2 and run_id=$3',[workspaceId,actorId,existingRunId]);
 for(const [section,rows] of Object.entries(sections))for(let i=0;i<rows.length;i++)await q(tx,'insert into report_rows(workspace_id,run_id,requested_by,section,row_number,row_data) values($1,$2,$3,$4,$5,$6::jsonb)',[workspaceId,run.id,actorId,section,i,JSON.stringify(rows[i])]);
 return {id:run.id,generatedAt:run.generatedAt,expiresAt:run.expiresAt,rowCount:count,contentHash:hash};
}

async function workerSettings(tx:TransactionSql){await q(tx,"select set_config('app.report_worker','true',true)");}

async function enqueueReportRunSafely(runId:string,workspaceId:string,userId:string){try{await enqueueReportRun(runId,workspaceId,userId);}catch{console.error('Report run enqueue failed; database recovery will retry.');}}
async function enqueueReportExportSafely(exportId:string,workspaceId:string,userId:string){try{await enqueueReportExport(exportId,workspaceId,userId);}catch{console.error('Report export enqueue failed; database recovery will retry.');}}

function startReportLeaseHeartbeat(table:'report_runs'|'report_exports',id:string,workspaceId:string,userId:string){const heartbeat=setInterval(()=>{void client.begin(async tx=>{await workerSettings(tx);await q(tx,`update ${table} set lease_expires_at=now()+interval '3 minutes' where id=$1 and workspace_id=$2 and requested_by=$3 and status='running'`,[id,workspaceId,userId]);}).catch(()=>console.error('Report job lease renewal failed',{kind:table==='report_runs'?'run':'export'}));},60_000);heartbeat.unref?.();return heartbeat;}

export async function processQueuedReportRun(runId:string,workspaceId:string,userId:string,attemptsMade=0){
 const claimed=await client.begin(async tx=>{await workerSettings(tx);const [run]=await q(tx,`select * from report_runs where id=$1 and workspace_id=$2 and requested_by=$3 and expires_at>now() and attempts<10 and (status='queued' or (status='running' and lease_expires_at<now())) for update skip locked`,[runId,workspaceId,userId]);if(!run)return null;const [next]=await q(tx,`update report_runs set status='running',attempts=attempts+1,lease_expires_at=now()+interval '2 minutes',failure_code=null where id=$1 returning *`,[runId]);return next;});
 if(!claimed)return;
 const heartbeat=startReportLeaseHeartbeat('report_runs',runId,workspaceId,userId);
 try{return await client.begin(async tx=>{await tx.unsafe('set transaction isolation level repeatable read');await workerSettings(tx);await q(tx,"select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[userId,workspaceId]);const [workspace]=await q(tx,'select w.id,w.currency,w.timezone,w.kind from workspaces w join workspace_memberships m on m.workspace_id=w.id and m.user_id=$2 where w.id=$1 and w.archived_at is null',[workspaceId,userId]);const [run]=await q(tx,'select * from report_runs where workspace_id=$1 and requested_by=$2 and id=$3 and status=\'running\'',[workspaceId,userId,runId]);if(!run) return;if(!workspace)throw Object.assign(new Error('Workspace access changed.'),{code:'ACCESS_REVOKED'});const preset=String(run.preset) as ReportPreset;if(!presets.has(preset))throw Object.assign(new Error('Invalid saved report preset.'),{code:'INVALID_REPORT'});const data=await buildData(tx,workspaceId,workspace,preset,String(run.currency),true);return saveSnapshot(tx,workspaceId,userId,workspace,String(run.reportType),preset,String(run.currency),String(run.requestKey),data,runId);});}
 catch(error){const detail=error as {code?:string;status?:number};const permanent=detail.status===413||detail.code==='ACCESS_REVOKED'||detail.code==='INVALID_REPORT';const final=permanent||attemptsMade>=2;await client.begin(async tx=>{await workerSettings(tx);await q(tx,`update report_runs set status=$4,lease_expires_at=null,failure_code=$5 where id=$1 and workspace_id=$2 and requested_by=$3 and status='running'`,[runId,workspaceId,userId,final?'failed':'queued',detail.status===413?'REPORT_TOO_LARGE':detail.code==='ACCESS_REVOKED'?'ACCESS_REVOKED':detail.code==='INVALID_REPORT'?'INVALID_REPORT':final?'REPORT_GENERATION_FAILED':null]);});throw error;}finally{clearInterval(heartbeat);}
}

export async function recoverReportJobs(){const [runs,exports]=await client.begin(async tx=>{await workerSettings(tx);await q(tx,`update report_runs set status='failed',lease_expires_at=null,failure_code=case when expires_at<=now() then 'REPORT_EXPIRED' else 'REPORT_ATTEMPTS_EXHAUSTED' end where (expires_at<=now() or attempts>=10) and status in ('queued','running')`);const runRows=await q(tx,`select id,workspace_id as "workspaceId",requested_by as "userId" from report_runs where expires_at>now() and attempts<10 and (status='queued' or (status='running' and lease_expires_at<now())) limit 100`);const exportRows=await q(tx,`select id,workspace_id as "workspaceId",requested_by as "userId" from report_exports where expires_at>now() and attempts<5 and (status='queued' or (status='running' and lease_expires_at<now())) limit 100`);return [runRows,exportRows] as const;});for(const run of runs)await enqueueReportRunSafely(run.id,run.workspaceId,run.userId);for(const item of exports)await enqueueReportExportSafely(item.id,item.workspaceId,item.userId);return runs.length+exports.length;}

export async function processQueuedReportExport(exportId:string,workspaceId:string,userId:string,attemptsMade=0){
 const claimed=await client.begin(async tx=>{await workerSettings(tx);const [row]=await q(tx,`select e.id,e.run_id as "runId",e.format from report_exports e join report_runs r on r.workspace_id=e.workspace_id and r.id=e.run_id where e.id=$1 and e.workspace_id=$2 and e.requested_by=$3 and e.attempts<5 and e.expires_at>now() and r.expires_at>now() and r.status='ready' and (e.status='queued' or (e.status='running' and e.lease_expires_at<now())) for update of e skip locked`,[exportId,workspaceId,userId]);if(!row)return null;const [next]=await q(tx,`update report_exports set status='running',attempts=attempts+1,lease_expires_at=now()+interval '3 minutes',failure_code=null where id=$1 returning id`,[exportId]);return {...row,...next};});if(!claimed)return;
 const heartbeat=startReportLeaseHeartbeat('report_exports',exportId,workspaceId,userId);
 let objectKey:string|undefined;
 try{
  const rendered=await client.begin(async tx=>{await tx.unsafe('set transaction isolation level repeatable read');await workerSettings(tx);await q(tx,"select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[userId,workspaceId]);const [member]=await q(tx,'select w.id,w.currency,w.timezone,w.kind from workspaces w join workspace_memberships m on m.workspace_id=w.id and m.user_id=$2 where w.id=$1 and w.archived_at is null',[workspaceId,userId]);if(!member)throw Object.assign(new Error('Workspace access changed.'),{code:'ACCESS_REVOKED'});const [run]=await q(tx,`select id,report_type as "reportType",preset,generated_at as "generatedAt",period_from as "periodFrom",period_to_exclusive as "periodToExclusive",timezone,currency,summary,quality_flags as "qualityFlags",content_hash as "contentHash",row_count as "rowCount",expires_at as "expiresAt" from report_runs where workspace_id=$1 and requested_by=$2 and id=$3 and status='ready' and expires_at>now()`,[workspaceId,userId,claimed.runId]);if(!run)throw Object.assign(new Error('Report expired or unavailable.'),{code:'REPORT_EXPIRED'});if(claimed.format==='pdf'&&Number(run.rowCount)>2500)throw Object.assign(new Error('PDF export is too large.'),{code:'PDF_TOO_LARGE'});const rows=await q(tx,'select section,row_number as "rowNumber",row_data as data from report_rows where workspace_id=$1 and requested_by=$2 and run_id=$3 order by section,row_number',[workspaceId,userId,claimed.runId]);return {run,data:rows.map(row=>({section:row.section,...asJson(row.data)}))};});
  const response=await renderReportExport(rendered.run,rendered.data,claimed.format as 'csv'|'xlsx'|'pdf'),buffer=new Uint8Array(await response.arrayBuffer());if(buffer.byteLength>64*1024*1024)throw Object.assign(new Error('Export exceeds the 64 MiB download limit.'),{code:'EXPORT_TOO_LARGE'});objectKey=`reports/${workspaceId}/${userId}/${exportId}.${claimed.format}`;await putAttachment(objectKey,buffer,response.headers.get('Content-Type')??'application/octet-stream');const checksum=createHash('sha256').update(buffer).digest('hex');
  await client.begin(async tx=>{await workerSettings(tx);await q(tx,"select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[userId,workspaceId]);const [active]=await q(tx,'select 1 from workspace_memberships where workspace_id=$1 and user_id=$2',[workspaceId,userId]);const [run]=await q(tx,'select id from report_runs where workspace_id=$1 and requested_by=$2 and id=$3 and status=\'ready\' and expires_at>now()',[workspaceId,userId,claimed.runId]);if(!active||!run)throw Object.assign(new Error('Workspace access changed before publishing.'),{code:'ACCESS_REVOKED'});await q(tx,`update report_exports set status='ready',object_key=$4,checksum=$5,byte_count=$6,ready_at=now(),lease_expires_at=null,failure_code=null where id=$1 and workspace_id=$2 and requested_by=$3 and status='running'`,[exportId,workspaceId,userId,objectKey,checksum,buffer.byteLength]);});
 }catch(error){if(objectKey){try{await deleteAttachment(objectKey);}catch{await client.begin(async tx=>{await workerSettings(tx);await q(tx,'insert into report_export_cleanup(object_key) values($1) on conflict do nothing',[objectKey]);});}}const detail=error as {code?:string};const permanent=['ACCESS_REVOKED','REPORT_EXPIRED','PDF_TOO_LARGE','EXPORT_TOO_LARGE'].includes(detail.code??'');await client.begin(async tx=>{await workerSettings(tx);await q(tx,`update report_exports set status=$4,lease_expires_at=null,failure_code=$5 where id=$1 and workspace_id=$2 and requested_by=$3 and status='running'`,[exportId,workspaceId,userId,permanent||attemptsMade>=2?'failed':'queued',detail.code==='PDF_TOO_LARGE'?'PDF_TOO_LARGE':detail.code==='EXPORT_TOO_LARGE'?'EXPORT_TOO_LARGE':detail.code==='ACCESS_REVOKED'?'ACCESS_REVOKED':detail.code==='REPORT_EXPIRED'?'REPORT_EXPIRED':'EXPORT_FAILED']);});throw error;}finally{clearInterval(heartbeat);}
}

export async function cleanupReportExports(){
 const expired=await client.begin(async tx=>{await workerSettings(tx);await q(tx,`update report_exports set status='failed',lease_expires_at=null,failure_code='EXPORT_ATTEMPTS_EXHAUSTED' where attempts>=5 and status in ('queued','running')`);return q(tx,`select id,object_key as "objectKey" from report_exports where expires_at<=now() and status<>'expired' limit 100`);});
 for(const row of expired){if(row.objectKey)await deleteAttachment(row.objectKey);await client.begin(async tx=>{await workerSettings(tx);await q(tx,`update report_exports set status='expired',object_key=null,lease_expires_at=null where id=$1`,[row.id]);});}
 await client.begin(async tx=>{await workerSettings(tx);await q(tx,'delete from report_runs where expires_at<=now()');});
 const pending=await client.begin(async tx=>q(tx,'select object_key as "objectKey" from report_export_cleanup order by queued_at limit 100'));
 for(const item of pending){try{await deleteAttachment(item.objectKey);await client.begin(async tx=>{await q(tx,'delete from report_export_cleanup where object_key=$1',[item.objectKey]);});}catch{await client.begin(async tx=>{await q(tx,"update report_export_cleanup set attempts=attempts+1,last_error='OBJECT_DELETE_FAILED' where object_key=$1",[item.objectKey]);});}}
 return expired.length+pending.length;
}

export async function markReportRunFailure(runId:string,workspaceId:string,userId:string,code:string){await client.begin(async tx=>{await workerSettings(tx);await q(tx,`update report_runs set status='failed',lease_expires_at=null,failure_code=$4 where id=$1 and workspace_id=$2 and requested_by=$3 and status in ('queued','running')`,[runId,workspaceId,userId,code]);});}

export const reportsRoutes=new Elysia({name:'reports-routes'})
 .get('/api/workspaces/:workspaceId/reports/runs',({request,params,query})=>withReportScope(request,params.workspaceId,async(tx,actor)=>{const limit=Math.min(50,Math.max(1,Number(query.limit??20)||20)),offset=Math.min(1000,Math.max(0,Number(query.offset??0)||0));const items=await q(tx,'select id,report_type as "reportType",preset,status,generated_at as "generatedAt",period_from as "periodFrom",period_to_exclusive as "periodToExclusive",currency,row_count as "rowCount",failure_code as "failureCode",expires_at as "expiresAt" from report_runs where workspace_id=$1 and requested_by=$2 and expires_at>now() order by generated_at desc,id desc limit $3 offset $4',[params.workspaceId,actor.id,limit+1,offset]);return Response.json({items:items.slice(0,limit),nextOffset:items.length>limit?offset+limit:null},{headers:{'Cache-Control':'private, no-store'}})}))
 .get('/api/workspaces/:workspaceId/reports/cashflow/mappings',({request,params})=>withReportScope(request,params.workspaceId,async(tx)=>({items:await q(tx,`select c.id as "categoryId",c.name as "categoryName",m.activity,m.version,m.updated_at as "updatedAt" from categories c left join cashflow_category_mappings m on m.workspace_id=c.workspace_id and m.category_id=c.id where c.workspace_id=$1 and c.archived_at is null and c.type in ('income','expense') order by c.sort_order,c.name`,[params.workspaceId])})))
 .put('/api/workspaces/:workspaceId/reports/cashflow/mappings/:categoryId',async({request,params})=>withReportScope(request,params.workspaceId,async(tx,actor)=>{if(!uuid.test(params.categoryId))return failure(400,'INVALID_CATEGORY_ID','Category ID is invalid.');const body=await request.json().catch(()=>null) as {activity?:string}|null;if(!body||!['operating','investing','financing','unclassified'].includes(String(body.activity)))return failure(422,'INVALID_CASHFLOW_ACTIVITY','Choose operating, investing, financing, or unclassified.');const [category]=await q(tx,"select id from categories where workspace_id=$1 and id=$2 and archived_at is null and type in ('income','expense')",[params.workspaceId,params.categoryId]);if(!category)return failure(404,'CATEGORY_NOT_FOUND','Category not found.');const [mapping]=await q(tx,`insert into cashflow_category_mappings(workspace_id,category_id,activity,version,updated_by) values($1,$2,$3,1,$4) on conflict(workspace_id,category_id) do update set activity=excluded.activity,version=cashflow_category_mappings.version+1,updated_by=excluded.updated_by,updated_at=now() returning category_id as "categoryId",activity,version,updated_at as "updatedAt"`,[params.workspaceId,params.categoryId,body.activity,actor.id]);return Response.json({mapping},{headers:{'Cache-Control':'private, no-store'}})}))
 .get('/api/workspaces/:workspaceId/reports/dashboard',({request,params,query})=>withReportScope(request,params.workspaceId,async(tx,_actor,workspace)=>{
   const preset=(query.preset??'this_month') as ReportPreset;if(!presets.has(preset))return failure(422,'INVALID_PRESET','Choose a supported report period.');const currency=String(query.currency??workspace.currency);if(!/^[A-Z]{3}$/.test(currency))return failure(422,'INVALID_CURRENCY','Choose a valid currency code.');const data=await buildData(tx,params.workspaceId,workspace,preset,currency,false);return Response.json({...data},{headers:{'Cache-Control':'private, no-store'}});
 }))
 .get('/api/workspaces/:workspaceId/reports/cashflow',({request,params,query})=>withReportScope(request,params.workspaceId,async(tx,_actor,workspace)=>{
   const preset=(query.preset??'this_month') as ReportPreset;if(!presets.has(preset))return failure(422,'INVALID_PRESET','Choose a supported report period.');const data=await buildData(tx,params.workspaceId,workspace,preset,String(query.currency??workspace.currency),false);return Response.json({summary:data.summary,rows:data.cashflowRows,qualityFlags:data.flags},{headers:{'Cache-Control':'private, no-store'}});
 }))
 .get('/api/workspaces/:workspaceId/reports/budget-actual',({request,params,query})=>withReportScope(request,params.workspaceId,async(tx,_actor,workspace)=>{
   const preset=(query.preset??'this_month') as ReportPreset;if(!presets.has(preset))return failure(422,'INVALID_PRESET','Choose a supported report period.');const data=await buildData(tx,params.workspaceId,workspace,preset,String(query.currency??workspace.currency),false);return Response.json({period:data.summary.period,currency:data.summary.currency,items:data.budgetActual,qualityFlags:data.flags},{headers:{'Cache-Control':'private, no-store'}});
 }))
 .post('/api/workspaces/:workspaceId/reports/runs',async({request,params})=>withReportScope(request,params.workspaceId,async(tx,actor,workspace)=>{
   const body=await request.json().catch(()=>null) as {reportType?:string;preset?:ReportPreset;currency?:string;idempotencyKey?:string}|null;if(!body||!types.has(String(body.reportType))||!presets.has(String(body.preset))||typeof body.idempotencyKey!=='string'||body.idempotencyKey.length<8||body.idempotencyKey.length>200)return failure(422,'INVALID_REPORT_REQUEST','Provide a supported report, period and idempotency key.');const currency=String(body.currency??workspace.currency);if(!/^[A-Z]{3}$/.test(currency))return failure(422,'INVALID_CURRENCY','Choose a valid currency code.');await q(tx,'select pg_advisory_xact_lock(hashtextextended($1,0))',[`${actor.id}:${body.idempotencyKey}`]);await q(tx,'delete from report_runs where workspace_id=$1 and requested_by=$2 and expires_at<=now()',[params.workspaceId,actor.id]);
   const [existing]=await q(tx,'select id,report_type as "reportType",preset,currency,status,generated_at as "generatedAt",expires_at as "expiresAt",row_count as "rowCount",content_hash as "contentHash" from report_runs where workspace_id=$1 and requested_by=$2 and request_key=$3',[params.workspaceId,actor.id,body.idempotencyKey]);if(existing){if(existing.reportType!==body.reportType||existing.preset!==body.preset||existing.currency!==currency)return failure(409,'IDEMPOTENCY_CONFLICT','This key was already used for another report.');return Response.json({run:existing,replayed:true},{status:200,headers:{'Cache-Control':'private, no-store'}});}
   const period=resolveReportPeriod(body.preset,workspace.timezone);const [run]=await q(tx,`insert into report_runs(workspace_id,requested_by,report_type,preset,parameters,request_key,status,period_from,period_to_exclusive,timezone,currency,content_hash) values($1,$2,$3,$4,$5::jsonb,$6,'queued',$7,$8,$9,$10,'queued') returning id,report_type as "reportType",preset,status,generated_at as "generatedAt",period_from as "periodFrom",period_to_exclusive as "periodToExclusive",timezone,currency,row_count as "rowCount",expires_at as "expiresAt"`,[params.workspaceId,actor.id,body.reportType,body.preset,JSON.stringify({currency}),body.idempotencyKey,period.from,period.toExclusive,workspace.timezone,currency]);await enqueueReportRunSafely(run.id,params.workspaceId,actor.id);return Response.json({run,replayed:false},{status:202,headers:{'Cache-Control':'private, no-store'}});
 }))
 .get('/api/workspaces/:workspaceId/reports/runs/:runId',({request,params})=>withReportScope(request,params.workspaceId,async(tx,actor)=>{
   if(!uuid.test(params.runId))return failure(400,'INVALID_RUN_ID','Report ID is invalid.');const [run]=await q(tx,'select id,report_type as "reportType",preset,status,failure_code as "failureCode",parameters,report_version as "reportVersion",generated_at as "generatedAt",period_from as "periodFrom",period_to_exclusive as "periodToExclusive",timezone,currency,summary,quality_flags as "qualityFlags",row_count as "rowCount",expires_at as "expiresAt" from report_runs where workspace_id=$1 and requested_by=$2 and id=$3 and expires_at>now()',[params.workspaceId,actor.id,params.runId]);if(!run)return failure(404,'REPORT_NOT_FOUND','Report not found or expired.');return Response.json({run},{headers:{'Cache-Control':'private, no-store'}});
 }))
 .get('/api/workspaces/:workspaceId/reports/runs/:runId/rows',({request,params,query})=>withReportScope(request,params.workspaceId,async(tx,actor)=>{
   if(!uuid.test(params.runId))return failure(400,'INVALID_RUN_ID','Report ID is invalid.');const section=String(query.section??'summary'),cursor=Math.max(0,Number(query.cursor??0)||0),limit=Math.min(500,Math.max(1,Number(query.limit??100)||100));const [run]=await q(tx,'select id from report_runs where workspace_id=$1 and requested_by=$2 and id=$3 and status=\'ready\' and expires_at>now()',[params.workspaceId,actor.id,params.runId]);if(!run)return failure(404,'REPORT_NOT_FOUND','Report not found or expired.');const items=await q(tx,'select row_number as "rowNumber",row_data as data from report_rows where workspace_id=$1 and requested_by=$2 and run_id=$3 and section=$4 and row_number >= $5 order by row_number limit $6',[params.workspaceId,actor.id,params.runId,section,cursor,limit]);return Response.json({items,nextCursor:items.length===limit?Number(items.at(-1)!.rowNumber)+1:null},{headers:{'Cache-Control':'private, no-store'}});
 }))
 .post('/api/workspaces/:workspaceId/reports/runs/:runId/exports',async({request,params})=>withReportScope(request,params.workspaceId,async(tx,actor)=>{if(!uuid.test(params.runId))return failure(400,'INVALID_RUN_ID','Report ID is invalid.');const body=await request.json().catch(()=>null) as {format?:string;idempotencyKey?:string}|null;if(!body||!['csv','xlsx','pdf'].includes(String(body.format))||typeof body.idempotencyKey!=='string'||body.idempotencyKey.length<8||body.idempotencyKey.length>200)return failure(422,'INVALID_EXPORT_REQUEST','Choose a format and provide an idempotency key.');await q(tx,'select pg_advisory_xact_lock(hashtextextended($1,0))',[`${actor.id}:${params.runId}:${body.idempotencyKey}`]);const [existing]=await q(tx,'select id,format,status,created_at as "createdAt",expires_at as "expiresAt",failure_code as "failureCode" from report_exports where workspace_id=$1 and requested_by=$2 and run_id=$3 and request_key=$4',[params.workspaceId,actor.id,params.runId,body.idempotencyKey]);if(existing)return Response.json({export:existing,replayed:true},{headers:{'Cache-Control':'private, no-store'}});const [run]=await q(tx,"select id,row_count as \"rowCount\",expires_at as \"expiresAt\" from report_runs where workspace_id=$1 and requested_by=$2 and id=$3 and status='ready' and expires_at>now()",[params.workspaceId,actor.id,params.runId]);if(!run)return failure(404,'REPORT_NOT_FOUND','Report not found or expired.');if(body.format==='pdf'&&Number(run.rowCount)>2500)return failure(413,'PDF_TOO_LARGE','This report is too large for PDF. Export CSV or Excel instead.');const [active]=await q(tx,"select count(*)::int as count from report_exports where workspace_id=$1 and requested_by=$2 and status in ('queued','running') and expires_at>now()",[params.workspaceId,actor.id]);if(Number(active.count)>=2)return failure(429,'EXPORT_LIMIT','Wait for your current report downloads to finish.');const [created]=await q(tx,`insert into report_exports(workspace_id,run_id,requested_by,format,request_key,expires_at) values($1,$2,$3,$4,$5,least($6::timestamptz,now()+interval '7 days')) returning id,format,status,created_at as "createdAt",expires_at as "expiresAt"`,[params.workspaceId,params.runId,actor.id,body.format,body.idempotencyKey,run.expiresAt]);await enqueueReportExportSafely(created.id,params.workspaceId,actor.id);return Response.json({export:created,replayed:false},{status:202,headers:{'Cache-Control':'private, no-store'}});}))
 .get('/api/workspaces/:workspaceId/reports/exports/:exportId',({request,params})=>withReportScope(request,params.workspaceId,async(tx,actor)=>{if(!uuid.test(params.exportId))return failure(400,'INVALID_EXPORT_ID','Export ID is invalid.');const [item]=await q(tx,`select e.id,e.run_id as "runId",e.format,e.status,e.created_at as "createdAt",e.ready_at as "readyAt",e.expires_at as "expiresAt",e.byte_count as "byteCount",e.checksum,e.failure_code as "failureCode" from report_exports e join report_runs r on r.workspace_id=e.workspace_id and r.id=e.run_id where e.workspace_id=$1 and e.requested_by=$2 and e.id=$3 and e.expires_at>now() and r.expires_at>now()`,[params.workspaceId,actor.id,params.exportId]);if(!item)return failure(404,'EXPORT_NOT_FOUND','Export not found or expired.');return Response.json({export:item},{headers:{'Cache-Control':'private, no-store'}})}))
 .get('/api/workspaces/:workspaceId/reports/exports/:exportId/download',({request,params})=>withReportScope(request,params.workspaceId,async(tx,actor)=>{if(!uuid.test(params.exportId))return failure(400,'INVALID_EXPORT_ID','Export ID is invalid.');const [item]=await q(tx,`select e.object_key as "objectKey",e.format,e.checksum,r.report_type as "reportType",r.period_from as "periodFrom",r.period_to_exclusive as "periodToExclusive" from report_exports e join report_runs r on r.workspace_id=e.workspace_id and r.id=e.run_id where e.workspace_id=$1 and e.requested_by=$2 and e.id=$3 and e.status='ready' and e.expires_at>now() and r.expires_at>now() and r.status='ready'`,[params.workspaceId,actor.id,params.exportId]);if(!item)return failure(404,'EXPORT_NOT_FOUND','Export not found or expired.');try{const object=await getAttachment(item.objectKey);const stream=object.Body?.transformToWebStream();if(!stream)return failure(410,'EXPORT_FILE_MISSING','This download has expired.');const ext=item.format==='xlsx'?'xlsx':item.format,contentType=item.format==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':item.format==='pdf'?'application/pdf':'text/csv; charset=utf-8',filename=`capybudget-${item.reportType}-${item.periodFrom}-${item.periodToExclusive}.${ext}`;return new Response(stream,{headers:{'Content-Type':contentType,'Content-Disposition':`attachment; filename=\"${filename}\"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','ETag':`\"${item.checksum}\"`}});}catch{return failure(410,'EXPORT_FILE_MISSING','This download has expired.');}}));


export async function renderReportExport(run:JsonRow,data:JsonRow[],format:'csv'|'xlsx'|'pdf'):Promise<Response>{data=data.map(row=>formatExportDates(row) as JsonRow);const filename=`capybudget-${run.reportType}-${run.periodFrom}-${run.periodToExclusive}.${format==='xlsx'?'xlsx':format}`;if(format==='csv'){const columns=['section',...new Set(data.flatMap(row=>Object.keys(row).filter(key=>key!=='section')))];const lines=[columns.join(',')];for(const row of data){const vals=columns.map(key=>{let value=(row as any)[key];if(value===undefined||value===null)return '';let text=typeof value==='object'?JSON.stringify(value):String(value);if(!['amount','income','expense','planned','actual','remaining','balance','cashBalance','target','saved'].includes(key)&&/^\s*[=+@\-\t\r]/.test(text))text="'"+text;if(/[",\r\n]/.test(text))text='"'+text.replace(/"/g,'""')+'"';return text;});lines.push(vals.join(','));}return new Response('\uFEFF'+lines.join('\r\n'),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${filename}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
   if(format==='xlsx'){const ExcelJS=(await import('exceljs')).default;const wb=new ExcelJS.Workbook();wb.creator='CapyBudget';wb.subject='Financial report snapshot';wb.created=new Date(run.generatedAt);const summary=asJson(formatExportDates(asJson(run.summary))),summarySheet=wb.addWorksheet('Summary');summarySheet.addRows([['CapyBudget report',String(run.reportType).toUpperCase()],['Period from',formatDate(run.periodFrom)],['Period through',formatDate(datePlus(String(run.periodToExclusive),-1))],['Currency',String(run.currency)],['Generated at',formatExportDates(new Date(run.generatedAt).toISOString())],['Snapshot ID',String(run.id)],['Snapshot rows',String(run.rowCount)],...Object.entries(summary).map(([key,value])=>[key,typeof value==='object'?JSON.stringify(value):String(value??'')])]);summarySheet.getColumn(1).width=30;summarySheet.getColumn(2).width=64;summarySheet.getRow(1).font={bold:true};const sheet=wb.addWorksheet('Data');const keys=[...new Set(data.flatMap(item=>Object.keys(item)))].filter(k=>k!=='section');sheet.columns=[{header:'section',key:'section',width:20},...keys.map(key=>({header:key,key,width:24}))];for(const item of data){const safe:any={section:String(item.section??'')};for(const key of keys){const value=item[key];safe[key]=value===null||value===undefined?'':typeof value==='object'?JSON.stringify(value):String(value);}sheet.addRow(safe);}sheet.getRow(1).font={bold:true};sheet.views=[{state:'frozen',ySplit:1}];const metadata=wb.addWorksheet('Metadata');metadata.addRows([['Report version','reports-v1'],['Snapshot hash',String(run.contentHash)],['Money storage','Authoritative amounts are decimal text to preserve exact precision.'],['Basis','Recorded income and expense transactions; effective-dated journal for cash balances and cashflow.'],['Period convention','Workspace-local dates; period end stored exclusive.'],['Exported rows','Every row in the immutable snapshot.']]);metadata.getColumn(1).width=28;metadata.getColumn(2).width=90;for(const tab of [summarySheet,sheet,metadata])tab.eachRow(row=>{row.eachCell(cell=>{cell.value=cell.value===null||cell.value===undefined?'':String(cell.value);});});const buffer=await wb.xlsx.writeBuffer();const arrayBuffer=new ArrayBuffer((buffer as any).length);const output=new Uint8Array(arrayBuffer);for(let i=0;i<output.length;i++)output[i]=(buffer as any)[i];return new Response(arrayBuffer,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="${filename}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
   const groups=new Map<string,any[]>();for(const row of data){const section=String(row.section??'Data');groups.set(section,[...(groups.get(section)??[]),row]);}const html=`<!doctype html><meta charset="utf-8"><style>body{font:11px Arial;color:#30251d;margin:28px}h1{color:#8a5f3a}h2{margin:22px 0 8px;color:#694b31;text-transform:capitalize}.record{border:1px solid #e6d5b8;padding:8px;margin:0 0 10px;break-inside:avoid}.record h3{margin:0 0 6px;font-size:11px;text-transform:capitalize}table{border-collapse:collapse;width:100%}th{background:#f3e6cf;text-align:left;width:24%}td,th{padding:5px 7px;border-bottom:1px solid #e6d5b8;overflow-wrap:anywhere}small{color:#73675d}</style><h1>CapyBudget · ${String(run.reportType).toUpperCase()}</h1><p>${formatDate(run.periodFrom)} – ${formatDate(datePlus(String(run.periodToExclusive),-1))} · ${run.currency} · generated ${formatExportDates(new Date(run.generatedAt).toISOString())}</p><small>Recorded financial activity. This report is informational and is not a statutory financial statement.</small>${[...groups].map(([section,items])=>`<h2>${escapeHtml(section.replaceAll('_',' '))}</h2>${items.map((row,index)=>`<div class="record"><h3>${escapeHtml(row.name??row.merchant??row.activity??row.type??`${section} ${index+1}`)}</h3><table><tbody>${Object.entries(row).filter(([key])=>key!=='section').map(([key,value])=>`<tr><th>${escapeHtml(key.replaceAll('_',' '))}</th><td>${escapeHtml(typeof value==='object'?JSON.stringify(value):value)}</td></tr>`).join('')}</tbody></table></div>`).join('')}`).join('')}`;const {chromium}=await import('playwright');const browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});try{const page=await browser.newPage();await page.route('**/*',route=>route.request().url().startsWith('about:')?route.continue():route.abort());await page.setContent(html,{waitUntil:'load'});const pdf=await page.pdf({format:'A4',printBackground:true,displayHeaderFooter:true,footerTemplate:'<div style="font:9px Arial;width:100%;text-align:center"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',margin:{top:'15mm',bottom:'18mm',left:'12mm',right:'12mm'}});const pdfBuffer=new ArrayBuffer((pdf as any).length);const pdfOutput=new Uint8Array(pdfBuffer);for(let i=0;i<pdfOutput.length;i++)pdfOutput[i]=(pdf as any)[i];return new Response(pdfBuffer,{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${filename}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}finally{await browser.close();}}

function escapeHtml(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
