<script lang="ts">
 import {getContext,untrack} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import DatePicker from '$lib/components/forms/date-picker.svelte';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import PageHeader from '$lib/components/shared/page-header.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';import {formatDate} from '$lib/dates';
 const workspace=getContext<{selectedId:string;ready:boolean;revision?:number;items:{id:string;timezone:string}[]}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 type Side='receivable'|'payable';
 type AgingRow={id:string;side:Side;number:string;name:string;dueDate:string;currency:string;outstanding:string;daysOverdue:number;bucket:string};
 type Report={asOf:string;rows:AgingRow[]};
 const buckets=['current','1–30','31–60','61–90','90+'];
 let asOf=$state(''),result:Report|null=$state(null),loading=$state(false),error=$state(''),rowPage=$state(0),sideFilter=$state(''),bucketFilter=$state(''),sequence=0;
 const currencies=$derived.by(()=>[...new Set(result?.rows.map(row=>row.currency)??[])].sort());
 const visibleRows=$derived.by(()=>(result?.rows??[]).filter(row=>(!sideFilter||row.side===sideFilter)&&(!bucketFilter||row.bucket===bucketFilter)));
 const pageRows=$derived(visibleRows.slice(rowPage*50,(rowPage+1)*50));
 const overdueCount=$derived.by(()=>result?.rows.filter(row=>row.daysOverdue>0).length??0);
 const pageCount=$derived(Math.max(1,Math.ceil(visibleRows.length/50)));
 function url(ws:string,date:string,format?:string){return '/api/workspaces/'+ws+'/business-aging?'+new URLSearchParams({asOf:date,...(format?{format}:{})});}
 async function load(){const ws=workspace.selectedId,date=asOf,current=++sequence;loading=true;error='';result=null;rowPage=0;try{const response=await fetch(url(ws,date)),data=await response.json();if(!response.ok)throw new Error(data.message);if(current===sequence&&ws===workspace.selectedId){result=data;sideFilter='';bucketFilter='';}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{void workspace.revision;if(workspace.ready&&workspace.selectedId){const timezone=workspace.items.find(w=>w.id===workspace.selectedId)?.timezone??'Asia/Jakarta';untrack(()=>{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=(key:string)=>parts.find(p=>p.type===key)?.value??'';asOf=part('year')+'-'+part('month')+'-'+part('day');result=null;rowPage=0;sideFilter='';bucketFilter='';void load();});}});
 function sideLabel(side:Side){return side==='receivable'?copy('Customers owe you','Pelanggan berutang kepada Anda'):copy('You owe suppliers','Anda berutang kepada pemasok');}
 function bucketLabel(bucket:string){return bucket==='current'?copy('Not overdue','Belum terlambat'):bucket==='90+'?copy('91+ days overdue','91+ hari terlambat'):bucket+copy(' days overdue',' hari terlambat');}
 function dueStatus(row:AgingRow){return row.daysOverdue>0?row.daysOverdue+(row.daysOverdue===1?copy(' day overdue',' hari terlambat'):copy(' days overdue',' hari terlambat')):row.daysOverdue===0?copy('Due on report date','Jatuh tempo pada tanggal laporan'):copy('Due in ','Jatuh tempo dalam ')+Math.abs(row.daysOverdue)+(row.daysOverdue===-1?copy(' day',' hari'):copy(' days',' hari'));}
 function documentUrl(row:AgingRow){return row.side==='receivable'?'/invoices/'+row.id:'/business/payables/'+row.id;}
 function rowsFor(currency:string,side:Side){return result?.rows.filter(row=>row.currency===currency&&row.side===side)??[];}
 // API money is NUMERIC with up to four decimal places. Sum exactly, without floating-point rounding.
 function sum(rows:AgingRow[]){const amount=rows.reduce((total,row)=>{const [whole,fraction='']=row.outstanding.split('.');return total+BigInt(whole)*10000n+BigInt(fraction.padEnd(4,'0'));},0n);return (amount/10000n).toString()+'.'+(amount%10000n).toString().padStart(4,'0');}
 function resetFilters(){sideFilter='';bucketFilter='';rowPage=0;}
</script>
<svelte:head><title>CapyBudget · {copy('Receivables & payables','Piutang & utang usaha')}</title></svelte:head>
<LoadingScope active={loading}/>
<PageHeader guidePath="/business/aging" title={copy('Receivables & payables','Piutang & utang usaha')} description={copy('See what customers still owe you and what you still owe suppliers, grouped by how long payments are overdue.','Lihat sisa pembayaran yang Anda tunggu dari pelanggan dan yang masih harus Anda bayar kepada pemasok, dikelompokkan berdasarkan keterlambatan.')}/>
<Card.Root><Card.Header><Card.Title>{copy('Choose a report date','Pilih tanggal laporan')}</Card.Title><Card.Description>{copy('Balances and overdue days are calculated as of this date, using recorded payments and corrections up to that day.','Saldo dan jumlah hari terlambat dihitung pada tanggal ini, memakai pembayaran dan koreksi yang tercatat hingga hari tersebut.')}</Card.Description></Card.Header><Card.Content class="space-y-4">
<form class="flex flex-wrap items-end gap-4" onsubmit={event=>{event.preventDefault();void load();}}><Field.Field class="w-full sm:w-64"><Field.FieldLabel for="aging-date">{copy('Report date','Tanggal laporan')}</Field.FieldLabel><DatePicker id="aging-date" bind:value={asOf} required disabled={loading}/></Field.Field><Button type="submit" disabled={loading||!asOf}>{copy('Show report','Tampilkan laporan')}</Button>{#if result}<Button href={url(workspace.selectedId,result.asOf,'csv')} variant="outline" disabled={loading}>{copy('Export full report (CSV)','Ekspor laporan lengkap (CSV)')}</Button>{/if}</form>
{#if result&&asOf!==result.asOf}<p role="status" class="text-sm text-muted-foreground">{copy('The date has changed. Choose “Show report” to apply it. The displayed report and CSV still use ','Tanggal telah berubah. Pilih “Tampilkan laporan” untuk menerapkannya. Laporan yang ditampilkan dan CSV masih memakai ')}{formatDate(result.asOf)}.</p>{/if}
</Card.Content></Card.Root>
{#if error}<div class="mt-6"><ErrorState title={copy('Could not load this report','Laporan gagal dimuat')} message={error} onRetry={load} retryLabel={copy('Try again','Coba lagi')}/></div>{/if}
{#if result}
 <div class="mt-6 space-y-6">
  <div class="flex flex-wrap items-start justify-between gap-4"><div class="space-y-2"><h2 class="text-lg font-semibold">{copy('Outstanding balances on ','Sisa pembayaran pada ')}{formatDate(result.asOf)}</h2><p class="text-sm text-muted-foreground">{result.rows.length} {copy('unpaid or partly paid documents','dokumen belum lunas atau dibayar sebagian')} · {overdueCount} {copy('overdue','terlambat')}</p></div><p class="max-w-lg text-sm leading-relaxed text-muted-foreground">{copy('Each currency is shown separately. These balances are payments still due; they are not your available account balance.','Setiap mata uang ditampilkan terpisah. Saldo ini adalah sisa pembayaran yang belum lunas; bukan saldo akun yang tersedia untuk digunakan.')}</p></div>
  {#each currencies as currency(currency)}
   <section class="space-y-4" aria-labelledby={'aging-currency-'+currency}><h3 id={'aging-currency-'+currency} class="text-base font-semibold">{copy('Balances in ','Saldo dalam ')}{currency}</h3><div class="grid items-start gap-4 lg:grid-cols-2">
    {#each ['receivable','payable'] as side}
     {@const documents=rowsFor(currency,side as Side)}
     {@const overdue=documents.filter(row=>row.daysOverdue>0)}
     <Card.Root><Card.Header><Card.Title>{sideLabel(side as Side)}</Card.Title><Card.Description>{side==='receivable'?copy('Receivables: the unpaid part of issued customer invoices.','Piutang: bagian invoice pelanggan yang sudah diterbitkan tetapi belum dibayar.'):copy('Payables: the unpaid part of issued supplier bills.','Utang usaha: bagian tagihan pemasok yang sudah diterbitkan tetapi belum dibayar.')}</Card.Description></Card.Header><Card.Content class="space-y-6">
      <dl class="grid gap-4 sm:grid-cols-2"><div class="space-y-2"><dt class="text-sm text-muted-foreground">{copy('Total still unpaid','Total belum lunas')}</dt><dd><MoneyDisplay amount={sum(documents)} {currency} size="xl"/></dd></div><div class="space-y-2"><dt class="text-sm text-muted-foreground">{copy('Of that, already overdue','Dari total tersebut, sudah terlambat')}</dt><dd class="space-y-2"><MoneyDisplay amount={sum(overdue)} {currency} size="lg"/><p class="text-sm text-muted-foreground">{overdue.length} {copy('overdue documents','dokumen terlambat')}</p></dd></div></dl>
      <div class="space-y-2"><h4 class="text-sm font-semibold">{copy('Breakdown by due date','Rincian menurut jatuh tempo')}</h4><dl class="divide-y divide-border">{#each buckets as bucket(bucket)}{@const group=documents.filter(row=>row.bucket===bucket)}<div class="flex flex-wrap items-center justify-between gap-2 py-3"><dt class="text-sm">{bucketLabel(bucket)} <span class="text-muted-foreground">({group.length})</span></dt><dd><MoneyDisplay amount={sum(group)} {currency}/></dd></div>{/each}</dl></div>
     </Card.Content></Card.Root>
    {/each}
   </div></section>
  {/each}
  {#if !result.rows.length}<Card.Root><Card.Content class="space-y-3 pt-6"><h3 class="text-base font-semibold">{copy('No unpaid documents on this date','Tidak ada dokumen belum lunas pada tanggal ini')}</h3><p class="text-sm leading-relaxed text-muted-foreground">{copy('There are no outstanding issued invoices or supplier bills to show. Drafts are excluded. Choose another date to review an earlier balance.','Tidak ada invoice atau tagihan pemasok yang sudah diterbitkan dengan sisa pembayaran. Draf tidak disertakan. Pilih tanggal lain untuk meninjau saldo sebelumnya.')}</p><div class="flex flex-wrap gap-3"><Button href="/invoices" variant="outline">{copy('View invoices','Lihat invoice')}</Button><Button href="/business/payables" variant="outline">{copy('View supplier bills','Lihat tagihan pemasok')}</Button></div></Card.Content></Card.Root>{/if}
  {#if result.rows.length}
   <Card.Root><Card.Header><Card.Title>{copy('Documents to review','Dokumen untuk ditinjau')}</Card.Title><Card.Description>{copy('Start with overdue documents. Open an invoice to review customer payment details, or a supplier bill to plan your payment.','Mulai dari dokumen yang terlambat. Buka invoice untuk meninjau detail pembayaran pelanggan, atau tagihan pemasok untuk merencanakan pembayaran Anda.')}</Card.Description></Card.Header><Card.Content class="space-y-6">
    <div class="grid gap-4 sm:grid-cols-2"><Field.Field><Field.FieldLabel for="aging-side">{copy('Payment direction','Arah pembayaran')}</Field.FieldLabel><ChoiceSelect id="aging-side" bind:value={sideFilter} onValueChange={()=>rowPage=0} items={[{value:'',label:copy('All unpaid documents','Semua dokumen belum lunas')},{value:'receivable',label:copy('Customers owe you','Pelanggan berutang kepada Anda')},{value:'payable',label:copy('You owe suppliers','Anda berutang kepada pemasok')}]}/></Field.Field><Field.Field><Field.FieldLabel for="aging-bucket">{copy('Due-date group','Kelompok jatuh tempo')}</Field.FieldLabel><ChoiceSelect id="aging-bucket" bind:value={bucketFilter} onValueChange={()=>rowPage=0} items={[{value:'',label:copy('All due-date groups','Semua kelompok jatuh tempo')},...buckets.map(value=>({value,label:bucketLabel(value)}))]}/></Field.Field></div>
    <p class="text-sm text-muted-foreground" aria-live="polite">{visibleRows.length} {copy('matching documents. Filters affect this list; the summary and CSV include the full report.','dokumen yang cocok. Filter berlaku untuk daftar ini; ringkasan dan CSV memuat laporan lengkap.')}</p>
    <ul class="space-y-4 md:hidden">{#each pageRows as row(row.side+':'+row.id)}<li class="space-y-3 rounded-[20px] border-2 border-border p-4"><div class="space-y-1"><p class="text-sm text-muted-foreground">{row.side==='receivable'?copy('Customer invoice','Invoice pelanggan'):copy('Supplier bill','Tagihan pemasok')}</p><a class="inline-flex min-h-11 items-center rounded-[14px] font-semibold text-brand-ink underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-ring" href={documentUrl(row)}>{row.number||copy('Open document','Buka dokumen')}</a><p class="break-words text-sm">{row.name||copy('Name not recorded','Nama tidak tercatat')}</p></div><dl class="grid gap-3 sm:grid-cols-2"><div class="space-y-1"><dt class="text-sm text-muted-foreground">{copy('Still unpaid','Belum lunas')}</dt><dd><MoneyDisplay amount={row.outstanding} currency={row.currency} size="lg"/></dd></div><div class="space-y-1"><dt class="text-sm text-muted-foreground">{copy('Due date','Jatuh tempo')}</dt><dd class="text-sm">{formatDate(row.dueDate)}</dd></div></dl><p class="inline-flex rounded-full border border-border bg-muted px-3 py-1 text-sm font-semibold" class:text-[var(--expense-ink)]={row.daysOverdue>0}>{dueStatus(row)}</p></li>{/each}</ul>
    <div class="hidden overflow-x-auto md:block"><table class="w-full text-left text-sm"><caption class="pb-4 text-left text-sm text-muted-foreground">{copy('Remaining payments and overdue days as of ','Sisa pembayaran dan jumlah hari terlambat per ')}{formatDate(result.asOf)}</caption><thead><tr class="bg-muted/40"><th scope="col" class="p-4">{copy('Document','Dokumen')}</th><th scope="col" class="p-4">{copy('Customer / supplier','Pelanggan / pemasok')}</th><th scope="col" class="p-4">{copy('Due date','Jatuh tempo')}</th><th scope="col" class="p-4">{copy('Still unpaid','Belum lunas')}</th><th scope="col" class="p-4">{copy('Payment timing','Waktu pembayaran')}</th></tr></thead><tbody>{#each pageRows as row(row.side+':'+row.id)}<tr class="border-t border-border"><th scope="row" class="p-4 font-normal"><a class="inline-flex min-h-11 items-center rounded-[14px] font-semibold text-brand-ink underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-ring" href={documentUrl(row)}>{row.number||copy('Open document','Buka dokumen')}</a><p class="text-xs text-muted-foreground">{row.side==='receivable'?copy('Customer invoice','Invoice pelanggan'):copy('Supplier bill','Tagihan pemasok')}</p></th><td class="max-w-64 break-words p-4">{row.name||copy('Name not recorded','Nama tidak tercatat')}</td><td class="whitespace-nowrap p-4">{formatDate(row.dueDate)}</td><td class="p-4"><MoneyDisplay amount={row.outstanding} currency={row.currency}/></td><td class="p-4"><span class="inline-flex rounded-full border border-border bg-muted px-3 py-1 text-sm font-semibold" class:text-[var(--expense-ink)]={row.daysOverdue>0}>{dueStatus(row)}</span></td></tr>{/each}</tbody></table></div>
    {#if !visibleRows.length}<div class="space-y-3 rounded-[20px] border-2 border-border bg-muted/40 p-4"><p class="text-sm">{copy('No documents match these filters.','Tidak ada dokumen yang cocok dengan filter ini.')}</p><Button variant="outline" onclick={resetFilters}>{copy('Show all documents','Tampilkan semua dokumen')}</Button></div>{/if}
    <nav class="flex flex-wrap items-center justify-between gap-3" aria-label={copy('Outstanding document pages','Halaman dokumen belum lunas')}><Button variant="outline" disabled={rowPage===0} onclick={()=>rowPage--}>{copy('Previous','Sebelumnya')}</Button><span class="text-sm text-muted-foreground" aria-live="polite">{copy('Page ','Halaman ')}{rowPage+1} {copy('of ','dari ')}{pageCount}</span><Button variant="outline" disabled={(rowPage+1)*50>=visibleRows.length} onclick={()=>rowPage++}>{copy('Next','Berikutnya')}</Button></nav>
   </Card.Content></Card.Root>
  {/if}
  <Card.Root><Card.Header><Card.Title>{copy('How to read this report','Cara membaca laporan ini')}</Card.Title></Card.Header><Card.Content class="space-y-4 text-sm leading-relaxed"><ul class="list-disc space-y-3 pl-5"><li>{copy('“Not overdue” includes future due dates and documents due on the report date. Overdue days begin the day after the due date.','“Belum terlambat” mencakup tanggal jatuh tempo mendatang dan dokumen yang jatuh tempo pada tanggal laporan. Hari terlambat dihitung mulai sehari setelah jatuh tempo.')}</li><li>{copy('For example, a document due on 01-10-2026 is 5 days overdue on 06-10-2026. It belongs in the 1–30 days group.','Contoh: dokumen yang jatuh tempo pada 01-10-2026 terlambat 5 hari pada 06-10-2026. Dokumen tersebut masuk kelompok 1–30 hari.')}</li><li>{copy('Only issued documents with an unpaid balance are included. Drafts and documents already cancelled by the report date are excluded.','Hanya dokumen yang sudah diterbitkan dengan sisa pembayaran yang disertakan. Draf dan dokumen yang telah dibatalkan pada tanggal laporan tidak disertakan.')}</li><li>{copy('Partial payments reduce the remaining amount. Refunds and reversed payments can increase it again. Payments or corrections dated after the report date do not change that date’s balance.','Pembayaran sebagian mengurangi sisa tagihan. Pengembalian dana dan pembatalan pembayaran dapat menambahnya lagi. Pembayaran atau koreksi bertanggal setelah tanggal laporan tidak mengubah saldo pada tanggal tersebut.')}</li><li>{copy('This report lists payments still due. Use Accounting for the full financial statements, and Accounts for your available balances.','Laporan ini mencantumkan sisa pembayaran. Gunakan Akuntansi untuk laporan keuangan lengkap, dan Akun untuk melihat saldo yang tersedia.')}</li></ul></Card.Content></Card.Root>
 </div>
{/if}
