<script lang="ts">
  import { getContext } from 'svelte';import { AUTH_UI_CONTEXT,type AuthUiState } from '$lib/i18n/auth';import { financeText } from '$lib/i18n/finance';import { Button } from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import { Input } from '$lib/components/ui/input';
  type WorkspaceState={selectedId:string;ready:boolean};type Bill={id:string;billId:string;name:string;amount:string;currency:string;dueOn:string;status:string;overdue:boolean};const workspace=getContext<WorkspaceState>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof financeText>[1])=>financeText(ui.locale,key);
  let items:Bill[]=$state([]),loading=$state(true),error=$state(''),name=$state(''),amount=$state(''),dueOn=$state(''),frequency=$state<'once'|'week'|'month'|'year'>('month'),saving=$state(false),emailEnabled=$state(true),pushEnabled=$state(false),pushBusy=$state(false);
  async function load(){if(!workspace.ready||!workspace.selectedId)return;loading=true;try{const [r,p]=await Promise.all([fetch(`/api/workspaces/${workspace.selectedId}/bills`),fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`)]);if(!r.ok||!p.ok)throw new Error(t('error'));items=(await r.json()).items;const prefs=await p.json();emailEnabled=prefs.emailBillReminders;pushEnabled=prefs.pushBillReminders;}catch(e){error=e instanceof Error?e.message:t('error');}finally{loading=false;}}
  $effect(()=>{if(workspace.ready&&workspace.selectedId)void load();});
  async function create(event:SubmitEvent){event.preventDefault();if(saving)return;saving=true;error='';try{const r=await fetch(`/api/workspaces/${workspace.selectedId}/bills`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,amount,dueOn,frequency,reminderDays:[3,0]})});const b=await r.json();if(!r.ok)throw new Error(b.message);name='';amount='';await load();}catch(e){error=e instanceof Error?e.message:t('error');}finally{saving=false;}}
  async function action(item:Bill,action:'paid'|'skip'|'reopen'){if(action==='paid'&&!confirm(t('paymentNote')))return;const r=await fetch(`/api/workspaces/${workspace.selectedId}/bill-occurrences/${item.id}/${action}`,{method:'POST'});if(!r.ok){const body=await r.json();error=body.message??t('error');}await load();}
  async function archive(id:string){const r=await fetch(`/api/workspaces/${workspace.selectedId}/bills/${id}`,{method:'DELETE'});if(!r.ok)error=t('error');await load();}
  async function preference(){const next=!emailEnabled;const r=await fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({emailBillReminders:next})});if(r.ok)emailEnabled=next;else error=t('error');}
  function decodeKey(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/');const raw=atob(normalized+'='.repeat((4-normalized.length%4)%4));return Uint8Array.from(raw,(c)=>c.charCodeAt(0));}
  async function togglePush(){if(pushBusy)return;pushBusy=true;error='';try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Browser notifications are not supported here.');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(pushEnabled){if(subscription){const removed=await fetch(`/api/workspaces/${workspace.selectedId}/push-subscriptions`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({endpoint:subscription.endpoint})});if(!removed.ok)throw new Error(t('error'));await subscription.unsubscribe();}const saved=await fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({pushBillReminders:false})});if(!saved.ok)throw new Error(t('error'));pushEnabled=false;return;}const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Allow notifications in your browser to enable bill reminders.');const keyResponse=await fetch('/api/push/vapid-public-key');if(!keyResponse.ok)throw new Error((await keyResponse.json()).message??'Push reminders are not configured.');const {publicKey}=await keyResponse.json();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(publicKey)});const stored=await fetch(`/api/workspaces/${workspace.selectedId}/push-subscriptions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(subscription.toJSON())});if(!stored.ok)throw new Error((await stored.json()).message??t('error'));const saved=await fetch(`/api/workspaces/${workspace.selectedId}/notification-preferences`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({pushBillReminders:true})});if(!saved.ok)throw new Error((await saved.json()).message??t('error'));pushEnabled=true;}catch(e){error=e instanceof Error?e.message:t('error');}finally{pushBusy=false;}}
</script>
<svelte:head><title>CapyBudget · {t('bills')}</title></svelte:head>
<div class="page-head"><div><p class="eyebrow">Personal finance</p><h1>{t('bills')}</h1><p>Upcoming bills stay visible. Reminders never move money.</p></div></div>{#if error}<p class="error" role="alert">{error}</p>{/if}
<div class="grid"><Card.Root><Card.Header><Card.Title>{t('addBill')}</Card.Title><Card.Description>Recurring dates follow the original day of the month.</Card.Description></Card.Header><Card.Content><form onsubmit={create}><Field.FieldGroup><Field.Field><Field.FieldLabel for="bill-name">{t('name')}</Field.FieldLabel><Input id="bill-name" bind:value={name} maxlength={120} required /></Field.Field><Field.Field><Field.FieldLabel for="bill-amount">{t('amount')}</Field.FieldLabel><Input id="bill-amount" type="text" inputmode="decimal" bind:value={amount} required /></Field.Field><Field.Field><Field.FieldLabel for="bill-due">{t('dueOn')}</Field.FieldLabel><Input id="bill-due" type="date" bind:value={dueOn} required /></Field.Field><Field.Field><Field.FieldLabel for="bill-frequency">{t('recurrence')}</Field.FieldLabel><select id="bill-frequency" bind:value={frequency}><option value="once">{t('once')}</option><option value="week">{t('week')}</option><option value="month">{t('month')}</option><option value="year">{t('year')}</option></select></Field.Field></Field.FieldGroup><Button class="submit" type="submit" disabled={saving||!workspace.selectedId}>{saving?'…':t('addBill')}</Button></form><label class="preference"><input type="checkbox" checked={emailEnabled} onchange={preference}/> {t('emailReminders')}</label><label class="preference"><input type="checkbox" checked={pushEnabled} onchange={togglePush} disabled={pushBusy}/> {t('pushReminders')}{pushBusy?'…':''}</label></Card.Content></Card.Root>
<section class="list">{#if loading}<p>{t('loading')}</p>{:else if !items.length}<Card.Root><Card.Content><p>{t('emptyBills')}</p></Card.Content></Card.Root>{:else}{#each items as item (item.id)}<Card.Root><Card.Header><div class="title-row"><div><Card.Title>{item.name}</Card.Title><Card.Description>{item.overdue?t('overdue'):item.dueOn===new Date().toISOString().slice(0,10)?t('dueToday'):`${t('dueOnLabel')} ${item.dueOn}`}</Card.Description></div><strong class:overdue={item.overdue}>{item.currency} {item.amount}</strong></div></Card.Header><Card.Footer class="actions">{#if item.status==='unpaid'}<Button size="sm" onclick={()=>action(item,'paid')}>{t('paid')}</Button><Button size="sm" variant="outline" onclick={()=>action(item,'skip')}>{t('skip')}</Button>{:else}<span>{item.status==='paid'?t('paid'):t('skip')}</span><Button size="sm" variant="ghost" onclick={()=>action(item,'reopen')}>{t('reopen')}</Button>{/if}<Button size="sm" variant="ghost" onclick={()=>archive(item.billId)}>{t('archiveBill')}</Button></Card.Footer></Card.Root>{/each}{/if}</section></div>
<style>.page-head{margin-bottom:24px}.eyebrow{color:var(--muted-foreground);font-size:13px;margin:0 0 5px}h1{font:500 clamp(28px,4vw,38px) 'Fredoka Variable',sans-serif;margin:0}.page-head p:last-child{color:var(--muted-foreground);margin:8px 0 0}.grid{display:grid;grid-template-columns:minmax(250px,350px) minmax(0,1fr);gap:20px;align-items:start}.list{display:grid;gap:14px}.title-row{display:flex;justify-content:space-between;align-items:center;gap:12px}.title-row strong{font-size:18px;font-variant-numeric:tabular-nums}:global(.actions){display:flex;justify-content:flex-end;gap:8px}.overdue{color:var(--destructive)}:global(.submit){margin-top:18px;width:100%}.preference{display:flex;gap:8px;align-items:center;margin-top:16px;font-size:13px}select{width:100%;height:40px;border:1px solid var(--input);border-radius:var(--radius);background:var(--background);color:var(--foreground);padding:8px}.error{color:var(--destructive)}.grid :global([data-slot=field-group]){gap:14px}@media(max-width:760px){.grid{grid-template-columns:1fr}}
</style>
