import {Elysia} from 'elysia';import {randomUUID} from 'node:crypto';import Decimal from 'decimal.js';import {scope} from './routes';import {q,reject,text,uuid,recordAudit,csvCell} from './shared';import {isoDate} from '../tracking/routes';import {validPositiveAmount,currencyScale} from './money';
const Money=Decimal.clone({precision:50,rounding:Decimal.ROUND_HALF_UP});
function period(request:Request){const query=new URL(request.url).searchParams,from=isoDate(query.get('from')),through=isoDate(query.get('through'));if(through<from||Date.parse(through)-Date.parse(from)>3660*86400000)reject('Choose a date range of up to ten years.');return {from,through};}
export const businessAnalyticsRoutes=new Elysia({name:'business-analytics'})
.get('/api/workspaces/:workspaceId/business-aging',({request,params})=>scope(request,params.workspaceId,async(tx)=>{
 const asOf=isoDate(new URL(request.url).searchParams.get('asOf'));const rows=await q(tx,`with documents as (
 select i.id,'receivable' as side,i.number,i.recipient_snapshot->>'name' as name,i.due_date,i.currency,i.total-coalesce((select sum(p.amount) from invoice_payments p where p.workspace_id=i.workspace_id and p.invoice_id=i.id and p.paid_on<=$2::date and (p.reversal_effective_on is null or p.reversal_effective_on>$2::date)),0)+coalesce((select sum(r.amount) from payment_refunds r join invoice_payments ip on ip.workspace_id=r.workspace_id and ip.id=r.invoice_payment_id where r.workspace_id=i.workspace_id and ip.invoice_id=i.id and r.paid_on<=$2::date and (r.reversal_effective_on is null or r.reversal_effective_on>$2::date)),0) as outstanding
 from invoices i where i.workspace_id=$1 and i.issued_at is not null and i.issue_date<=$2::date and (i.state<>'void' or i.void_effective_on>$2::date)
 union all
 select b.id,'payable',b.supplier_number,b.vendor_snapshot->>'name',b.due_date,b.currency,b.total-coalesce((select sum(p.amount) from vendor_bill_payments p where p.workspace_id=b.workspace_id and p.bill_id=b.id and p.paid_on<=$2::date and (p.reversal_effective_on is null or p.reversal_effective_on>$2::date)),0)
 from vendor_bills b where b.workspace_id=$1 and b.issued_at is not null and b.issue_date<=$2::date and (b.state<>'void' or b.void_effective_on>$2::date)
 ) select id,side,number,name,due_date as "dueDate",currency,outstanding::text,$2::date-due_date as "daysOverdue",case when due_date>=$2::date then 'current' when $2::date-due_date<=30 then '1–30' when $2::date-due_date<=60 then '31–60' when $2::date-due_date<=90 then '61–90' else '90+' end as bucket from documents where outstanding>0 order by side,due_date,id limit 5001`,[params.workspaceId,asOf]);if(rows.length>5000)reject('Too many documents. Narrow this report or archive completed records.',422);
 const totals=new Map<string,any>();for(const row of rows){const key=row.side+':'+row.currency+':'+row.bucket;const old=totals.get(key);totals.set(key,{side:row.side,currency:row.currency,bucket:row.bucket,amount:new Money(old?.amount??'0').add(row.outstanding).toFixed(4)});}
 if(new URL(request.url).searchParams.get('format')==='csv')return new Response(['side,number,name,due_date,currency,outstanding,bucket',...rows.map(r=>[r.side,r.number,r.name,r.dueDate,r.currency,r.outstanding,r.bucket].map(csvCell).join(','))].join('\r\n'),{headers:{'content-type':'text/csv','content-disposition':'attachment; filename="capybudget-aging.csv"'}});return {asOf,rows,totals:[...totals.values()]};
},true))
.get('/api/workspaces/:workspaceId/business-tax/purchases',({request,params})=>scope(request,params.workspaceId,async tx=>{
 const {from,through}=period(request);const rows=await q(tx,`select b.id as "billId",b.supplier_number as number,b.issue_date as "issueDate",b.currency,l.description,l.net_amount::text as "netAmount",l.tax_amount::text as "taxAmount",l.total_amount::text as "totalAmount",l.tax_snapshot as "taxSnapshot" from vendor_bills b join vendor_bill_lines l on l.workspace_id=b.workspace_id and l.bill_id=b.id where b.workspace_id=$1 and b.issued_at is not null and b.issue_date between $2::date and $3::date and (b.state<>'void' or b.void_effective_on>$3::date) order by b.issue_date,b.id,l.position limit 5001`,[params.workspaceId,from,through]);if(rows.length>5000)reject('Narrow the purchase register date range.');return {rows,inputTaxCreditEligibility:'Not determined. Review the underlying tax invoice and local rules before claiming input credits.'};
},true))
.get('/api/workspaces/:workspaceId/business-tax/reminders',({request,params})=>scope(request,params.workspaceId,async tx=>({items:await q(tx,'select id,name,due_on as "dueOn",completed_at as "completedAt" from business_tax_reminders where workspace_id=$1 order by completed_at nulls first,due_on limit 100',[params.workspaceId])})))
.post('/api/workspaces/:workspaceId/business-tax/reminders',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{const b=await request.json() as any,id=randomUUID();await q(tx,'insert into business_tax_reminders(id,workspace_id,name,due_on,created_by) values($1,$2,$3,$4,$5)',[id,params.workspaceId,text(b.name,200,true),isoDate(b.dueOn),actor.id]);await recordAudit(tx,params.workspaceId,actor.id,id,'tax_reminder','created',{dueOn:b.dueOn});return {id};}))
.post('/api/workspaces/:workspaceId/business-tax/reminders/:id/complete',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{const [r]=await q(tx,'update business_tax_reminders set completed_at=now() where workspace_id=$1 and id=$2 and completed_at is null returning id',[params.workspaceId,uuid(params.id)]);if(!r)reject('Reminder unavailable.',404);await recordAudit(tx,params.workspaceId,actor.id,r.id,'tax_reminder','completed',{});return {completed:true};}))
.get('/api/workspaces/:workspaceId/projects',({request,params})=>scope(request,params.workspaceId,async tx=>({items:await q(tx,'select p.id,p.name,p.client_id as "clientId",c.name as "clientName" from business_projects p left join business_contacts c on c.workspace_id=p.workspace_id and c.id=p.client_id where p.workspace_id=$1 and p.archived_at is null order by lower(p.name),p.id limit 100',[params.workspaceId])})))
.post('/api/workspaces/:workspaceId/projects',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{const b=await request.json() as any,id=randomUUID();if(b.clientId){const [c]=await q(tx,"select id from business_contacts where workspace_id=$1 and id=$2 and kind in ('customer','both') and archived_at is null",[params.workspaceId,uuid(b.clientId)]);if(!c)reject('Choose an active customer.');}await q(tx,'insert into business_projects(id,workspace_id,name,client_id) values($1,$2,$3,$4)',[id,params.workspaceId,text(b.name,200,true),b.clientId||null]);await recordAudit(tx,params.workspaceId,actor.id,id,'project','created',{});return {id};}))
.delete('/api/workspaces/:workspaceId/projects/:id',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{const [saved]=await q(tx,'update business_projects set archived_at=now() where workspace_id=$1 and id=$2 and archived_at is null returning id',[params.workspaceId,uuid(params.id)]);if(!saved)reject('Project not found.',404);await recordAudit(tx,params.workspaceId,actor.id,saved.id,'project','archived',{});return {archived:true};}))
.get('/api/workspaces/:workspaceId/projects/:id/allocations',({request,params})=>scope(request,params.workspaceId,async tx=>({items:await q(tx,`select a.id,a.amount::text,a.currency,a.transaction_id as "transactionId",a.invoice_line_id as "invoiceLineId",coalesce(t.merchant,l.description,t.notes) as description from project_allocations a left join transactions t on t.workspace_id=a.workspace_id and t.id=a.transaction_id left join invoice_lines l on l.workspace_id=a.workspace_id and l.id=a.invoice_line_id where a.workspace_id=$1 and a.project_id=$2 order by a.created_at limit 500`,[params.workspaceId,uuid(params.id)])})))
.post('/api/workspaces/:workspaceId/projects/:id/allocations',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{
 const b=await request.json() as any,ws=params.workspaceId;const [project]=await q(tx,'select id from business_projects where workspace_id=$1 and id=$2 and archived_at is null',[ws,uuid(params.id)]);if(!project)reject('Project unavailable.');if(!!b.transactionId===!!b.invoiceLineId)reject('Choose one transaction or invoice line.');let source,currency,maximum;
 if(b.transactionId){[source]=await q(tx,"select * from transactions where workspace_id=$1 and id=$2 and type in ('income','expense') and deleted_at is null for update",[ws,uuid(b.transactionId)]);if(!source)reject('Choose an active income or expense.');if((await q(tx,'select id from payment_refunds where workspace_id=$1 and transaction_id=$2',[ws,source.id])).length)reject('Refunds reduce allocated invoice revenue automatically; do not allocate them as additional costs.');if((await q(tx,'select id from invoice_payments where workspace_id=$1 and transaction_id=$2',[ws,source.id])).length)reject('Allocate the invoice line instead of its receipt to avoid duplicate revenue.');currency=source.currency;maximum=String(source.amount);}
 else{[source]=await q(tx,"select l.*,i.currency from invoice_lines l join invoices i on i.workspace_id=l.workspace_id and i.id=l.invoice_id where l.workspace_id=$1 and l.id=$2 and i.state='issued' for update of l,i",[ws,uuid(b.invoiceLineId)]);if(!source)reject('Choose an issued invoice line.');currency=source.currency;maximum=String(source.net_amount);}
 if(!validPositiveAmount(b.amount,currencyScale(currency)))reject('Enter a positive allocation amount in the source currency.');const [allocated]=await q(tx,'select coalesce(sum(amount),0)::text as amount from project_allocations where workspace_id=$1 and project_id<>$2 and (($3::uuid is not null and transaction_id=$3) or ($4::uuid is not null and invoice_line_id=$4))',[ws,project.id,b.transactionId||null,b.invoiceLineId||null]);if(new Money(allocated.amount).add(b.amount).gt(maximum))reject('Combined project allocations cannot exceed the source amount.');
 const [saved]=b.transactionId?await q(tx,'insert into project_allocations(workspace_id,project_id,transaction_id,amount,currency) values($1,$2,$3,$4,$5) on conflict(project_id,transaction_id) do update set amount=excluded.amount returning id',[ws,project.id,b.transactionId,b.amount,currency]):await q(tx,'insert into project_allocations(workspace_id,project_id,invoice_line_id,amount,currency) values($1,$2,$3,$4,$5) on conflict(project_id,invoice_line_id) do update set amount=excluded.amount returning id',[ws,project.id,b.invoiceLineId,b.amount,currency]);await recordAudit(tx,ws,actor.id,saved.id,'project_allocation','saved',{amount:b.amount,currency});return {id:saved.id};
}))
.delete('/api/workspaces/:workspaceId/projects/:id/allocations/:allocationId',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{const [saved]=await q(tx,'delete from project_allocations where workspace_id=$1 and project_id=$2 and id=$3 returning id',[params.workspaceId,uuid(params.id),uuid(params.allocationId)]);if(!saved)reject('Allocation unavailable.',404);await recordAudit(tx,params.workspaceId,actor.id,saved.id,'project_allocation','removed',{});return {removed:true};}))
.get('/api/workspaces/:workspaceId/projects/:id/profitability',({request,params})=>scope(request,params.workspaceId,async tx=>{
 const {from,through}=period(request),ws=params.workspaceId,id=uuid(params.id);const [project]=await q(tx,'select id,name,client_id from business_projects where workspace_id=$1 and id=$2',[ws,id]);if(!project)reject('Project unavailable.',404);
 const movements=await q(tx,`select a.currency,t.type as kind,sum((case when t.type='income' then l.credit-l.debit else l.debit-l.credit end)*a.amount/t.amount)::text as amount
 from project_allocations a join transactions t on t.workspace_id=a.workspace_id and t.id=a.transaction_id join journal_entries e on e.workspace_id=t.workspace_id and e.transaction_id=t.id join journal_lines l on l.workspace_id=e.workspace_id and l.entry_id=e.id join ledger_accounts la on la.workspace_id=l.workspace_id and la.id=l.ledger_account_id and la.class=t.type
 where a.workspace_id=$1 and a.project_id=$2 and e.effective_date between $3::date and $4::date group by a.currency,t.type`,[ws,id,from,through]);
 const invoiceRevenue=await q(tx,`select a.currency,'income' as kind,sum(a.amount*p.amount/i.total*(case when p.paid_on between $3::date and $4::date then 1 else 0 end-case when p.reversal_effective_on between $3::date and $4::date then 1 else 0 end))::text as amount from project_allocations a join invoice_lines l on l.workspace_id=a.workspace_id and l.id=a.invoice_line_id join invoices i on i.workspace_id=l.workspace_id and i.id=l.invoice_id join invoice_payments p on p.workspace_id=i.workspace_id and p.invoice_id=i.id where a.workspace_id=$1 and a.project_id=$2 group by a.currency`,[ws,id,from,through]);
 const refundedRevenue=await q(tx,`select a.currency,'income' as kind,(-sum(a.amount*r.amount/i.total*(case when r.paid_on between $3::date and $4::date then 1 else 0 end-case when r.reversal_effective_on between $3::date and $4::date then 1 else 0 end)))::text as amount from project_allocations a join invoice_lines l on l.workspace_id=a.workspace_id and l.id=a.invoice_line_id join invoices i on i.workspace_id=l.workspace_id and i.id=l.invoice_id join invoice_payments p on p.workspace_id=i.workspace_id and p.invoice_id=i.id join payment_refunds r on r.workspace_id=p.workspace_id and r.invoice_payment_id=p.id where a.workspace_id=$1 and a.project_id=$2 group by a.currency`,[ws,id,from,through]);
 const grouped=new Map<string,{currency:string;income:Decimal;expense:Decimal}>();for(const row of [...movements,...invoiceRevenue,...refundedRevenue]){const current=grouped.get(row.currency)??{currency:row.currency,income:new Money(0),expense:new Money(0)};current[row.kind as 'income'|'expense']=current[row.kind as 'income'|'expense'].add(row.amount??'0');grouped.set(row.currency,current);}return {project,from,through,basis:'cash',policy:'Invoice revenue excludes sales tax. Transaction income and costs use their recorded cash amounts; purchase tax is included in costs. Unallocated entries are excluded. Reversals follow their effective dates. Currencies stay separate.',totals:[...grouped.values()].map(r=>({currency:r.currency,revenue:r.income.toFixed(4),cost:r.expense.toFixed(4),profit:r.income.sub(r.expense).toFixed(4),marginPercent:r.income.isZero()?null:r.income.sub(r.expense).div(r.income).mul(100).toFixed(4)}))};
},true));
