import {Elysia} from 'elysia';import {randomUUID,createHash} from 'node:crypto';import {scope} from './routes';import {q,text,uuid,reject,recordAudit} from './shared';import {protectedContact} from '../security/business-fields';
import {calculateInvoice,currencyScale,validPositiveAmount,addMoney,compareMoney} from './money';import {calculateTax} from './tax-money';import {isoDate,makeTransaction,assertUnlinkedBusinessTransaction} from '../tracking/routes';import {workspaceToday} from '../tracking/recurrence';
export async function vendorDetail(tx:Parameters<typeof q>[0],ws:string,id:string){const [bill]=await q(tx,'select * from vendor_bills where workspace_id=$1 and id=$2',[ws,uuid(id)]);if(!bill)reject('Vendor bill not found.',404);const [paid]=await q(tx,'select coalesce(sum(amount) filter(where reversed_at is null),0)::text as amount from vendor_bill_payments where workspace_id=$1 and bill_id=$2',[ws,id]);return {...bill,paidAmount:paid.amount,outstanding:addMoney(String(bill.total),'-'+paid.amount,bill.currency_scale),lines:await q(tx,'select * from vendor_bill_lines where workspace_id=$1 and bill_id=$2 order by position',[ws,id]),payments:await q(tx,'select id,amount::text,currency,paid_on as "paidOn",reversed_at as "reversedAt" from vendor_bill_payments where workspace_id=$1 and bill_id=$2 order by paid_on desc',[ws,id])};}
export const payableRoutes=new Elysia({name:'business-payables'})
.get('/api/workspaces/:workspaceId/vendor-bills',({request,params})=>scope(request,params.workspaceId,async tx=>({items:await q(tx,"select b.*,coalesce((select sum(p.amount) from vendor_bill_payments p where p.workspace_id=b.workspace_id and p.bill_id=b.id and p.reversed_at is null),0)::text as paid from vendor_bills b where b.workspace_id=$1 order by due_date,id limit 100",[params.workspaceId])})))
.get('/api/workspaces/:workspaceId/vendor-bills/:id',({request,params})=>scope(request,params.workspaceId,async tx=>({bill:await vendorDetail(tx,params.workspaceId,params.id)})))
.post('/api/workspaces/:workspaceId/vendor-bills',({request,params})=>scope(request,params.workspaceId,async(tx,actor,w)=>{
 return saveVendorBill(tx,params.workspaceId,actor,w,await request.json());
}))
.patch('/api/workspaces/:workspaceId/vendor-bills/:id',({request,params})=>scope(request,params.workspaceId,async(tx,actor,w)=>saveVendorBill(tx,params.workspaceId,actor,w,await request.json(),uuid(params.id))))
.post('/api/workspaces/:workspaceId/vendor-bills/:id/issue',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{const [saved]=await q(tx,"update vendor_bills set state='open',issued_at=now(),version=version+1 where workspace_id=$1 and id=$2 and state='draft' returning id",[params.workspaceId,uuid(params.id)]);if(!saved)reject('Only draft bills can be issued.',409);await recordAudit(tx,params.workspaceId,actor.id,saved.id,'vendor_bill','issued',{});return {bill:await vendorDetail(tx,params.workspaceId,saved.id)};}))
.post('/api/workspaces/:workspaceId/vendor-bills/:id/void',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{const b=await request.json() as any,reason=text(b.reason,1000,true);if(!isoDate(b.effectiveOn))reject('Enter the effective date.');const [bill]=await q(tx,'select * from vendor_bills where workspace_id=$1 and id=$2 for update',[params.workspaceId,uuid(params.id)]);if(!bill||bill.state==='void')reject('Bill unavailable.',409);const [paid]=await q(tx,'select count(*)::int as count from vendor_bill_payments where workspace_id=$1 and bill_id=$2 and reversed_at is null',[params.workspaceId,bill.id]);if(paid.count)reject('Reverse payments before voiding.',409);if(b.effectiveOn<bill.issue_date)reject('Void date cannot precede the bill.');await q(tx,"update vendor_bills set state='void',void_effective_on=$3,void_reason=$4,version=version+1 where workspace_id=$1 and id=$2",[params.workspaceId,bill.id,b.effectiveOn,reason]);await recordAudit(tx,params.workspaceId,actor.id,bill.id,'vendor_bill','voided',{effectiveOn:b.effectiveOn});return {voided:true};}))
.post('/api/workspaces/:workspaceId/vendor-bills/:id/payments',({request,params})=>scope(request,params.workspaceId,async(tx,actor,w)=>{
 const b=await request.json() as any,ws=params.workspaceId;const [bill]=await q(tx,"select * from vendor_bills where workspace_id=$1 and id=$2 and state='open' for update",[ws,uuid(params.id)]);if(!bill)reject('Choose an open bill.');if(!validPositiveAmount(b.amount,bill.currency_scale)||!isoDate(b.paidOn)||b.paidOn>workspaceToday(w.timezone)||b.paidOn<bill.issue_date)reject('Enter a positive payment and date between the bill date and today.');const key=text(b.idempotencyKey,200,true);if(key.length<8)reject('Provide a payment key.');const hash=createHash('sha256').update(JSON.stringify({billId:bill.id,amount:b.amount,paidOn:b.paidOn,accountId:b.accountId,categoryId:b.categoryId,transactionId:b.transactionId??null})).digest('hex');const [old]=await q(tx,'select id,request_hash from vendor_bill_payments where workspace_id=$1 and idempotency_key=$2',[ws,key]);if(old){if(old.request_hash!==hash)reject('Payment key belongs to another request.',409);return {id:old.id,replayed:true};}
 const current=await vendorDetail(tx,ws,bill.id);if(compareMoney(b.amount,current.outstanding,bill.currency_scale)>0)reject('Payment exceeds the remaining amount.');const [account]=await q(tx,'select currency from accounts where workspace_id=$1 and id=$2 and archived_at is null and deleted_at is null',[ws,uuid(b.accountId)]),[category]=await q(tx,"select id from categories where workspace_id=$1 and id=$2 and type='expense' and archived_at is null",[ws,uuid(b.categoryId)]);if(!account||account.currency!==bill.currency||!category)reject('Choose a same-currency account and expense category.');
 let transactionId;if(b.transactionId){await assertUnlinkedBusinessTransaction(tx,ws,uuid(b.transactionId));const [t]=await q(tx,"select * from transactions where workspace_id=$1 and id=$2 and type='expense' and deleted_at is null for update",[ws,uuid(b.transactionId)]);if(!t||t.currency!==bill.currency||t.account_id!==b.accountId||t.category_id!==b.categoryId||t.occurred_at!==b.paidOn||compareMoney(String(t.amount),b.amount,bill.currency_scale)!==0)reject('Match an expense with the same amount, date, account and category.');if((await q(tx,'select id from vendor_bill_payments where workspace_id=$1 and transaction_id=$2',[ws,t.id])).length)reject('This expense is already linked.',409);transactionId=t.id;}else transactionId=(await makeTransaction(tx,ws,actor,{type:'expense',accountId:b.accountId,categoryId:b.categoryId,amount:b.amount,date:b.paidOn,merchant:bill.vendor_snapshot.name,notes:'Vendor bill '+bill.supplier_number})).id;
 const id=randomUUID();await q(tx,'insert into vendor_bill_payments(id,workspace_id,bill_id,transaction_id,amount,currency,paid_on,idempotency_key,request_hash,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,ws,bill.id,transactionId,b.amount,bill.currency,b.paidOn,key,hash,actor.id]);await recordAudit(tx,ws,actor.id,bill.id,'vendor_bill','paid',{paymentId:id,amount:b.amount,currency:bill.currency});return {bill:await vendorDetail(tx,ws,bill.id)};
}))
.post('/api/workspaces/:workspaceId/vendor-bills/:id/payments/:paymentId/reverse',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{
 const b=await request.json() as any,reason=text(b.reason,1000,true),ws=params.workspaceId;if(!isoDate(b.effectiveOn))reject('Enter a valid correction date.');await q(tx,'select id from vendor_bills where workspace_id=$1 and id=$2 for update',[ws,uuid(params.id)]);const [payment]=await q(tx,'select * from vendor_bill_payments where workspace_id=$1 and bill_id=$2 and id=$3 for update',[ws,params.id,uuid(params.paymentId)]);if(!payment||payment.reversed_at)reject('Payment is unavailable or already reversed.',409);if(b.effectiveOn<payment.paid_on)reject('Correction date cannot precede the payment.');
 const [original]=await q(tx,'select id from journal_entries j where workspace_id=$1 and transaction_id=$2 and not exists(select 1 from journal_entries r where r.reverses_entry_id=j.id) order by created_at desc limit 1 for update',[ws,payment.transaction_id]);if(!original)reject('Payment journal unavailable.',409);const lines=await q(tx,'select * from journal_lines where workspace_id=$1 and entry_id=$2',[ws,original.id]),id=randomUUID();await q(tx,"insert into journal_entries(id,workspace_id,transaction_id,effective_date,reason,reverses_entry_id,created_by) values($1,$2,$3,$4,'vendor_payment_reversal',$5,$6)",[id,ws,payment.transaction_id,b.effectiveOn,original.id,actor.id]);for(const line of lines)await q(tx,'insert into journal_lines(workspace_id,entry_id,ledger_account_id,debit,credit,currency,base_debit,base_credit) values($1,$2,$3,$4,$5,$6,$7,$8)',[ws,id,line.ledger_account_id,line.credit,line.debit,line.currency,line.base_credit,line.base_debit]);await q(tx,'update transactions set deleted_at=now(),deleted_by=$3,version=version+1,updated_at=now() where workspace_id=$1 and id=$2',[ws,payment.transaction_id,actor.id]);await q(tx,'update vendor_bill_payments set reversed_at=now(),reversal_effective_on=$3,reversal_reason=$4 where workspace_id=$1 and id=$2',[ws,payment.id,b.effectiveOn,reason]);await recordAudit(tx,ws,actor.id,params.id,'vendor_bill','payment_reversed',{paymentId:payment.id,effectiveOn:b.effectiveOn});return {reversed:true};
}));

async function saveVendorBill(tx:Parameters<typeof q>[0],ws:string,actor:{id:string;name:string;email:string},w:any,b:any,existingId?:string){
if(!isoDate(b.issueDate)||!isoDate(b.dueDate)||b.dueDate<b.issueDate||!Array.isArray(b.lines))reject('Enter valid dates and bill lines.');
 const [vendor]=await q(tx,"select * from business_contacts where workspace_id=$1 and id=$2 and kind in ('vendor','both') and archived_at is null",[ws,uuid(b.vendorId)]);if(!vendor)reject('Choose an active vendor.');const currency=b.currency??w.currency;if(typeof currency!=='string'||!/^[A-Z]{3}$/.test(currency))reject('Choose a currency.');const number=text(b.supplierNumber,100,true);
 const policies:any[]=[];for(const line of b.lines){let policy=null;if(line.taxRateId){const [enabled]=await q(tx,'select enabled from business_tax_settings where workspace_id=$1',[ws]);if(!enabled?.enabled)reject('Enable business tax before applying purchase tax.');const [rate]=await q(tx,'select * from business_tax_rates where workspace_id=$1 and id=$2 and archived_at is null and effective_from<=$3::date and (effective_to is null or effective_to>=$3::date)',[ws,uuid(line.taxRateId),b.issueDate]);if(!rate)reject('Choose a tax rate applicable to the bill date.');policy={rate:rate.statutory_rate,baseNumerator:rate.base_numerator,baseDenominator:rate.base_denominator,inclusive:rate.inclusive,name:rate.name,applicability:rate.applicability,effectiveFrom:rate.effective_from,effectiveTo:rate.effective_to};}else if(Number(line.taxRate??'0')>0){reject('Select a saved dated tax rate for purchase tax.');}policies.push(policy);}
 let calculated;try{calculated=calculateInvoice(b.lines.map((l:any,i:number)=>({...l,taxRate:policies[i]?calculateTax('0',currency,policies[i]).effectiveRate:'0',taxPolicy:policies[i]??undefined})),currency);}catch(e){reject(e instanceof Error?e.message:'Enter valid bill amounts.');}
 const id=existingId??randomUUID();
 if(existingId){const [current]=await q(tx,"select version from vendor_bills where workspace_id=$1 and id=$2 and state='draft' for update",[ws,id]);if(!current||current.version!==b.version)reject('Draft changed. Reload before editing.',409);await q(tx,'delete from vendor_bill_lines where workspace_id=$1 and bill_id=$2',[ws,id]);await q(tx,'update vendor_bills set vendor_id=$3,vendor_snapshot=$4::jsonb,supplier_number=$5,issue_date=$6,due_date=$7,currency=$8,currency_scale=$9,subtotal=$10,discount_total=$11,tax_total=$12,total=$13,version=version+1 where workspace_id=$1 and id=$2',[ws,id,vendor.id,protectedContact({...vendor.details,name:vendor.name},ws,id,'vendor_snapshot'),number,b.issueDate,b.dueDate,currency,currencyScale(currency),calculated.subtotal,calculated.discountTotal,calculated.taxTotal,calculated.total]);}
 else await q(tx,'insert into vendor_bills(id,workspace_id,vendor_id,vendor_snapshot,supplier_number,issue_date,due_date,currency,currency_scale,subtotal,discount_total,tax_total,total,created_by) values($1,$2,$3,$4::jsonb,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)',[id,ws,vendor.id,protectedContact({...vendor.details,name:vendor.name},ws,id,'vendor_snapshot'),number,b.issueDate,b.dueDate,currency,currencyScale(currency),calculated.subtotal,calculated.discountTotal,calculated.taxTotal,calculated.total,actor.id]);
 for(let i=0;i<calculated.lines.length;i++){const l=calculated.lines[i]!;await q(tx,'insert into vendor_bill_lines(workspace_id,bill_id,position,description,quantity,unit_price,discount_amount,tax_rate,net_amount,tax_amount,total_amount,tax_snapshot) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb)',[ws,id,i,l.description,l.quantity,l.unitPrice,l.discountAmount,l.taxRate,l.netAmount,l.taxAmount,l.totalAmount,policies[i]?JSON.stringify(policies[i]):null]);}await recordAudit(tx,ws,actor.id,id,'vendor_bill',existingId?'draft_updated':'draft_created',{total:calculated.total,currency});return {bill:await vendorDetail(tx,ws,id)};
}
