import {Elysia} from 'elysia';import {randomUUID,createHash} from 'node:crypto';import {scope} from './routes';import {q,reject,text,uuid,recordAudit} from './shared';import {makeTransaction,isoDate,assertUnlinkedBusinessTransaction} from '../tracking/routes';import {workspaceToday} from '../tracking/recurrence';import {addMoney,compareMoney,validPositiveAmount} from './money';
export const paymentAdjustmentRoutes=new Elysia({name:'payment-adjustments'})
.get('/api/workspaces/:workspaceId/payment-requests/:id/adjustments',({request,params})=>scope(request,params.workspaceId,async tx=>({refunds:await q(tx,'select id,amount::text,currency,paid_on as "paidOn",kind,reversed_at as "reversedAt" from payment_refunds where workspace_id=$1 and request_id=$2 order by paid_on',[params.workspaceId,uuid(params.id)]),fees:await q(tx,'select id,amount::text,currency,paid_on as "paidOn",reversed_at as "reversedAt" from payment_request_fees where workspace_id=$1 and request_id=$2 order by paid_on',[params.workspaceId,params.id])})))
.post('/api/workspaces/:workspaceId/payment-requests/:id/unapplied',({request,params})=>scope(request,params.workspaceId,async(tx,actor,w)=>{
 const b=await request.json() as any,ws=params.workspaceId;const [p]=await q(tx,"select * from payment_requests where workspace_id=$1 and id=$2 and state='reconciliation' for update",[ws,uuid(params.id)]);if(!p||p.payment_id||!['SUCCESS','REFUNDED'].includes(p.provider_status?.status)||b.confirm!==true)reject('Confirm the verified, unapplied funds after checking the bank statement.');if(p.unapplied_transaction_id)return {id:p.unapplied_transaction_id,replayed:true};const date=isoDate(b.paidOn);if(date>workspaceToday(w.timezone))reject('Received date cannot be in the future.');let id;
 if(b.transactionId){await assertUnlinkedBusinessTransaction(tx,ws,uuid(b.transactionId));const [t]=await q(tx,"select * from transactions where workspace_id=$1 and id=$2 and type='income' and deleted_at is null for update",[ws,b.transactionId]);if(!t||t.account_id!==p.account_id||t.currency!==p.currency||t.occurred_at!==date||compareMoney(String(t.amount),String(p.amount),0)!==0)reject('Match the same received amount, currency, date and account.');id=t.id;}
 else id=(await makeTransaction(tx,ws,actor,{type:'income',accountId:p.account_id,categoryId:p.category_id,amount:addMoney(String(p.amount),'0',0),date,merchant:'Unapplied Payment gateway funds',notes:'Unapplied payment '+p.provider_reference+'; not allocated to an invoice.'})).id;
 await q(tx,"update payment_requests set unapplied_transaction_id=$3,failure_code='UNAPPLIED_FUNDS_REVIEW_REQUIRED' where workspace_id=$1 and id=$2",[ws,p.id,id]);await recordAudit(tx,ws,actor.id,p.id,'payment_request','unapplied_funds_recorded',{transactionId:id,amount:String(p.amount)});return {id};
}))
.post('/api/workspaces/:workspaceId/payment-requests/:id/refunds',({request,params})=>scope(request,params.workspaceId,async(tx,actor,w)=>{return recordPaymentAdjustment(tx,params.workspaceId,actor,w,uuid(params.id),await request.json(),true);}))
.post('/api/workspaces/:workspaceId/payment-requests/:id/fees',({request,params})=>scope(request,params.workspaceId,async(tx,actor,w)=>{return recordPaymentAdjustment(tx,params.workspaceId,actor,w,uuid(params.id),await request.json(),false);}))
.post('/api/workspaces/:workspaceId/payment-requests/:id/adjustments/:adjustmentId/reverse',({request,params})=>scope(request,params.workspaceId,async(tx,actor,w)=>reverseAdjustment(tx,params.workspaceId,actor,w,uuid(params.id),uuid(params.adjustmentId),await request.json())));
export async function recordPaymentAdjustment(tx:Parameters<typeof q>[0],ws:string,actor:{id:string;name:string},w:any,id:string,b:any,refund:boolean){
 const [p]=await q(tx,'select * from payment_requests where workspace_id=$1 and id=$2 for update',[ws,id]);if(!p||(!p.payment_id&&!p.unapplied_transaction_id))reject('Resolve the received funds before recording a refund or fee.',409);if(b.confirm!==true||!validPositiveAmount(b.amount,0)||!['refund','chargeback'].includes(b.kind??'refund'))reject('Confirm the actual bank movement and a positive whole-rupiah amount.');const date=isoDate(b.paidOn);if(date>workspaceToday(w.timezone))reject('Date cannot be in the future.');const key=text(b.idempotencyKey,200,true),reason=text(b.reason,1000,true),table=refund?'payment_refunds':'payment_request_fees';if(key.length<8)reject('Provide an adjustment key.');const hash=createHash('sha256').update(JSON.stringify({id,amount:b.amount,date,categoryId:b.categoryId,kind:b.kind??'refund',reason,transactionId:b.transactionId??null})).digest('hex');const [old]=await q(tx,`select id,request_hash from ${table} where workspace_id=$1 and idempotency_key=$2`,[ws,key]);if(old){if(old.request_hash!==hash)reject('Adjustment key belongs to another request.',409);return {id:old.id,replayed:true};}
 if(p.payment_id){await q(tx,'select i.id from invoices i join invoice_payments ip on ip.workspace_id=i.workspace_id and ip.invoice_id=i.id where ip.workspace_id=$1 and ip.id=$2 for update of i',[ws,p.payment_id]);}
 if(refund&&p.unapplied_transaction_id){const [income]=await q(tx,'select occurred_at,deleted_at from transactions where workspace_id=$1 and id=$2',[ws,p.unapplied_transaction_id]);if(!income||income.deleted_at||date<income.occurred_at)reject('Refund date cannot precede the active received funds.');}
 if(refund){const [already]=await q(tx,'select coalesce(sum(amount),0)::text as amount from payment_refunds where workspace_id=$1 and request_id=$2 and reversed_at is null',[ws,id]);if(compareMoney(addMoney(already.amount,b.amount,0),String(p.amount),0)>0)reject('Refunds and chargebacks cannot exceed received funds.');if(p.payment_id){const [receipt]=await q(tx,'select reversed_at,paid_on from invoice_payments where workspace_id=$1 and id=$2 for update',[ws,p.payment_id]);if(receipt.reversed_at)reject('This receipt was reversed; review before refunding again.');if(date<receipt.paid_on)reject('Refund date cannot precede receipt date.');}}
 const categoryId=uuid(b.categoryId);const [category]=await q(tx,"select id from categories where workspace_id=$1 and id=$2 and type='expense' and archived_at is null",[ws,categoryId]);if(!category)reject('Choose an active expense category.');let transactionId;
 if(b.transactionId){await assertUnlinkedBusinessTransaction(tx,ws,uuid(b.transactionId));const [t]=await q(tx,"select * from transactions where workspace_id=$1 and id=$2 and type='expense' and deleted_at is null for update",[ws,b.transactionId]);if(!t||t.account_id!==p.account_id||t.category_id!==categoryId||t.currency!=='IDR'||t.occurred_at!==date||compareMoney(String(t.amount),b.amount,0)!==0)reject('Match an expense with the same amount, currency, date, account and category.');transactionId=t.id;}
 else transactionId=(await makeTransaction(tx,ws,actor,{type:'expense',accountId:p.account_id,categoryId,amount:b.amount,date,merchant:refund?'Payment gateway '+(b.kind??'refund'):'Payment gateway fee',notes:reason})).id;
 const keyId=randomUUID();if(refund){await q(tx,'insert into payment_refunds(id,workspace_id,request_id,invoice_payment_id,transaction_id,amount,currency,paid_on,kind,reason,idempotency_key,request_hash,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[keyId,ws,id,p.payment_id,transactionId,b.amount,'IDR',date,b.kind??'refund',reason,key,hash,actor.id]);if(p.payment_id)await q(tx,'update invoice_payments set refunded_amount=refunded_amount+$3 where workspace_id=$1 and id=$2',[ws,p.payment_id,b.amount]);const [total]=await q(tx,'select coalesce(sum(amount),0)::text as amount from payment_refunds where workspace_id=$1 and request_id=$2 and reversed_at is null',[ws,id]);await q(tx,"update payment_requests set state=$3,failure_code=null,updated_at=now() where workspace_id=$1 and id=$2",[ws,id,compareMoney(total.amount,String(p.amount),0)===0?'refunded':'partially_refunded']);}
 else await q(tx,'insert into payment_request_fees(id,workspace_id,request_id,transaction_id,amount,currency,paid_on,idempotency_key,request_hash,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[keyId,ws,id,transactionId,b.amount,'IDR',date,key,hash,actor.id]);
 await recordAudit(tx,ws,actor.id,id,'payment_request',refund?'refund_recorded':'fee_recorded',{amount:b.amount,transactionId,matched:!!b.transactionId});return {id:keyId};
}

async function reverseAdjustment(tx:Parameters<typeof q>[0],ws:string,actor:{id:string},w:any,requestId:string,id:string,b:any){
 const date=isoDate(b.effectiveOn),reason=text(b.reason,1000,true);if(b.confirm!==true||date>workspaceToday(w.timezone))reject('Confirm the correction and a date no later than today.');
 const [p]=await q(tx,'select * from payment_requests where workspace_id=$1 and id=$2 for update',[ws,requestId]);if(!p)reject('Payment request unavailable.',404);
 if(p.payment_id)await q(tx,'select i.id from invoices i join invoice_payments ip on ip.workspace_id=i.workspace_id and ip.invoice_id=i.id where ip.workspace_id=$1 and ip.id=$2 for update of i',[ws,p.payment_id]);
 let table='payment_refunds';let [adjustment]=await q(tx,'select * from payment_refunds where workspace_id=$1 and request_id=$2 and id=$3 for update',[ws,requestId,id]);
 if(!adjustment){table='payment_request_fees';[adjustment]=await q(tx,'select * from payment_request_fees where workspace_id=$1 and request_id=$2 and id=$3 for update',[ws,requestId,id]);}
 if(!adjustment)reject('Adjustment unavailable.',404);if(adjustment.reversed_at)return {reversed:true,replayed:true};if(date<adjustment.paid_on)reject('Correction date cannot precede the bank movement.');
 const [original]=await q(tx,'select id from journal_entries where workspace_id=$1 and transaction_id=$2 and reverses_entry_id is null for update',[ws,adjustment.transaction_id]);if(!original)reject('Adjustment journal unavailable.',409);
 if((await q(tx,'select id from journal_entries where reverses_entry_id=$1',[original.id])).length)reject('The journal was already corrected; review before proceeding.',409);
 const lines=await q(tx,'select * from journal_lines where workspace_id=$1 and entry_id=$2',[ws,original.id]),entryId=randomUUID();
 await q(tx,"insert into journal_entries(id,workspace_id,transaction_id,effective_date,reason,reverses_entry_id,created_by) values($1,$2,$3,$4,'payment_adjustment_reversal',$5,$6)",[entryId,ws,adjustment.transaction_id,date,original.id,actor.id]);
 for(const l of lines)await q(tx,'insert into journal_lines(workspace_id,entry_id,ledger_account_id,debit,credit,currency,base_debit,base_credit) values($1,$2,$3,$4,$5,$6,$7,$8)',[ws,entryId,l.ledger_account_id,l.credit,l.debit,l.currency,l.base_credit,l.base_debit]);
 await q(tx,'update transactions set deleted_at=now(),deleted_by=$3,version=version+1,updated_at=now() where workspace_id=$1 and id=$2',[ws,adjustment.transaction_id,actor.id]);
 await q(tx,`update ${table} set reversed_at=now(),reversal_effective_on=$3,reversal_reason=$4 where workspace_id=$1 and id=$2`,[ws,id,date,reason]);
 if(table==='payment_refunds'){
  if(p.payment_id)await q(tx,'update invoice_payments set refunded_amount=refunded_amount-$3 where workspace_id=$1 and id=$2',[ws,p.payment_id,adjustment.amount]);
  const [remaining]=await q(tx,'select coalesce(sum(amount),0)::text as amount from payment_refunds where workspace_id=$1 and request_id=$2 and reversed_at is null',[ws,requestId]);
  await q(tx,'update payment_requests set state=$3,updated_at=now() where workspace_id=$1 and id=$2',[ws,requestId,compareMoney(remaining.amount,'0',0)===0?(p.payment_id?'paid':'reconciliation'):'partially_refunded']);
 }
 await recordAudit(tx,ws,actor.id,id,'payment_adjustment','reversed',{effectiveOn:date,reason});return {reversed:true};
}
