import { formatDate } from '../../../../shared/dates';
import { chromium } from 'playwright';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Doc={number?:string|null;state:string;issueDate:string;dueDate:string;currency:string;currencyScale:number;sellerSnapshot:any;recipientSnapshot:any;notes?:string|null;paymentInstructions?:string|null;subtotal:string;discountTotal:string;taxTotal:string;total:string;locale:'en'|'id'};
type Line={description:string;quantity:string;unitPrice:string;discountAmount:string;taxRate:string;netAmount:string;taxAmount:string;totalAmount:string};
export async function renderInvoicePdf(invoice:Doc,lines:Line[]):Promise<Uint8Array>{
 const en=invoice.locale==='en',label=(a:string,b:string)=>en?a:b,seller=invoice.sellerSnapshot??{},recipient=invoice.recipientSnapshot??{};
 const money=(v:string)=>new Intl.NumberFormat(en?'en-US':'id-ID',{style:'currency',currency:invoice.currency,minimumFractionDigits:invoice.currencyScale,maximumFractionDigits:invoice.currencyScale}).format(Number(v));
 const address=(a:any)=>[a?.street,a?.city,a?.region,a?.postalCode,a?.country].filter(Boolean).map(escape).join('<br>');
 const rows=lines.map(x=>'<tr><td>'+escape(x.description)+'</td><td class="num">'+escape(x.quantity)+'</td><td class="num">'+money(x.unitPrice)+'</td><td class="num">'+money(x.discountAmount)+'</td><td class="num">'+escape(x.taxRate)+'%</td><td class="num">'+money(x.totalAmount)+'</td></tr>').join('');
 const heading=label('INVOICE','FAKTUR'),draft=label('DRAFT PREVIEW','PRATINJAU DRAF');
 const html='<!doctype html><html lang="'+invoice.locale+'"><meta charset="utf-8"><style>'+
 '*{box-sizing:border-box}body{font:12px Arial,sans-serif;color:#30251d;margin:0}.page{padding:44px 48px}.top{display:flex;justify-content:space-between;border-bottom:3px solid #b98b5e;padding-bottom:22px}.title{font-size:30px;color:#8a5f3a;margin:4px 0 12px}.muted{color:#73675d;line-height:1.6}.brand{font-size:19px;font-weight:bold}.logo{display:block;max-width:140px;max-height:56px;object-fit:contain;margin-bottom:10px}.num{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.dates{display:flex;gap:28px;margin:22px 0}.billto{margin:28px 0 18px}.billto h2{font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#8a5f3a}table{width:100%;border-collapse:collapse;margin-top:16px}thead{display:table-header-group}th{background:#f3e6cf;color:#563a27;text-align:left;font-size:10px;text-transform:uppercase;padding:10px 7px}td{padding:10px 7px;border-bottom:1px solid #e6d5b8;vertical-align:top}.totals{margin:18px 0 0 auto;width:280px}.grand td{font-size:17px;font-weight:bold;color:#563a27;border-top:2px solid #b98b5e;padding-top:12px}.notes{margin-top:30px;white-space:pre-wrap}footer{margin-top:34px;padding-top:10px;border-top:1px solid #e6d5b8;color:#73675d;font-size:10px}.draft{position:fixed;top:46%;left:12%;font-size:68px;font-weight:bold;color:#eee2d2;transform:rotate(-24deg);z-index:-1}'+
 '</style><body><main class="page">'+(invoice.state==='draft'?'<div class="draft">'+draft+'</div>':'')+
 '<header class="top"><section>'+(seller.logoDataUri?'<img class="logo" alt="" src="'+escape(seller.logoDataUri)+'">':'')+'<div class="brand">'+escape(seller.tradingName||seller.legalName||'Business')+'</div><div class="muted">'+address(seller.address)+'<br>'+escape(seller.contactEmail)+'<br>'+escape(seller.phone)+'</div></section><section style="text-align:right"><h1 class="title">'+heading+'</h1><strong>'+escape(invoice.number||draft)+'</strong></section></header>'+
 '<div class="dates"><div><span class="muted">'+label('Issue date','Tanggal')+'</span><br><strong>'+escape(formatDate(invoice.issueDate))+'</strong></div><div><span class="muted">'+label('Due date','Jatuh tempo')+'</span><br><strong>'+escape(formatDate(invoice.dueDate))+'</strong></div></div>'+
 '<section class="billto"><h2>'+label('Bill to','Ditagihkan kepada')+'</h2><strong>'+escape(recipient.name)+'</strong><div class="muted">'+address(recipient.address)+'<br>'+escape(recipient.email)+'<br>'+escape(recipient.phone)+'</div></section>'+
 '<table><thead><tr><th>'+label('Description','Deskripsi')+'</th><th class="num">'+label('Qty','Jumlah')+'</th><th class="num">'+label('Unit price','Harga')+'</th><th class="num">'+label('Discount','Diskon')+'</th><th class="num">'+label('Tax','Pajak')+'</th><th class="num">'+label('Total','Total')+'</th></tr></thead><tbody>'+rows+'</tbody></table>'+
 '<table class="totals"><tbody><tr><td>'+label('Subtotal','Subtotal')+'</td><td class="num">'+money(invoice.subtotal)+'</td></tr><tr><td>'+label('Discount','Diskon')+'</td><td class="num">−'+money(invoice.discountTotal)+'</td></tr><tr><td>'+label('Tax','Pajak')+'</td><td class="num">'+money(invoice.taxTotal)+'</td></tr><tr class="grand"><td>'+label('Total','Total')+'</td><td class="num">'+money(invoice.total)+'</td></tr></tbody></table>'+
 (invoice.notes?'<section class="notes"><strong>'+label('Notes','Catatan')+'</strong><br>'+escape(invoice.notes)+'</section>':'')+(invoice.paymentInstructions?'<section class="notes"><strong>'+label('Payment instructions','Instruksi pembayaran')+'</strong><br>'+escape(invoice.paymentInstructions)+'</section>':'')+'<footer>'+escape(seller.legalName||'')+' · '+escape(invoice.currency)+'</footer></main></body></html>';
 const browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 try{const page=await browser.newPage({locale:en?'en-US':'id-ID'});await page.route('**/*',route=>{const url=route.request().url();return url.startsWith('data:')||url.startsWith('about:')?route.continue():route.abort();});await page.setContent(html,{waitUntil:'load',timeout:10000});return await page.pdf({format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'14mm',bottom:'15mm',left:'14mm'}});}
 finally{await browser.close();}
}
