import {createHash,randomUUID} from 'node:crypto';import type {TransactionSql} from 'postgres';
import {q,reject,uuid,recordAudit} from './shared';import {validPositiveAmount,compareMoney,addMoney} from './money';import {makeTransaction,isoDate,assertUnlinkedBusinessTransaction} from '../tracking/routes';import {protectedText} from '../security/business-fields';import {workspaceToday} from '../tracking/recurrence';
export type ReceiptInput={invoiceId:string;amount:string;paidOn:string;accountId:string;categoryId:string;reference?:string|null;idempotencyKey:string;existingTransactionId?:string;checkExistingIncome?:boolean};
/** Caller must authorize the actor. The invoice lock serializes manual and provider receipts. */
export async function recordInvoiceReceipt(tx:TransactionSql,ws:string,actor:{id:string;name:string},input:ReceiptInput){
 const [inv]=await q(tx,'select * from invoices where workspace_id=$1 and id=$2 and archived_at is null for update',[ws,uuid(input.invoiceId)]);if(!inv)reject('Invoice not found.',404);
 const scale=Number(inv.currency_scale);if(!validPositiveAmount(input.amount,scale)||!isoDate(input.paidOn)||typeof input.idempotencyKey!=='string'||input.idempotencyKey.length<8||input.idempotencyKey.length>200)reject('Enter a positive amount, valid payment date, and payment key.');
 const amount=addMoney(input.amount,'0',scale),[w]=await q(tx,'select timezone from workspaces where id=$1',[ws]);if(input.paidOn>workspaceToday(w.timezone))reject('Payment date cannot be in the future.');
 const reference=input.reference??null;if(reference!==null&&(typeof reference!=='string'||reference.length>300))reject('Payment reference is too long.');
 const hash=createHash('sha256').update(JSON.stringify({...input,amount,reference})).digest('hex');
 const [old]=await q(tx,"select request_hash,resource_id from idempotency_keys where workspace_id=$1 and actor_key=$2 and operation='invoice_payment' and key=$3",[ws,actor.id,input.idempotencyKey]);
 if(old){if(old.request_hash!==hash)reject('This key belongs to another payment.',409,'IDEMPOTENCY_CONFLICT');if(!old.resource_id)reject('Payment is pending.',409);return {payment:(await q(tx,'select id,amount::text,currency,paid_on as "paidOn",transaction_id as "transactionId" from invoice_payments where workspace_id=$1 and id=$2',[ws,old.resource_id]))[0],replayed:true};}
 if(inv.state!=='issued')reject('Payments require an issued invoice.',409);if(input.paidOn<inv.issue_date)reject('Payment date cannot precede the invoice date.');
 const [balance]=await q(tx,'select coalesce(sum(amount-refunded_amount) filter(where reversed_at is null),0)::text as paid from invoice_payments where workspace_id=$1 and invoice_id=$2',[ws,inv.id]);
 if(compareMoney(balance.paid,String(inv.total),scale)>=0||compareMoney(amount,addMoney(String(inv.total),'-'+balance.paid,scale),scale)>0)reject('Payment exceeds the outstanding amount.',409,'PAYMENT_RECONCILIATION_REQUIRED');
 const [account]=await q(tx,'select id,currency from accounts where workspace_id=$1 and id=$2 and deleted_at is null and archived_at is null',[ws,uuid(input.accountId)]),[category]=await q(tx,"select id from categories where workspace_id=$1 and id=$2 and type='income' and archived_at is null",[ws,uuid(input.categoryId)]);if(!account||account.currency!==inv.currency||!category)reject('Choose an active same-currency account and income category.');
 let txid:string;
 if(input.existingTransactionId){await assertUnlinkedBusinessTransaction(tx,ws,uuid(input.existingTransactionId));const [t]=await q(tx,"select t.* from transactions t where t.workspace_id=$1 and t.id=$2 and t.deleted_at is null and t.type='income' for update",[ws,uuid(input.existingTransactionId)]);if(!t||t.account_id!==account.id||t.category_id!==category.id||t.currency!==inv.currency||compareMoney(String(t.amount),amount,scale)!==0||t.occurred_at!==input.paidOn)reject('Match an unlinked income with the same amount, date, account, currency and category.');if((await q(tx,'select id from invoice_payments where workspace_id=$1 and transaction_id=$2',[ws,t.id])).length)reject('This income is already linked to an invoice.',409);txid=t.id;}
 else {if(input.checkExistingIncome){const candidates=await q(tx,"select t.id from transactions t where t.workspace_id=$1 and t.account_id=$2 and t.type='income' and t.currency=$3 and t.amount<=$4 and t.amount>0 and t.deleted_at is null and t.occurred_at between $5::date-7 and $5::date+7 and not exists(select 1 from invoice_payments p where p.workspace_id=t.workspace_id and p.transaction_id=t.id) limit 1",[ws,account.id,inv.currency,amount,input.paidOn]);if(candidates.length)reject('An existing income may match this payment. Review before adding another transaction.',409,'EXISTING_INCOME_REVIEW_REQUIRED');}txid=(await makeTransaction(tx,ws,actor,{type:'income',accountId:account.id,categoryId:category.id,amount,date:input.paidOn,notes:reference??undefined,merchant:'Invoice '+inv.number})).id;}
 const id=randomUUID();const [payment]=await q(tx,'insert into invoice_payments(id,workspace_id,invoice_id,transaction_id,account_id,category_id,amount,currency,paid_on,reference,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id,amount::text,currency,paid_on as "paidOn",transaction_id as "transactionId"',[id,ws,inv.id,txid,account.id,category.id,amount,inv.currency,input.paidOn,protectedText(reference,ws,id,'reference'),actor.id]);
 await q(tx,"insert into idempotency_keys(workspace_id,actor_key,operation,key,request_hash,resource_id,expires_at) values($1,$2,'invoice_payment',$3,$4,$5,now()+interval '100 years')",[ws,actor.id,input.idempotencyKey,hash,id]);await recordAudit(tx,ws,actor.id,inv.id,'invoice','payment_recorded',{paymentId:id,amount,currency:inv.currency,matched:!!input.existingTransactionId});return {payment};
}
