import {Elysia} from 'elysia';import {randomUUID} from 'node:crypto';import {client} from '../db';
import {scope,detail,issue,ensurePdf} from './routes';import {q,text,reject,uuid,recordAudit} from './shared';import {protectedJson,protectedContact,protectedText} from '../security/business-fields';
import {isoDate} from '../tracking/routes';import {nextOccurrenceDate,workspaceToday} from '../tracking/recurrence';import {dispatchInvoiceDeliveries} from './worker';
const columns='id,name,anchor_date as "anchorDate",frequency,interval,due_days as "dueDays",end_date as "endDate",active,auto_issue as "autoIssue",auto_send as "autoSend",version,next_index as "nextIndex"';
export const recurringInvoiceRoutes=new Elysia({name:'recurring-invoices'})
.get('/api/workspaces/:workspaceId/recurring-invoices',({request,params})=>scope(request,params.workspaceId,async(tx)=>({items:await q(tx,'select '+columns+' from recurring_invoice_templates where workspace_id=$1 order by created_at desc limit 100',[params.workspaceId])})))
.post('/api/workspaces/:workspaceId/recurring-invoices',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{
 const b=await request.json() as any,name=text(b.name,200,true);if(!isoDate(b.anchorDate)||!['day','week','month','year'].includes(b.frequency)||!Number.isInteger(b.interval)||b.interval<1||b.interval>120||!Number.isInteger(b.dueDays)||b.dueDays<0||b.dueDays>365||(b.endDate&&(!isoDate(b.endDate)||b.endDate<b.anchorDate))||typeof b.autoIssue!=='boolean'||typeof b.autoSend!=='boolean'||(b.autoSend&&!b.autoIssue))reject('Choose valid recurrence dates, interval, due days, and sending options.');
 const source=await detail(tx,params.workspaceId,uuid(b.invoiceId));if(source.state==='void'||!source.lines.length)reject('Choose a draft or issued invoice with saved lines.');
 const payload={currency:source.currency,currencyScale:source.currency_scale,recipient:source.recipientSnapshot,locale:source.locale,notes:source.notes,paymentInstructions:source.payment_instructions,contactId:source.contact_id,lines:source.lines,subtotal:source.subtotal,discountTotal:source.discountTotal,taxTotal:source.taxTotal,total:source.total};
 const id=randomUUID();await q(tx,'insert into recurring_invoice_templates(id,workspace_id,name,anchor_date,frequency,interval,due_days,end_date,auto_issue,auto_send,payload,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12)',[id,params.workspaceId,name,b.anchorDate,b.frequency,b.interval,b.dueDays,b.endDate||null,b.autoIssue,b.autoSend,protectedJson(payload,params.workspaceId,id,'payload'),actor.id]);await recordAudit(tx,params.workspaceId,actor.id,id,'recurring_invoice','created',{autoIssue:b.autoIssue,autoSend:b.autoSend});return {id};
}))
.patch('/api/workspaces/:workspaceId/recurring-invoices/:id',({request,params})=>scope(request,params.workspaceId,async(tx,actor)=>{
 const b=await request.json() as any;if(typeof b.active!=='boolean'||!Number.isInteger(b.version))reject('Choose pause or resume and provide the current version.');const [saved]=await q(tx,'update recurring_invoice_templates set active=$3,version=version+1,updated_at=now() where workspace_id=$1 and id=$2 and version=$4 returning id',[params.workspaceId,uuid(params.id),b.active,b.version]);if(!saved)reject('Template changed. Reload before updating.',409);await recordAudit(tx,params.workspaceId,actor.id,saved.id,'recurring_invoice',b.active?'resumed':'paused',{});return {updated:true};
}))
.get('/api/workspaces/:workspaceId/recurring-invoices/:id/occurrences',({request,params})=>scope(request,params.workspaceId,async(tx)=>({items:await q(tx,'select id,scheduled_on as "scheduledOn",template_version as "templateVersion",invoice_id as "invoiceId",state,failure_code as "failureCode",attempts from recurring_invoice_occurrences where workspace_id=$1 and template_id=$2 order by scheduled_on desc limit 100',[params.workspaceId,uuid(params.id)])})))
.post('/api/workspaces/:workspaceId/recurring-invoice-occurrences/:id/retry',({request,params})=>scope(request,params.workspaceId,async(tx)=>{const [saved]=await q(tx,"update recurring_invoice_occurrences set state='pending',next_attempt_at=now(),failure_code=null where workspace_id=$1 and id=$2 and state='failed' and attempts<20 returning id",[params.workspaceId,uuid(params.id)]);if(!saved)reject('This occurrence cannot be retried.',409);return {queued:true};}));
async function context<T>(ws:string,user:string,run:(tx:Parameters<typeof q>[0],today:string)=>Promise<T>){return client.begin(async tx=>{const [eligible]=await tx.unsafe("select w.timezone from workspaces w join workspace_memberships m on m.workspace_id=w.id and m.user_id=$2 and m.role in ('owner','accountant') join \"user\" u on u.id=m.user_id and u.account_status='active' and u.email_verified=true join \"user\" owner on owner.id=w.owner_user_id and owner.account_status='active' where w.id=$1 and w.kind='business' and w.archived_at is null for share of m",[ws,user]);if(!eligible)reject('Recurring invoice access is unavailable.',403);await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[user,ws]);return run(tx,workspaceToday(eligible.timezone));});}
export async function prepareRecurringInvoices(ws:string,user:string){return context(ws,user,async(tx,today)=>{
 const templates=await q(tx,'select * from recurring_invoice_templates where workspace_id=$1 and created_by=$2 and active for update',[ws,user]);let count=0;
 for(const template of templates){let index=template.next_index;for(let generated=0;generated<10;generated++){
  const scheduled=nextOccurrenceDate(template.anchor_date,template.frequency,template.interval,index);if(scheduled>today||(template.end_date&&scheduled>template.end_date))break;
  const id=randomUUID();await q(tx,'insert into recurring_invoice_occurrences(id,workspace_id,template_id,scheduled_on,template_version,payload,auto_issue,auto_send,requested_by,due_days) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10) on conflict(template_id,scheduled_on) do nothing',[id,ws,template.id,scheduled,template.version,protectedJson(template.payload,ws,id,'payload'),template.auto_issue,template.auto_send,user,template.due_days]);index++;count++;
 }await q(tx,"update recurring_invoice_templates set next_index=$3,next_scan_at=now()+interval '60 seconds' where workspace_id=$1 and id=$2",[ws,template.id,index]);}return count;
});}
export async function processRecurringInvoice(ws:string,id:string,user:string){
 const prepared=await context(ws,user,async(tx)=>{const [row]=await q(tx,"update recurring_invoice_occurrences set state='processing',attempts=attempts+1,lease_until=now()+interval '3 minutes' where workspace_id=$1 and id=$2 and requested_by=$3 and attempts<20 and ((state in ('pending','failed') and next_attempt_at<=now()) or (state='processing' and lease_until<now())) returning *",[ws,id,user]);return row;});if(!prepared)return;
 try{
  const invoiceId=await context(ws,user,async tx=>{const [row]=await q(tx,"select * from recurring_invoice_occurrences where workspace_id=$1 and id=$2 and attempts=$3 and state='processing' for update",[ws,id,prepared.attempts]);if(!row)reject('Occurrence lease changed.',409);if(row.invoice_id)return row.invoice_id;
   const p=row.payload,key=randomUUID(),due=new Date(row.scheduled_on+'T12:00:00Z');due.setUTCDate(due.getUTCDate()+row.due_days);
   await q(tx,'insert into invoices(id,workspace_id,contact_id,issue_date,due_date,currency,currency_scale,recipient_snapshot,locale,notes,payment_instructions,subtotal,discount_total,tax_total,total,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12,$13,$14,$15,$16,$16)',[key,ws,p.contactId??null,row.scheduled_on,due.toISOString().slice(0,10),p.currency,p.currencyScale,protectedContact(p.recipient,ws,key,'recipient_snapshot'),p.locale,protectedText(p.notes,ws,key,'notes'),protectedText(p.paymentInstructions,ws,key,'payment_instructions'),p.subtotal,p.discountTotal,p.taxTotal,p.total,user]);
   for(let i=0;i<p.lines.length;i++){const line=p.lines[i];await q(tx,'insert into invoice_lines(workspace_id,invoice_id,position,description,quantity,unit_price,discount_amount,tax_rate,net_amount,tax_amount,total_amount,tax_rate_id,tax_snapshot,catalog_item_id,catalog_snapshot) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14,$15::jsonb)',[ws,key,i,line.description,line.quantity,line.unitPrice,line.discountAmount,line.taxRate,line.netAmount,line.taxAmount,line.totalAmount,line.taxRateId||null,line.taxSnapshot?JSON.stringify(line.taxSnapshot):null,line.catalogItemId||null,line.catalogSnapshot?JSON.stringify(line.catalogSnapshot):null]);}
   await q(tx,'update recurring_invoice_occurrences set invoice_id=$3 where workspace_id=$1 and id=$2',[ws,id,key]);await recordAudit(tx,ws,user,key,'invoice','recurring_draft_created',{occurrenceId:id,templateVersion:row.template_version});return key;
  });
  if(prepared.auto_issue)await context(ws,user,async tx=>{const current=await detail(tx,ws,invoiceId);if(current.state==='draft')await issue(tx,ws,user,invoiceId);if(current.state==='void')reject('Recurring invoice was voided.',409);});
  if(prepared.auto_send){const pdf=await ensurePdf(ws,invoiceId);if(!('id' in pdf)||!pdf.id)reject('Invoice PDF unavailable.',409);await context(ws,user,async tx=>{const inv=await detail(tx,ws,invoiceId);if(inv.state!=='issued'||!inv.recipientSnapshot.email)reject('Review recipient before sending.',409);const delivery=randomUUID();await q(tx,"insert into invoice_deliveries(id,workspace_id,invoice_id,document_id,requested_by,recipient_snapshot,locale,idempotency_key) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(workspace_id,idempotency_key) do nothing",[delivery,ws,invoiceId,pdf.id,user,protectedText(inv.recipientSnapshot.email,ws,delivery,'recipient_snapshot'),inv.locale,'recurring-'+id]);});}
  await context(ws,user,async tx=>{await q(tx,'update recurring_invoice_occurrences set state=$4,lease_until=null,failure_code=null where workspace_id=$1 and id=$2 and attempts=$3',[ws,id,prepared.attempts,prepared.auto_send?'queued':prepared.auto_issue?'issued':'draft']);});
  if(prepared.auto_send)await dispatchInvoiceDeliveries();
 }catch{await context(ws,user,async tx=>{await q(tx,"update recurring_invoice_occurrences set state='failed',lease_until=null,next_attempt_at=now()+interval '1 hour',failure_code='REVIEW_INVOICE_CONFIGURATION' where workspace_id=$1 and id=$2 and attempts=$3",[ws,id,prepared.attempts]);}).catch(()=>{});}
}
export async function sweepRecurringInvoices(){await client`update recurring_invoice_occurrences o set state='sent' where o.state='queued' and exists(select 1 from invoice_deliveries d where d.workspace_id=o.workspace_id and d.invoice_id=o.invoice_id and d.idempotency_key='recurring-'||o.id::text and d.state='accepted')`; const templates=await client`select t.workspace_id,t.created_by from recurring_invoice_templates t join workspaces w on w.id=t.workspace_id and w.archived_at is null join workspace_memberships m on m.workspace_id=t.workspace_id and m.user_id=t.created_by and m.role in ('owner','accountant') join "user" u on u.id=t.created_by and u.account_status='active' and u.email_verified=true where t.active and t.next_scan_at<=now() group by t.workspace_id,t.created_by order by min(t.next_scan_at) limit 100`;for(const template of templates)try{await prepareRecurringInvoices(template.workspace_id,template.created_by);}catch{console.error('Recurring invoice scheduling deferred.');}
 const pending=await client`select o.workspace_id,o.id,o.requested_by from recurring_invoice_occurrences o join workspaces w on w.id=o.workspace_id and w.archived_at is null join workspace_memberships m on m.workspace_id=o.workspace_id and m.user_id=o.requested_by and m.role in ('owner','accountant') join "user" u on u.id=o.requested_by and u.account_status='active' and u.email_verified=true where o.attempts<20 and ((o.state in ('pending','failed') and o.next_attempt_at<=now()) or (o.state='processing' and o.lease_until<now())) order by o.scheduled_on limit 50`;for(const row of pending)try{await processRecurringInvoice(row.workspace_id,row.id,row.requested_by);}catch{console.error('Recurring invoice processing deferred.');}}
export function startRecurringInvoiceScheduler(){let running=false;const tick=async()=>{if(running)return;running=true;try{await sweepRecurringInvoices();}finally{running=false;}};void tick();const timer=setInterval(()=>void tick(),60000);timer.unref();}
