<script lang="ts">
  import { getContext, onMount, tick } from 'svelte';
  import { AUTH_UI_CONTEXT, type AuthUiState } from '$lib/i18n/auth';
  import { readPrivacyMode, writePrivacyMode } from '$lib/privacy';
  import * as Card from '$lib/components/ui/card';
  import { Button } from '$lib/components/ui/button';
  type Workspace={id:string;currency:string;kind:'personal'|'business'};
  type CashflowMapping={categoryId:string;categoryName:string;activity:string|null;version:number|null};
  type ReportRun={id:string;reportType:string;preset:string;status:string;generatedAt:string;periodFrom:string;periodToExclusive:string;currency:string;rowCount:number;expiresAt:string;failureCode?:string|null};
  type Dashboard={summary:{currency:string;period:{from:string;through:string;toExclusive:string;preset:string};cashBalance:string;trackedAccountNetBalance:string;income:string;expense:string;netActivity:string;cashflow:{opening:string;closing:string;reconciled:boolean};generatedAt:string};flags:string[];accounts:any[];series:any[];categories:any[];budgetActual:any[];goals:any[];bills:any[];cashflowRows:any[]};
  const authUi=getContext<AuthUiState>(AUTH_UI_CONTEXT);
  const workspace=getContext<{selectedId:string;ready:boolean;items:Workspace[]}>('capybudget-workspaces');
  let preset=$state('this_month'),data:Dashboard|undefined=$state(),privacyMode=$state(false),mappings:CashflowMapping[]=$state([]),runs:ReportRun[]=$state([]),loading=$state(false),error=$state(''),status=$state(''),runId=$state('');
  let incomeChart=$state<HTMLDivElement>(),trendChart=$state<HTMLDivElement>(),pieChart=$state<HTMLDivElement>(),cashChart=$state<HTMLDivElement>();
  let charts:any[]=[],requestSequence=0,activeRequest:AbortController|undefined;
  const label=(en:string,id:string)=>authUi.locale==='id'?id:en;
  const presets=[['this_week','This week','Minggu ini'],['last_week','Last week','Minggu lalu'],['this_month','This month','Bulan ini'],['last_month','Last month','Bulan lalu'],['year_to_date','Year to date','Tahun ini']];
  const money=(value:string)=>privacyMode?'••••••':`${data?.summary.currency??''} ${value}`;
  async function load(id:string){
    activeRequest?.abort();const controller=new AbortController(),sequence=++requestSequence;activeRequest=controller;loading=true;error='';status='';runId='';data=undefined;mappings=[];
    try{const [response,mappingResponse,historyResponse]=await Promise.all([fetch(`/api/workspaces/${id}/reports/dashboard?preset=${preset}`,{signal:controller.signal}),fetch(`/api/workspaces/${id}/reports/cashflow/mappings`,{signal:controller.signal}),fetch(`/api/workspaces/${id}/reports/runs?limit=10`,{signal:controller.signal})]);const result=await response.json(),mappingBody=await mappingResponse.json(),history=await historyResponse.json();if(sequence!==requestSequence)return;if(!response.ok)throw new Error(result.message??'Unable to load reports.');data=result;mappings=mappingResponse.ok?mappingBody.items:[];runs=historyResponse.ok?history.items:[];}
    catch(e){if(sequence!==requestSequence||controller.signal.aborted)return;data=undefined;error=e instanceof Error?e.message:'Unable to load reports.';}
    finally{if(sequence===requestSequence)loading=false;}
  }
  async function drawCharts(){
    charts.forEach(chart=>chart.dispose());charts=[];if(!data||typeof window==='undefined'||privacyMode)return;const echarts=await import('echarts');
    const refs=[incomeChart,trendChart,pieChart,cashChart];if(refs.some(ref=>!ref))return;
    const text=getComputedStyle(document.documentElement).getPropertyValue('--foreground').trim()||'#3b2a1e';
    const axis={axisLabel:{color:text},axisLine:{lineStyle:{color:'#b98b5e'}},splitLine:{lineStyle:{color:'rgba(130,100,70,.16)'}}};
    const init=(el:HTMLDivElement,option:any)=>{const chart=echarts.init(el);chart.setOption(option);charts.push(chart);};
    init(incomeChart!,{color:['#2f7a2a','#c7473a'],tooltip:{trigger:'axis'},legend:{textStyle:{color:text}},grid:{left:54,right:20,bottom:42,top:38},xAxis:{type:'category',data:data.series.map(r=>r.date.slice(5)),...axis},yAxis:{type:'value',...axis},series:[{name:label('Income','Pemasukan'),type:'bar',data:data.series.map(r=>Number(r.income)),itemStyle:{borderRadius:[5,5,0,0]}},{name:label('Expense','Pengeluaran'),type:'bar',data:data.series.map(r=>Number(r.expense)),itemStyle:{borderRadius:[5,5,0,0]}}]});
    init(trendChart!,{color:['#1f7a96'],tooltip:{trigger:'axis',formatter:(items:any[])=>`${items[0]?.axisValue}<br/>${money(data!.series[items[0]?.dataIndex]?.cashBalance??'0.0000')}`},grid:{left:54,right:20,bottom:42,top:24},xAxis:{type:'category',data:data.series.map(r=>r.date.slice(5)),...axis},yAxis:{type:'value',...axis},series:[{name:label('Cash balance','Saldo kas'),type:'line',smooth:true,symbol:'circle',data:data.series.map(r=>Number(r.cashBalance)),areaStyle:{opacity:.12}}]});
    init(pieChart!,{color:['#c7473a','#b98b5e','#5bb8d4','#ffc53d','#6bbf59','#8a5f3a'],tooltip:{trigger:'item',formatter:(item:any)=>`${item.name}<br/>${money(item.data?.exactAmount??'0.0000')} (${item.percent}%)`},legend:{bottom:0,textStyle:{color:text}},series:[{type:'pie',radius:['38%','68%'],avoidLabelOverlap:true,data:data.categories.filter(r=>Number(r.amount)>0).map(r=>({name:r.categoryName??label('Uncategorized','Tanpa kategori'),value:Number(r.amount),exactAmount:r.amount}))}]});
    init(cashChart!,{color:['#5bb8d4'],tooltip:{trigger:'axis'},grid:{left:54,right:20,bottom:42,top:24},xAxis:{type:'category',data:data.series.map(r=>r.date.slice(5)),...axis},yAxis:{type:'value',...axis},series:[{name:label('Income / expense trend','Tren pemasukan / pengeluaran'),type:'bar',data:data.series.map(r=>Number(r.income)-Number(r.expense)),itemStyle:{borderRadius:[5,5,0,0]}}]});
  }
  const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
  async function waitForRun(id:string){for(let attempt=0;attempt<600;attempt++){const response=await fetch(`/api/workspaces/${workspace.selectedId}/reports/runs/${id}`);const body=await response.json();if(!response.ok)throw new Error(body.message??'Report expired or could not be loaded.');const run=body.run as ReportRun;runs=runs.map(item=>item.id===run.id?{...item,...run}:item);if(run.status==='ready')return run;if(run.status==='failed')throw new Error(run.failureCode??'Report generation failed.');status=label('Generating report…','Membuat laporan…');await pause(500);}throw new Error(label('Report generation timed out. Retry from report history.','Pembuatan laporan melewati batas waktu. Coba lagi dari riwayat laporan.'));}
  async function startExport(id:string,format:'csv'|'xlsx'|'pdf'){if(!workspace.selectedId)return;status=label('Preparing download…','Menyiapkan unduhan…');const created=await fetch(`/api/workspaces/${workspace.selectedId}/reports/runs/${id}/exports`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({format,idempotencyKey:crypto.randomUUID()})});const createdBody=await created.json();if(!created.ok)throw new Error(createdBody.message??'Unable to queue export.');const exportId=createdBody.export.id;let ready=false;for(let attempt=0;attempt<600;attempt++){const response=await fetch(`/api/workspaces/${workspace.selectedId}/reports/exports/${exportId}`),body=await response.json();if(!response.ok)throw new Error(body.message??'Export expired.');if(body.export.status==='failed')throw new Error(body.export.failureCode??'Export failed.');if(body.export.status==='expired')throw new Error('Export expired.');if(body.export.status==='ready'){ready=true;break;}status=label('Preparing download…','Menyiapkan unduhan…');await pause(500);}if(!ready)throw new Error(label('Export is taking too long. You can retry from report history.','Ekspor terlalu lama. Anda dapat mencoba lagi dari riwayat laporan.'));const response=await fetch(`/api/workspaces/${workspace.selectedId}/reports/exports/${exportId}/download`);if(!response.ok)throw new Error('The report file is no longer available.');const blob=await response.blob(),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1]??`capybudget-report.${format}`;anchor.click();URL.revokeObjectURL(url);status=label('Report downloaded.','Laporan diunduh.');}
  async function exportFile(format:'csv'|'xlsx'|'pdf'){
    if(!workspace.selectedId)return;status=label('Preparing a report snapshot…','Menyiapkan laporan…');error='';
    try{if(!runId){const response=await fetch(`/api/workspaces/${workspace.selectedId}/reports/runs`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reportType:'analytics',preset,currency:data?.summary.currency,idempotencyKey:crypto.randomUUID()})});const body=await response.json();if(!response.ok)throw new Error(body.message??'Unable to create report.');runId=body.run.id;runs=[{...body.run,reportType:'analytics',preset,status:body.run.status,periodFrom:data?.summary.period.from??'',periodToExclusive:data?.summary.period.toExclusive??'',currency:data?.summary.currency??'',rowCount:body.run.rowCount??0},...runs.filter(run=>run.id!==body.run.id)].slice(0,10);}await waitForRun(runId);await startExport(runId,format);}
    catch(e){error=e instanceof Error?e.message:'Export failed.';status='';}
  }
  function togglePrivacy(){privacyMode=!privacyMode;writePrivacyMode(privacyMode);}
  async function exportExisting(id:string,format:'csv'|'xlsx'|'pdf'){if(!workspace.selectedId)return;error='';try{await waitForRun(id);await startExport(id,format);}catch(e){error=e instanceof Error?e.message:'Export failed.';status='';}}
  async function saveMapping(categoryId:string,activity:string){if(!workspace.selectedId)return;const response=await fetch(`/api/workspaces/${workspace.selectedId}/reports/cashflow/mappings/${categoryId}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({activity})});if(!response.ok){const body=await response.json();error=body.message??label('Could not update category mapping.','Gagal memperbarui kategori.');return;}mappings=mappings.map(mapping=>mapping.categoryId===categoryId?{...mapping,activity}:mapping);if(data)await load(workspace.selectedId);}
  $effect(()=>{const locale=authUi.locale,dark=authUi.dark,current=data,privateView=privacyMode;void locale;void dark;void privateView;if(current)void tick().then(drawCharts);});
  $effect(()=>{const id=workspace.selectedId,period=preset;if(workspace.ready&&id)void load(id);return()=>{activeRequest?.abort();charts.forEach(chart=>chart.dispose());charts=[];};});
  onMount(()=>{privacyMode=readPrivacyMode();return()=>{charts.forEach(chart=>chart.dispose());};});
</script>

<svelte:head><title>{label('Reports and analytics','Laporan dan analitik')} · CapyBudget</title></svelte:head>
<header class="heading"><div><p class="eyebrow">{label('A CLEAR VIEW OF YOUR MONEY','RINGKASAN KEUANGAN ANDA')}</p><h1>{label('Reports and analytics','Laporan dan analitik')}</h1><p>{label('Recorded activity by workspace period. Forecasts are shown separately.','Aktivitas tercatat untuk periode workspace. Proyeksi ditampilkan terpisah.')}</p></div><div class="controls"><Button variant="outline" onclick={togglePrivacy} aria-pressed={privacyMode}>{privacyMode?label('Show amounts','Tampilkan jumlah'):label('Hide amounts','Sembunyikan jumlah')}</Button><label for="period">{label('Period','Periode')}<select id="period" bind:value={preset} onchange={()=>{if(workspace.selectedId)void load(workspace.selectedId);}}>{#each presets as item}<option value={item[0]}>{label(item[1],item[2])}</option>{/each}</select></label><div class="exports"><Button variant="outline" onclick={()=>void exportFile('csv')}>CSV</Button><Button variant="outline" onclick={()=>void exportFile('xlsx')}>Excel</Button><Button variant="outline" onclick={()=>void exportFile('pdf')}>PDF</Button></div></div></header>
{#if loading}<p role="status">{label('Loading report…','Memuat laporan…')}</p>{:else if error}<p class="error" role="alert">{error}</p>{:else if data}
  <p class="period">{data.summary.period.from} – {data.summary.period.through} · {data.summary.currency} · {label('Generated','Dibuat')} {new Date(data.summary.generatedAt).toLocaleString(authUi.locale==='id'?'id-ID':'en')}</p>
  {#if status}<p role="status">{status}</p>{/if}{#if privacyMode}<p class="flags" role="status">{label('Amounts and charts are hidden on this screen. Downloaded reports still contain financial data.','Jumlah dan grafik disembunyikan di layar ini. File yang diunduh tetap berisi data keuangan.')}</p>{/if}{#if data.flags.length}<aside class="flags" aria-label={label('Coverage notes','Catatan cakupan')}>{#each data.flags as flag}<p>{flag.replaceAll('_',' ')}</p>{/each}</aside>{/if}
  <section class="metrics" aria-label={label('Summary','Ringkasan')}>
    <Card.Root><Card.Header><Card.Description>{label('Cash balance','Saldo kas')}</Card.Description><Card.Title>{money(data.summary.cashBalance)}</Card.Title></Card.Header></Card.Root>
    <Card.Root><Card.Header><Card.Description>{label('Income','Pemasukan')}</Card.Description><Card.Title class="income">{money(data.summary.income)}</Card.Title></Card.Header></Card.Root>
    <Card.Root><Card.Header><Card.Description>{label('Expenses','Pengeluaran')}</Card.Description><Card.Title class="expense">{money(data.summary.expense)}</Card.Title></Card.Header></Card.Root>
    <Card.Root><Card.Header><Card.Description>{label('Net activity','Aktivitas bersih')}</Card.Description><Card.Title>{money(data.summary.netActivity)}</Card.Title></Card.Header></Card.Root>
  </section>
  <section class="grid">
    <Card.Root><Card.Header><Card.Title>{label('Income and expenses','Pemasukan dan pengeluaran')}</Card.Title></Card.Header><Card.Content><div class="chart" role="img" aria-label={label('Grouped daily income and expense bars. Exact values are in the daily report table.','Grafik batang pemasukan dan pengeluaran harian. Nilai tepat tersedia pada tabel harian.')} bind:this={incomeChart}></div></Card.Content></Card.Root>
    <Card.Root><Card.Header><Card.Title>{label('Daily trend','Tren harian')}</Card.Title></Card.Header><Card.Content><div class="chart" bind:this={trendChart}></div></Card.Content></Card.Root>
    <Card.Root><Card.Header><Card.Title>{label('Spending by category','Pengeluaran per kategori')}</Card.Title></Card.Header><Card.Content><div class="chart" role="img" aria-label={label('Expense share by category. Exact values are in the category table.','Proporsi pengeluaran per kategori. Nilai tepat tersedia pada tabel kategori.')} bind:this={pieChart}></div></Card.Content></Card.Root>
    <Card.Root><Card.Header><Card.Title>{label('Net change trend','Tren perubahan bersih')}</Card.Title></Card.Header><Card.Content><div class="chart" role="img" aria-label={label('Daily net income and expense trend. Exact values are in the daily report table.','Tren harian bersih pemasukan dan pengeluaran. Nilai tepat tersedia pada tabel harian.')} bind:this={cashChart}></div></Card.Content></Card.Root>
  </section>
  <Card.Root class="table-card"><Card.Header><Card.Title>{label('Spending by category','Pengeluaran per kategori')}</Card.Title><Card.Description>{label('Exact expense amounts; negative values are excluded from the pie share.','Jumlah pengeluaran; nilai negatif tidak dihitung dalam proporsi diagram.')}</Card.Description></Card.Header><Card.Content><div class="scroll"><table><thead><tr><th>{label('Category','Kategori')}</th><th>{label('Transactions','Transaksi')}</th><th>{label('Amount','Jumlah')}</th></tr></thead><tbody>{#each data.categories as category}<tr><td>{category.categoryName??label('Uncategorized','Tanpa kategori')}</td><td>{category.count}</td><td>{money(category.amount)}</td></tr>{:else}<tr><td colspan="3">{label('No expenses in this period.','Tidak ada pengeluaran pada periode ini.')}</td></tr>{/each}</tbody></table></div></Card.Content></Card.Root>
  <Card.Root class="statement"><Card.Header><Card.Title>{label('Cashflow statement','Laporan arus kas')}</Card.Title><Card.Description>{label('Recorded cash movements; unclassified items stay visible.','Pergerakan kas tercatat; transaksi belum terklasifikasi tetap ditampilkan.')}</Card.Description></Card.Header><Card.Content><p>{label('Opening cash','Saldo awal')} <strong>{money(data.summary.cashflow.opening)}</strong> → {label('Closing cash','Saldo akhir')} <strong>{money(data.summary.cashflow.closing)}</strong> · {data.summary.cashflow.reconciled?label('Reconciled','Seimbang'):label('Needs review','Perlu ditinjau')}</p><div class="scroll"><table><caption>{label('Cash movements by journal entry','Pergerakan kas dari jurnal')}</caption><thead><tr><th>{label('Date','Tanggal')}</th><th>{label('Activity','Aktivitas')}</th><th>{label('Category','Kategori')}</th><th>{label('Amount','Jumlah')}</th></tr></thead><tbody>{#each data.cashflowRows as row}<tr><td>{row.date}</td><td>{row.activity.replaceAll('_',' ')}</td><td>{row.categoryName??row.reason}</td><td>{money(row.amount)}</td></tr>{:else}<tr><td colspan="4">{label('No cash movements in this period.','Tidak ada pergerakan kas pada periode ini.')}</td></tr>{/each}</tbody></table></div><h3>{label('Classify cashflow categories','Klasifikasikan arus kas')}</h3><p class="mapping-help">{label('Choose the statement section for each category.','Pilih bagian laporan arus kas untuk setiap kategori.')}</p>{#each mappings as mapping}<label class="mapping-row">{mapping.categoryName}<select value={mapping.activity??'unclassified'} onchange={(event)=>void saveMapping(mapping.categoryId,event.currentTarget.value)}><option value="unclassified">{label('Unclassified','Belum diklasifikasikan')}</option><option value="operating">{label('Operating','Operasi')}</option><option value="investing">{label('Investing','Investasi')}</option><option value="financing">{label('Financing','Pendanaan')}</option></select></label>{/each}</Card.Content></Card.Root>
  <section class="grid lower">
    <Card.Root><Card.Header><Card.Title>{label('Budget vs actual','Anggaran vs aktual')}</Card.Title></Card.Header><Card.Content><div class="scroll"><table><thead><tr><th>{label('Budget','Anggaran')}</th><th>{label('Planned','Rencana')}</th><th>{label('Actual','Aktual')}</th><th>{label('Remaining','Sisa')}</th></tr></thead><tbody>{#each data.budgetActual as row}<tr><td>{row.name} · {row.categoryName}</td><td>{money(row.planned)}</td><td>{money(row.actual)}</td><td>{money(row.remaining)}</td></tr>{:else}<tr><td colspan="4">{label('No budgets cover this period.','Tidak ada anggaran untuk periode ini.')}</td></tr>{/each}</tbody></table></div></Card.Content></Card.Root>
    <Card.Root><Card.Header><Card.Title>{label('Upcoming bills','Tagihan mendatang')}</Card.Title></Card.Header><Card.Content>{#each data.bills as bill}<p class="list-row"><span>{bill.name} · {bill.dueOn}{#if bill.overdue}<small> · {label('Overdue','Terlambat')}</small>{/if}</span><strong>{money(bill.amount)}</strong></p>{:else}<p>{label('No unpaid bills in the next 30 days.','Tidak ada tagihan dalam 30 hari ke depan.')}</p>{/each}</Card.Content></Card.Root>
    <Card.Root><Card.Header><Card.Title>{label('Savings goals','Target tabungan')}</Card.Title></Card.Header><Card.Content>{#each data.goals as goal}<p class="list-row"><span>{goal.name} · {goal.progressPercent===null?'—':`${goal.progressPercent}%`}</span><strong>{money(goal.saved)} / {money(goal.target)}</strong></p>{:else}<p>{label('No active savings goals.','Tidak ada target tabungan aktif.')}</p>{/each}</Card.Content></Card.Root>
  </section>
  <Card.Root class="table-card"><Card.Header><Card.Title>{label('Recent report snapshots','Snapshot laporan terbaru')}</Card.Title><Card.Description>{label('Private snapshots are available for seven days.','Snapshot pribadi tersedia selama tujuh hari.')}</Card.Description></Card.Header><Card.Content>{#each runs as run (run.id)}<div class="history-row"><span><strong>{run.reportType.replaceAll('_',' ')} · {run.preset.replaceAll('_',' ')} · {run.status}</strong><small>{new Date(run.generatedAt).toLocaleString(authUi.locale==='id'?'id-ID':'en')} · {run.currency} · {run.rowCount} {label('rows','baris')}{run.failureCode?` · ${run.failureCode}`:''}</small></span><div class="exports"><Button size="sm" variant="outline" onclick={()=>void exportExisting(run.id,'csv')}>CSV</Button><Button size="sm" variant="outline" onclick={()=>void exportExisting(run.id,'xlsx')}>Excel</Button><Button size="sm" variant="outline" onclick={()=>void exportExisting(run.id,'pdf')}>PDF</Button></div></div>{:else}<p>{label('No saved report snapshots yet. Use an export button to create one.','Belum ada snapshot laporan. Gunakan tombol ekspor untuk membuat snapshot.')}</p>{/each}</Card.Content></Card.Root>
  <Card.Root class="table-card"><Card.Header><Card.Title>{label('Income and expense by day','Pemasukan dan pengeluaran per hari')}</Card.Title></Card.Header><Card.Content><div class="scroll"><table><caption>{label('Exact amounts shown as recorded','Jumlah sesuai pencatatan')}</caption><thead><tr><th>{label('Date','Tanggal')}</th><th>{label('Income','Pemasukan')}</th><th>{label('Expenses','Pengeluaran')}</th><th>{label('Net','Bersih')}</th><th>{label('Cash balance','Saldo kas')}</th></tr></thead><tbody>{#each data.series as row}<tr><td>{row.date}</td><td>{money(row.income)}</td><td>{money(row.expense)}</td><td>{money(row.net)}</td><td>{money(row.cashBalance)}</td></tr>{/each}</tbody></table></div></Card.Content></Card.Root>
{:else if !loading}<p>{label('Choose a workspace to view reports.','Pilih workspace untuk melihat laporan.')}</p>{/if}

<style>
  .heading{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:14px}.eyebrow{font-size:11px;letter-spacing:1px;color:var(--muted-foreground);font-weight:700;margin:0 0 6px}h1{font:500 clamp(27px,4vw,38px) 'Fredoka Variable',sans-serif;margin:0}.heading p:last-child,.period{color:var(--muted-foreground);font-size:13px}.controls{display:flex;align-items:end;gap:10px}.controls label{display:grid;gap:5px;font-size:12px}.controls select{min-height:40px}.exports{display:flex;gap:6px;flex-wrap:wrap}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:14px 0}.metrics :global([data-slot=card-title]){font-size:clamp(17px,2vw,24px);overflow-wrap:anywhere;font-variant-numeric:tabular-nums}:global(.income){color:#2f7a2a}:global(.expense){color:#c7473a}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:14px 0}.chart{width:100%;height:270px}.lower{margin-top:14px}.period{margin:8px 0}.flags{padding:10px 14px;border:1px solid var(--border);border-radius:12px;background:var(--muted)}.flags p{margin:3px 0;text-transform:capitalize;font-size:12px}.scroll{max-height:420px;overflow:auto;border:1px solid var(--border);border-radius:10px}table{border-collapse:collapse;width:100%;font-size:12px}caption{text-align:left;padding:9px;font-weight:600}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--border);font-variant-numeric:tabular-nums}td:nth-last-child(-n+3):not(:first-child),th:nth-last-child(-n+3):not(:first-child){text-align:right}.list-row{display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid var(--border);padding:9px 0;font-size:12px}.list-row strong{white-space:nowrap;font-variant-numeric:tabular-nums}.list-row small{color:var(--destructive)}.mapping-help{color:var(--muted-foreground);font-size:13px}.mapping-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:7px 0;border-bottom:1px solid var(--border);font-size:13px}.mapping-row select{min-height:36px}.history-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)}.history-row span{display:grid;gap:4px}.history-row small{color:var(--muted-foreground)}.error{color:var(--destructive)}
  @media(max-width:850px){.heading{align-items:stretch;flex-direction:column}.controls{align-items:end;justify-content:space-between}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.grid{grid-template-columns:1fr}}
  @media(max-width:480px){.controls{align-items:stretch;flex-direction:column}.chart{height:240px}.metrics{gap:8px}}
</style>
