/** Explicit registry: newly introduced workspace tables must be reviewed before exporting/deleting. */
export const workspaceTables = [
  "workspace_memberships",
  "accounts",
  "ledger_accounts",
  "categories",
  "tags",
  "transactions",
  "transaction_tags",
  "journal_entries",
  "journal_lines",
  "audit_logs",
  "idempotency_keys",
  "recurring_rules",
  "recurring_occurrences",
  "budgets",
  "budget_revisions",
  "savings_goals",
  "goal_contributions",
  "bills",
  "bill_group_forecast_settings",
  "bill_occurrences",
  "finance_notifications",
  "finance_notification_preferences",
  "push_subscriptions",
  "finance_notification_rules",
  "finance_notification_evaluation_state",
  "finance_notification_deliveries",
  "business_profiles",
  "invoice_number_sequences",
  "invoices",
  "invoice_lines",
  "business_documents",
  "invoice_payments",
  "invoice_deliveries",
  "attachments",
  "assistant_settings",
  "assistant_refresh_state",
  "assistant_account_settings",
  "forecast_transaction_overrides",
  "forecast_runs",
  "forecast_events",
  "forecast_daily_balances",
  "assistant_suggestions",
  "assistant_action_proposals",
  "category_rules",
  "category_feedback",
  "ai_invocations",
  "cashflow_category_mappings",
  "report_runs",
  "report_rows",
  "report_exports",
] as const;
export const secretColumns = new Set([
  "password",
  "token",
  "access_token",
  "refresh_token",
  "id_token",
  "secret",
  "backup_codes",
  "pin_hash",
  "public_key",
  "p256dh",
  "auth",
  "endpoint",
  "request_hash",
]);
export function exportRecord(row: Record<string, unknown>) {
  return Object.fromEntries(
    Object.entries(row).filter(([key]) => !secretColumns.has(key)),
  );
}
