<script lang="ts">
 import {getContext} from 'svelte';
 import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';
 import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';
 import {Button} from '$lib/components/ui/button';import {Input} from '$lib/components/ui/input';
 import * as Checkbox from '$lib/components/ui/checkbox';import * as AlertDialog from '$lib/components/ui/alert-dialog';
 import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import DatePicker from '$lib/components/forms/date-picker.svelte';
 import PageHeader from '$lib/components/shared/page-header.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import {formatDate,formatDateTime} from '$lib/dates';
 const workspace=getContext<{selectedId:string;ready:boolean;revision?:number}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 const today=new Date().toISOString().slice(0,10);
 let loading=$state(false),saving=$state(false),error=$state(''),notice=$state(''),accountStatus:any=$state(null),review:any=$state(null),readiness:any=$state(null),report:any=$state(null);
 let cutover=$state(today),from=$state(today.slice(0,7)+'-01'),through=$state(today),closeThrough=$state(today),basis=$state('cash'),reference=$state(''),reviewConfirm=$state(false),backupConfirm=$state(false),activateConfirm=$state(false),closeConfirm=$state(false),sequence=0;
 let storageConfirm=$state(false);
 const endpoint=(ws=workspace.selectedId)=>'/api/workspaces/'+ws+'/business-accounting';
 async function call(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.message??copy('Request failed.','Permintaan gagal.'));return result;}
 async function load(ws:string){const current=++sequence;loading=true;error='';try{const result=await call(endpoint(ws));if(current!==sequence||ws!==workspace.selectedId)return;accountStatus=result;if(result.settings){basis='accrual';from=result.settings.cutover_on;}else basis='cash';}catch(cause){if(current===sequence)error=cause instanceof Error?cause.message:String(cause);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{void workspace.revision;if(workspace.ready&&workspace.selectedId){accountStatus=null;review=null;readiness=null;report=null;reference='';reviewConfirm=false;backupConfirm=false;activateConfirm=false;closeConfirm=false;storageConfirm=false;void load(workspace.selectedId);}});
 async function action(run:(ws:string)=>Promise<void>){if(saving||loading)return;const ws=workspace.selectedId;saving=true;error='';notice='';try{await run(ws);}catch(cause){if(ws===workspace.selectedId)error=cause instanceof Error?cause.message:String(cause);}finally{saving=false;}}
 function preview(){void action(async ws=>{const result=await call(endpoint(ws)+'/preview','POST',{cutoverOn:cutover});if(ws===workspace.selectedId){review={id:result.id,state:'draft',plan:result.plan};reviewConfirm=false;reference='';await load(ws);}});}
 function openReview(id:string){void action(async ws=>{const result=await call(endpoint(ws)+'/reviews/'+id);if(ws===workspace.selectedId){review=result.review;reference=result.review.review_reference??'';reviewConfirm=false;backupConfirm=false;activateConfirm=false;}});}
 function recordReview(){void action(async ws=>{await call(endpoint(ws)+'/reviews/'+review.id+'/review','POST',{reference,confirm:reviewConfirm});if(ws===workspace.selectedId){review={...review,state:'reviewed'};await load(ws);notice=copy('Review evidence recorded. Activation is a separate owner action.','Bukti peninjauan tersimpan. Aktivasi adalah tindakan pemilik yang terpisah.');}});}
 function activate(){void action(async ws=>{await call(endpoint(ws)+'/reviews/'+review.id+'/activate','POST',{confirm:activateConfirm,backupConfirmed:backupConfirm});if(ws===workspace.selectedId){review=null;await load(ws);notice=copy('Accrual accounting activated. Cash history and wallet balances are unchanged. Postings are synchronizing.','Akuntansi akrual aktif. Riwayat kas dan saldo akun tetap sama. Posting sedang disinkronkan.');}});}
 function sync(){void action(async ws=>{const result=await call(endpoint(ws)+'/sync','POST',{});if(ws===workspace.selectedId){await load(ws);notice=copy('Remaining postings: ','Posting tersisa: ')+result.pending;}});}
 function closePeriod(){void action(async ws=>{await call(endpoint(ws)+'/close','POST',{through:closeThrough,confirm:closeConfirm});if(ws===workspace.selectedId){closeConfirm=false;await load(ws);notice=copy('Period closed. Future corrections must use an open date.','Periode ditutup. Koreksi berikutnya harus memakai tanggal terbuka.');}});}
 const query=()=>new URLSearchParams({from,through,basis});
 function statement(){void action(async ws=>{const result=await call(endpoint(ws)+'/statement?'+query());if(ws===workspace.selectedId)report=result;});}
 function preflight(){void action(async ws=>{const result=await call(endpoint(ws)+'/readiness','POST',{});if(ws===workspace.selectedId)readiness=result;});}
 function storageCheck(){storageConfirm=false;void action(async ws=>{const result=await call(endpoint(ws)+'/storage-check','POST',{confirm:true});if(ws===workspace.selectedId)notice=result.message;});}
 function reviewState(value:string){return value==='draft'?copy('Awaiting review','Menunggu peninjauan'):value==='reviewed'?copy('Reviewed · ready for owner activation','Ditinjau · siap diaktifkan pemilik'):value==='applied'?copy('Activated','Diaktifkan'):copy('Review status unavailable','Status peninjauan tidak tersedia');}
 function accountClass(value:string){return ({asset:copy('Assets · what the business owns','Aset · yang dimiliki bisnis'),liability:copy('Liabilities · what the business owes','Liabilitas · kewajiban bisnis'),equity:copy('Equity · owner’s share','Ekuitas · bagian pemilik'),income:copy('Income','Pendapatan'),expense:copy('Expenses','Beban')} as Record<string,string>)[value]??value;}
 function accountName(row:any){const type=String(row.code).split(':')[1];return String(row.code).startsWith('accrual:')?({ar:copy('Unpaid customer invoices','Invoice pelanggan belum lunas'),ap:copy('Unpaid supplier bills','Tagihan pemasok belum lunas'),revenue:copy('Sales recorded when invoiced','Penjualan tercatat saat invoice terbit'),cost:copy('Purchases recorded when billed','Pembelian tercatat saat tagihan terbit'),tax:copy('Sales tax payable','Pajak penjualan terutang'),opening:copy('Starting balance adjustment','Penyesuaian saldo awal'),deposit:copy('Customer funds awaiting allocation','Dana pelanggan belum dialokasikan'),fx_gain:copy('Currency conversion gains','Keuntungan selisih kurs'),fx_loss:copy('Currency conversion losses','Kerugian selisih kurs')} as Record<string,string>)[type]??row.name:row.name;}
 function checkName(value:string){return ({'Database & migrations':copy('Database and accounting setup','Database dan pengaturan akuntansi'),Redis:copy('Background-job connection','Koneksi pekerjaan latar belakang'),SMTP:copy('Email service','Layanan email'),'File storage':copy('Invoice and attachment storage','Penyimpanan invoice dan lampiran'),'Backup storage':copy('Backup storage','Penyimpanan cadangan'),'Encryption keyring':copy('Data encryption','Enkripsi data'),'Public URLs':copy('App and login addresses','Alamat aplikasi dan login')} as Record<string,string>)[value]??value;}
 function checkHelp(check:any){if(check.status!=='passed')return copy('Check this service’s configuration, permissions, and connection. The check did not confirm it is ready.','Periksa konfigurasi, izin, dan koneksi layanan ini. Pemeriksaan belum mengonfirmasi kesiapannya.');return ({'Database & migrations':copy('The database is reachable and the required accounting tables are present.','Database dapat diakses dan tabel akuntansi yang dibutuhkan tersedia.'),Redis:copy('The job service is reachable. Check separately that your background workers are running.','Layanan antrean dapat diakses. Pastikan secara terpisah bahwa pekerja latar belakang berjalan.'),SMTP:copy('The app can connect to the email service. Check inbox delivery with an actual invoice email.','Aplikasi dapat terhubung ke layanan email. Periksa penerimaan di kotak masuk dengan email invoice nyata.'),'File storage':copy('The file storage location is reachable. Use the encrypted storage check to confirm upload and retrieval.','Lokasi penyimpanan file dapat diakses. Gunakan pemeriksaan penyimpanan terenkripsi untuk memastikan unggah dan pengambilan.'),'Backup storage':copy('The backup storage location is reachable. A backup restore must be checked separately.','Lokasi penyimpanan cadangan dapat diakses. Pemulihan cadangan perlu diperiksa secara terpisah.'),'Encryption keyring':copy('The active key can encrypt and decrypt sample data. Keep historical keys available.','Kunci aktif dapat mengenkripsi dan mendekripsi data contoh. Simpan kunci lama agar tetap tersedia.'),'Public URLs':copy('App and login settings are compatible. Public access and payment notifications need separate checks.','Pengaturan aplikasi dan login sesuai. Akses publik dan notifikasi pembayaran perlu diperiksa terpisah.')} as Record<string,string>)[check.name]??check.message;}
</script>
<svelte:head><title>CapyBudget · {copy('Business accounting','Akuntansi bisnis')}</title></svelte:head>
<LoadingScope active={loading||saving}/>
<PageHeader title={copy('Business accounting','Akuntansi bisnis')} description={copy('Keep cash tracking clear. Review and enable accrual accounting when your business is ready.','Pantau kas dengan jelas. Tinjau dan aktifkan akuntansi akrual saat bisnis Anda siap.')}/>
{#if error}<p role="alert" class="mb-4 rounded-[14px] border-2 border-border bg-muted p-4 text-sm">{error}</p>{/if}
{#if notice}<p role="status" class="mb-4 rounded-[14px] border-2 border-border bg-muted p-4 text-sm">{notice}</p>{/if}
{#if accountStatus}<div class="space-y-6">
<Card.Root><Card.Header><Card.Title>{copy('Accounting basis','Dasar akuntansi')}</Card.Title><Card.Description>{copy('Cash records money when it moves. Accrual recognizes an invoice or vendor bill when issued, then treats payments as settlements.','Kas mencatat uang saat berpindah. Akrual mencatat faktur atau tagihan pemasok saat diterbitkan, lalu memperlakukan pembayaran sebagai pelunasan.')}</Card.Description></Card.Header><Card.Content class="space-y-4">
<div class="grid gap-4 sm:grid-cols-2"><div class="space-y-2 rounded-[20px] border-2 border-border bg-muted/40 p-4"><h2 class="text-sm font-semibold">{copy('Cash basis: follow payments','Dasar kas: ikuti pembayaran')}</h2><p class="text-sm leading-relaxed text-muted-foreground">{copy('An invoice issued in January and paid in February counts as income in February.','Invoice terbit pada Januari dan dibayar pada Februari dihitung sebagai pendapatan pada Februari.')}</p></div><div class="space-y-2 rounded-[20px] border-2 border-border bg-muted/40 p-4"><h2 class="text-sm font-semibold">{copy('Accrual basis: follow issued documents','Dasar akrual: ikuti dokumen terbit')}</h2><p class="text-sm leading-relaxed text-muted-foreground">{copy('The same invoice counts as income in January. Its February payment settles the unpaid invoice.','Invoice yang sama dihitung sebagai pendapatan pada Januari. Pembayaran Februari melunasi invoice yang belum dibayar.')}</p></div></div><p class="text-sm text-muted-foreground">{copy('You can view cash statements immediately. Accrual requires a reviewed starting date and owner activation.','Anda dapat langsung melihat laporan kas. Akrual membutuhkan tanggal mulai yang ditinjau dan aktivasi oleh pemilik.')}</p>
<p class="font-semibold">{accountStatus.settings?copy('Accrual active since ','Akrual aktif sejak ')+formatDate(accountStatus.settings.cutover_on):copy('Cash basis active','Dasar kas aktif')}</p>
{#if accountStatus.settings}<p class="text-sm text-muted-foreground">{copy('Records locked through: ','Catatan dikunci sampai: ')}{accountStatus.settings.closed_through?formatDate(accountStatus.settings.closed_through):copy('No period closed yet','Belum ada periode ditutup')} · {copy('Accounting entries waiting to sync: ','Catatan akuntansi menunggu sinkronisasi: ')}{accountStatus.pending}</p>{#if ['owner','accountant'].includes(accountStatus.role)}<Button variant="outline" disabled={saving} onclick={sync}>{copy('Update accounting entries','Perbarui catatan akuntansi')}</Button>{/if}{/if}
{#if accountStatus.settings}<p class="text-sm leading-relaxed text-muted-foreground">{accountStatus.pending?copy('Some entries are waiting to be recorded in the accrual reports. Update them before reviewing the reports or closing a period. Foreign-currency entries require an exchange rate for their posting date.','Beberapa catatan menunggu untuk dimasukkan ke laporan akrual. Perbarui sebelum meninjau laporan atau menutup periode. Catatan mata uang asing membutuhkan kurs sesuai tanggal pencatatannya.'):copy('No accounting entries are waiting to sync. You can review a financial statement below.','Tidak ada catatan akuntansi yang menunggu sinkronisasi. Anda dapat meninjau laporan keuangan di bawah.')}</p>{/if}</Card.Content></Card.Root>
{#if ['owner','accountant'].includes(accountStatus.role)&&!accountStatus.settings}
<Card.Root><Card.Header><Card.Title>{copy('1. Choose when accrual starts','1. Pilih kapan akrual dimulai')}</Card.Title><Card.Description>{copy('A preview changes no cash history or balances. It shows opening unpaid invoices and bills, plus the exact posting policy.','Pratinjau tidak mengubah riwayat atau saldo kas. Pratinjau menampilkan piutang dan utang awal serta kebijakan posting yang tepat.')}</Card.Description></Card.Header><Card.Content class="space-y-4">
<Field.Field><Field.FieldLabel for="accounting-cutover">{copy('Accrual start date','Tanggal mulai akrual')}</Field.FieldLabel><DatePicker id="accounting-cutover" aria-describedby="accounting-cutover-help" disabled={saving||loading} bind:value={cutover}/><p id="accounting-cutover-help" class="text-sm leading-relaxed text-muted-foreground">{copy('Choose today or an earlier date. Older unpaid invoices and supplier bills become starting balances. Keep a restorable backup and arrange an accounting review before activating.','Pilih hari ini atau tanggal sebelumnya. Invoice dan tagihan pemasok lama yang belum lunas menjadi saldo awal. Siapkan cadangan yang dapat dipulihkan dan peninjauan akuntansi sebelum mengaktifkan.')}</p></Field.Field>
<Button disabled={saving||!cutover} onclick={preview}>{copy('Create conversion preview','Buat pratinjau konversi')}</Button>
{#if accountStatus.reviews.length}<ul class="divide-y divide-border">{#each accountStatus.reviews as r(r.id)}<li class="flex flex-wrap items-center justify-between gap-3 py-3"><span class="text-sm">{formatDate(r.cutoverOn)} · {reviewState(r.state)}</span><Button variant="outline" disabled={saving} onclick={()=>openReview(r.id)}>{copy('Open preview','Buka pratinjau')}</Button></li>{/each}</ul>{/if}
</Card.Content></Card.Root>
{#if review}<Card.Root><Card.Header><Card.Title>{copy('2. Review the starting balances','2. Tinjau saldo awal')}</Card.Title></Card.Header><Card.Content class="space-y-4">
<p class="text-sm">{copy('Cutover: ','Peralihan: ')}{formatDate(review.plan.cutover)} · {review.plan.documentCount} {copy('issued documents included','dokumen terbit disertakan')} · {review.plan.cashEntryCount} {copy('existing cash entries checked','catatan kas yang diperiksa')}</p><p class="text-sm leading-relaxed text-muted-foreground">{copy('Customers owe you and you owe suppliers: these are unpaid amounts from before the chosen start date. The preview also covers issued documents from the start date onward.','Piutang pelanggan dan utang pemasok: ini adalah sisa pembayaran dari sebelum tanggal mulai. Pratinjau juga mencakup dokumen terbit sejak tanggal mulai.')}</p>
<div class="overflow-x-auto"><table class="w-full text-left text-sm"><caption class="sr-only">{copy('Opening balances by currency','Saldo awal per mata uang')}</caption><thead><tr><th class="p-3">{copy('Currency','Mata uang')}</th><th class="p-3">{copy('Customers owe you','Pelanggan berutang kepada Anda')}</th><th class="p-3">{copy('You owe suppliers','Anda berutang kepada pemasok')}</th></tr></thead><tbody>{#each Object.entries(review.plan.totals) as [currency,total]}<tr class="border-t border-border"><td class="p-3">{currency}</td><td class="p-3"><MoneyDisplay amount={String((total as any).receivable)} {currency}/></td><td class="p-3"><MoneyDisplay amount={String((total as any).payable)} {currency}/></td></tr>{/each}</tbody></table></div>{#if !Object.keys(review.plan.totals).length}<p class="text-sm text-muted-foreground">{copy('No unpaid customer invoices or supplier bills need starting balances for this date.','Tidak ada invoice pelanggan atau tagihan pemasok yang belum lunas yang membutuhkan saldo awal untuk tanggal ini.')}</p>{/if}
<details class="rounded-[14px] border border-border"><summary class="min-h-11 cursor-pointer rounded-[14px] px-4 py-3 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-ring">{copy('What this conversion records','Apa yang dicatat dalam peralihan ini')}</summary><p class="px-4 pb-4 text-sm leading-relaxed text-muted-foreground">{copy('Old unpaid documents open against retained equity. Historical income is not recognized again. Purchase tax stays in cost; no input-tax eligibility is assumed. Refunds reopen receivables rather than cancelling sales. Cash and accrual reports remain separate.','Dokumen lama yang belum lunas menjadi saldo awal terhadap ekuitas ditahan. Pendapatan lama tidak dicatat ulang. Pajak pembelian tetap menjadi biaya; kelayakan kredit pajak tidak diasumsikan. Pengembalian dana membuka kembali piutang tanpa membatalkan penjualan. Laporan kas dan akrual tetap terpisah.')}</p></details>
{#if review.state==='draft'}<Field.Field><Field.FieldLabel for="accounting-review-reference">{copy('Reviewer and review reference','Peninjau dan referensi peninjauan')}</Field.FieldLabel><Input id="accounting-review-reference" aria-describedby="accounting-review-help" bind:value={reference} maxlength={1000} placeholder={copy('Reviewer name and signed review reference','Nama peninjau dan referensi peninjauan bertanda tangan')}/><p id="accounting-review-help" class="text-sm text-muted-foreground">{copy('At least 8 characters. Record who reviewed the balances and where their signed review is documented.','Minimal 8 karakter. Catat siapa yang meninjau saldo dan referensi dokumen peninjauan yang ditandatangani.')}</p></Field.Field>
<label class="flex min-h-11 items-start gap-3 text-sm"><Checkbox.Root id="accounting-review-confirm" aria-label={copy('Confirm accounting review obtained','Konfirmasi peninjauan akuntansi diperoleh')} bind:checked={reviewConfirm} class="mt-1 shrink-0"/>{copy('I have obtained review of the posting policy, opening balances, tax treatment and historical conversion. Recording this evidence does not certify statutory compliance.','Saya telah memperoleh peninjauan kebijakan posting, saldo awal, perlakuan pajak, dan konversi riwayat. Pencatatan bukti ini bukan sertifikasi kepatuhan hukum.')}</label>
<Button disabled={saving||!reviewConfirm||reference.trim().length<8} onclick={recordReview}>{copy('Record review evidence','Catat bukti peninjauan')}</Button>
{:else}<p role="status" class="text-sm">{copy('Review evidence recorded.','Bukti peninjauan tersimpan.')}</p>{/if}
{#if review.state==='reviewed'&&accountStatus.role==='owner'}<hr class="border-border"/><h2 class="text-base font-semibold">{copy('3. Owner activates accrual accounting','3. Pemilik mengaktifkan akuntansi akrual')}</h2>
<label class="flex min-h-11 items-start gap-3 text-sm"><Checkbox.Root id="accounting-backup-confirm" aria-label={copy('Confirm restorable backup available','Konfirmasi cadangan dapat dipulihkan tersedia')} bind:checked={backupConfirm} class="mt-1 shrink-0"/>{copy('I have a recent backup that can be restored.','Saya memiliki cadangan terbaru yang dapat dipulihkan.')}</label>
<label class="flex min-h-11 items-start gap-3 text-sm"><Checkbox.Root id="accounting-activate-confirm" aria-label={copy('Confirm accrual activation','Konfirmasi aktivasi akrual')} bind:checked={activateConfirm} class="mt-1 shrink-0"/>{copy('Apply this reviewed cutover. Switching back requires reviewed corrective entries.','Terapkan peralihan yang telah ditinjau ini. Beralih kembali membutuhkan entri koreksi yang ditinjau.')}</label>
<Button disabled={saving||!backupConfirm||!activateConfirm} onclick={activate}>{copy('Activate accrual accounting','Aktifkan akuntansi akrual')}</Button>{:else if review.state==='reviewed'}<p class="text-sm text-muted-foreground">{copy('Ask the business owner to confirm the backup and activate this reviewed start date.','Minta pemilik bisnis mengonfirmasi cadangan dan mengaktifkan tanggal mulai yang telah ditinjau.')}</p>{/if}
</Card.Content></Card.Root>{/if}{/if}
<Card.Root><Card.Header><Card.Title>{copy('Financial statements','Laporan keuangan')}</Card.Title><Card.Description>{copy('Profit and loss for the selected period, and balances as of the end date. All totals use the workspace base currency.','Laba rugi untuk periode pilihan, dan saldo pada tanggal akhir. Semua total memakai mata uang dasar ruang kerja.')}</Card.Description></Card.Header><Card.Content class="space-y-4">
<form class="grid items-end gap-4 sm:grid-cols-2 lg:grid-cols-4" onsubmit={event=>{event.preventDefault();statement();}}>
<Field.Field><Field.FieldLabel for="accounting-basis">{copy('How income and costs are recorded','Cara pendapatan dan biaya dicatat')}</Field.FieldLabel><ChoiceSelect id="accounting-basis" bind:value={basis} items={[{value:'cash',label:copy('Cash · when paid','Kas · saat dibayar')},...(accountStatus.settings?[{value:'accrual',label:copy('Accrual · when issued','Akrual · saat diterbitkan')}]:[])]}/></Field.Field>
<Field.Field><Field.FieldLabel for="accounting-from">{copy('Period start','Awal periode')}</Field.FieldLabel><DatePicker id="accounting-from" bind:value={from}/></Field.Field><Field.Field><Field.FieldLabel for="accounting-through">{copy('Period end','Akhir periode')}</Field.FieldLabel><DatePicker id="accounting-through" bind:value={through}/></Field.Field>
<Button type="submit" disabled={saving||!from||!through}>{copy('Show statement','Tampilkan laporan')}</Button></form><p class="text-sm leading-relaxed text-muted-foreground">{basis==='cash'?copy('Cash statements follow the dates money was recorded as received or paid.','Laporan kas mengikuti tanggal uang dicatat sebagai diterima atau dibayar.'):copy('Accrual statements follow issued invoices and supplier bills. Choose a start date on or after the reviewed accrual start date.','Laporan akrual mengikuti invoice dan tagihan pemasok yang diterbitkan. Pilih awal periode pada atau setelah tanggal mulai akrual yang ditinjau.')}</p>
{#if report}<h2 class="text-base font-semibold">{copy('Income, costs, and profit','Pendapatan, biaya, dan laba')}</h2><p class="text-sm text-muted-foreground">{copy('Income minus expenses gives the profit or loss for this period.','Pendapatan dikurangi beban menghasilkan laba atau rugi untuk periode ini.')}</p><p class="text-sm font-semibold">{report.basis==='accrual'?copy('Accrual basis','Dasar akrual'):copy('Cash basis','Dasar kas')} · {formatDate(report.from)} – {formatDate(report.through)}</p>
<div class="grid gap-4 sm:grid-cols-3">{#each [{label:copy('Income','Pendapatan'),amount:report.profitAndLoss.income},{label:copy('Expense','Beban'),amount:report.profitAndLoss.expense},{label:copy('Profit / loss','Laba / rugi'),amount:report.profitAndLoss.profit}] as metric}<div class="space-y-2 rounded-[20px] border-2 border-border bg-muted/40 p-4"><p class="text-sm text-muted-foreground">{metric.label}</p><MoneyDisplay amount={metric.amount} currency={report.currency} size="xl"/></div>{/each}</div>
<h2 class="text-base font-semibold">{copy('What the business owns and owes','Yang dimiliki dan menjadi kewajiban bisnis')}</h2><p class="text-sm leading-relaxed text-muted-foreground">{copy('Assets are what the business owns. Liabilities are what it owes. Equity is the owner’s remaining share, including accumulated profit. These balances use the period end date.','Aset adalah yang dimiliki bisnis. Liabilitas adalah kewajiban bisnis. Ekuitas adalah bagian pemilik yang tersisa, termasuk laba terkumpul. Saldo ini memakai tanggal akhir periode.')}</p><dl class="grid gap-4 sm:grid-cols-3">{#each [{label:copy('Assets','Aset'),amount:report.balanceSheet.assets},{label:copy('Liabilities','Liabilitas'),amount:report.balanceSheet.liabilities},{label:copy('Equity incl. retained earnings','Ekuitas termasuk laba ditahan'),amount:report.balanceSheet.equity}] as metric}<div class="space-y-2"><dt class="text-sm text-muted-foreground">{metric.label}</dt><dd><MoneyDisplay amount={metric.amount} currency={report.currency}/></dd></div>{/each}</dl>
<p role="status" class="text-sm">{report.balanced?copy('Account totals balance. Review the underlying records for accuracy.','Total akun seimbang. Tinjau catatan sumber untuk memastikan ketepatannya.'):copy('Trial balance requires review.','Neraca saldo perlu ditinjau.')}</p>
<a class="inline-flex min-h-11 items-center rounded-full border-2 border-border px-4 text-sm font-semibold" href={endpoint()+'/statement?'+new URLSearchParams({from:report.from,through:report.through,basis:report.basis,format:'csv'})}>{copy('Export trial balance CSV','Ekspor neraca saldo CSV')}</a>
<details class="rounded-[14px] border border-border"><summary class="min-h-11 cursor-pointer rounded-[14px] px-4 py-3 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-ring">{copy('Detailed account balances for review','Rincian saldo akun untuk peninjauan')}</summary><p class="px-4 pb-4 text-sm leading-relaxed text-muted-foreground">{copy('Original-currency balances keep each account’s currency. Base-currency balances convert them to the business currency. Positive figures are debit balances; negative figures are credit balances. Income and liabilities usually have credit balances.','Saldo mata uang asli memakai mata uang masing-masing akun. Saldo mata uang bisnis dikonversi ke mata uang bisnis. Angka positif adalah saldo debit; angka negatif adalah saldo kredit. Pendapatan dan liabilitas biasanya memiliki saldo kredit.')}</p><div class="overflow-x-auto"><table class="w-full text-left text-sm"><caption class="sr-only">{copy('Trial balance','Neraca saldo')}</caption><thead><tr><th class="p-3">{copy('Account','Akun')}</th><th class="p-3">{copy('Account type','Jenis akun')}</th><th class="p-3">{copy('Original-currency balance','Saldo mata uang asli')}</th><th class="p-3">{copy('Business-currency balance','Saldo mata uang bisnis')}</th></tr></thead><tbody>{#each report.rows as row(row.id)}<tr class="border-t border-border"><td class="p-3">{accountName(row)}</td><td class="p-3">{accountClass(row.class)}</td><td class="p-3"><MoneyDisplay amount={row.native_balance} currency={row.currency}/></td><td class="p-3"><MoneyDisplay amount={row.base_balance} currency={report.currency}/></td></tr>{/each}</tbody></table></div></details>{/if}
</Card.Content></Card.Root>
{#if accountStatus.settings&&['owner','accountant'].includes(accountStatus.role)}<Card.Root><Card.Header><Card.Title>{copy('Close a reviewed period','Tutup periode yang ditinjau')}</Card.Title><Card.Description>{copy('Closing stops backdated cash and accrual postings. Correct mistakes using a date in an open period.','Penutupan menghentikan posting kas dan akrual bertanggal lampau. Koreksi kesalahan memakai tanggal dalam periode terbuka.')}</Card.Description></Card.Header><Card.Content class="space-y-4">
<Field.Field><Field.FieldLabel for="accounting-close">{copy('Lock records up to this date','Kunci catatan hingga tanggal ini')}</Field.FieldLabel><DatePicker id="accounting-close" aria-describedby="accounting-close-help" bind:value={closeThrough}/><p id="accounting-close-help" class="text-sm leading-relaxed text-muted-foreground">{copy('Use this after reviewing the statement and reconciling entries. Records on or before this date become locked for new postings. Later corrections must use an open date; there is no reopen action here.','Gunakan setelah meninjau laporan dan mencocokkan catatan. Catatan pada atau sebelum tanggal ini dikunci untuk pencatatan baru. Koreksi berikutnya harus memakai tanggal terbuka; tidak ada tindakan buka kembali di sini.')}</p></Field.Field><label class="flex min-h-11 items-center gap-3 text-sm"><Checkbox.Root id="accounting-close-confirm" aria-label={copy('Confirm period reviewed and reconciled','Konfirmasi periode ditinjau dan direkonsiliasi')} bind:checked={closeConfirm}/>{copy('I reviewed and reconciled this period.','Saya telah meninjau dan merekonsiliasi periode ini.')}</label><Button variant="outline" disabled={saving||!closeConfirm} onclick={closePeriod}>{copy('Close period','Tutup periode')}</Button>
</Card.Content></Card.Root>{/if}
{#if accountStatus.role==='owner'}<Card.Root><Card.Header><Card.Title>{copy('Optional service checks','Pemeriksaan layanan opsional')}</Card.Title><Card.Description>{copy('Checks use the environment where this API is running. A local pass does not certify the VPS.','Pemeriksaan memakai lingkungan tempat API ini berjalan. Hasil lokal tidak menyatakan VPS telah terverifikasi.')}</Card.Description></Card.Header><Card.Content class="space-y-4"><div class="flex flex-wrap gap-3"><Button variant="outline" disabled={saving} onclick={preflight}>{copy('Check connections','Periksa koneksi')}</Button><Button variant="outline" disabled={saving} onclick={()=>storageConfirm=true}>{copy('Check encrypted storage','Periksa penyimpanan terenkripsi')}</Button></div>
{#if readiness}<p class="text-sm font-semibold">{readiness.environment==='production'?copy('Live server','Server produksi'):copy('Local environment','Lingkungan lokal')} · {formatDateTime(readiness.checkedAt,ui.locale)}</p><ul class="divide-y divide-border">{#each readiness.checks as check}<li class="space-y-1 py-3"><p class="font-semibold">{checkName(check.name)} · {check.status==='passed'?copy('Passed','Lulus'):copy('Needs attention','Perlu perhatian')}</p><p class="text-sm text-muted-foreground">{checkHelp(check)}</p></li>{/each}</ul><p class="text-sm text-muted-foreground">{copy('No email or payment was sent. Check a real invoice email, an authenticated payment callback and a backup restore separately.','Tidak ada email atau pembayaran dikirim. Periksa email faktur nyata, callback pembayaran terautentikasi, dan pemulihan cadangan secara terpisah.')}</p>{/if}
</Card.Content></Card.Root>{/if}
</div>{/if}

<AlertDialog.Root open={storageConfirm} onOpenChange={next=>{if(!saving)storageConfirm=next;}}><AlertDialog.Content><AlertDialog.Header><AlertDialog.Title>{copy('Check encrypted file storage?','Periksa penyimpanan file terenkripsi?')}</AlertDialog.Title><AlertDialog.Description>{copy('Uploads a temporary encrypted PDF, reads it back, and deletes it from the configured storage. This checks file access in the environment where this API is running.','Mengunggah PDF terenkripsi sementara, membacanya kembali, lalu menghapusnya dari penyimpanan yang dikonfigurasi. Ini memeriksa akses file pada lingkungan tempat API ini berjalan.')}</AlertDialog.Description></AlertDialog.Header><AlertDialog.Footer><AlertDialog.Cancel disabled={saving} onclick={()=>storageConfirm=false}>{copy('Cancel','Batal')}</AlertDialog.Cancel><Button disabled={saving||loading} onclick={storageCheck}>{copy('Run storage check','Jalankan pemeriksaan penyimpanan')}</Button></AlertDialog.Footer></AlertDialog.Content></AlertDialog.Root>
