<script lang="ts">
 import {getContext,untrack} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import * as Dialog from '$lib/components/ui/dialog';import * as AlertDialog from '$lib/components/ui/alert-dialog';import {Input} from '$lib/components/ui/input';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import CurrencySelect from '$lib/components/forms/currency-select.svelte';import AmountInput from '$lib/components/forms/amount-input.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import PageHeader from '$lib/components/shared/page-header.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';
 let {kind}:{kind:'contacts'|'catalog'}=$props();const workspace=getContext<{selectedId:string;ready:boolean;revision?:number;items:{id:string;currency:string}[]}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT);const copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 const title=$derived(kind==='contacts'?copy('Customers & vendors','Pelanggan & pemasok'):copy('Products & services','Produk & jasa'));
 type RecordItem={id:string;name:string;kind:string;version:number;details?:any;sku?:string;unit?:string;description?:string;unit_price?:string;currency?:string;tax_rate_id?:string|null};
 let rows:RecordItem[]=$state([]),page=$state(1),search=$state(''),loading=$state(false),saving=$state(false),error=$state(''),notice=$state(''),open=$state(false),editing:RecordItem|null=$state(null),canEdit=$state(false),rates:any[]=$state([]),sequence=0;
 let appliedSearch=$state(''),archiveTarget:RecordItem|null=$state(null);
 let name=$state(''),recordKind=$state('customer'),email=$state(''),phone=$state(''),taxId=$state(''),street=$state(''),city=$state(''),region=$state(''),postalCode=$state(''),country=$state(''),sku=$state(''),unit=$state('item'),description=$state(''),price=$state(''),currency=$state('IDR'),taxRateId=$state('');
 const endpoint=(ws:string)=>'/api/workspaces/'+ws;
 async function call(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.message??copy('Request failed.','Permintaan gagal.'));return result;}
 async function load(ws:string){const current=++sequence,currentKind=kind,query=search;loading=true;error='';try{const [result,access,tax]=await Promise.all([call(endpoint(ws)+'/'+kind+'?'+new URLSearchParams({q:query,page:String(page)})),call(endpoint(ws)+'/business-access'),kind==='catalog'?call(endpoint(ws)+'/business-tax'):Promise.resolve({rates:[]})]);if(current===sequence&&ws===workspace.selectedId&&kind===currentKind){appliedSearch=query;rows=result.items;canEdit=['owner','accountant'].includes(access.role);rates=tax.rates.filter((r:any)=>!r.archivedAt);}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{void workspace.revision;void kind;if(workspace.ready&&workspace.selectedId){const ws=workspace.selectedId;untrack(()=>{page=1;search='';appliedSearch='';notice='';rows=[];canEdit=false;open=false;archiveTarget=null;void load(ws);});}});
 function edit(item:RecordItem|null=null){editing=item;name=item?.name??'';recordKind=item?.kind??(kind==='contacts'?'customer':'service');email=item?.details?.email??'';phone=item?.details?.phone??'';taxId=item?.details?.taxId??'';const address=item?.details?.address??{};street=address.street??'';city=address.city??'';region=address.region??'';postalCode=address.postalCode??'';country=address.country??'';sku=item?.sku??'';unit=item?.unit??'item';description=item?.description??'';price=item?.unit_price??'';currency=item?.currency??workspace.items.find(x=>x.id===workspace.selectedId)?.currency??'IDR';taxRateId=item?.tax_rate_id??'';error='';open=true;}
 async function save(event:SubmitEvent){event.preventDefault();if(saving||loading)return;const ws=workspace.selectedId,currentKind=kind;saving=true;error='';notice='';const body=kind==='contacts'?{name,kind:recordKind,version:editing?.version,details:{email,phone,taxId,address:{street,city,region,postalCode,country}}}:{name,kind:recordKind,version:editing?.version,sku,unit,description:description||name,unitPrice:price,currency,taxRateId:taxRateId||null};try{const result=await call(endpoint(ws)+'/'+kind+(editing?'/'+editing.id:''),editing?'PATCH':'POST',body);if(ws===workspace.selectedId&&currentKind===kind){open=false;await load(ws);if(ws!==workspace.selectedId||kind!==currentKind)return;notice=result.duplicates?.length?copy('Saved. A contact with the same name exists; review both before using them.','Tersimpan. Ada kontak bernama sama; tinjau keduanya sebelum digunakan.'):copy('Saved. Existing issued invoices keep their original details.','Tersimpan. Faktur terbit tetap memakai detail aslinya.');}}catch(e){if(ws===workspace.selectedId)error=e instanceof Error?e.message:String(e);}finally{saving=false;}}
 async function archive(){const item=archiveTarget;if(!item||saving||loading)return;const ws=workspace.selectedId;archiveTarget=null;saving=true;error='';notice='';try{await call(endpoint(ws)+'/'+kind+'/'+item.id,'DELETE');if(ws===workspace.selectedId){await load(ws);if(ws===workspace.selectedId)notice=copy('Archived. Existing issued invoices keep their original details.','Diarsipkan. Invoice yang sudah diterbitkan tetap menyimpan detail aslinya.');}}catch(e){if(ws===workspace.selectedId)error=e instanceof Error?e.message:String(e);}finally{saving=false;}}
 function typeLabel(value:string){return value==='customer'?copy('Customer','Pelanggan'):value==='vendor'?copy('Vendor','Pemasok'):value==='both'?copy('Customer and vendor','Pelanggan dan pemasok'):value==='product'?copy('Product','Produk'):value==='service'?copy('Service','Jasa'):copy('Other','Lainnya');}
 function typeHelp(value:string){return value==='customer'?copy('Someone you sell to. Select them when preparing an invoice.','Pihak yang membeli dari Anda. Pilih saat menyiapkan invoice.'):value==='vendor'?copy('Someone you buy from. Select them when recording a supplier bill.','Pihak yang menjual kepada Anda. Pilih saat mencatat tagihan pemasok.'):value==='both'?copy('A contact you both sell to and buy from. Available for customer and supplier records.','Kontak yang menjadi pembeli sekaligus pemasok Anda. Tersedia untuk catatan pelanggan dan pemasok.'):value==='product'?copy('A physical item you sell, priced per unit, such as a piece or box.','Barang fisik yang Anda jual dengan harga per satuan, seperti buah atau kotak.'):copy('Work you provide, priced per unit, such as an hour, session, or project.','Pekerjaan yang Anda berikan dengan harga per satuan, seperti jam, sesi, atau proyek.');}
 const addLabel=$derived(kind==='contacts'?copy('Add customer or vendor','Tambah pelanggan atau pemasok'):copy('Add product or service','Tambah produk atau jasa'));
 const dialogTitle=$derived.by(()=>kind==='contacts'?(editing?copy('Edit contact','Edit kontak'):copy('Add customer or vendor','Tambah pelanggan atau pemasok')):(editing?copy('Edit product or service','Edit produk atau jasa'):copy('Add product or service','Tambah produk atau jasa')));
</script>
<svelte:head><title>CapyBudget · {title}</title></svelte:head><LoadingScope active={loading||saving}/>
<PageHeader guidePath={kind==='contacts'?'/business/contacts':'/business/catalog'} {title} description={kind==='contacts'?copy('Save the people and businesses you sell to or buy from, then reuse their details in invoices and supplier bills.','Simpan orang dan bisnis yang menjadi pelanggan atau pemasok, lalu gunakan kembali detailnya pada invoice dan tagihan pemasok.'):copy('Keep reusable products, services, and prices ready for your next invoice draft.','Siapkan produk, jasa, dan harga yang dapat digunakan kembali pada draf invoice berikutnya.')}>
 {#snippet actions()}{#if canEdit}<Button disabled={loading||saving} onclick={()=>edit()}>{addLabel}</Button>{/if}{/snippet}
</PageHeader>
{#if error&&!open}<ErrorState title={copy('Could not update directory','Direktori gagal diperbarui')} message={error} onRetry={()=>load(workspace.selectedId)} retryLabel={copy('Reload directory','Muat ulang direktori')}/>{/if}
<div role="status" aria-live="polite" aria-atomic="true">{#if notice}<p class="mb-6 rounded-[14px] border border-border bg-muted p-4 text-sm leading-relaxed">{notice}</p>{/if}</div>
<Card.Root><Card.Header><Card.Title>{kind==='contacts'?copy('Your business contacts','Kontak bisnis Anda'):copy('Your product and service catalog','Katalog produk dan jasa Anda')}</Card.Title><Card.Description>{kind==='contacts'?copy('Customer means someone you sell to; vendor means someone you buy from. One contact can be both.','Pelanggan adalah pihak yang membeli dari Anda; pemasok adalah pihak yang menjual kepada Anda. Satu kontak dapat menjadi keduanya.'):copy('Saved prices are copied into invoice drafts when you select an item. Changing a saved item does not update an issued invoice.','Harga tersimpan disalin ke draf invoice saat Anda memilih item. Mengubah item tersimpan tidak memperbarui invoice yang sudah diterbitkan.')}</Card.Description></Card.Header>
<Card.Content class="space-y-6">
 <form class="flex flex-wrap items-end gap-3" onsubmit={event=>{event.preventDefault();page=1;void load(workspace.selectedId);}}><div class="min-w-0 flex-1 space-y-2"><label class="text-sm font-semibold" for="directory-search">{kind==='catalog'?copy('Search by name or item code','Cari berdasarkan nama atau kode item'):copy('Search by contact name','Cari berdasarkan nama kontak')}</label><Input id="directory-search" type="search" bind:value={search} maxlength={100} disabled={loading||saving} placeholder={kind==='catalog'?copy('e.g. Design session or DESIGN-01','mis. Sesi desain atau DESIGN-01'):copy('Enter a person or business name','Masukkan nama orang atau bisnis')}/></div><Button type="submit" disabled={loading||saving}>{copy('Search','Cari')}</Button>{#if appliedSearch}<Button variant="outline" disabled={loading||saving} onclick={()=>{search='';page=1;void load(workspace.selectedId);}}>{copy('Clear search','Hapus pencarian')}</Button>{/if}</form>
 {#if !loading&&!error}<div class="flex flex-wrap items-center justify-between gap-2"><p class="text-sm text-muted-foreground">{rows.length} {copy('shown on this page','ditampilkan di halaman ini')}{#if appliedSearch} · {copy('Results for ','Hasil untuk ')}“{appliedSearch}”{/if}</p>{#if !canEdit}<p class="text-sm text-muted-foreground">{copy('Owners and accountants can add, edit, and archive entries.','Pemilik dan akuntan dapat menambah, mengedit, dan mengarsipkan catatan.')}</p>{/if}</div>{/if}
 {#if !loading&&!error&&!rows.length}<div class="space-y-3 rounded-[20px] border-2 border-border bg-muted/40 p-6"><h2 class="text-base font-semibold">{appliedSearch?copy('No matching entries','Tidak ada catatan yang cocok'):kind==='contacts'?copy('Your first contact starts here','Mulai dengan kontak pertama Anda'):copy('Your catalog is ready for its first item','Katalog siap untuk item pertama Anda')}</h2><p class="text-sm leading-relaxed text-muted-foreground">{appliedSearch?copy('Try a different name or clear the search to see all entries.','Coba nama lain atau hapus pencarian untuk melihat semua catatan.'):kind==='contacts'?copy('Add a customer for invoices or a vendor for supplier bills.','Tambahkan pelanggan untuk invoice atau pemasok untuk tagihan pemasok.'):copy('Save an item code, unit, and price to use in an invoice draft.','Simpan kode item, satuan, dan harga untuk digunakan pada draf invoice.')}</p>{#if canEdit&&!appliedSearch}<Button onclick={()=>edit()}>{addLabel}</Button>{/if}</div>{/if}
 <ul class="divide-y divide-border">{#each rows as item(item.id)}
  <li class="space-y-4 py-6 first:pt-0 last:pb-0"><div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0 flex-1 space-y-2"><span class="inline-flex rounded-full border border-border bg-muted px-3 py-1 text-sm font-semibold">{typeLabel(item.kind)}</span><h2 class="break-words text-base font-semibold">{item.name}</h2>
   {#if kind==='contacts'}<dl class="grid gap-3 sm:grid-cols-2">{#if item.details?.email}<div class="space-y-1"><dt class="text-sm text-muted-foreground">Email</dt><dd class="break-all text-sm">{item.details.email}</dd></div>{/if}{#if item.details?.phone}<div class="space-y-1"><dt class="text-sm text-muted-foreground">{copy('Phone','Telepon')}</dt><dd class="break-words text-sm">{item.details.phone}</dd></div>{/if}</dl>{#if !item.details?.email&&!item.details?.phone}<p class="text-sm text-muted-foreground">{copy('No email or phone saved yet.','Belum ada email atau telepon tersimpan.')}</p>{/if}
   {:else}<p class="text-sm text-muted-foreground">{copy('Saved unit price','Harga satuan tersimpan')}</p><p><MoneyDisplay amount={String(item.unit_price)} currency={item.currency??'IDR'} size="lg"/> <span class="text-sm text-muted-foreground">{copy('per ','per ')}{item.unit}</span></p><p class="break-words text-sm text-muted-foreground">{copy('Item code (SKU): ','Kode item (SKU): ')}{item.sku}</p>{#if item.description}<p class="max-w-3xl break-words text-sm leading-relaxed">{item.description}</p>{/if}{/if}
  </div>{#if canEdit}<div class="flex flex-wrap gap-2"><Button variant="outline" disabled={saving||loading} aria-label={copy('Edit ','Edit ')+item.name} onclick={()=>edit(item)}>{copy('Edit','Edit')}</Button><Button variant="outline" disabled={saving||loading} aria-label={copy('Archive ','Arsipkan ')+item.name} onclick={()=>archiveTarget=item}>{copy('Archive','Arsipkan')}</Button></div>{/if}</div>
  <details class="rounded-[14px] border border-border"><summary class="min-h-11 cursor-pointer rounded-[14px] px-4 py-3 text-sm text-muted-foreground focus-visible:outline-2 focus-visible:outline-ring">{kind==='contacts'?copy('Address and billing details','Alamat dan detail penagihan'):copy('Unit and tax details','Detail satuan dan pajak')}</summary><dl class="grid gap-4 px-4 pb-4 sm:grid-cols-2">{#if kind==='contacts'}<div class="space-y-1"><dt class="text-sm font-semibold">{copy('Billing address','Alamat penagihan')}</dt><dd class="break-words text-sm leading-relaxed">{[item.details?.address?.street,item.details?.address?.city,item.details?.address?.region,item.details?.address?.postalCode,item.details?.address?.country].filter(Boolean).join(', ')||copy('No address saved','Belum ada alamat tersimpan')}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Tax number','Nomor pajak')}</dt><dd class="break-words text-sm">{item.details?.taxId||copy('Not provided','Belum diisi')}</dd></div>{:else}<div class="space-y-1"><dt class="text-sm font-semibold">{copy('Unit of sale','Satuan penjualan')}</dt><dd class="break-words text-sm">{item.unit}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Default tax rate','Tarif pajak bawaan')}</dt><dd class="break-words text-sm">{item.tax_rate_id?(rates.find(rate=>rate.id===item.tax_rate_id)?.name??copy('Saved rate unavailable or archived','Tarif tersimpan tidak tersedia atau diarsipkan')):copy('No default rate selected','Belum ada tarif bawaan dipilih')}</dd></div>{/if}</dl></details>
 </li>{/each}</ul>
 <nav class="flex flex-wrap items-center justify-between gap-3" aria-label={copy('Directory pages','Halaman direktori')}><Button variant="outline" disabled={loading||saving||page<=1} onclick={()=>{page--;void load(workspace.selectedId);}}>{copy('Previous','Sebelumnya')}</Button><span class="text-sm text-muted-foreground" aria-live="polite">{copy('Page','Halaman')} {page}</span><Button variant="outline" disabled={loading||saving||rows.length<50} onclick={()=>{page++;void load(workspace.selectedId);}}>{copy('Next','Berikutnya')}</Button></nav>
</Card.Content></Card.Root>
<Dialog.Root {open} onOpenChange={next=>{if(!saving)open=next;}}><Dialog.Content class="max-h-[85dvh] overflow-auto p-6 sm:max-w-2xl" showCloseButton={!saving}><Dialog.Header><Dialog.Title>{dialogTitle}</Dialog.Title><Dialog.Description>{copy('Fields marked “required” must be filled in. Changes here leave issued invoice details unchanged.','Kolom bertanda “wajib” harus diisi. Perubahan di sini tidak mengubah detail invoice yang sudah diterbitkan.')}</Dialog.Description></Dialog.Header>
<form onsubmit={save} class="space-y-6">{#if error}<p role="alert">{error}</p>{/if}<fieldset disabled={saving||loading} class="min-w-0 space-y-6" aria-label={dialogTitle}><section class="space-y-4" aria-labelledby="directory-basics"><h2 id="directory-basics" class="text-base font-semibold">{copy('Basic details','Detail dasar')}</h2><div class="grid gap-4 sm:grid-cols-2">
<Field.Field><Field.FieldLabel for="directory-name">{copy('Name (required)','Nama (wajib)')}</Field.FieldLabel><Input id="directory-name" bind:value={name} maxlength={200} required/></Field.Field>
<Field.Field><Field.FieldLabel for="directory-kind">{copy('Type (required)','Jenis (wajib)')}</Field.FieldLabel><ChoiceSelect id="directory-kind" aria-describedby="directory-kind-help" bind:value={recordKind} items={kind==='contacts'?[{value:'customer',label:copy('Customer','Pelanggan')},{value:'vendor',label:copy('Vendor','Pemasok')},{value:'both',label:copy('Customer and vendor','Pelanggan dan pemasok')}]:[{value:'product',label:copy('Product','Produk')},{value:'service',label:copy('Service','Jasa')}]}/></Field.Field>
</div><p id="directory-kind-help" class="rounded-[14px] border border-border bg-muted/40 p-4 text-sm leading-relaxed text-muted-foreground" aria-live="polite">{typeHelp(recordKind)}</p></section>
{#if kind==='contacts'}
<section class="space-y-4" aria-labelledby="directory-contact-info"><h2 id="directory-contact-info" class="text-base font-semibold">{copy('Contact information','Informasi kontak')}</h2><p class="text-sm text-muted-foreground">{copy('Optional now. A valid recipient email is needed before issuing a customer invoice.','Opsional saat ini. Email penerima yang valid diperlukan sebelum menerbitkan invoice pelanggan.')}</p><div class="grid gap-4 sm:grid-cols-2">
<Field.Field><Field.FieldLabel for="directory-email">{copy('Email (optional)','Email (opsional)')}</Field.FieldLabel><Input id="directory-email" type="email" bind:value={email} maxlength={320}/></Field.Field>
<Field.Field><Field.FieldLabel for="directory-phone">{copy('Phone (optional)','Telepon (opsional)')}</Field.FieldLabel><Input id="directory-phone" type="tel" bind:value={phone} maxlength={80}/></Field.Field>
<Field.Field><Field.FieldLabel for="directory-tax">{copy('Tax number (optional)','Nomor pajak / NPWP (opsional)')}</Field.FieldLabel><Input id="directory-tax" bind:value={taxId} maxlength={100}/></Field.Field>
</div></section><section class="space-y-4" aria-labelledby="directory-address"><h2 id="directory-address" class="text-base font-semibold">{copy('Billing address','Alamat penagihan')}</h2><p class="text-sm text-muted-foreground">{copy('Optional. Save the address you want to reuse for billing.','Opsional. Simpan alamat yang ingin Anda gunakan kembali untuk penagihan.')}</p><div class="grid gap-4 sm:grid-cols-2">
{#each [{key:'street',en:'Street',id:'Jalan'},{key:'city',en:'City',id:'Kota'},{key:'region',en:'Region',id:'Provinsi'},{key:'postalCode',en:'Postal code',id:'Kode pos'},{key:'country',en:'Country',id:'Negara'}] as field(field.key)}<Field.Field><Field.FieldLabel for={'directory-'+field.key}>{copy(field.en,field.id)}</Field.FieldLabel><Input id={'directory-'+field.key} value={field.key==='street'?street:field.key==='city'?city:field.key==='region'?region:field.key==='postalCode'?postalCode:country} oninput={(event)=>{const next=event.currentTarget.value;if(field.key==='street')street=next;else if(field.key==='city')city=next;else if(field.key==='region')region=next;else if(field.key==='postalCode')postalCode=next;else country=next;}} maxlength={200}/></Field.Field>{/each}
</div></section>
{:else}
<section class="space-y-4" aria-labelledby="directory-pricing"><h2 id="directory-pricing" class="text-base font-semibold">{copy('Pricing and invoice details','Harga dan detail invoice')}</h2><div class="grid gap-4 sm:grid-cols-2">
<Field.Field><Field.FieldLabel for="directory-sku">{copy('Item code / SKU (required)','Kode item / SKU (wajib)')}</Field.FieldLabel><Input id="directory-sku" bind:value={sku} maxlength={80} required aria-describedby="directory-sku-help"/><p id="directory-sku-help" class="text-sm text-muted-foreground">{copy('A unique short code, e.g. DESIGN-01. Use it to find this item quickly.','Kode singkat yang unik, mis. DESIGN-01. Gunakan untuk menemukan item dengan cepat.')}</p></Field.Field>
<Field.Field><Field.FieldLabel for="directory-unit">{copy('Unit of sale (required)','Satuan penjualan (wajib)')}</Field.FieldLabel><Input id="directory-unit" bind:value={unit} maxlength={80} required aria-describedby="directory-unit-help"/><p id="directory-unit-help" class="text-sm text-muted-foreground">{copy('For example: item, box, hour, session, or project.','Contoh: buah, kotak, jam, sesi, atau proyek.')}</p></Field.Field>
<Field.Field><Field.FieldLabel for="directory-currency">{copy('Currency','Mata uang')}</Field.FieldLabel><CurrencySelect id="directory-currency" bind:value={currency}/></Field.Field>
<Field.Field><Field.FieldLabel for="directory-price">{copy('Price per unit (required)','Harga per satuan (wajib)')}</Field.FieldLabel><AmountInput id="directory-price" bind:value={price} {currency} required/></Field.Field>
<Field.Field class="sm:col-span-2"><Field.FieldLabel for="directory-description">{copy('Invoice description (optional)','Deskripsi invoice (opsional)')}</Field.FieldLabel><Input id="directory-description" bind:value={description} maxlength={500} aria-describedby="directory-description-help"/><p id="directory-description-help" class="text-sm text-muted-foreground">{copy('Describe what your customer is paying for. If empty, the item name is used.','Jelaskan apa yang dibayar pelanggan. Jika kosong, nama item digunakan.')}</p></Field.Field>
<Field.Field class="sm:col-span-2"><Field.FieldLabel for="directory-rate">{copy('Default tax rate (optional)','Tarif pajak bawaan (opsional)')}</Field.FieldLabel><ChoiceSelect id="directory-rate" aria-describedby="directory-rate-help" bind:value={taxRateId} items={[{value:'',label:copy('No default rate','Tanpa tarif bawaan')},...rates.map(r=>({value:r.id,label:r.name}))]}/><p id="directory-rate-help" class="text-sm text-muted-foreground">{copy('Choose a saved business tax rate to reuse in a draft. Review tax settings on the invoice before issuing it.','Pilih tarif pajak bisnis tersimpan untuk digunakan pada draf. Tinjau pengaturan pajak invoice sebelum menerbitkannya.')}</p></Field.Field>
</div></section>{/if}<Dialog.Footer><Button type="button" variant="outline" disabled={saving} onclick={()=>open=false}>{copy('Cancel','Batal')}</Button><Button type="submit" disabled={saving||loading}>{kind==='contacts'?copy('Save contact','Simpan kontak'):copy('Save product or service','Simpan produk atau jasa')}</Button></Dialog.Footer></fieldset></form></Dialog.Content></Dialog.Root>

<AlertDialog.Root open={!!archiveTarget} onOpenChange={next=>{if(!next&&!saving)archiveTarget=null;}}><AlertDialog.Content class="max-h-[85dvh] overflow-y-auto sm:max-w-lg"><AlertDialog.Header><AlertDialog.Title>{kind==='contacts'?copy('Archive this contact?','Arsipkan kontak ini?'):copy('Archive this product or service?','Arsipkan produk atau jasa ini?')}</AlertDialog.Title><AlertDialog.Description>{archiveTarget?.name}. {copy('This removes the entry from the active directory and new selections. Existing issued invoices keep their saved details. Archiving does not cancel invoices or payments.','Catatan akan dihapus dari direktori aktif dan pilihan baru. Invoice yang sudah diterbitkan tetap menyimpan detailnya. Mengarsipkan tidak membatalkan invoice atau pembayaran.')}</AlertDialog.Description></AlertDialog.Header><AlertDialog.Footer><AlertDialog.Cancel disabled={saving} onclick={()=>archiveTarget=null}>{copy('Keep active','Tetap aktif')}</AlertDialog.Cancel><Button disabled={saving||loading} onclick={archive}>{copy('Archive entry','Arsipkan catatan')}</Button></AlertDialog.Footer></AlertDialog.Content></AlertDialog.Root>
