<script lang="ts">
 import PaymentAdjustmentsPanel from './payment-adjustments-panel.svelte';
 import {getContext,onMount} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import {formatDate} from '$lib/dates';
 let {workspaceId,invoiceId,onChanged}:{workspaceId:string;invoiceId:string;onChanged:()=>void}=$props();const ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 let requests:any[]=$state([]),channels:any[]=$state([]),channel=$state(''),loading=$state(false),busy=$state(false),canWrite=$state(false),error=$state(''),matching=$state(''),transactions:any[]=$state([]),transaction=$state(''),key=$state(crypto.randomUUID()),sequence=0;
 let copiedLink=$state('');
 let now=$state(Date.now());onMount(()=>{const timer=setInterval(()=>{now=Date.now();},5000);return()=>clearInterval(timer);});
 const endpoint=(ws:string)=>'/api/workspaces/'+ws;
 async function call(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.message??copy('Request failed.','Permintaan gagal.'));return result;}
 async function load(ws:string,id:string){const current=++sequence;loading=true;try{const [list,available,access]=await Promise.all([call(endpoint(ws)+'/invoices/'+id+'/payment-requests'),call(endpoint(ws)+'/payment-channels'),call(endpoint(ws)+'/business-access')]);if(ws===workspaceId&&current===sequence){requests=list.items;channels=available.items;canWrite=['owner','accountant'].includes(access.role);}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{if(workspaceId&&invoiceId){requests=[];channels=[];matching='';error='';channel='';canWrite=false;key=crypto.randomUUID();void load(workspaceId,invoiceId);}});
 async function perform(path:string,body?:unknown){if(busy)return;const ws=workspaceId,id=invoiceId;busy=true;error='';try{await call(endpoint(ws)+path,'POST',body);if(ws===workspaceId&&id===invoiceId){await load(ws,id);onChanged();}}catch(e){if(ws===workspaceId)error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 function failureMessage(code:string){
  if(code==='PAYMENT_PROVIDER_HTTP_401'||code==='PAYMENT_PROVIDER_HTTP_403')return copy('The payment provider rejected access. Ask the owner to verify the project slug, API key, webhook secret, sandbox/production environment, and Checkout activation.','Penyedia pembayaran menolak akses. Minta pemilik memeriksa project slug, API key, webhook secret, lingkungan sandbox/produksi, dan aktivasi Checkout.');
  if(code?.startsWith('PAYMENT_PROVIDER_HTTP_'))return copy('The payment provider rejected checkout creation (HTTP '+code.slice(-3)+'). Review the merchant Checkout configuration and reconcile this request before creating another.','Penyedia pembayaran menolak pembuatan checkout (HTTP '+code.slice(-3)+'). Periksa konfigurasi Checkout merchant dan rekonsiliasi permintaan ini sebelum membuat yang baru.');
  if(code==='INVALID_PAYMENT_PROVIDER_RESPONSE')return copy('Pakasir returned checkout details the app could not validate. No usable link was saved. Reconcile this request before creating another.','Pakasir mengembalikan detail checkout yang tidak dapat divalidasi aplikasi. Tautan yang dapat digunakan belum tersimpan. Rekonsiliasi permintaan ini sebelum membuat yang baru.');
  if(code==='PAYMENT_PROVIDER_UNAVAILABLE'||code==='PAYMENT_PROVIDER_RATE_LIMITED'||code==='CHECKOUT_OUTCOME_UNCERTAIN'||code==='STATUS_CHECK_FAILED')return copy('A usable payment link could not be confirmed. Use Check status to reconcile the existing request; Pakasir recovery reuses the original order reference.','Tautan pembayaran belum dapat dikonfirmasi. Gunakan Periksa status untuk merekonsiliasi permintaan yang ada; pemulihan Pakasir menggunakan referensi pesanan yang sama.');
  if(code==='REFUND_REVIEW_REQUIRED')return copy('The provider reports a refund. Verify the refund amount and correct the recorded receipt before closing this review.','Penyedia melaporkan pengembalian dana. Verifikasi jumlahnya dan koreksi penerimaan sebelum menutup peninjauan.');
  return copy('Review the existing checkout and receipt before creating another payment.','Tinjau checkout dan penerimaan yang ada sebelum membuat pembayaran baru.');
 }
 async function copyLink(url:string){try{await navigator.clipboard.writeText(new URL(url,window.location.origin).href);copiedLink=url;}catch{error=copy('Could not copy the link. Open it and copy the address instead.','Tautan belum dapat disalin. Buka halaman dan salin alamatnya.');}}
 function create(){void perform('/invoices/'+invoiceId+'/payment-requests',{connectionId:channel,qrisOnly:true,idempotencyKey:key});}
 async function openMatch(item:any){if(busy)return;const ws=workspaceId;busy=true;error='';transaction='';try{const result=await call(endpoint(ws)+'/transactions?type=income&limit=100');if(ws===workspaceId){matching=item.id;transactions=result.items.filter((t:any)=>t.type==='income'&&t.currency==='IDR'&&String(t.amount).replace(/\.0+$/,'')===String(item.amount).replace(/\.0+$/,''));}}catch(e){error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 function match(){const selected=transactions.find(t=>t.id===transaction);if(selected)void perform('/payment-requests/'+matching+'/match',{transactionId:selected.id,paidOn:selected.date});}
</script>
<LoadingScope active={loading||busy}/><Card.Root class="mt-4"><Card.Header><Card.Title>{copy('QRIS payment links','Tautan pembayaran QRIS')}</Card.Title><Card.Description>{copy('Customers pay on your CapyBudget page using QRIS. Confirmation is verified on the server.','Pelanggan membayar melalui halaman CapyBudget Anda menggunakan QRIS. Konfirmasi diverifikasi oleh server.')}</Card.Description></Card.Header><Card.Content class="space-y-4">
{#if error}<p role="alert">{error}</p>{/if}
{#if canWrite&&channels.length}<div class="grid gap-4 sm:grid-cols-2"><Field.Field><Field.FieldLabel for="invoice-channel">{copy('Connection','Koneksi')}</Field.FieldLabel><ChoiceSelect id="invoice-channel" bind:value={channel} items={[{value:'',label:copy('Select','Pilih')},...channels.map(c=>({value:c.id,label:(c.sandbox?'Sandbox':copy('Production','Produksi'))+' · '+c.id.slice(0,8)}))]}/></Field.Field></div><Button disabled={busy||loading||!channel||requests.some(r=>['creating','ready','uncertain'].includes(r.state))} onclick={create}>{copy('Create QRIS payment','Buat pembayaran QRIS')}</Button>{:else if canWrite}<p class="text-sm text-muted-foreground">{copy('Ask the owner to configure Pakasir in Business → Pakasir payments.','Minta pemilik mengatur Pakasir melalui Bisnis → Pembayaran Pakasir.')}</p>{/if}
<ul class="divide-y divide-border">{#each requests as item(item.id)}<li class="space-y-3 py-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="font-semibold">{item.state==='refunded'?copy('Refunded','Dikembalikan'):item.state==='partially_refunded'?copy('Partially refunded','Dikembalikan sebagian'):item.state==='paid'?copy('Paid','Dibayar'):item.state==='reconciliation'?copy('Needs review','Perlu ditinjau'):item.state==='expired'?copy('Expired','Kedaluwarsa'):item.state==='uncertain'?copy('Checking checkout outcome','Memeriksa hasil checkout'):copy('Awaiting payment','Menunggu pembayaran')} · {(item.provider==='doku'?'DOKU (legacy)':'Pakasir')+(item.qrisOnly?' · QRIS':'')}</p><MoneyDisplay amount={item.amount} currency="IDR"/></div><div class="flex flex-wrap gap-2">{#if item.paymentUrl&&item.state==='ready'}<Button href={item.paymentUrl} target="_blank" rel="noopener noreferrer" variant="outline">{copy('Open payment page','Buka halaman pembayaran')}</Button><Button variant="secondary" onclick={()=>copyLink(item.paymentUrl)}>{copiedLink===item.paymentUrl?copy('Link copied','Tautan disalin'):copy('Copy payment link','Salin tautan pembayaran')}</Button>{/if}{#if canWrite&&item.state!=='expired'}<Button variant="outline" disabled={busy||loading||now-Date.parse(item.createdAt)<60000} onclick={()=>perform('/payment-requests/'+item.id+'/reconcile')}>{copy('Check status','Periksa status')}</Button>{/if}</div></div>
{#if item.paymentUrl&&item.state==='ready'}<a class="block break-all text-sm text-primary underline underline-offset-4" href={item.paymentUrl} target="_blank" rel="noopener noreferrer">{item.paymentUrl}</a>{:else if ['creating','uncertain'].includes(item.state)}<p role="status" class="text-sm">{copy('No payment link is available yet.','Tautan pembayaran belum tersedia.')}</p>{/if}
{#if item.failureCode}<p role="status" class="text-sm text-muted-foreground">{failureMessage(item.failureCode)}</p>{/if}
{#if Array.isArray(item.checkoutError)&&item.checkoutError.length}<div class="space-y-2 rounded-[14px] border-2 border-border p-4"><p class="text-sm font-semibold">{item.failureCode==='INVALID_PAYMENT_PROVIDER_RESPONSE'?copy('Checkout response validation details','Detail validasi respons checkout'):copy('Provider validation details','Detail validasi penyedia')}</p><ul class="list-disc space-y-1 pl-4 text-sm">{#each item.checkoutError as detail}<li class="break-words">{detail}</li>{/each}</ul></div>{/if}
{#if canWrite&&item.state==='reconciliation'&&!item.paymentId}<Button variant="outline" disabled={busy} onclick={()=>openMatch(item)}>{copy('Match existing income','Cocokkan pemasukan yang ada')}</Button>{/if}
{#if matching===item.id}<div class="space-y-3 rounded-[14px] border-2 border-border p-4"><Field.Field><Field.FieldLabel for="match-income">{copy('Matching income (latest 100)','Pemasukan yang cocok (100 terbaru)')}</Field.FieldLabel><ChoiceSelect id="match-income" bind:value={transaction} items={[{value:'',label:copy('Select','Pilih')},...transactions.map(t=>({value:t.id,label:formatDate(t.date)+' · '+(t.merchant??t.notes??copy('Income','Pemasukan'))}))]}/></Field.Field><Button disabled={busy||!transaction} onclick={match}>{copy('Confirm match','Konfirmasi pencocokan')}</Button></div>{/if}<PaymentAdjustmentsPanel {workspaceId} {item} {canWrite} onChanged={()=>{void load(workspaceId,invoiceId);onChanged();}}/></li>{/each}</ul>
<p class="text-xs text-muted-foreground">{copy('Status checks wait at least 60 seconds. Provider timeouts do not mean a payment failed. Bank imports that may match are held for review to avoid counting the income twice.','Pemeriksaan status menunggu minimal 60 detik. Timeout penyedia tidak berarti pembayaran gagal. Impor bank yang mungkin cocok ditinjau agar pemasukan tidak dihitung dua kali.')}</p></Card.Content></Card.Root>
