<script lang="ts">
 import {getContext} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Dialog from '$lib/components/ui/dialog';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import DatePicker from '$lib/components/forms/date-picker.svelte';import AmountInput from '$lib/components/forms/amount-input.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import {formatDate} from '$lib/dates';
 let {workspaceId,item,canWrite,onChanged}:{workspaceId:string;item:any;canWrite:boolean;onChanged:()=>void}=$props();const ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 let open=$state(false),historyOpen=$state(false),busy=$state(false),error=$state(''),mode=$state('fees'),amount=$state(''),paidOn=$state(''),categoryId=$state(''),reason=$state(''),categories:any[]=$state([]),history:any[]=$state([]),transactions:any[]=$state([]),transactionId=$state(''),key=$state(''),reverseId=$state(''),sequence=0;
 const base=(ws:string,id:string)=>'/api/workspaces/'+ws+'/payment-requests/'+id;
 async function call(path:string,method='GET',body?:unknown){const r=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const b=await r.json();if(!r.ok)throw new Error(b.message??copy('Request failed.','Permintaan gagal.'));return b;}
 $effect(()=>{void workspaceId;void item.id;sequence++;open=false;historyOpen=false;history=[];error='';});
 async function start(value:string,id=''){if(busy)return;const ws=workspaceId,requestId=item.id,current=++sequence;mode=value;reverseId=id;amount='';paidOn='';categoryId='';reason='';transactionId='';transactions=[];key=crypto.randomUUID();error='';busy=true;try{const result=await call('/api/workspaces/'+ws+'/categories');if(current===sequence&&ws===workspaceId&&requestId===item.id){categories=result.items.filter((c:any)=>c.type==='expense');open=true;}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 async function showHistory(){if(busy)return;const ws=workspaceId,id=item.id,current=++sequence;busy=true;error='';try{const r=await call(base(ws,id)+'/adjustments');if(current===sequence){history=[...r.refunds.map((a:any)=>({...a,label:a.kind})),...r.fees.map((a:any)=>({...a,label:'fee'}))];historyOpen=true;}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 async function findMatches(){if(busy)return;const ws=workspaceId,current=sequence;busy=true;error='';try{const type=['unapplied','net-match'].includes(mode)?'income':'expense',r=await call('/api/workspaces/'+ws+'/transactions?type='+type+'&limit=100');if(current===sequence)transactions=r.items.filter((t:any)=>t.type===type&&t.currency==='IDR'&&t.date===paidOn&&String(t.amount).replace(/\.0+$/,'')===(mode==='unapplied'?String(item.amount):mode==='net-match'&&/^\d+$/.test(amount)?String(BigInt(String(item.amount).replace(/\.0+$/,''))-BigInt(amount)):amount).replace(/\.0+$/,''));}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 async function save(event:SubmitEvent){event.preventDefault();if(busy)return;if(!confirm(copy('Confirm this is an actual bank movement or a correction of a mistaken record. No money will be sent.','Konfirmasi ini adalah mutasi bank nyata atau koreksi catatan yang salah. Tidak ada uang yang dikirim.')))return;const ws=workspaceId,id=item.id,current=sequence;busy=true;error='';try{const path=mode==='reverse'?'/adjustments/'+reverseId+'/reverse':'/'+(mode==='chargeback'?'refunds':mode);await call(base(ws,id)+path,'POST',{confirm:true,amount,feeAmount:amount,paidOn,effectiveOn:paidOn,categoryId,reason,kind:mode==='chargeback'?'chargeback':'refund',idempotencyKey:key,transactionId:transactionId||undefined});if(current===sequence){open=false;historyOpen=false;onChanged();}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
</script>
<LoadingScope active={busy}/>
<div class="space-y-3"><div class="flex flex-wrap gap-2">{#if canWrite&&(item.paymentId||item.unappliedTransactionId)}<Button variant="outline" disabled={busy} onclick={()=>start('fees')}>{copy('Record fee','Catat biaya')}</Button><Button variant="outline" disabled={busy||item.state==='refunded'} onclick={()=>start('refunds')}>{copy('Record refund','Catat pengembalian')}</Button><Button variant="outline" disabled={busy||item.state==='refunded'} onclick={()=>start('chargeback')}>{copy('Record chargeback','Catat chargeback')}</Button>{/if}{#if canWrite&&item.state==='reconciliation'&&!item.paymentId&&!item.unappliedTransactionId}<Button variant="outline" disabled={busy} onclick={()=>start('net-match')}>{copy('Match net bank settlement','Cocokkan penerimaan bersih bank')}</Button><Button variant="outline" disabled={busy} onclick={()=>start('unapplied')}>{copy('Record unapplied funds','Catat dana belum dialokasikan')}</Button>{/if}<Button variant="ghost" disabled={busy} onclick={showHistory}>{copy('Fees and refund history','Riwayat biaya dan pengembalian')}</Button></div>
{#if error&&!open}<p role="alert" class="text-sm">{error}</p>{/if}
{#if historyOpen}<ul class="divide-y divide-border">{#each history as a(a.id)}<li class="flex flex-wrap items-center justify-between gap-3 py-3"><div><p>{a.label} · {formatDate(a.paidOn)} {#if a.reversedAt}· {copy('Corrected','Dikoreksi')}{/if}</p><MoneyDisplay amount={a.amount} currency="IDR"/></div>{#if canWrite&&!a.reversedAt}<Button variant="outline" disabled={busy} onclick={()=>start('reverse',a.id)}>{copy('Correct record','Koreksi catatan')}</Button>{/if}</li>{/each}{#if !history.length}<li class="py-3 text-sm text-muted-foreground">{copy('No adjustments recorded.','Belum ada penyesuaian.')}</li>{/if}</ul>{/if}</div>
<Dialog.Root bind:open><Dialog.Content class="max-h-[85dvh] overflow-y-auto"><Dialog.Header><Dialog.Title>{mode==='net-match'?copy('Match net bank settlement','Cocokkan penerimaan bersih bank'):mode==='fees'?copy('Record actual fee','Catat biaya aktual'):mode==='unapplied'?copy('Record unapplied funds','Catat dana belum dialokasikan'):mode==='reverse'?copy('Correct a mistaken record','Koreksi catatan yang salah'):mode==='chargeback'?copy('Record actual chargeback','Catat chargeback aktual'):copy('Record actual refund','Catat pengembalian aktual')}</Dialog.Title><Dialog.Description>{copy('Check your bank statement first. This records past movements; it does not send money or request a provider refund.','Periksa rekening bank terlebih dahulu. Ini mencatat mutasi yang sudah terjadi; tidak mengirim uang atau meminta pengembalian ke penyedia.')}</Dialog.Description></Dialog.Header><form onsubmit={save} class="space-y-4">{#if error}<p role="alert">{error}</p>{/if}
{#if !['unapplied','reverse'].includes(mode)}<Field.Field><Field.FieldLabel for={'adjust-amount-'+item.id}>{mode==='net-match'?copy('Verified fee (IDR)','Biaya terverifikasi (IDR)'):copy('Amount (IDR)','Jumlah (IDR)')}</Field.FieldLabel><AmountInput id={'adjust-amount-'+item.id} bind:value={amount} currency="IDR" required/></Field.Field><Field.Field><Field.FieldLabel for={'adjust-category-'+item.id}>{copy('Expense category','Kategori pengeluaran')}</Field.FieldLabel><ChoiceSelect id={'adjust-category-'+item.id} bind:value={categoryId} required items={[{value:'',label:copy('Select','Pilih')},...categories.map(c=>({value:c.id,label:c.name}))]}/></Field.Field>{/if}
<Field.Field><Field.FieldLabel for={'adjust-date-'+item.id}>{copy('Effective bank movement date','Tanggal efektif mutasi bank')}</Field.FieldLabel><DatePicker id={'adjust-date-'+item.id} bind:value={paidOn} required/></Field.Field>
{#if !['unapplied','net-match'].includes(mode)}<Field.Field><Field.FieldLabel for={'adjust-reason-'+item.id}>{copy('Reason','Alasan')}</Field.FieldLabel><Input id={'adjust-reason-'+item.id} bind:value={reason} maxlength={1000} required/></Field.Field>{/if}
{#if mode!=='reverse'}<Button type="button" variant="outline" disabled={busy||!paidOn||(!amount&&mode!=='unapplied')} onclick={findMatches}>{copy('Find existing bank movement','Cari mutasi bank yang ada')}</Button><Field.Field><Field.FieldLabel for={'adjust-match-'+item.id}>{copy('Existing movement (latest 100; optional)','Mutasi yang ada (100 terbaru; opsional)')}</Field.FieldLabel><ChoiceSelect id={'adjust-match-'+item.id} bind:value={transactionId} items={[{value:'',label:mode==='net-match'?copy('Select existing net income','Pilih pemasukan bersih yang ada'):copy('Create a new record','Buat catatan baru')},...transactions.map(t=>({value:t.id,label:formatDate(t.date)+' · '+(t.merchant??t.notes??t.id.slice(0,8))}))]}/></Field.Field><p class="text-xs text-muted-foreground">{copy('Server matching also checks the receiving account and category. Select an existing movement to avoid counting an import twice.','Pencocokan server juga memeriksa akun dan kategori. Pilih mutasi yang ada agar impor tidak dihitung dua kali.')}</p>{/if}
<Dialog.Footer><Button type="button" variant="outline" disabled={busy} onclick={()=>open=false}>{copy('Cancel','Batal')}</Button><Button type="submit" disabled={busy||(mode==='net-match'&&!transactionId)}>{copy('Confirm record','Konfirmasi catatan')}</Button></Dialog.Footer></form></Dialog.Content></Dialog.Root>
