<script lang="ts">
 import {getContext} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';import DatePicker from '$lib/components/forms/date-picker.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import {formatDate} from '$lib/dates';
 let {workspaceId}:{workspaceId:string}=$props();const ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 let busy=$state(false),error=$state(''),canWrite=$state(false),reminders:any[]=$state([]),rows:any[]=$state([]),loaded=$state(false),name=$state(''),dueOn=$state(''),from=$state(''),through=$state(''),page=$state(0),sequence=0;
 const endpoint=(ws:string)=>'/api/workspaces/'+ws+'/business-tax';
 async function call(path:string,method='GET',body?:unknown){const r=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const b=await r.json();if(!r.ok)throw new Error(b.message);return b;}
 async function load(ws:string){const current=++sequence;busy=true;try{const [r,a]=await Promise.all([call(endpoint(ws)+'/reminders'),call('/api/workspaces/'+ws+'/business-access')]);if(current===sequence){reminders=r.items;canWrite=['owner','accountant'].includes(a.role);}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 $effect(()=>{if(workspaceId){reminders=[];rows=[];loaded=false;canWrite=false;error='';name='';dueOn='';void load(workspaceId);}});
 async function mutate(path:string,body:unknown){if(busy)return false;const ws=workspaceId,current=sequence;busy=true;error='';try{await call(endpoint(ws)+path,'POST',body);if(current!==sequence)return false;await load(ws);return true;}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);return false;}finally{busy=false;}}
 async function add(event:SubmitEvent){event.preventDefault();if(await mutate('/reminders',{name,dueOn})){name='';dueOn='';}}
 async function report(event:SubmitEvent){event.preventDefault();if(busy)return;const ws=workspaceId,current=sequence;busy=true;error='';loaded=false;try{const r=await call(endpoint(ws)+'/purchases?'+new URLSearchParams({from,through}));if(current===sequence){rows=r.rows;loaded=true;page=0;}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
 function download(){const keys=['number','issueDate','currency','description','netAmount','taxAmount','totalAmount'];const cell=(v:unknown)=>'"'+(/^[=+@\-\t\r]/.test(String(v))?"'":'')+String(v).replaceAll('"','""')+'"';const content='\uFEFF'+keys.join(',')+'\r\n'+rows.map(r=>keys.map(k=>cell(k==='issueDate'?formatDate(r[k]):r[k])).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='capybudget-purchase-tax-register.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
</script>
<LoadingScope active={busy}/><div class="space-y-6">{#if error}<p role="alert">{error}</p>{/if}
<Card.Root><Card.Header><Card.Title>{copy('Purchase tax register','Daftar pajak pembelian')}</Card.Title><Card.Description>{copy('Issued vendor bills with currencies kept separate. Input-tax credit eligibility is not determined: check the tax invoice and applicable rules before claiming a credit.','Tagihan pemasok terbit dengan mata uang terpisah. Kelayakan kredit pajak masukan tidak ditentukan: periksa faktur pajak dan aturan yang berlaku sebelum mengklaim kredit.')}</Card.Description></Card.Header><Card.Content class="space-y-4"><form onsubmit={report} class="space-y-4"><div class="grid gap-4 sm:grid-cols-2"><Field.Field><Field.FieldLabel for="purchase-from">{copy('From','Dari')}</Field.FieldLabel><DatePicker id="purchase-from" bind:value={from} required/></Field.Field><Field.Field><Field.FieldLabel for="purchase-through">{copy('Through','Sampai')}</Field.FieldLabel><DatePicker id="purchase-through" bind:value={through} min={from||undefined} required/></Field.Field></div><div class="flex flex-wrap gap-3"><Button type="submit" disabled={busy}>{copy('Show purchases','Tampilkan pembelian')}</Button>{#if loaded}<Button type="button" variant="outline" onclick={download}>{copy('Export CSV','Ekspor CSV')}</Button>{/if}</div></form>
{#if loaded}<ul class="divide-y divide-border">{#each rows.slice(page*50,(page+1)*50) as r,i(i)}<li class="grid gap-3 py-4 sm:grid-cols-2"><div><a class="inline-flex min-h-11 items-center font-semibold" href={'/business/payables/'+r.billId}>{r.number}</a><p class="text-sm text-muted-foreground">{formatDate(r.issueDate)} · {r.description}</p></div><div><p>{copy('Net','Bersih')}: <MoneyDisplay amount={r.netAmount} currency={r.currency}/></p><p>{copy('Tax','Pajak')}: <MoneyDisplay amount={r.taxAmount} currency={r.currency}/></p></div></li>{/each}</ul>{#if !rows.length}<p>{copy('No issued purchases in this period.','Tidak ada pembelian terbit pada periode ini.')}</p>{:else}<div class="flex flex-wrap items-center gap-3"><p aria-live="polite">{page*50+1}–{Math.min((page+1)*50,rows.length)} / {rows.length}</p><Button variant="outline" disabled={page===0} onclick={()=>page--}>{copy('Previous','Sebelumnya')}</Button><Button variant="outline" disabled={(page+1)*50>=rows.length} onclick={()=>page++}>{copy('Next','Berikutnya')}</Button></div>{/if}{/if}</Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{copy('Tax reminders','Pengingat pajak')}</Card.Title><Card.Description>{copy('Set the deadlines that apply to this business. These dates are chosen by you; no filing deadline is assumed.','Atur tenggat yang berlaku untuk bisnis ini. Tanggal ditentukan oleh Anda; tidak ada tenggat pelaporan yang diasumsikan.')}</Card.Description></Card.Header><Card.Content class="space-y-4">{#if canWrite}<form onsubmit={add} class="space-y-4"><div class="grid gap-4 sm:grid-cols-2"><Field.Field><Field.FieldLabel for="tax-reminder-name">{copy('Reminder','Pengingat')}</Field.FieldLabel><Input id="tax-reminder-name" bind:value={name} maxlength={200} required/></Field.Field><Field.Field><Field.FieldLabel for="tax-reminder-due">{copy('Due date','Jatuh tempo')}</Field.FieldLabel><DatePicker id="tax-reminder-due" bind:value={dueOn} required/></Field.Field></div><Button type="submit" disabled={busy}>{copy('Add reminder','Tambah pengingat')}</Button></form>{/if}<ul class="divide-y divide-border">{#each reminders as r(r.id)}<li class="flex flex-wrap items-center justify-between gap-4 py-4"><div><p class="font-semibold">{r.name}</p><p class="text-sm text-muted-foreground">{formatDate(r.dueOn)} · {r.completedAt?copy('Completed','Selesai'):copy('Upcoming','Mendatang')}</p></div>{#if canWrite&&!r.completedAt}<Button variant="outline" disabled={busy} onclick={()=>mutate('/reminders/'+r.id+'/complete',{})}>{copy('Mark completed','Tandai selesai')}</Button>{/if}</li>{/each}</ul>{#if !reminders.length}<p>{copy('No tax reminders yet.','Belum ada pengingat pajak.')}</p>{/if}</Card.Content></Card.Root></div>
