<script lang="ts">
 import {getContext,untrack} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';import DatePicker from '$lib/components/forms/date-picker.svelte';import AmountInput from '$lib/components/forms/amount-input.svelte';import MoneyDisplay from '$lib/components/shared/money-display.svelte';import PageHeader from '$lib/components/shared/page-header.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';import {formatDate} from '$lib/dates';
 const workspace=getContext<{selectedId:string;ready:boolean;revision?:number;items:{id:string;timezone:string;currency:string}[]}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 let projects:any[]=$state([]),contacts:any[]=$state([]),transactions:any[]=$state([]),invoices:any[]=$state([]),invoiceLines:any[]=$state([]),allocations:any[]=$state([]),report:any=$state(null),projectId=$state(''),name=$state(''),clientId=$state(''),sourceType=$state('transaction'),sourceId=$state(''),invoiceId=$state(''),amount=$state(''),from=$state(''),through=$state(''),canWrite=$state(false),loading=$state(false),busy=$state(false),error=$state(''),sequence=0,selectionSequence=0,lineSequence=0;
 const endpoint=(ws:string)=>'/api/workspaces/'+ws;const currentCurrency=$derived(sourceType==='transaction'?transactions.find(t=>t.id===sourceId)?.currency:invoiceLines.find(l=>l.id===sourceId)?.currency);
 async function call(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.message);return result;}
 async function load(ws:string){const current=++sequence;loading=true;error='';try{const [list,customers,txs,docs,access]=await Promise.all([call(endpoint(ws)+'/projects'),call(endpoint(ws)+'/contacts?kind=customer'),call(endpoint(ws)+'/transactions?limit=100'),call(endpoint(ws)+'/invoices?limit=100'),call(endpoint(ws)+'/business-access')]);if(current===sequence&&ws===workspace.selectedId){projects=list.items;contacts=customers.items;transactions=txs.items.filter((t:any)=>t.type!=='transfer');invoices=docs.items.filter((i:any)=>i.state==='issued');canWrite=['owner','accountant'].includes(access.role);}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{void workspace.revision;if(workspace.ready&&workspace.selectedId){projectId='';sourceId='';invoiceId='';report=null;allocations=[];name='';clientId='';canWrite=false;selectionSequence++;lineSequence++;through=new Intl.DateTimeFormat('en-CA',{timeZone:workspace.items.find(w=>w.id===workspace.selectedId)?.timezone??'Asia/Jakarta'}).format(new Date());from=through.slice(0,8)+'01';void load(workspace.selectedId);}});
 async function show(){if(!projectId)return;const ws=workspace.selectedId,id=projectId,current=++selectionSequence;busy=true;error='';try{const [list,profit]=await Promise.all([call(endpoint(ws)+'/projects/'+id+'/allocations'),call(endpoint(ws)+'/projects/'+id+'/profitability?'+new URLSearchParams({from,through}))]);if(current===selectionSequence&&ws===workspace.selectedId&&id===projectId){allocations=list.items;report=profit;}}catch(e){if(current===selectionSequence)error=e instanceof Error?e.message:String(e);}finally{if(current===selectionSequence)busy=false;}}
 $effect(()=>{const selected=projectId;report=null;allocations=[];if(selected)untrack(()=>void show());});
 async function loadLines(id:string){const ws=workspace.selectedId,current=++lineSequence;sourceId='';invoiceLines=[];if(!id)return;try{const result=await call(endpoint(ws)+'/invoices/'+id);if(current===lineSequence&&ws===workspace.selectedId)invoiceLines=result.invoice.lines.map((l:any)=>({...l,currency:result.invoice.currency}));}catch(e){error=e instanceof Error?e.message:String(e);}}
 async function mutate(path:string,method:string,body?:unknown){if(busy||loading)return null;const ws=workspace.selectedId;busy=true;error='';try{const result=await call(endpoint(ws)+path,method,body);if(ws===workspace.selectedId){await load(ws);return result;}return null;}catch(e){if(ws===workspace.selectedId)error=e instanceof Error?e.message:String(e);return null;}finally{busy=false;}}
 async function create(event:SubmitEvent){event.preventDefault();const result=await mutate('/projects','POST',{name,clientId:clientId||null});if(result){name='';projectId=result.id;}}
 async function allocate(event:SubmitEvent){event.preventDefault();if(await mutate('/projects/'+projectId+'/allocations','POST',{amount,...(sourceType==='transaction'?{transactionId:sourceId}:{invoiceLineId:sourceId})})){amount='';await show();}}
 async function remove(id:string){if(confirm(copy('Remove this allocation? The original money record stays unchanged.','Hapus alokasi ini? Catatan uang asli tetap sama.'))&&await mutate('/projects/'+projectId+'/allocations/'+id,'DELETE'))await show();}
</script>
<svelte:head><title>CapyBudget · {copy('Project profitability','Profitabilitas proyek')}</title></svelte:head><LoadingScope active={loading||busy}/><PageHeader guidePath="/business/projects" title={copy('Project profitability','Profitabilitas proyek')} description={copy('Assign revenue and costs without recording the same money twice.','Alokasikan pemasukan dan biaya tanpa mencatat uang yang sama dua kali.')}/>
{#if error}<ErrorState title={copy('Could not update project','Proyek gagal diperbarui')} message={error} onRetry={()=>load(workspace.selectedId)} retryLabel={copy('Retry','Coba lagi')}/>{/if}
<div class="space-y-6">{#if canWrite}<Card.Root><Card.Header><Card.Title>{copy('New project','Proyek baru')}</Card.Title></Card.Header><Card.Content><form onsubmit={create} class="space-y-4"><div class="grid gap-4 sm:grid-cols-2"><Field.Field><Field.FieldLabel for="project-name">{copy('Name','Nama')}</Field.FieldLabel><Input id="project-name" bind:value={name} maxlength={200} required/></Field.Field><Field.Field><Field.FieldLabel for="project-client">{copy('Customer (optional, first 50)','Pelanggan (opsional, 50 pertama)')}</Field.FieldLabel><ChoiceSelect id="project-client" bind:value={clientId} items={[{value:'',label:'—'},...contacts.map(c=>({value:c.id,label:c.name}))]}/></Field.Field></div><Button type="submit" disabled={busy||loading}>{copy('Create project','Buat proyek')}</Button></form></Card.Content></Card.Root>{/if}
<Card.Root><Card.Header><Card.Title>{copy('Project report','Laporan proyek')}</Card.Title></Card.Header><Card.Content class="space-y-4"><Field.Field><Field.FieldLabel for="project-select">{copy('Project','Proyek')}</Field.FieldLabel><ChoiceSelect id="project-select" bind:value={projectId} items={[{value:'',label:copy('Select','Pilih')},...projects.map(p=>({value:p.id,label:p.name+(p.clientName?' · '+p.clientName:'')}))]}/></Field.Field>
<form onsubmit={(event)=>{event.preventDefault();void show();}} class="flex flex-wrap items-end gap-3"><Field.Field><Field.FieldLabel for="profit-from">{copy('From','Dari')}</Field.FieldLabel><DatePicker id="profit-from" bind:value={from} required/></Field.Field><Field.Field><Field.FieldLabel for="profit-through">{copy('Through','Sampai')}</Field.FieldLabel><DatePicker id="profit-through" bind:value={through} min={from||undefined} required/></Field.Field><Button type="submit" disabled={busy||loading||!projectId}>{copy('Show cash report','Tampilkan laporan kas')}</Button></form>
{#if report}{#each report.totals as total(total.currency)}<div class="grid gap-4 rounded-[20px] border-2 border-border bg-muted/40 p-4 sm:grid-cols-3"><div><h2 class="text-sm font-semibold">{copy('Revenue','Pemasukan')}</h2><MoneyDisplay amount={total.revenue} currency={total.currency} type="income"/></div><div><h2 class="text-sm font-semibold">{copy('Costs','Biaya')}</h2><MoneyDisplay amount={total.cost} currency={total.currency} type="expense"/></div><div><h2 class="text-sm font-semibold">{copy('Profit','Laba')}</h2><MoneyDisplay amount={total.profit} currency={total.currency} type={total.profit.startsWith('-')?'expense':'income'}/><p class="text-sm">{copy('Margin','Margin')}: {total.marginPercent===null?'—':total.marginPercent+'%'}</p></div></div>{/each}{#if !report.totals.length}<p>{copy('No allocated cash movement in this period.','Tidak ada pergerakan kas yang dialokasikan pada periode ini.')}</p>{/if}{/if}
<p class="text-sm text-muted-foreground">{copy('Cash basis: allocated invoice revenue excludes sales tax and follows payments received. Other income and costs use recorded cash amounts, including purchase tax. Unallocated records are excluded. Reversals use their effective dates. Each currency is separate; this is not a statutory profit-and-loss statement.','Basis kas: pemasukan faktur yang dialokasikan tidak termasuk pajak penjualan dan mengikuti penerimaan pembayaran. Pemasukan lain dan biaya memakai nilai kas tercatat, termasuk pajak pembelian. Catatan tanpa alokasi tidak dihitung. Pembalikan memakai tanggal efektif. Mata uang dipisahkan; ini bukan laporan laba-rugi resmi.')}</p></Card.Content></Card.Root>
{#if canWrite&&projectId}<Card.Root><Card.Header><Card.Title>{copy('Allocate a source','Alokasikan sumber')}</Card.Title></Card.Header><Card.Content><form onsubmit={allocate} class="space-y-4"><div class="grid gap-4 sm:grid-cols-2"><Field.Field><Field.FieldLabel for="allocation-type">{copy('Source type','Jenis sumber')}</Field.FieldLabel><ChoiceSelect id="allocation-type" bind:value={sourceType} onValueChange={()=>{sourceId='';amount='';}} items={[{value:'transaction',label:copy('Income or expense','Pemasukan atau pengeluaran')},{value:'invoice',label:copy('Issued invoice line','Baris faktur terbit')}]}/></Field.Field>
{#if sourceType==='invoice'}<Field.Field><Field.FieldLabel for="allocation-invoice">{copy('Invoice (latest 100)','Faktur (100 terbaru)')}</Field.FieldLabel><ChoiceSelect id="allocation-invoice" bind:value={invoiceId} onValueChange={(id)=>void loadLines(id)} items={[{value:'',label:copy('Select','Pilih')},...invoices.map(i=>({value:i.id,label:i.number}))]}/></Field.Field>{/if}
<Field.Field><Field.FieldLabel for="allocation-source">{copy('Source record','Catatan sumber')}</Field.FieldLabel><ChoiceSelect id="allocation-source" bind:value={sourceId} required items={[{value:'',label:copy('Select','Pilih')},...(sourceType==='transaction'?transactions.map(t=>({value:t.id,label:formatDate(t.date)+' · '+(t.merchant??t.notes??t.type)+' · '+t.currency})):invoiceLines.map(l=>({value:l.id,label:l.description+' · '+l.currency})))]}/></Field.Field><Field.Field><Field.FieldLabel for="allocation-amount">{copy('Amount assigned to this project','Jumlah untuk proyek ini')}</Field.FieldLabel><AmountInput id="allocation-amount" bind:value={amount} currency={currentCurrency} required/></Field.Field></div><p class="text-sm text-muted-foreground">{copy('Source pickers show the latest 100 records. Invoice receipts must be assigned through invoice lines. An existing allocation for the same source and project is replaced by the amount you enter.','Pemilih sumber menampilkan 100 catatan terbaru. Penerimaan faktur dialokasikan melalui baris faktur. Alokasi yang ada untuk sumber dan proyek yang sama diganti dengan jumlah yang dimasukkan.')}</p><Button type="submit" disabled={busy||loading||!sourceId}>{copy('Save allocation','Simpan alokasi')}</Button></form></Card.Content></Card.Root>{/if}
{#if projectId}<Card.Root><Card.Header><Card.Title>{copy('Assigned records','Catatan teralokasi')}</Card.Title></Card.Header><Card.Content><ul class="divide-y divide-border">{#each allocations as item(item.id)}<li class="flex flex-wrap items-center justify-between gap-4 py-4"><div><p>{item.description??copy('Money record','Catatan uang')}</p><MoneyDisplay amount={item.amount} currency={item.currency}/></div>{#if canWrite}<Button variant="outline" disabled={busy} onclick={()=>remove(item.id)}>{copy('Remove allocation','Hapus alokasi')}</Button>{/if}</li>{/each}</ul>{#if !allocations.length}<p>{copy('No allocations yet.','Belum ada alokasi.')}</p>{/if}</Card.Content></Card.Root>{/if}</div>
