import { client } from '../db';
import { enqueueEmail } from '../email/queue';
import { nextOccurrenceDate, workspaceHour, workspaceToday } from '../tracking/recurrence';
import webpush from 'web-push';
import { decryptPushAuth } from './push-crypto';

let running = false;

type PushSender = (subscription: { endpoint: string; keys: { p256dh: string; auth: string } }, payload: string) => Promise<unknown>;
type PushJob={workspaceId:string;userId:string;deliveryId:string;notificationId:string;occurrenceId:string;subscriptionId:string};
type AssistantPushJob={workspaceId:string;userId:string;deliveryId:string;notificationId:string;subscriptionId:string};

async function deliverPushJob(job:PushJob,pushSender?:PushSender){
  const [target]=await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);const [row]=await tx.unsafe("update finance_notification_deliveries d set status='processing',attempts=d.attempts+1,send_started_at=null,lease_expires_at=now()+interval '1 minute',updated_at=now() from finance_notifications n,bill_occurrences o,bills b,push_subscriptions s,workspace_memberships m,finance_notification_preferences p where d.workspace_id=$1 and d.user_id=$2 and d.id=$3 and d.channel='push' and d.status in ('pending','retryable') and d.available_at<=now() and d.attempts<5 and d.expires_at>now() and n.workspace_id=d.workspace_id and n.user_id=d.user_id and n.id=d.notification_id and n.id=$4 and n.kind='bill-reminder' and n.resolved_at is null and n.dismissed_at is null and (n.snoozed_until is null or n.snoozed_until<=now()) and n.expires_at>now() and o.workspace_id=n.workspace_id and o.id=n.source_id and o.id=$5 and o.status='unpaid' and n.message_params->>'dueDate'=o.due_on::text and b.workspace_id=o.workspace_id and b.id=o.bill_id and (b.enabled or b.frequency='once') and b.archived_at is null and s.workspace_id=d.workspace_id and s.user_id=d.user_id and s.id=d.push_subscription_id and s.id=$6 and m.workspace_id=d.workspace_id and m.user_id=d.user_id and p.workspace_id=d.workspace_id and p.user_id=d.user_id and p.event_type='bill-reminder' and p.channel='push' and p.enabled=true and d.preference_version=p.version returning s.id,s.endpoint,s.p256dh,s.auth",[job.workspaceId,job.userId,job.deliveryId,job.notificationId,job.occurrenceId,job.subscriptionId]);return [row];});
  if(!target){await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);await tx.unsafe("update finance_notification_deliveries set status='cancelled',lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status in ('pending','retryable') and available_at<=now()",[job.workspaceId,job.userId,job.deliveryId]);});return;}
  try{const [started]=await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);return tx.unsafe("update finance_notification_deliveries set send_started_at=now(),updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing' returning id",[job.workspaceId,job.userId,job.deliveryId]);});if(!started)return;const payload=JSON.stringify({title:'A bill is due',body:'Open CapyBudget to view your upcoming bill.',url:'/bills',tag:`bill-${job.notificationId}`}),subscription={endpoint:target.endpoint,keys:{p256dh:target.p256dh,auth:decryptPushAuth(target.auth)}};if(pushSender)await pushSender(subscription,payload);else await webpush.sendNotification(subscription,payload);await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);await tx.unsafe("update finance_notification_deliveries set status='accepted',accepted_at=now(),lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing'",[job.workspaceId,job.userId,job.deliveryId]);await tx.unsafe('update finance_notifications set push_sent_at=coalesce(push_sent_at,now()) where workspace_id=$1 and user_id=$2 and id=$3',[job.workspaceId,job.userId,job.notificationId]);});}
  catch(error){const status=Number((error as {statusCode?:number}).statusCode??0),code=status===404||status===410?'PUSH_GONE':String((error as {code?:string}).code??'PUSH_ERROR').replace(/[^A-Z0-9_]/gi,'').slice(0,40);if(status===404||status===410){await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);await tx.unsafe("update finance_notification_deliveries set status='failed',last_error_code=$4,send_started_at=null,lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing'",[job.workspaceId,job.userId,job.deliveryId,code]);await tx.unsafe('delete from push_subscriptions where workspace_id=$1 and user_id=$2 and id=$3',[job.workspaceId,job.userId,job.subscriptionId]);});return;}await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);await tx.unsafe("update finance_notification_deliveries set status=case when attempts>=5 then 'failed' else 'retryable' end,last_error_code=$4,available_at=now()+make_interval(secs=>least(3600,power(2,least(attempts,10))::int)),send_started_at=null,lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing'",[job.workspaceId,job.userId,job.deliveryId,code]);});console.error('Browser reminder delivery failed',{deliveryId:job.deliveryId,status:status||'unknown'});}
}

async function deliverAssistantPushJob(job:AssistantPushJob,pushSender?:PushSender){
  const [target]=await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);const [row]=await tx.unsafe(`update finance_notification_deliveries d set status='processing',attempts=d.attempts+1,send_started_at=null,lease_expires_at=now()+interval '1 minute',updated_at=now()
    from finance_notifications n,push_subscriptions s,workspace_memberships m,finance_notification_preferences p,assistant_suggestions x,forecast_runs r,assistant_settings a,assistant_refresh_state f
    where d.workspace_id=$1 and d.user_id=$2 and d.id=$3 and d.channel='push' and d.status in ('pending','retryable') and d.available_at<=now() and d.attempts<5 and d.expires_at>now()
      and n.workspace_id=d.workspace_id and n.user_id=d.user_id and n.id=d.notification_id and n.id=$4 and n.kind in ('cashflow-shortfall','cashflow-low-balance','assistant-invoice-followup') and n.resolved_at is null and n.dismissed_at is null and (n.snoozed_until is null or n.snoozed_until<=now()) and n.expires_at>now()
      and s.workspace_id=d.workspace_id and s.user_id=d.user_id and s.id=d.push_subscription_id
      and m.workspace_id=d.workspace_id and m.user_id=d.user_id
      and p.workspace_id=d.workspace_id and p.user_id=d.user_id and p.event_type='assistant-alert' and p.channel='push' and p.enabled=true and p.version=d.preference_version
      and x.workspace_id=n.workspace_id and x.user_id=n.user_id and x.id=n.assistant_suggestion_id and x.state in ('active','reviewing') and x.expires_at>now()
      and r.workspace_id=x.workspace_id and r.id=x.run_id and a.workspace_id=n.workspace_id and a.user_id=n.user_id and f.workspace_id=n.workspace_id and f.user_id=n.user_id
      and a.local_forecast_enabled and a.suggestions_enabled and a.consent_version=r.consent_version and f.checked_at>=n.created_at
      and not (x.facts->>'scope'='account' and exists(select 1 from finance_notifications wn join assistant_suggestions ws on ws.workspace_id=wn.workspace_id and ws.user_id=wn.user_id and ws.id=wn.assistant_suggestion_id where wn.workspace_id=n.workspace_id and wn.user_id=n.user_id and wn.kind=n.kind and wn.resolved_at is null and ws.state in ('active','reviewing') and ws.facts->>'scope'='workspace' and ws.facts->>'date'=x.facts->>'date'))
    returning s.endpoint,s.p256dh,s.auth,a.locale`,[job.workspaceId,job.userId,job.deliveryId,job.notificationId]);return [row];});
  if(!target){await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);await tx.unsafe("update finance_notification_deliveries set status='cancelled',lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status in ('pending','retryable') and available_at<=now()",[job.workspaceId,job.userId,job.deliveryId]);});return;}
  try{const [started]=await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);return tx.unsafe("update finance_notification_deliveries set send_started_at=now(),updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing' returning id",[job.workspaceId,job.userId,job.deliveryId]);});if(!started)return;const subscription={endpoint:target.endpoint,keys:{p256dh:target.p256dh,auth:decryptPushAuth(target.auth)}},isId=target.locale==='id',payload=JSON.stringify({title:isId?'Pembaruan arus kas':'Cashflow update',body:isId?'Buka CapyBudget untuk meninjau proyeksi Anda.':'Open CapyBudget to review your forecast.',url:'/assistant',tag:`assistant-${job.notificationId}`});if(pushSender)await pushSender(subscription,payload);else await webpush.sendNotification(subscription,payload);await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);await tx.unsafe("update finance_notification_deliveries set status='accepted',accepted_at=now(),lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing'",[job.workspaceId,job.userId,job.deliveryId]);await tx.unsafe("update finance_notifications set push_sent_at=coalesce(push_sent_at,now()) where workspace_id=$1 and user_id=$2 and id=$3 and resolved_at is null",[job.workspaceId,job.userId,job.notificationId]);});}
  catch(error){const status=Number((error as {statusCode?:number}).statusCode??0),code=status===404||status===410?'PUSH_GONE':String((error as {code?:string}).code??'PUSH_ERROR').replace(/[^A-Z0-9_]/gi,'').slice(0,40);await client.begin(async(tx)=>{await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)",[job.userId,job.workspaceId]);if(status===404||status===410){await tx.unsafe("update finance_notification_deliveries set status='failed',last_error_code=$4,send_started_at=null,lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing'",[job.workspaceId,job.userId,job.deliveryId,code]);await tx.unsafe('delete from push_subscriptions where workspace_id=$1 and user_id=$2 and id=$3',[job.workspaceId,job.userId,job.subscriptionId]);}else await tx.unsafe("update finance_notification_deliveries set status=case when attempts>=5 then 'failed' else 'retryable' end,last_error_code=$4,available_at=now()+make_interval(secs=>least(3600,power(2,least(attempts,10))::int)),send_started_at=null,lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and id=$3 and status='processing'",[job.workspaceId,job.userId,job.deliveryId,code]);});console.error('Assistant push delivery failed',{deliveryId:job.deliveryId,status:status||'unknown'});}
}

export async function sweepBillReminders(now = new Date(), pushSender?: PushSender, emailEnqueuer:typeof enqueueEmail=enqueueEmail): Promise<void> {
  if (running) return;
  running = true;
  try {
    const workspaces = await client.unsafe("select id,owner_user_id,timezone from workspaces where archived_at is null");
    for (const workspace of workspaces) {
      const emailJobs:{message:import('../email/types').EmailMessage;jobId:string}[]=[];
      const pushJobs:PushJob[]=[];
      const assistantPushJobs:AssistantPushJob[]=[];
      try {
        await client.begin(async (tx) => {
          await tx.unsafe("select set_config('app.user_id',$1,true),set_config('app.workspace_id',$2,true)", [workspace.owner_user_id, workspace.id]);
          const [lock] = await tx.unsafe("select pg_try_advisory_xact_lock(hashtextextended('capybudget:bill-reminders:'||$1,0)) as acquired", [workspace.id]);
          if (!lock?.acquired) return;
          await tx.unsafe("update finance_notification_deliveries set status=case when send_started_at is null then 'retryable' else 'unknown' end,last_error_code='LEASE_EXPIRED',available_at=case when send_started_at is null then now() else available_at end,lease_expires_at=null,updated_at=now() where workspace_id=$1 and user_id=$2 and status='processing' and lease_expires_at<now()",[workspace.id,workspace.owner_user_id]);
          await tx.unsafe("update finance_notification_deliveries set status='expired',lease_expires_at=null,updated_at=now() where workspace_id=$1 and status in ('pending','retryable') and expires_at<=now()",[workspace.id]);
          const today = workspaceToday(workspace.timezone, now), remindersReleased=workspaceHour(workspace.timezone,now)>=9, end = new Date(`${today}T00:00:00Z`); end.setUTCDate(end.getUTCDate() + 90);
          const through = end.toISOString().slice(0,10);
          const bills = await tx.unsafe('select * from bills where workspace_id=$1 and enabled and archived_at is null and next_due_date<=$2 order by next_due_date limit 1000', [workspace.id, through]);
          for (const bill of bills) {
            let due = bill.next_due_date as string, count = 0;
            while (due <= through && count++ < 100) {
              await tx.unsafe('insert into bill_occurrences(workspace_id,bill_id,due_on,name,amount,currency) values($1,$2,$3,$4,$5,$6) on conflict do nothing', [workspace.id,bill.id,due,bill.name,bill.amount,bill.currency]);
              if (bill.frequency === 'once') break;
              const occurrenceCount = Number((await tx.unsafe('select count(*)::int as n from bill_occurrences where workspace_id=$1 and bill_id=$2 and due_on >= $3', [workspace.id,bill.id,bill.anchor_date]))[0]!.n);
              const next = nextOccurrenceDate(bill.anchor_date,bill.frequency,Number(bill.interval),occurrenceCount);
              if (next <= due || (bill.end_date && next > bill.end_date)) break;
              due = next;
            }
            await tx.unsafe("update bills set next_due_date=$3,enabled=case when frequency='once' and exists(select 1 from bill_occurrences where workspace_id=$1 and bill_id=$2) then false else enabled end,updated_at=now() where workspace_id=$1 and id=$2", [workspace.id,bill.id,due]);
          }
          const dueItems = await tx.unsafe("select o.id,o.name,o.amount::text,o.currency,o.due_on,b.reminder_days from bill_occurrences o join bills b on b.workspace_id=o.workspace_id and b.id=o.bill_id where o.workspace_id=$1 and o.status='unpaid' and o.due_on >= $2::date and o.due_on <= $3::date and (b.enabled or b.frequency='once') and b.archived_at is null", [workspace.id,today,through]);
          for (const item of dueItems) {
            if(!remindersReleased)continue;
            const days = Math.round((new Date(`${item.due_on}T00:00:00Z`).valueOf()-new Date(`${today}T00:00:00Z`).valueOf())/86400000);
            if (!(item.reminder_days as number[]).includes(days)) continue;
            const dueOn=String(item.due_on).slice(0,10),key=`bill:${item.id}:${dueOn}:due-in:${days}`, title=days?'Bill due soon':'Bill due today';
            const staleStages=await tx.unsafe("update finance_notifications set resolved_at=coalesce(resolved_at,now()),resolution_reason='reminder_stage_changed',updated_at=now() where workspace_id=$1 and user_id=$2 and kind='bill-reminder' and source_type='bill_occurrence' and source_id=$3 and resolved_at is null and dedupe_key<>$4 returning id",[workspace.id,workspace.owner_user_id,item.id,key]);
            if(staleStages.length)await tx.unsafe("update finance_notification_deliveries set status='cancelled',updated_at=now() where workspace_id=$1 and user_id=$2 and notification_id=any($3::uuid[]) and status in ('pending','retryable')",[workspace.id,workspace.owner_user_id,staleStages.map((notice)=>notice.id)]);
            const [notification] = await tx.unsafe("insert into finance_notifications(workspace_id,user_id,kind,source_id,source_type,dedupe_key,title,message,message_key,message_params,evidence,action_type) values($1,$2,'bill-reminder',$3,'bill_occurrence',$4,$5,$6,$7,$8::jsonb,$9::jsonb,'open_bill') on conflict(workspace_id,user_id,dedupe_key) do update set source_type=excluded.source_type,title=excluded.title,message=excluded.message,message_key=excluded.message_key,message_params=excluded.message_params,evidence=excluded.evidence,action_type=excluded.action_type,updated_at=now() returning id,email_sent_at", [workspace.id,workspace.owner_user_id,item.id,key,title,`${item.name} · ${item.currency} ${item.amount} · ${item.due_on}`,days?'bill.upcoming':'bill.today',JSON.stringify({name:item.name,amount:item.amount,currency:item.currency,dueDate:item.due_on}),JSON.stringify({amount:item.amount,currency:item.currency,dueDate:item.due_on})]);
          const [preference] = await tx.unsafe("select enabled,version from finance_notification_preferences where workspace_id=$1 and user_id=$2 and event_type='bill-reminder' and channel='email'", [workspace.id,workspace.owner_user_id]);
          if(preference?.enabled===false)await tx.unsafe("update finance_notification_deliveries d set status='cancelled',updated_at=now() from finance_notifications n where d.workspace_id=$1 and d.user_id=$2 and d.notification_id=n.id and n.workspace_id=d.workspace_id and n.user_id=d.user_id and n.kind='bill-reminder' and d.channel='email' and d.status in ('pending','retryable')",[workspace.id,workspace.owner_user_id]);
            if (preference?.enabled === false) continue;
            const [user] = await tx.unsafe('select email from "user" where id=$1', [workspace.owner_user_id]);
            if (!user?.email) continue;
            if(notification!.email_sent_at)continue;
            const [cutover]=await tx.unsafe("select state->>'cutoverAt' as at from finance_notification_evaluation_state where workspace_id=$1 and user_id=$2 and rule_key='rollout' and period_key='notifications-mvp'",[workspace.id,workspace.owner_user_id]);
            if(cutover){const [legacy]=await tx.unsafe('select 1 from finance_notifications where workspace_id=$1 and user_id=$2 and id=$3 and created_at<=$4::timestamptz',[workspace.id,workspace.owner_user_id,notification!.id,cutover.at]);if(legacy)continue;}

            const [delivery]=await tx.unsafe("insert into finance_notification_deliveries(workspace_id,user_id,notification_id,channel,destination_key,generation,preference_version,expires_at) values($1,$2,$3,'email',$4,1,$5,now()+interval '7 days') on conflict(workspace_id,user_id,notification_id,channel,destination_key,generation) do nothing returning id",[workspace.id,workspace.owner_user_id,notification!.id,`email:${workspace.owner_user_id}`,preference?.version??1]);
            const [pending]=delivery?[delivery]:await tx.unsafe("select id from finance_notification_deliveries where workspace_id=$1 and user_id=$2 and notification_id=$3 and channel='email' and destination_key=$4 and generation=1 and status in ('pending','retryable') and available_at<=now() and attempts<5 and expires_at>now()",[workspace.id,workspace.owner_user_id,notification!.id,`email:${workspace.owner_user_id}`]);
            if(pending)emailJobs.push({jobId:String(pending.id),message:{kind:'bill-reminder',to:user.email,billName:item.name,amount:item.amount,currency:item.currency,dueDate:item.due_on,workspaceId:workspace.id,userId:workspace.owner_user_id,occurrenceId:item.id,notificationId:String(notification!.id),deliveryId:String(pending.id),locale:'en',expiresAt:now.valueOf()+7*86400000}});
          }
          const overdueCutoff=new Date(`${today}T00:00:00Z`);overdueCutoff.setUTCDate(overdueCutoff.getUTCDate()-7);
          const expiredNotices=await tx.unsafe("update finance_notifications n set resolved_at=coalesce(n.resolved_at,now()),resolution_reason='bill_no_longer_eligible',updated_at=now() where n.workspace_id=$1 and n.user_id=$2 and n.kind='bill-reminder' and n.source_type='bill_occurrence' and n.resolved_at is null and not exists(select 1 from bill_occurrences o join bills b on b.workspace_id=o.workspace_id and b.id=o.bill_id where o.workspace_id=n.workspace_id and o.id=n.source_id and o.status='unpaid' and (b.enabled or b.frequency='once') and b.archived_at is null and o.due_on >= $3::date and n.dedupe_key like 'bill:'||o.id::text||':'||o.due_on::text||':%') returning n.id",[workspace.id,workspace.owner_user_id,overdueCutoff.toISOString().slice(0,10)]);
          if(expiredNotices.length)await tx.unsafe("update finance_notification_deliveries set status='cancelled',updated_at=now() where workspace_id=$1 and notification_id=any($2::uuid[]) and status in ('pending','retryable')",[workspace.id,expiredNotices.map((item)=>item.id)]);
          const [pushPreference]=await tx.unsafe("select enabled,version from finance_notification_preferences where workspace_id=$1 and user_id=$2 and event_type='bill-reminder' and channel='push'",[workspace.id,workspace.owner_user_id]);
          if(pushPreference?.enabled===false)await tx.unsafe("update finance_notification_deliveries d set status='cancelled',updated_at=now() from finance_notifications n where d.workspace_id=$1 and d.user_id=$2 and d.notification_id=n.id and n.workspace_id=d.workspace_id and n.user_id=d.user_id and n.kind='bill-reminder' and d.channel='push' and d.status in ('pending','retryable')",[workspace.id,workspace.owner_user_id]);
          const publicKey=process.env.VAPID_PUBLIC_KEY,privateKey=process.env.VAPID_PRIVATE_KEY,subject=process.env.VAPID_SUBJECT??'mailto:hello@capybudget.local';
          if(pushPreference?.enabled===true&&(pushSender||publicKey&&privateKey)){
            const notifications=await tx.unsafe("select n.id,n.source_id from finance_notifications n join bill_occurrences o on o.workspace_id=n.workspace_id and o.id=n.source_id where n.workspace_id=$1 and n.user_id=$2 and n.kind='bill-reminder' and n.resolved_at is null and n.dismissed_at is null and (n.created_at at time zone $4)::date >= $3::date and o.status='unpaid'",[workspace.id,workspace.owner_user_id,today,workspace.timezone]);
            const subscriptions=await tx.unsafe('select id from push_subscriptions where workspace_id=$1 and user_id=$2',[workspace.id,workspace.owner_user_id]);
            for(const notification of notifications)for(const subscription of subscriptions){
              await tx.unsafe("insert into finance_notification_deliveries(workspace_id,user_id,notification_id,channel,destination_key,push_subscription_id,preference_version,expires_at) select $1,$2,$3,'push',$4,$5,$6,now()+interval '7 days' where not exists(select 1 from finance_notification_deliveries where workspace_id=$1 and user_id=$2 and notification_id=$3 and channel='push' and destination_key=$4 and generation=1)",[workspace.id,workspace.owner_user_id,notification.id,`push:${subscription.id}`,subscription.id,pushPreference.version??1]);
            }
            const pendingPush=await tx.unsafe("select d.id as delivery_id,d.notification_id,n.source_id as occurrence_id,d.push_subscription_id from finance_notification_deliveries d join finance_notifications n on n.workspace_id=d.workspace_id and n.user_id=d.user_id and n.id=d.notification_id where d.workspace_id=$1 and d.user_id=$2 and d.channel='push' and d.status in ('pending','retryable') and d.available_at<=now() and n.kind='bill-reminder' and (n.created_at at time zone $4)::date >= $3::date",[workspace.id,workspace.owner_user_id,today,workspace.timezone]);
            for(const item of pendingPush)pushJobs.push({workspaceId:String(workspace.id),userId:String(workspace.owner_user_id),deliveryId:String(item.delivery_id),notificationId:String(item.notification_id),occurrenceId:String(item.occurrence_id),subscriptionId:String(item.push_subscription_id)});
            if(!pushSender)webpush.setVapidDetails(subject,publicKey!,privateKey!);
          }

          const assistantAlerts=await tx.unsafe(`select n.id,n.title,n.message,n.user_id as "userId",u.email,a.locale,a.consent_version as "consentVersion",r.consent_version as "runConsentVersion",f.checked_at as "checkedAt",p.version as "preferenceVersion"
            from finance_notifications n
            join assistant_suggestions s on s.workspace_id=n.workspace_id and s.user_id=n.user_id and s.id=n.assistant_suggestion_id
            join forecast_runs r on r.workspace_id=s.workspace_id and r.id=s.run_id
            join assistant_settings a on a.workspace_id=n.workspace_id and a.user_id=n.user_id
            join assistant_refresh_state f on f.workspace_id=n.workspace_id and f.user_id=n.user_id
            join finance_notification_preferences p on p.workspace_id=n.workspace_id and p.user_id=n.user_id and p.event_type='assistant-alert' and p.channel='email' and p.enabled=true
            join "user" u on u.id=n.user_id
            where n.workspace_id=$1 and n.kind in ('cashflow-shortfall','cashflow-low-balance','assistant-invoice-followup') and n.resolved_at is null and n.email_sent_at is null and s.state in ('active','reviewing') and s.expires_at>now()
              and a.local_forecast_enabled and a.suggestions_enabled and a.consent_version=r.consent_version and f.checked_at>=n.created_at
              and not exists(select 1 from finance_notification_evaluation_state cutover where cutover.workspace_id=n.workspace_id and cutover.user_id=n.user_id and cutover.rule_key='rollout' and cutover.period_key='notifications-mvp' and n.created_at<=(cutover.state->>'cutoverAt')::timestamptz)
              and not (s.facts->>'scope'='account' and exists(select 1 from finance_notifications wn join assistant_suggestions ws on ws.workspace_id=wn.workspace_id and ws.user_id=wn.user_id and ws.id=wn.assistant_suggestion_id where wn.workspace_id=n.workspace_id and wn.user_id=n.user_id and wn.kind=n.kind and wn.resolved_at is null and ws.state in ('active','reviewing') and ws.facts->>'scope'='workspace' and ws.facts->>'date'=s.facts->>'date'))
            order by n.created_at limit 50`,[workspace.id]);
          for(const alert of assistantAlerts){
            if(!alert.email||Number(alert.consentVersion)!==Number(alert.runConsentVersion))continue;
            const [created]=await tx.unsafe("insert into finance_notification_deliveries(workspace_id,user_id,notification_id,channel,destination_key,generation,preference_version,expires_at) values($1,$2,$3,'email',$4,1,$5,now()+interval '7 days') on conflict(workspace_id,user_id,notification_id,channel,destination_key,generation) do nothing returning id",[workspace.id,alert.userId,alert.id,`email:${alert.userId}`,alert.preferenceVersion??1]);
            const [delivery]=created?[created]:await tx.unsafe("select id from finance_notification_deliveries where workspace_id=$1 and user_id=$2 and notification_id=$3 and channel='email' and destination_key=$4 and generation=1 and status in ('pending','retryable') and available_at<=now() and expires_at>now()",[workspace.id,alert.userId,alert.id,`email:${alert.userId}`]);
            if(delivery)emailJobs.push({jobId:String(delivery.id),message:{kind:'assistant-alert',to:alert.email,workspaceId:workspace.id,userId:alert.userId,notificationId:alert.id,deliveryId:String(delivery.id),title:alert.title,message:alert.message,locale:alert.locale==='id'?'id':'en',expiresAt:now.valueOf()+7*86400000}});
          }
          const pushAlerts=await tx.unsafe(`select n.id,n.user_id as "userId",a.locale,p.version as "preferenceVersion"
            from finance_notifications n join assistant_suggestions s on s.workspace_id=n.workspace_id and s.user_id=n.user_id and s.id=n.assistant_suggestion_id
            join forecast_runs r on r.workspace_id=s.workspace_id and r.id=s.run_id
            join assistant_settings a on a.workspace_id=n.workspace_id and a.user_id=n.user_id
            join assistant_refresh_state f on f.workspace_id=n.workspace_id and f.user_id=n.user_id
            join finance_notification_preferences p on p.workspace_id=n.workspace_id and p.user_id=n.user_id and p.event_type='assistant-alert' and p.channel='push' and p.enabled=true
            where n.workspace_id=$1 and n.kind in ('cashflow-shortfall','cashflow-low-balance','assistant-invoice-followup') and n.resolved_at is null and s.state in ('active','reviewing') and s.expires_at>now()
              and a.local_forecast_enabled and a.suggestions_enabled and a.consent_version=r.consent_version and f.checked_at>=n.created_at
              and not exists(select 1 from finance_notification_evaluation_state cutover where cutover.workspace_id=n.workspace_id and cutover.user_id=n.user_id and cutover.rule_key='rollout' and cutover.period_key='notifications-mvp' and n.created_at<=(cutover.state->>'cutoverAt')::timestamptz)
              and not (s.facts->>'scope'='account' and exists(select 1 from finance_notifications wn join assistant_suggestions ws on ws.workspace_id=wn.workspace_id and ws.user_id=wn.user_id and ws.id=wn.assistant_suggestion_id where wn.workspace_id=n.workspace_id and wn.user_id=n.user_id and wn.kind=n.kind and wn.resolved_at is null and ws.state in ('active','reviewing') and ws.facts->>'scope'='workspace' and ws.facts->>'date'=s.facts->>'date')) order by n.created_at limit 50`,[workspace.id]);
          if(pushAlerts.length&&(pushSender||publicKey&&privateKey)){
            if(!pushSender)webpush.setVapidDetails(subject,publicKey!,privateKey!);
            for(const alert of pushAlerts){
              await tx.unsafe("insert into finance_notification_deliveries(workspace_id,user_id,notification_id,channel,destination_key,push_subscription_id,generation,preference_version,expires_at) select $1,$2,$3,'push','push:'||s.id::text,s.id,1,$4,now()+interval '7 days' from push_subscriptions s where s.workspace_id=$1 and s.user_id=$2 on conflict(workspace_id,user_id,notification_id,channel,destination_key,generation) do nothing",[workspace.id,alert.userId,alert.id,alert.preferenceVersion]);
              const pending=await tx.unsafe("select d.id as \"deliveryId\",d.notification_id as \"notificationId\",d.push_subscription_id as \"subscriptionId\" from finance_notification_deliveries d where d.workspace_id=$1 and d.user_id=$2 and d.notification_id=$3 and d.channel='push' and d.status in ('pending','retryable') and d.available_at<=now() and d.attempts<5 and d.expires_at>now() order by d.created_at",[workspace.id,alert.userId,alert.id]);
              for(const delivery of pending)assistantPushJobs.push({workspaceId:String(workspace.id),userId:String(alert.userId),deliveryId:String(delivery.deliveryId),notificationId:String(delivery.notificationId),subscriptionId:String(delivery.subscriptionId)});
            }
          }
        });
        for(const job of emailJobs){try{await emailEnqueuer(job.message,job.jobId);}catch(error){console.error('Notification email enqueue failed',{workspaceId:workspace.id,deliveryId:job.jobId,errorCode:(error as {code?:string}).code??'unknown'});}}
        for(const job of pushJobs)await deliverPushJob(job,pushSender);
        for(const job of assistantPushJobs)await deliverAssistantPushJob(job,pushSender);
      } catch (error) { console.error('Bill reminder sweep failed for workspace', { workspaceId: workspace.id, errorCode: (error as {code?:string}).code??'unknown', errorMessage: (error as {message?:string}).message??'unknown' }); }
    }
  } finally { running = false; }
}

export function startBillReminderScheduler(): void {
  void sweepBillReminders();
  const timer = setInterval(() => void sweepBillReminders(), 60_000);
  timer.unref();
}
