<script lang="ts">
  import { formatDateTime } from '$lib/dates';
  import PasswordInput from '$lib/components/forms/password-input.svelte';
  import LoadingScope from '$lib/components/shared/loading-scope.svelte';
 import {goto} from '$app/navigation';
 import {getContext,onMount} from 'svelte';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {securityRequest} from '$lib/security/request';import {readPrivacyMode,writePrivacyMode} from '$lib/privacy';import {uxText} from '$lib/i18n/ux';
 import {Button} from '$lib/components/ui/button';import {Input} from '$lib/components/ui/input';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';
 import PageHeader from '$lib/components/shared/page-header.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';
 const ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),text=(en:string,id:string)=>ui.locale==='id'?id:en;
 const ux=(key:Parameters<typeof uxText>[1])=>uxText(ui.locale,key);
 let password=$state(''),code=$state(''),confirmation=$state(''),masked=$state(true),preview=$state<any>(null),exports:any[]=$state([]),busy=$state(false),error=$state(''),receipt=$state<any>(null),backups=$state<any>(null);
 async function load(){const b=await fetch('/api/security/backups/status');if(b.ok)backups=await b.json();const r=await fetch('/api/privacy/exports',{cache:'no-store'});if(r.ok)exports=(await r.json()).items;}
 onMount(()=>{masked=readPrivacyMode();void load();const timer=setInterval(()=>void load(),10_000);return()=>clearInterval(timer);});
 async function grant(purpose:string){return (await securityRequest('reauthenticate',{password,code,purpose})).grant;}
 async function request(path:string,body:unknown,purpose:string){const token=await grant(purpose);return fetch('/api/privacy/'+path,{method:'POST',headers:{'content-type':'application/json','x-security-grant':token},body:JSON.stringify(body)});}
 async function action(fn:()=>Promise<void>){busy=true;error='';try{await fn();await load();}catch(e){error=e instanceof Error?e.message:'Request failed.';}finally{busy=false;password='';code='';}}
 async function createExport(){await action(async()=>{const r=await request('exports',{requestKey:crypto.randomUUID()},'export');if(!r.ok)throw new Error((await r.json()).message);});}
 async function download(id:string){await action(async()=>{const r=await request('exports/'+id+'/download',{},'export');if(!r.ok)throw new Error((await r.json()).message);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='capybudget-account.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 async function showPreview(){await action(async()=>{const r=await fetch('/api/privacy/deletion/preview',{cache:'no-store'});if(!r.ok)throw new Error('Preview unavailable.');preview=await r.json();});}
 async function remove(){await action(async()=>{const r=await request('deletion',{scopeVersion:preview.scopeVersion,confirmation},'delete');const data=await r.json();if(!r.ok)throw new Error(data.message);receipt=data;preview=null;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='capybudget-deletion-receipt.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await goto('/deletion-receipt',{invalidateAll:true});});}
</script>
<LoadingScope active={!!busy} />
<svelte:head><title>{text('Privacy settings','Pengaturan privasi')} · CapyBudget</title></svelte:head>
<div class="privacy-settings"><PageHeader eyebrow={text('PROTECTION','PERLINDUNGAN')} title={text('Privacy and your data','Privasi dan data Anda')} />
{#if receipt}<Card.Root><Card.Header><Card.Title>{text('Deletion accepted','Penghapusan diterima')}</Card.Title><Card.Description>{text('Your account is quarantined. Save this private receipt to check cleanup status. Backups expire within 35 days.','Akun Anda dikarantina. Simpan tanda terima pribadi ini untuk memeriksa pembersihan. Cadangan kedaluwarsa dalam 35 hari.')}</Card.Description></Card.Header><Card.Content><pre>{JSON.stringify(receipt,null,2)}</pre><Button onclick={async()=>{const r=await fetch('/api/privacy/deletion/receipt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:receipt.id,receipt:receipt.receipt})});if(r.ok)receipt={...receipt,...await r.json()};}}>{text('Check status','Periksa status')}</Button></Card.Content></Card.Root>{:else}
<Card.Root><Card.Header><Card.Title>{text('Hide financial amounts','Sembunyikan jumlah keuangan')}</Card.Title><Card.Description>{text('Conceal on-screen amounts. Downloaded exports contain your full financial data.','Sembunyikan jumlah di layar. Ekspor berisi data keuangan lengkap Anda.')}</Card.Description></Card.Header><Card.Content><Button variant="outline" onclick={()=>{masked=!masked;writePrivacyMode(masked);}}>{masked?text('Show amounts','Tampilkan jumlah'):text('Hide amounts','Sembunyikan jumlah')}</Button></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{text('Confirm identity for data requests','Konfirmasi identitas untuk permintaan data')}</Card.Title><Card.Description>{text('Use your password and authenticator code if enabled.','Gunakan kata sandi dan kode autentikator jika aktif.')}</Card.Description></Card.Header><Card.Content><Field.FieldGroup><Field.Field><Field.FieldLabel for="privacy-password">{text('Password','Kata sandi')}</Field.FieldLabel><PasswordInput id="privacy-password"  bind:value={password} autocomplete="current-password"/></Field.Field><Field.Field><Field.FieldLabel for="privacy-code">{text('Authenticator code','Kode autentikator')}</Field.FieldLabel><Input id="privacy-code" bind:value={code} autocomplete="one-time-code" inputmode="numeric"/></Field.Field></Field.FieldGroup></Card.Content></Card.Root>
{#if error}<ErrorState title={ux('errorTitle')} message={error} />{/if}
<Card.Root><Card.Header><Card.Title>{text('Export all account data','Ekspor semua data akun')}</Card.Title><Card.Description>{text('Personal and business records, including retained files, in a ZIP archive. Downloads expire after 24 hours. Large accounts may require operator assistance.','Catatan pribadi dan bisnis, termasuk berkas tersimpan, dalam arsip ZIP. Unduhan kedaluwarsa setelah 24 jam. Akun besar mungkin memerlukan bantuan operator.')}</Card.Description></Card.Header><Card.Content><Button disabled={busy} onclick={createExport}>{text('Request export','Minta ekspor')}</Button>{#each exports as item}<div class="export"><span>{formatDateTime(item.created_at, ui.locale)} · {item.status}{item.failure_code?' · '+item.failure_code:''}</span>{#if item.status==='ready'}<Button variant="outline" disabled={busy} onclick={()=>download(item.id)}>{text('Download full data','Unduh data lengkap')}</Button>{/if}</div>{/each}</Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{text('Backups and online sync','Cadangan dan sinkronisasi daring')}</Card.Title><Card.Description>{text('Changes are saved to the server while online. Encrypted daily backups include your database and retained files.','Perubahan disimpan di server saat daring. Cadangan harian terenkripsi mencakup database dan berkas tersimpan.')}</Card.Description></Card.Header><Card.Content>{#if backups}<p role={backups.stale?'alert':'status'}>{backups.stale?text('No verified backup within 26 hours. Ask the operator to check the backup service.','Tidak ada cadangan terverifikasi dalam 26 jam. Minta operator memeriksa layanan cadangan.'):text('Recent backup verified.','Cadangan terbaru terverifikasi.')}</p><p>{text('Last verified backup','Cadangan terakhir terverifikasi')}: {backups.lastVerifiedAt?formatDateTime(backups.lastVerifiedAt, ui.locale):'—'}</p><p>{text('Last restore drill','Uji pemulihan terakhir')}: {backups.lastRestoreAt?formatDateTime(backups.lastRestoreAt, ui.locale):'—'} · {backups.restoreOutcome??'—'}</p>{/if}<p>{text('Local backups use SeaweedFS. External S3 will be configured for deployment.','Cadangan lokal menggunakan SeaweedFS. S3 eksternal akan dikonfigurasi untuk penerapan.')}</p></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{text('Delete account','Hapus akun')}</Card.Title><Card.Description>{text('Permanently erase all owned workspaces and files. Delivered emails and prior downloads cannot be recalled.','Hapus permanen semua ruang kerja dan berkas milik Anda. Email terkirim dan unduhan sebelumnya tidak dapat ditarik kembali.')}</Card.Description></Card.Header><Card.Content><Button variant="outline" disabled={busy} onclick={showPreview}>{text('Review deletion','Tinjau penghapusan')}</Button>{#if preview}<p>{preview.workspaces.length} {text('workspaces','ruang kerja')} · {preview.files} {text('files','berkas')}</p><ul>{#each preview.workspaces as ws}<li>{ws.name} · {ws.kind}</li>{/each}</ul><Field.Field><Field.FieldLabel for="deletion-confirm">{text('Type DELETE MY ACCOUNT to confirm','Ketik DELETE MY ACCOUNT untuk konfirmasi')}</Field.FieldLabel><Input id="deletion-confirm" bind:value={confirmation}/></Field.Field><Button variant="destructive" disabled={busy||preview.blocked||confirmation!=='DELETE MY ACCOUNT'} onclick={remove}>{text('Permanently delete account','Hapus akun permanen')}</Button>{/if}</Card.Content></Card.Root>{/if}</div>
<style>.privacy-settings{max-width:760px;display:grid;gap:16px}.export{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px;margin-top:16px}pre{white-space:pre-wrap;overflow-wrap:anywhere}:global(.privacy-settings :global([data-slot="button"])){min-height:44px}</style>
