<script lang="ts">
 import {getContext} from 'svelte';import {goto} from '$app/navigation';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {businessText} from '$lib/i18n/business';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';
 type Workspace={selectedId:string;ready:boolean;items:{id:string;kind:string;timezone?:string}[]};type Line={description:string;quantity:string;unitPrice:string;discountAmount:string;taxRate:string};
 const workspace=getContext<Workspace>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof businessText>[1])=>businessText(ui.locale,key);
 function today(){const timezone=workspace.items.find(x=>x.id===workspace.selectedId)?.timezone??'Asia/Jakarta',parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=(name:string)=>parts.find(x=>x.type===name)?.value;return get('year')+'-'+get('month')+'-'+get('day');}
 let recipient=$state({name:'',email:'',phone:'',taxId:'',address:{street:'',city:'',region:'',postalCode:'',country:''}}),issueDate=$state(''),dueDate=$state(''),notes=$state(''),paymentInstructions=$state(''),lines:Line[]=$state([{description:'',quantity:'1',unitPrice:'',discountAmount:'0',taxRate:'0'}]),saving=$state(false),error=$state('');
 $effect(()=>{if(workspace.ready&&workspace.selectedId&&!issueDate){issueDate=today();const d=new Date(issueDate+'T12:00:00');d.setDate(d.getDate()+14);dueDate=d.toISOString().slice(0,10);}});
 function addLine(){if(lines.length<100)lines=[...lines,{description:'',quantity:'1',unitPrice:'',discountAmount:'0',taxRate:'0'}];}
 function removeLine(i:number){if(lines.length>1)lines=lines.filter((_,n)=>n!==i);}
 async function create(event:SubmitEvent){event.preventDefault();if(saving)return;saving=true;error='';try{const response=await fetch('/api/workspaces/'+workspace.selectedId+'/invoices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recipient,issueDate,dueDate,notes:notes||null,paymentInstructions:paymentInstructions||null,locale:ui.locale,lines})}),data=await response.json();if(!response.ok)throw new Error(data.message??t('error'));await goto('/invoices/'+data.invoice.id);}catch(e){error=e instanceof Error?e.message:t('error');}finally{saving=false;}}
</script>
<svelte:head><title>CapyBudget · {t('newInvoice')}</title></svelte:head>
<div class="head"><p><a href="/invoices">{t('invoices')}</a></p><h1>{t('newInvoice')}</h1><span>Start a draft. Totals are calculated by the server when you save.</span></div>
{#if error}<p class="error" role="alert">{error}</p>{/if}
<form onsubmit={create}><div class="stack">
<Card.Root><Card.Header><Card.Title>{t('customer')}</Card.Title><Card.Description>Recipient details are saved on this invoice.</Card.Description></Card.Header><Card.Content><Field.FieldGroup class="grid">
<Field.Field><Field.FieldLabel for="recipient">{t('customer')}</Field.FieldLabel><Input id="recipient" bind:value={recipient.name} maxlength={200} required /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-email">{t('email')}</Field.FieldLabel><Input id="recipient-email" type="email" bind:value={recipient.email} maxlength={320} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-phone">{t('phone')}</Field.FieldLabel><Input id="recipient-phone" bind:value={recipient.phone} maxlength={80} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-tax">{t('taxId')}</Field.FieldLabel><Input id="recipient-tax" bind:value={recipient.taxId} maxlength={100} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-street">{t('street')}</Field.FieldLabel><Input id="recipient-street" bind:value={recipient.address.street} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-city">{t('city')}</Field.FieldLabel><Input id="recipient-city" bind:value={recipient.address.city} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-region">{t('region')}</Field.FieldLabel><Input id="recipient-region" bind:value={recipient.address.region} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-postal">{t('postalCode')}</Field.FieldLabel><Input id="recipient-postal" bind:value={recipient.address.postalCode} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-country">{t('country')}</Field.FieldLabel><Input id="recipient-country" bind:value={recipient.address.country} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="issue-date">{t('issueDate')}</Field.FieldLabel><Input id="issue-date" type="date" bind:value={issueDate} required /></Field.Field>
<Field.Field><Field.FieldLabel for="due-date">{t('dueDate')}</Field.FieldLabel><Input id="due-date" type="date" bind:value={dueDate} required /></Field.Field>
</Field.FieldGroup></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{t('invoice')}</Card.Title><Card.Description>Use a separate line for each item or service.</Card.Description></Card.Header><Card.Content><div class="lines">{#each lines as line,i (i)}<div class="line"><Field.Field><Field.FieldLabel for={'line-description-'+i}>{t('description')}</Field.FieldLabel><Input id={'line-description-'+i} bind:value={line.description} maxlength={500} required /></Field.Field><Field.Field><Field.FieldLabel for={'line-quantity-'+i}>{t('quantity')}</Field.FieldLabel><Input id={'line-quantity-'+i} bind:value={line.quantity} inputmode="decimal" required /></Field.Field><Field.Field><Field.FieldLabel for={'line-price-'+i}>{t('unitPrice')}</Field.FieldLabel><Input id={'line-price-'+i} bind:value={line.unitPrice} inputmode="decimal" required /></Field.Field><Field.Field><Field.FieldLabel for={'line-discount-'+i}>{t('discount')}</Field.FieldLabel><Input id={'line-discount-'+i} bind:value={line.discountAmount} inputmode="decimal" /></Field.Field><Field.Field><Field.FieldLabel for={'line-tax-'+i}>{t('taxRate')}</Field.FieldLabel><Input id={'line-tax-'+i} bind:value={line.taxRate} inputmode="decimal" /></Field.Field>{#if lines.length>1}<Button type="button" variant="ghost" onclick={()=>removeLine(i)}>{t('removeLine')}</Button>{/if}</div>{/each}</div><Button type="button" variant="outline" onclick={addLine} disabled={lines.length>=100}>{t('addLine')}</Button>
<Field.FieldGroup class="grid extra"><Field.Field><Field.FieldLabel for="invoice-notes">{t('notes')}</Field.FieldLabel><Input id="invoice-notes" bind:value={notes} maxlength={4000} /></Field.Field><Field.Field><Field.FieldLabel for="payment-instructions">{t('paymentInstructions')}</Field.FieldLabel><Input id="payment-instructions" bind:value={paymentInstructions} maxlength={2000} /></Field.Field></Field.FieldGroup>
</Card.Content></Card.Root><div class="actions"><Button href="/invoices" variant="outline">{t('cancel')}</Button><Button type="submit" disabled={saving||!workspace.selectedId}>{saving?'…':t('saveDraft')}</Button></div></div></form>
<style>.head{margin-bottom:20px}.head p{margin:0;color:var(--muted-foreground)}.head a{color:inherit}.head h1{font:500 clamp(28px,4vw,38px) 'Fredoka Variable',sans-serif;margin:3px 0}.head span{color:var(--muted-foreground)}.stack{display:grid;gap:18px}:global(.grid){display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.lines{display:grid;gap:18px;margin-bottom:16px}.line{display:grid;grid-template-columns:minmax(190px,2fr) repeat(4,minmax(90px,1fr)) auto;gap:10px;align-items:end;border-bottom:1px solid var(--border);padding-bottom:14px}:global(.extra){margin-top:20px}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.error{color:var(--destructive)}@media(max-width:800px){.line{grid-template-columns:repeat(2,minmax(0,1fr))}:global(.line)>:first-child{grid-column:1/-1}}@media(max-width:560px){:global(.grid){grid-template-columns:1fr}}</style>
