<script lang="ts">
  import AmountInput from '$lib/components/forms/amount-input.svelte';
  import LoadingScope from '$lib/components/shared/loading-scope.svelte';
  import DatePicker from '$lib/components/forms/date-picker.svelte';
  import {getContext as privacyContext} from 'svelte';
  import {concealed,PRIVACY_CONTEXT,type PrivacyState} from '$lib/privacy';
  const privacy=privacyContext<PrivacyState>(PRIVACY_CONTEXT);
 import {getContext} from 'svelte';import {goto} from '$app/navigation';import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {businessText} from '$lib/i18n/business';import {uxText} from '$lib/i18n/ux';import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import {Input} from '$lib/components/ui/input';import PageHeader from '$lib/components/shared/page-header.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';
 type Workspace={selectedId:string;ready:boolean;items:{id:string;kind:string;timezone?:string}[]};type Line={description:string;quantity:string;unitPrice:string;discountAmount:string;taxRate:string};
 const workspace=getContext<Workspace>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT),t=(key:Parameters<typeof businessText>[1])=>businessText(ui.locale,key);
 const ux=(key:Parameters<typeof uxText>[1])=>uxText(ui.locale,key);
 function today(){const timezone=workspace.items.find(x=>x.id===workspace.selectedId)?.timezone??'Asia/Jakarta',parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=(name:string)=>parts.find(x=>x.type===name)?.value;return get('year')+'-'+get('month')+'-'+get('day');}
 let recipient=$state({name:'',email:'',phone:'',taxId:'',address:{street:'',city:'',region:'',postalCode:'',country:''}}),issueDate=$state(''),dueDate=$state(''),notes=$state(''),paymentInstructions=$state(''),lines:Line[]=$state([{description:'',quantity:'1',unitPrice:'',discountAmount:'0',taxRate:'0'}]),saving=$state(false),error=$state('');
 $effect(()=>{void (workspace as {revision?:number}).revision;if(workspace.ready&&workspace.selectedId&&!issueDate){issueDate=today();const d=new Date(issueDate+'T12:00:00');d.setDate(d.getDate()+14);dueDate=d.toISOString().slice(0,10);}});
 function addLine(){if(lines.length<100)lines=[...lines,{description:'',quantity:'1',unitPrice:'',discountAmount:'0',taxRate:'0'}];}
 function removeLine(i:number){if(lines.length>1)lines=lines.filter((_,n)=>n!==i);}
 async function create(event:SubmitEvent){event.preventDefault();if(saving)return;saving=true;error='';try{const response=await fetch('/api/workspaces/'+workspace.selectedId+'/invoices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recipient,issueDate,dueDate,notes:notes||null,paymentInstructions:paymentInstructions||null,locale:ui.locale,lines})}),data=await response.json();if(!response.ok)throw new Error(data.message??t('error'));await goto('/invoices/'+data.invoice.id);}catch(e){error=e instanceof Error?e.message:t('error');}finally{saving=false;}}
</script>
<LoadingScope active={!!saving} />
<svelte:head><title>CapyBudget · {t('newInvoice')}</title></svelte:head>
<p class="back"><a href="/invoices">← {t('invoices')}</a></p>
<PageHeader eyebrow={t('studioMode').toUpperCase()} title={t('newInvoice')} description={t('draftHint')} />
{#if error}<ErrorState title={ux('errorTitle')} message={error} />{/if}
<form onsubmit={create}><div class="stack">
<Card.Root><Card.Header><Card.Title>{t('customer')}</Card.Title><Card.Description>{t('recipientHint')}</Card.Description></Card.Header><Card.Content><Field.FieldGroup class="invoice-fields">
<Field.Field><Field.FieldLabel for="recipient">{t('customer')}</Field.FieldLabel><Input id="recipient" bind:value={recipient.name} maxlength={200} required /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-email">{t('email')}</Field.FieldLabel><Input id="recipient-email" type="email" bind:value={recipient.email} maxlength={320} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-phone">{t('phone')}</Field.FieldLabel><Input id="recipient-phone" bind:value={recipient.phone} maxlength={80} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-tax">{t('taxId')}</Field.FieldLabel><Input id="recipient-tax" bind:value={recipient.taxId} maxlength={100} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-street">{t('street')}</Field.FieldLabel><Input id="recipient-street" bind:value={recipient.address.street} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-city">{t('city')}</Field.FieldLabel><Input id="recipient-city" bind:value={recipient.address.city} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-region">{t('region')}</Field.FieldLabel><Input id="recipient-region" bind:value={recipient.address.region} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-postal">{t('postalCode')}</Field.FieldLabel><Input id="recipient-postal" bind:value={recipient.address.postalCode} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="recipient-country">{t('country')}</Field.FieldLabel><Input id="recipient-country" bind:value={recipient.address.country} maxlength={200} /></Field.Field>
<Field.Field><Field.FieldLabel for="issue-date">{t('issueDate')}</Field.FieldLabel><DatePicker id="issue-date" bind:value={issueDate} required /></Field.Field>
<Field.Field><Field.FieldLabel for="due-date">{t('dueDate')}</Field.FieldLabel><DatePicker id="due-date" bind:value={dueDate} required /></Field.Field>
</Field.FieldGroup></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{t('invoice')}</Card.Title><Card.Description>{t('linesHint')}</Card.Description></Card.Header><Card.Content><div class="lines">{#each lines as line,i (i)}<div class="line"><Field.Field><Field.FieldLabel for={'line-description-'+i}>{t('description')}</Field.FieldLabel><Input id={'line-description-'+i} bind:value={line.description} maxlength={500} required /></Field.Field><Field.Field><Field.FieldLabel for={'line-quantity-'+i}>{t('quantity')}</Field.FieldLabel><Input id={'line-quantity-'+i} bind:value={line.quantity} inputmode="decimal" required /></Field.Field><Field.Field><Field.FieldLabel for={'line-price-'+i}>{t('unitPrice')}</Field.FieldLabel><AmountInput id={'line-price-'+i}  type={privacy.hidden?'password':'text'} bind:value={line.unitPrice} inputmode="decimal" required /></Field.Field><Field.Field><Field.FieldLabel for={'line-discount-'+i}>{t('discount')}</Field.FieldLabel><AmountInput id={'line-discount-'+i}  type={privacy.hidden?'password':'text'} bind:value={line.discountAmount} inputmode="decimal" /></Field.Field><Field.Field><Field.FieldLabel for={'line-tax-'+i}>{t('taxRate')}</Field.FieldLabel><Input id={'line-tax-'+i} bind:value={line.taxRate} inputmode="decimal" /></Field.Field>{#if lines.length>1}<Button type="button" variant="ghost" onclick={()=>removeLine(i)}>{t('removeLine')}</Button>{/if}</div>{/each}</div><Button type="button" variant="outline" onclick={addLine} disabled={lines.length>=100}>{t('addLine')}</Button>
<Field.FieldGroup class="invoice-fields extra"><Field.Field><Field.FieldLabel for="invoice-notes">{t('notes')}</Field.FieldLabel><Input id="invoice-notes" bind:value={notes} maxlength={4000} /></Field.Field><Field.Field><Field.FieldLabel for="payment-instructions">{t('paymentInstructions')}</Field.FieldLabel><Input id="payment-instructions" bind:value={paymentInstructions} maxlength={2000} /></Field.Field></Field.FieldGroup>
</Card.Content></Card.Root><div class="actions"><Button href="/invoices" variant="outline">{t('cancel')}</Button><Button type="submit" disabled={saving||!workspace.selectedId}>{saving?'…':t('saveDraft')}</Button></div></div></form>
<style>.back{margin:0 0 4px}.back a{color:var(--brand-ink);font-weight:600;text-decoration:none}.stack{display:grid;gap:16px}.stack :global(.invoice-fields){display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.lines{display:grid;gap:16px;margin-bottom:16px}.line{display:grid;grid-template-columns:minmax(190px,2fr) repeat(4,minmax(90px,1fr)) auto;gap:8px;align-items:end;border-bottom:1px solid var(--border);padding-bottom:12px}:global(.extra){margin-top:16px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px;flex-wrap:wrap}@media(max-width:800px){.line{grid-template-columns:repeat(2,minmax(0,1fr))}:global(.line)>:first-child{grid-column:1/-1}}@media(max-width:560px){.stack :global(.invoice-fields){grid-template-columns:1fr}.line{grid-template-columns:minmax(0,1fr)}}</style>
