import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright';
import {hashPassword} from 'better-auth/crypto';
if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL required');const database=new URL(process.env.DATABASE_URL);if(!['localhost','127.0.0.1'].includes(database.hostname))throw new Error('Local isolated database required');database.pathname='/capybudget_assistant_v2_test';process.env.DATABASE_URL=database.toString();const redis=new URL(process.env.REDIS_URL??'redis://localhost:6379');if(!['localhost','127.0.0.1'].includes(redis.hostname)||redis.pathname==='/14')throw new Error('Dedicated local Redis database required');redis.pathname='/14';process.env.REDIS_URL=redis.toString();
process.env.DATABASE_POOL_MAX='2';process.env.BETTER_AUTH_SECRET=randomUUID()+randomUUID();process.env.NODE_ENV='test';process.env.WEB_ORIGIN='http://localhost:5317';process.env.PUBLIC_APP_URL=process.env.WEB_ORIGIN;process.env.BETTER_AUTH_URL=process.env.WEB_ORIGIN;process.env.API_INTERNAL_URL='http://localhost:3317';process.env.PUBLIC_API_URL=process.env.WEB_ORIGIN;process.env.ASSISTANT_AI_PROVIDER='groq';process.env.GROQ_API_KEY='isolated-mocked-key';process.env.GROQ_MODEL='openai/gpt-oss-20b';process.env.ASSISTANT_EXTERNAL_DATA_TERMS_ACKNOWLEDGED='true';
const originalFetch=globalThis.fetch;globalThis.fetch=(async(input:any,init?:any)=>{if(!String(input).startsWith('https://api.groq.com/openai/v1/'))return originalFetch(input,init);if(String(input).endsWith('/audio/transcriptions'))return Response.json({text:'How much is safe to spend?'});const body=JSON.parse(String(init?.body));const value=body.response_format?.json_schema?.schema?.properties?.amountToken?{type:'expense',amountToken:'50k',currency:'IDR',dateToken:'',accountName:'',categoryName:'',merchant:'Point Cofee Indomaret'}:{tool:'spending',category:'',period:'this_month'};return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}]});}) as typeof fetch;
const {client}=await import('../src/db'),{app}=await import('../src/app');app.listen(3317);const {recoverQueuedAssistantForecasts}=await import('../src/assistant/routes');const timer=setInterval(()=>void recoverQueuedAssistantForecasts().catch(()=>{}),1000);
const web=Bun.spawn(['bun','run','dev','--port','5317','--strictPort'],{cwd:import.meta.dir+'/../../web',env:{...process.env,CAPY_VITE_CACHE_DIR:`/tmp/capybudget-assistant-browser-vite-${process.pid}`},stdout:'ignore',stderr:'inherit'});let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{
 const id='assistant-browser-'+randomUUID(),email=id+'@example.test',password='IsolatedAssistantBrowser!42';await client`insert into "user"(id,name,email,email_verified) values(${id},'Browser fixture',${email},true)`;await client`insert into account(id,account_id,provider_id,user_id,password) values(${randomUUID()},${id},'credential',${id},${await hashPassword(password)})`;
 const login=await app.handle(new Request(process.env.WEB_ORIGIN+'/api/auth/sign-in/email',{method:'POST',headers:{origin:process.env.WEB_ORIGIN,'content-type':'application/json'},body:JSON.stringify({email,password})}));if(!login.ok)throw new Error('Fixture login failed');const cookies=login.headers.getSetCookie().map(v=>{const [part]=v.split(';'),i=part!.indexOf('=');return {name:part!.slice(0,i),value:part!.slice(i+1),url:process.env.WEB_ORIGIN!};}),cookie=cookies.map(c=>c.name+'='+c.value).join('; ');
 const request=(path:string,method='GET',body?:unknown)=>app.handle(new Request(process.env.WEB_ORIGIN+path,{method,headers:{cookie,origin:process.env.WEB_ORIGIN,'content-type':'application/json','idempotency-key':randomUUID()},...(body===undefined?{}:{body:JSON.stringify(body)})}));
 const created=await request('/api/workspaces','POST',{kind:'business',name:'Assistant browser fixture',currency:'IDR',timezone:'Asia/Jakarta'});const ws=(await created.json()).workspace.id;await client`insert into onboarding_state(user_id,usage_type,current_step,first_workspace_id,completed_at) values(${id},'both','done',${ws},now())`;
 const account=await request('/api/workspaces/'+ws+'/accounts','POST',{name:'Fixture cash',kind:'cash',currency:'IDR',openingBalance:'1000000',openingDate:'2026-01-01'});const accounts=await (await request('/api/workspaces/'+ws+'/accounts')).json();const settings=await request('/api/workspaces/'+ws+'/assistant/settings','PATCH',{version:1,sourcePermissions:{history:true,merchant:true,invoices:true},externalAiEnabled:true,externalAiProvider:'groq',voiceAiEnabled:true,accounts:accounts.items.map((a:any)=>({id:a.id,included:true,allowExternalAi:true,protectedAmount:'0',lowBalanceThreshold:'0'}))});if(!settings.ok)throw new Error('Fixture settings failed');
 const {workspaceToday}=await import('../src/tracking/recurrence'),{shiftDate}=await import('../src/assistant/v2/calculations');const today=workspaceToday('Asia/Jakarta'),previousEnd=shiftDate(today.slice(0,8)+'01',-1),categoryList=await (await request('/api/workspaces/'+ws+'/categories')).json(),categoryId=categoryList.items.find((c:any)=>c.type==='expense').id;
 for(let n=0;n<8;n++)await client`insert into transactions(id,workspace_id,account_id,category_id,type,amount,currency,occurred_at,merchant) values(${randomUUID()},${ws},${accounts.items[0].id},${categoryId},'expense',100,'IDR',${shiftDate(previousEnd,-20+n)},'Usual groceries')`;
 await client`insert into transactions(id,workspace_id,account_id,category_id,type,amount,currency,occurred_at,merchant) values(${randomUUID()},${ws},${accounts.items[0].id},${categoryId},'expense',500,'IDR',${shiftDate(previousEnd,-5)},'Larger purchase')`;
 for(let n=0;n<2;n++)await client`insert into transactions(id,workspace_id,account_id,category_id,type,amount,currency,occurred_at,merchant) values(${randomUUID()},${ws},${accounts.items[0].id},${categoryId},'expense',45,'IDR',${shiftDate(previousEnd,-5)},'Matching shop')`;
 const customerId=randomUUID(),invoiceId=randomUUID();
 await client`insert into business_contacts(id,workspace_id,name,kind,details) values(${customerId},${ws},'Browser customer','customer','{}')`;
 await client`insert into invoices(id,workspace_id,contact_id,number,state,issue_date,due_date,currency,currency_scale,recipient_snapshot,total,expected_account_id,issued_at) values(${invoiceId},${ws},${customerId},'BROWSER-EVIDENCE','issued',${today},${shiftDate(today,14)},'IDR',0,'{}',1000,${accounts.items[0].id},now())`;
 await client`insert into transactions(id,workspace_id,account_id,category_id,type,amount,currency,occurred_at,merchant) values(${randomUUID()},${ws},${accounts.items[0].id},${categoryId},'expense',7,'IDR',${previousEnd.slice(0,8)+'03'},'Comparison fixture')`;
 const summaryId=randomUUID();const [prefs]=await client`select consent_version from assistant_settings where workspace_id=${ws} and user_id=${id}`;
 await client`insert into assistant_summaries(id,workspace_id,user_id,consent_version,period_start,period_end,kind,metrics,schedule_version) values(${summaryId},${ws},${id},${prefs!.consent_version},'2026-09-28','2026-10-04','weekly',${JSON.stringify({income:'0.0000',expenses:'0.0000'})}::jsonb,1)`;
 let ready=false;for(let n=0;n<120;n++){try{if((await fetch(process.env.WEB_ORIGIN)).ok){ready=true;break;}}catch{}await Bun.sleep(250);}if(!ready)throw new Error('Isolated web did not start');browser=await chromium.launch({headless:true});
 for(const size of [{width:1440,height:1000},{width:390,height:844}]){
  await client`update assistant_summaries set state='ready' where id=${summaryId}`;await client`delete from assistant_feedback where source_id=${summaryId}`;
  const context=await browser.newContext({viewport:size,serviceWorkers:'block'});await context.addCookies(cookies);await context.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:'capybudget-workspace:'+id,value:ws});const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(process.env.WEB_ORIGIN+'/assistant',{waitUntil:'domcontentloaded',timeout:45000});if(!response?.ok())throw new Error('Assistant page failed');await page.locator('.v2-panel').waitFor({timeout:30000});
  if(size.width===1440){const wav=await page.evaluate(async()=>{const audio=await new Function('return import("/src/lib/assistant/audio.ts")')();const converted=await audio.recordingToWav(audio.encodePcmWav(new Float32Array(16000),16000));const view=new DataView(await converted.arrayBuffer());return {type:converted.type,rate:view.getUint32(24,true),channels:view.getUint16(22,true),bits:view.getUint16(34,true),size:converted.size};});if(wav.type!=='audio/wav'||wav.rate!==24000||wav.channels!==1||wav.bits!==16||wav.size!==48044)throw new Error('Browser Muse WAV conversion failed');console.log('Browser WAV decoding, mono conversion and resampling passed.');}
  const panel=page.locator('.v2-panel');await panel.getByRole('button',{name:'Refresh insights',exact:true}).click();await panel.getByText('Business runway',{exact:true}).waitFor();await panel.getByRole('button',{name:'See records',exact:true}).first().click();await panel.getByRole('button',{name:/Source records/}).first().click();await panel.getByText('Amounts for category comparisons',{exact:false}).waitFor();await panel.getByRole('button',{name:'See invoices',exact:true}).click();await panel.getByRole('link',{name:'BROWSER-EVIDENCE',exact:true}).waitFor();await panel.getByRole('button',{name:'Compare with the cashflow forecast',exact:true}).click();await panel.getByText('Runway uses historical operating cash.',{exact:false}).waitFor();console.log('Comparison sources, customer invoices and runway comparison passed at '+size.width+'px.');const unusual=panel.locator('.item-list article').filter({has:page.getByRole('heading',{name:/Unusual purchase/})}).first();await unusual.getByRole('button',{name:'See why',exact:true}).click();await unusual.getByText('Review threshold',{exact:false}).waitFor();const duplicate=panel.locator('.item-list article').filter({has:page.getByRole('heading',{name:/Possible duplicate/})}).first();await duplicate.getByRole('button',{name:'See why',exact:true}).click();await duplicate.getByText('Matching records',{exact:false}).waitFor();await page.screenshot({path:'/tmp/capybudget-detection-'+size.width+'.png',fullPage:true});console.log('Detection explanations and cited evidence passed at '+size.width+'px.');
  for(const tab of ['What if?','Payment plan','Ask Capy','Text & voice entry','Check-ins']){await panel.getByRole('button',{name:tab,exact:true}).click();if(tab==='Payment plan'){await panel.getByRole('button',{name:'Review payment plan',exact:true}).click();await panel.getByText('Total still to plan',{exact:false}).waitFor();}if(tab==='Ask Capy'){await panel.getByLabel('Your question').fill('How much did I spend this month?');await panel.getByRole('button',{name:'Ask Capy',exact:true}).last().click();await panel.getByText('No matching expenses were found in the permitted accounts and period.').waitFor();}if(tab==='Check-ins'){await panel.getByRole('button',{name:'Load check-ins',exact:true}).click();await panel.getByText('Last complete week',{exact:false}).waitFor();const feedback=panel.locator('.feedback-controls').last();await feedback.getByRole('button',{name:'Helpful',exact:true}).click();await feedback.getByRole('button',{name:'Helpful ✓',exact:true}).waitFor();await panel.getByRole('button',{name:'Load check-ins',exact:true}).click();await feedback.getByRole('button',{name:'Helpful ✓',exact:true}).waitFor();if(await feedback.getByRole('button',{name:'Helpful ✓',exact:true}).getAttribute('aria-pressed')!=='true')throw new Error('Feedback selected state missing');await feedback.getByRole('button',{name:'Not helpful',exact:true}).click();await feedback.getByRole('button',{name:'Not helpful ✓',exact:true}).waitFor();const target=await feedback.getByRole('button',{name:'Dismiss',exact:true}).boundingBox();if(!target||target.height<44)throw new Error('Feedback touch target too small');await feedback.getByRole('button',{name:'Dismiss',exact:true}).click();await feedback.waitFor({state:'detached'});console.log('Feedback save, reload, selected state and dismissal passed at '+size.width+'px.');}if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2))throw new Error('Page overflow at '+size.width+' '+tab);}
  await page.getByRole('button',{name:'Open Capy chat',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Ask Capy'});await dialog.getByRole('button',{name:'New',exact:true}).click();await dialog.getByLabel('Your question',{exact:true}).fill('How much did I spend this month?');await dialog.getByRole('button',{name:'Send',exact:true}).click();await dialog.getByText('These totals come from your recorded expenses in the permitted accounts.').or(dialog.getByText('No matching expenses were found in the permitted accounts and period.')).waitFor();
  await dialog.getByLabel('Your question',{exact:true}).fill('capy, gue abis transaksi 50k idr di Point Cofee Indomaret menggunakan BCA');await dialog.getByRole('button',{name:'Send',exact:true}).click();await dialog.getByRole('button',{name:'Review transaction entry',exact:true}).click();const review=dialog.locator('form.review');await review.getByRole('heading',{name:'Review your transaction'}).waitFor();if(Number((await review.locator('[data-slot="amount-input"] input').inputValue()).replaceAll(',',''))!==50000)throw new Error('Entry amount not extracted');if(!await review.getByRole('button',{name:'Confirm & save',exact:true}).isDisabled())throw new Error('Missing fields must block confirmation');await review.getByRole('button',{name:'Cancel',exact:true}).click();console.log('Colloquial transaction opens inline review at '+size.width+'px.');
  if(size.width===1440){await page.evaluate(()=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{const audio=new AudioContext(),output=audio.createMediaStreamDestination(),oscillator=audio.createOscillator();oscillator.connect(output);oscillator.start();await audio.resume();const track=output.stream.getAudioTracks()[0];track.addEventListener('ended',()=>{oscillator.stop();void audio.close();});return output.stream;}});});await dialog.getByRole('button',{name:'Record a voice question'}).click();await dialog.getByRole('button',{name:/^Stop/}).waitFor();await page.waitForTimeout(900);await dialog.getByRole('button',{name:/^Stop/}).click();await dialog.getByText('Transcript ready. Review it, then send your question.').waitFor();if(await dialog.getByLabel('Your question',{exact:true}).inputValue()!=='How much is safe to spend?')throw new Error('Widget voice transcript missing');}
  const bounds=await dialog.boundingBox();if(!bounds||bounds.x<0||bounds.y<0||bounds.x+bounds.width>size.width+1||bounds.y+bounds.height>size.height+1)throw new Error('Widget exceeds viewport');await page.screenshot({path:'/tmp/capybudget-chat-widget-'+size.width+'.png'});await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});await page.getByRole('button',{name:'Open Capy chat',exact:true}).click();await dialog.getByText('These totals come from your recorded expenses in the permitted accounts.').or(dialog.getByText('No matching expenses were found in the permitted accounts and period.')).waitFor();await page.keyboard.press('Escape');console.log('Chat widget, saved history and dismissal passed at '+size.width+'px.');
  if(errors.length)throw new Error(errors.join('; '));console.log('Assistant tabs and local flows passed at '+size.width+'px.');await page.screenshot({path:'/tmp/capybudget-assistant-v2-'+size.width+'.png',fullPage:true});await context.close();
 }
 for(const size of [{width:1440,height:1000},{width:360,height:844}]){
  const changed=await request('/api/preferences','PUT',{theme:'dark',locale:'id'});if(!changed.ok)throw new Error('Fixture preferences failed');
  const context=await browser.newContext({viewport:size,serviceWorkers:'block',reducedMotion:'reduce'});await context.addCookies(cookies);await context.addInitScript(({key,value})=>{localStorage.setItem(key,value);localStorage.setItem('capybudget-theme','dark');localStorage.setItem('capybudget-locale','id');},{key:'capybudget-workspace:'+id,value:ws});const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.WEB_ORIGIN+'/assistant',{waitUntil:'domcontentloaded',timeout:45000});const panel=page.locator('.v2-panel');await panel.getByRole('button',{name:'Perbarui wawasan',exact:true}).click();await panel.getByText('Ketahanan kas bisnis',{exact:true}).waitFor();const unusualId=panel.locator('.item-list article').filter({has:page.getByRole('heading',{name:/Pembelian tidak biasa/})}).first();await unusualId.getByRole('button',{name:'Lihat alasannya',exact:true}).click();await unusualId.getByText('Ambang peninjauan',{exact:false}).waitFor();console.log('Indonesian Night Pond detection explanation passed at '+size.width+'px.');await panel.getByRole('button',{name:'Ringkasan',exact:true}).click();await panel.getByRole('button',{name:'Muat ringkasan',exact:true}).click();await panel.getByText('Minggu penuh terakhir',{exact:false}).waitFor();
  if(!await page.evaluate(()=>document.documentElement.classList.contains('dark')&&document.documentElement.lang==='id'))throw new Error('Theme/locale did not apply');if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2))throw new Error('Night Pond overflow at '+size.width);await page.getByRole('button',{name:'Buka percakapan Capy',exact:true}).click();const darkChat=page.getByRole('dialog',{name:'Tanya Capy'});await darkChat.getByRole('button',{name:'Baru',exact:true}).waitFor();await page.screenshot({path:'/tmp/capybudget-chat-widget-dark-id-'+size.width+'.png'});await page.keyboard.press('Escape');if(errors.length)throw new Error(errors.join('; '));await page.screenshot({path:'/tmp/capybudget-assistant-v2-dark-id-'+size.width+'.png',fullPage:true});console.log('Night Pond, Indonesian and reduced motion passed at '+size.width+'px.');await context.close();
 }
}finally{clearInterval(timer);await browser?.close();web.kill();await app.stop();await client.end();globalThis.fetch=originalFetch;}
process.exit(0);
