<script lang="ts">
  import { formatDateTime } from '$lib/dates';
  import PasswordInput from '$lib/components/forms/password-input.svelte';
  import LoadingScope from '$lib/components/shared/loading-scope.svelte';
  import {getContext,onMount} from 'svelte';import QRCode from 'qrcode';import {startRegistration,browserSupportsWebAuthn} from '@simplewebauthn/browser';
  import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';import {authClient} from '$lib/auth-client';import {securityRequest} from '$lib/security/request';import {uxText} from '$lib/i18n/ux';
  import {Button} from '$lib/components/ui/button';import {Input} from '$lib/components/ui/input';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';
  import PageHeader from '$lib/components/shared/page-header.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';
  const ui=getContext<AuthUiState>(AUTH_UI_CONTEXT);const text=(en:string,id:string)=>ui.locale==='id'?id:en;
  const ux=(key:Parameters<typeof uxText>[1])=>uxText(ui.locale,key);
  let password=$state(''),code=$state(''),pin=$state(''),qr=$state(''),backupCodes:string[]=$state([]),status=$state<any>(null),sessions:any[]=$state([]),devices:any[]=$state([]),credentials:any[]=$state([]),busy=$state(false),error=$state(''),message=$state(''),supported=$state(false);
  async function load(){status=await securityRequest('status',undefined,'GET');sessions=(await securityRequest('sessions',undefined,'GET')).items;devices=(await securityRequest('devices',undefined,'GET')).items;credentials=(await securityRequest('webauthn/credentials',undefined,'GET')).items;}
  onMount(()=>{supported=browserSupportsWebAuthn();void load().catch(()=>error=text('Unable to load security settings.','Tidak dapat memuat pengaturan keamanan.'));});
  async function grant(purpose:string){const result=await securityRequest('reauthenticate',{password,code,purpose});return result.grant;}
  async function action(fn:()=>Promise<void>){if(busy)return;busy=true;error='';message='';try{await fn();await load();message=text('Security settings updated.','Pengaturan keamanan diperbarui.');}catch(e){error=e instanceof Error?e.message:text('Request failed.','Permintaan gagal.');}finally{busy=false;password='';code='';pin='';}}
  async function enable(){await action(async()=>{const token=await grant('factor');const response=await fetch('/api/auth/two-factor/enable',{method:'POST',headers:{'content-type':'application/json','x-security-grant':token},body:JSON.stringify({password})});const data=await response.json();if(!response.ok)throw new Error(data.message);qr=await QRCode.toDataURL(data.totpURI,{width:240});backupCodes=data.backupCodes;});}
  async function verify(){await action(async()=>{const result=await authClient.twoFactor.verifyTotp({code,trustDevice:false});if(result.error)throw new Error(result.error.message);qr='';});}
  async function factor(path:string){await action(async()=>{const token=await grant('factor');const response=await fetch('/api/auth/two-factor/'+path,{method:'POST',headers:{'content-type':'application/json','x-security-grant':token},body:JSON.stringify({password})});const data=await response.json();if(!response.ok)throw new Error(data.message);backupCodes=data.backupCodes??[];});}
  async function device(){await action(async()=>{const options=await securityRequest('webauthn/register/options',{},'POST',await grant('webauthn'));const response=await startRegistration({optionsJSON:options.options});await securityRequest('webauthn/register/verify',{challengeId:options.challengeId,response});});}
</script>
<LoadingScope active={!!busy} />
<svelte:head><title>{text('Security settings','Pengaturan keamanan')} · CapyBudget</title></svelte:head>
<div class="security-settings"><PageHeader eyebrow={text('PROTECTION','PERLINDUNGAN')} title={text('Security and devices','Keamanan dan perangkat')} description={text('Sensitive changes require your password and enabled second factor.','Perubahan sensitif memerlukan kata sandi dan faktor kedua yang aktif.')} />
<Card.Root><Card.Header><Card.Title>{text('Confirm your identity','Konfirmasi identitas')}</Card.Title><Card.Description>{text('Credentials are cleared after each operation. Your app PIN cannot authorize changes.','Kredensial dihapus setelah setiap tindakan. PIN aplikasi tidak dapat mengizinkan perubahan.')}</Card.Description></Card.Header><Card.Content><Field.FieldGroup><Field.Field><Field.FieldLabel for="security-password">{text('Password','Kata sandi')}</Field.FieldLabel><PasswordInput id="security-password"  bind:value={password} autocomplete="current-password"/></Field.Field><Field.Field><Field.FieldLabel for="security-code">{text('Authenticator or unused recovery code (if enabled)','Kode autentikator atau pemulihan yang belum dipakai (jika aktif)')}</Field.FieldLabel><Input id="security-code" bind:value={code} inputmode="numeric" autocomplete="one-time-code" maxlength={32}/></Field.Field></Field.FieldGroup></Card.Content></Card.Root>
{#if error}<ErrorState title={ux('errorTitle')} message={error} />{/if}{#if message}<p class="message" role="status">{message}</p>{/if}
<Card.Root><Card.Header><Card.Title>{text('Two-factor authentication','Autentikasi dua faktor')}</Card.Title><Card.Description>{text('Use an authenticator app. Keep recovery codes somewhere safe outside this browser.','Gunakan aplikasi autentikator. Simpan kode pemulihan di tempat aman di luar browser ini.')}</Card.Description></Card.Header><Card.Content>
{#if qr}<img src={qr} width="240" height="240" alt={text('Scan this QR code with your authenticator','Pindai kode QR dengan autentikator')}/><Button disabled={busy} onclick={verify}>{text('Verify first code to enable','Verifikasi kode pertama untuk mengaktifkan')}</Button>{:else if status?.twoFactorEnabled}<Button variant="outline" disabled={busy} onclick={()=>factor('generate-backup-codes')}>{text('Replace recovery codes','Ganti kode pemulihan')}</Button><Button variant="destructive" disabled={busy} onclick={()=>factor('disable')}>{text('Disable two-factor','Nonaktifkan dua faktor')}</Button>{:else}<Button disabled={busy} onclick={enable}>{text('Set up authenticator','Siapkan autentikator')}</Button>{/if}
{#if backupCodes.length}<section aria-label={text('Recovery codes','Kode pemulihan')}><pre>{backupCodes.join('\n')}</pre><Button variant="outline" onclick={()=>backupCodes=[]}>{text('I have saved these codes','Saya telah menyimpan kode')}</Button></section>{/if}</Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{text('Lock this browser','Kunci browser ini')}</Card.Title><Card.Description>{text('Locks after five minutes idle or when backgrounded. Device security may use fingerprint, face, or device PIN.','Terkunci setelah lima menit tidak aktif atau saat di latar belakang. Keamanan perangkat dapat menggunakan sidik jari, wajah, atau PIN perangkat.')}</Card.Description></Card.Header><Card.Content><Field.FieldGroup><Field.Field><Field.FieldLabel for="new-pin">{text('New PIN (6–8 digits)','PIN baru (6–8 digit)')}</Field.FieldLabel><PasswordInput id="new-pin"  bind:value={pin} inputmode="numeric" maxlength={8}/></Field.Field><Button disabled={busy} onclick={()=>action(async()=>{await securityRequest('pin',{pin},'PUT',await grant('pin'));})}>{text('Set PIN','Atur PIN')}</Button>{#if status?.hasPin}<Button variant="outline" disabled={busy} onclick={()=>action(async()=>{await securityRequest('pin',undefined,'DELETE',await grant('pin'));})}>{text('Remove PIN','Hapus PIN')}</Button>{/if}{#if supported}<Button variant="outline" disabled={busy} onclick={device}>{text('Register device security','Daftarkan keamanan perangkat')}</Button>{/if}</Field.FieldGroup></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{text('Device security credentials','Kredensial keamanan perangkat')}</Card.Title><Card.Description>{text('Removing a credential prevents future unlock with it.','Menghapus kredensial mencegah penggunaannya untuk membuka kunci.')}</Card.Description></Card.Header><Card.Content>{#each credentials as credential}<div class="session"><span>{credential.label}<small>{formatDateTime(credential.created_at, ui.locale)}</small></span><Button variant="outline" disabled={busy} onclick={()=>action(async()=>{await securityRequest('webauthn/credentials/'+credential.id,undefined,'DELETE',await grant('webauthn'));})}>{text('Remove credential','Hapus kredensial')}</Button></div>{/each}</Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{text('Active sessions','Sesi aktif')}</Card.Title><Card.Description>{text('Revoke a session or sign out other browsers.','Cabut sesi atau keluarkan browser lain.')}</Card.Description></Card.Header><Card.Content>{#each sessions as session}<div class="session"><span>{session.label??text('Browser','Browser')} {session.current?text('(current)','(saat ini)'):''}<small>{formatDateTime(session.created_at, ui.locale)}</small></span><Button variant="outline" disabled={busy} onclick={()=>action(async()=>{await securityRequest('sessions/'+session.id,undefined,'DELETE',await grant('sessions'));if(session.current)location.assign('/login');})}>{text('Sign out','Keluar')}</Button></div>{/each}<Button variant="outline" disabled={busy} onclick={()=>action(async()=>{await securityRequest('sessions/revoke-others',{},'POST',await grant('sessions'));})}>{text('Sign out other sessions','Keluar dari sesi lain')}</Button></Card.Content></Card.Root>
<Card.Root><Card.Header><Card.Title>{text('Registered browsers','Browser terdaftar')}</Card.Title><Card.Description>{text('Removing a browser revokes its sessions and unlock credentials.','Menghapus browser mencabut sesi dan kredensial buka kuncinya.')}</Card.Description></Card.Header><Card.Content>{#each devices as device}<div class="session"><span>{device.label}<small>{device.credentials} {text('device credentials','kredensial perangkat')}</small></span><Button variant="outline" disabled={busy} onclick={()=>action(async()=>{await securityRequest('devices/'+device.id,undefined,'DELETE',await grant('sessions'));if(device.id===status.deviceId)location.assign('/login');})}>{text('Remove browser','Hapus browser')}</Button></div>{/each}</Card.Content></Card.Root></div>
<style>.security-settings{max-width:760px;display:grid;gap:16px}.message{color:var(--income-ink)}.session{display:flex;gap:12px;justify-content:space-between;align-items:center;padding:12px 0;overflow-wrap:anywhere}.session small{display:block;color:var(--muted-foreground)}:global(.security-settings :global([data-slot="button"])){min-height:44px}pre{white-space:pre-wrap}</style>
