import type {Locale} from './auth';
const words={
 en:{
  draftStatusHint:'Not issued yet.',issuedStatusHint:'Issued and ready to send.',sentStatusHint:'Sent; waiting for payment.',partialStatusHint:'Payment received; a balance remains.',paidStatusHint:'No balance remaining.',overdueStatusHint:'Past the due date; payment is still pending.',voidStatusHint:'This invoice has been cancelled.',
  invoices:'Invoices',invoice:'Invoice',businessProfile:'Business profile',businessSettings:'Business settings',newInvoice:'New invoice',editInvoice:'Edit draft',invoiceNumber:'Invoice number',customer:'Customer',email:'Email',phone:'Phone',street:'Street address',city:'City',region:'State / province',postalCode:'Postal code',country:'Country',issueDate:'Issue date',dueDate:'Due date',description:'Description',quantity:'Quantity',unitPrice:'Unit price',discount:'Discount',taxRate:'Tax rate (%)',subtotal:'Subtotal',tax:'Tax',total:'Total',paid:'Paid',outstanding:'Outstanding',notes:'Notes',paymentInstructions:'Payment instructions',saveDraft:'Save draft',issueInvoice:'Issue invoice',sendInvoice:'Send invoice',downloadPdf:'Download PDF',voidInvoice:'Void invoice',recordPayment:'Record payment',paymentDate:'Received on',receivingAccount:'Receiving account',incomeCategory:'Income category',reference:'Reference',reversePayment:'Reverse payment',reason:'Reason for correction',search:'Search invoices',allStatuses:'All statuses',draft:'Draft',issued:'Issued',sent:'Sent',partially_paid:'Partially paid',paidStatus:'Paid',overdue:'Overdue',void:'Void',loading:'Loading…',empty:'No invoices yet. Create your first business invoice.',error:'Could not load business data.',saved:'Saved.',addLine:'Add line',removeLine:'Remove',fiscalMonth:'Fiscal year starts in month',fiscalDay:'Fiscal year starts on day',legalName:'Legal business name',tradingName:'Trading name',taxId:'Tax ID',saveProfile:'Save business profile',logo:'Business logo',dueIn:'Due',sendFailed:'Send failed',sending:'Sending',profileRequired:'Complete the legal name, business email, and address before issuing.',paymentLimit:'Payment cannot exceed the outstanding balance.',cancel:'Cancel',studioMode:'Studio mode',invoiceListIntro:'Draft, send, and track business invoices.',draftHint:'Start a draft. Totals are calculated by the server when you save.',recipientHint:'Recipient details are saved on this invoice.',linesHint:'Use a separate line for each item or service.',profileHint:'These details appear on invoices issued from this business.',logoHint:'PNG, JPEG, or WebP · up to 2 MiB',paymentHint:'This records a new income transaction in the selected receiving account.',deliveryHistory:'Send attempts and accepted messages',voidTitle:'Void this invoice?',reverseTitle:'Reverse this payment?',statusCol:'Status'
 },
 id:{
  draftStatusHint:'Belum diterbitkan.',issuedStatusHint:'Sudah diterbitkan dan siap dikirim.',sentStatusHint:'Sudah dikirim; menunggu pembayaran.',partialStatusHint:'Pembayaran diterima; masih ada sisa tagihan.',paidStatusHint:'Tidak ada sisa tagihan.',overdueStatusHint:'Sudah melewati jatuh tempo; pembayaran masih tertunda.',voidStatusHint:'Faktur ini telah dibatalkan.',
  invoices:'Faktur',invoice:'Faktur',businessProfile:'Profil bisnis',businessSettings:'Pengaturan bisnis',newInvoice:'Faktur baru',editInvoice:'Edit draf',invoiceNumber:'Nomor faktur',customer:'Pelanggan',email:'Email',phone:'Telepon',street:'Alamat jalan',city:'Kota',region:'Provinsi',postalCode:'Kode pos',country:'Negara',issueDate:'Tanggal terbit',dueDate:'Jatuh tempo',description:'Deskripsi',quantity:'Jumlah',unitPrice:'Harga satuan',discount:'Diskon',taxRate:'Tarif pajak (%)',subtotal:'Subtotal',tax:'Pajak',total:'Total',paid:'Dibayar',outstanding:'Sisa tagihan',notes:'Catatan',paymentInstructions:'Instruksi pembayaran',saveDraft:'Simpan draf',issueInvoice:'Terbitkan faktur',sendInvoice:'Kirim faktur',downloadPdf:'Unduh PDF',voidInvoice:'Batalkan faktur',recordPayment:'Catat pembayaran',paymentDate:'Diterima pada',receivingAccount:'Akun penerima',incomeCategory:'Kategori pemasukan',reference:'Referensi',reversePayment:'Balik pembayaran',reason:'Alasan koreksi',search:'Cari faktur',allStatuses:'Semua status',draft:'Draf',issued:'Terbit',sent:'Terkirim',partially_paid:'Dibayar sebagian',paidStatus:'Lunas',overdue:'Terlambat',void:'Dibatalkan',loading:'Memuat…',empty:'Belum ada faktur. Buat faktur bisnis pertama Anda.',error:'Data bisnis tidak dapat dimuat.',saved:'Tersimpan.',addLine:'Tambah baris',removeLine:'Hapus',fiscalMonth:'Bulan awal tahun fiskal',fiscalDay:'Hari awal tahun fiskal',legalName:'Nama legal bisnis',tradingName:'Nama dagang',taxId:'NPWP',saveProfile:'Simpan profil bisnis',logo:'Logo bisnis',dueIn:'Jatuh tempo',sendFailed:'Pengiriman gagal',sending:'Mengirim',profileRequired:'Lengkapi nama legal, email bisnis, dan alamat sebelum menerbitkan faktur.',paymentLimit:'Pembayaran tidak boleh melebihi sisa tagihan.',cancel:'Batal',studioMode:'Mode studio',invoiceListIntro:'Buat, kirim, dan pantau faktur bisnis.',draftHint:'Mulai draf. Total dihitung server saat disimpan.',recipientHint:'Detail penerima disimpan pada faktur ini.',linesHint:'Gunakan satu baris untuk setiap barang atau jasa.',profileHint:'Detail ini muncul pada faktur yang diterbitkan bisnis ini.',logoHint:'PNG, JPEG, atau WebP · hingga 2 MiB',paymentHint:'Ini mencatat transaksi pemasukan baru di akun penerima yang dipilih.',deliveryHistory:'Upaya kirim dan pesan yang diterima',voidTitle:'Batalkan faktur ini?',reverseTitle:'Balikkan pembayaran ini?',statusCol:'Status'
 }
} as const;
export function businessText(locale:Locale,key:keyof typeof words.en){return words[locale][key];}
