import type {Locale} from './auth';
const words={
 en:{
  invoices:'Invoices',invoice:'Invoice',businessProfile:'Business profile',businessSettings:'Business settings',newInvoice:'New invoice',editInvoice:'Edit draft',invoiceNumber:'Invoice number',customer:'Customer',email:'Email',phone:'Phone',street:'Street address',city:'City',region:'State / province',postalCode:'Postal code',country:'Country',issueDate:'Issue date',dueDate:'Due date',description:'Description',quantity:'Quantity',unitPrice:'Unit price',discount:'Discount',taxRate:'Tax rate (%)',subtotal:'Subtotal',tax:'Tax',total:'Total',paid:'Paid',outstanding:'Outstanding',notes:'Notes',paymentInstructions:'Payment instructions',saveDraft:'Save draft',issueInvoice:'Issue invoice',sendInvoice:'Send invoice',downloadPdf:'Download PDF',voidInvoice:'Void invoice',recordPayment:'Record payment',paymentDate:'Received on',receivingAccount:'Receiving account',incomeCategory:'Income category',reference:'Reference',reversePayment:'Reverse payment',reason:'Reason for correction',search:'Search invoices',allStatuses:'All statuses',draft:'Draft',issued:'Issued',sent:'Sent',partially_paid:'Partially paid',paidStatus:'Paid',overdue:'Overdue',void:'Void',loading:'Loading…',empty:'No invoices yet. Create your first business invoice.',error:'Could not load business data.',saved:'Saved.',addLine:'Add line',removeLine:'Remove',fiscalMonth:'Fiscal year starts in month',fiscalDay:'Fiscal year starts on day',legalName:'Legal business name',tradingName:'Trading name',taxId:'Tax ID',saveProfile:'Save business profile',logo:'Business logo',dueIn:'Due',sendFailed:'Send failed',sending:'Sending',profileRequired:'Complete the legal name, business email, and address before issuing.',paymentLimit:'Payment cannot exceed the outstanding balance.',cancel:'Cancel'
 },
 id:{
  invoices:'Faktur',invoice:'Faktur',businessProfile:'Profil bisnis',businessSettings:'Pengaturan bisnis',newInvoice:'Faktur baru',editInvoice:'Edit draf',invoiceNumber:'Nomor faktur',customer:'Pelanggan',email:'Email',phone:'Telepon',street:'Alamat jalan',city:'Kota',region:'Provinsi',postalCode:'Kode pos',country:'Negara',issueDate:'Tanggal terbit',dueDate:'Jatuh tempo',description:'Deskripsi',quantity:'Jumlah',unitPrice:'Harga satuan',discount:'Diskon',taxRate:'Tarif pajak (%)',subtotal:'Subtotal',tax:'Pajak',total:'Total',paid:'Dibayar',outstanding:'Sisa tagihan',notes:'Catatan',paymentInstructions:'Instruksi pembayaran',saveDraft:'Simpan draf',issueInvoice:'Terbitkan faktur',sendInvoice:'Kirim faktur',downloadPdf:'Unduh PDF',voidInvoice:'Batalkan faktur',recordPayment:'Catat pembayaran',paymentDate:'Diterima pada',receivingAccount:'Akun penerima',incomeCategory:'Kategori pemasukan',reference:'Referensi',reversePayment:'Balik pembayaran',reason:'Alasan koreksi',search:'Cari faktur',allStatuses:'Semua status',draft:'Draf',issued:'Terbit',sent:'Terkirim',partially_paid:'Dibayar sebagian',paidStatus:'Lunas',overdue:'Terlambat',void:'Dibatalkan',loading:'Memuat…',empty:'Belum ada faktur. Buat faktur bisnis pertama Anda.',error:'Data bisnis tidak dapat dimuat.',saved:'Tersimpan.',addLine:'Tambah baris',removeLine:'Hapus',fiscalMonth:'Bulan awal tahun fiskal',fiscalDay:'Hari awal tahun fiskal',legalName:'Nama legal bisnis',tradingName:'Nama dagang',taxId:'NPWP',saveProfile:'Simpan profil bisnis',logo:'Logo bisnis',dueIn:'Jatuh tempo',sendFailed:'Pengiriman gagal',sending:'Mengirim',profileRequired:'Lengkapi nama legal, email bisnis, dan alamat sebelum menerbitkan faktur.',paymentLimit:'Pembayaran tidak boleh melebihi sisa tagihan.',cancel:'Batal'
 }
} as const;
export function businessText(locale:Locale,key:keyof typeof words.en){return words[locale][key];}
