import type { Locale } from './auth';

const messages={
  en:{overview:'Overview',transactions:'Transactions',accounts:'Accounts',categories:'Categories & tags',recurring:'Recurring',workspace:'Workspace',addBusiness:'＋ Add business workspace',signOut:'Sign out',tagline:'Stay chill with your money.',
    accountHeading:'Accounts',accountIntro:'Keep the money in each wallet easy to see.',yourAccounts:'Your accounts',accountDescription:'Balances include opening amounts and recorded transactions.',addAccount:'Add an account',openingHint:'Enter a starting balance if you already use this wallet.',accountName:'Account name',accountType:'Account type',openingBalance:'Opening balance',save:'Save',saving:'Saving…',archive:'Archive',
    categoryHeading:'Categories & tags',categoryIntro:'Categories describe where money came from or went. Tags add your own cross-category labels.',income:'Income',expenses:'Expenses',newCategory:'New category',parentCategory:'Parent category (optional)',topLevel:'Top-level category',addCategory:'Add category',newTag:'New tag',addTag:'Add tag',
    transactionHeading:'Transactions',transactionIntro:'A clear history of money in, money out, and transfers.',quickAdd:'Quick add',history:'History',search:'Search notes or merchant',saveTransaction:'Save transaction',saveChanges:'Save changes',date:'Date',amount:'Amount',account:'Account',category:'Category',note:'Note',merchant:'Merchant (optional)',categorySuggestion:'Suggested category: {category}.',categorySuggestionExplicit:'Based on a rule you created.',categorySuggestionLearned:'Based on your previous choices.',useSuggestion:'Use suggestion',
    recurringHeading:'Recurring',recurringIntro:'Review upcoming entries before they affect your balance.',upcoming:'Upcoming occurrences',addRule:'Add a recurring rule',rules:'Rules',confirm:'Confirm',skip:'Skip',pause:'Pause',resume:'Resume',
    loading:'Loading…',chooseWorkspace:'Choose a workspace first.',emptyRules:'Create a rule for a regular income, bill, or transfer.',showDeleted:'Show recently deleted',hideDeleted:'Hide recently deleted',restore:'Restore',delete:'Delete',cancel:'Cancel',dashboardHeading:'Your money, at a glance',dashboardSubtitle:'A steady picture helps you decide what to do next.',addTransaction:'＋ Add transaction',balance:'Account balance',netChange:'Net change',recentTransactions:'Recent transactions',latestActivity:'Your latest activity in this workspace.',nap:'Capy is napping.',firstTransaction:'Add your first transaction to wake them up.',viewHistory:'View transaction history →'},
  id:{overview:'Ringkasan',transactions:'Transaksi',accounts:'Akun',categories:'Kategori & tag',recurring:'Berulang',workspace:'Ruang kerja',addBusiness:'＋ Tambah ruang kerja bisnis',signOut:'Keluar',tagline:'Kelola uang dengan lebih tenang.',
    accountHeading:'Akun',accountIntro:'Lihat uang di setiap dompet dengan mudah.',yourAccounts:'Akun Anda',accountDescription:'Saldo mencakup saldo awal dan transaksi yang tercatat.',addAccount:'Tambah akun',openingHint:'Masukkan saldo awal jika dompet ini sudah digunakan.',accountName:'Nama akun',accountType:'Jenis akun',openingBalance:'Saldo awal',save:'Simpan',saving:'Menyimpan…',archive:'Arsipkan',
    categoryHeading:'Kategori & tag',categoryIntro:'Kategori menjelaskan asal atau penggunaan uang. Tag memberi label lintas kategori.',income:'Pemasukan',expenses:'Pengeluaran',newCategory:'Kategori baru',parentCategory:'Kategori induk (opsional)',topLevel:'Kategori utama',addCategory:'Tambah kategori',newTag:'Tag baru',addTag:'Tambah tag',
    transactionHeading:'Transaksi',transactionIntro:'Riwayat pemasukan, pengeluaran, dan transfer Anda.',quickAdd:'Tambah cepat',history:'Riwayat',search:'Cari catatan atau merchant',saveTransaction:'Simpan transaksi',saveChanges:'Simpan perubahan',date:'Tanggal',amount:'Jumlah',account:'Akun',category:'Kategori',note:'Catatan',merchant:'Merchant (opsional)',categorySuggestion:'Kategori yang disarankan: {category}.',categorySuggestionExplicit:'Berdasarkan aturan yang Anda buat.',categorySuggestionLearned:'Berdasarkan pilihan Anda sebelumnya.',useSuggestion:'Gunakan saran',
    recurringHeading:'Transaksi berulang',recurringIntro:'Tinjau transaksi mendatang sebelum memengaruhi saldo.',upcoming:'Jadwal mendatang',addRule:'Tambah aturan berulang',rules:'Aturan',confirm:'Konfirmasi',skip:'Lewati',pause:'Jeda',resume:'Lanjutkan',
    loading:'Memuat…',chooseWorkspace:'Pilih ruang kerja terlebih dahulu.',emptyRules:'Buat aturan untuk pemasukan, tagihan, atau transfer rutin.',showDeleted:'Tampilkan yang baru dihapus',hideDeleted:'Sembunyikan yang baru dihapus',restore:'Pulihkan',delete:'Hapus',cancel:'Batal',dashboardHeading:'Ringkasan keuangan Anda',dashboardSubtitle:'Gambaran yang jelas membantu menentukan langkah berikutnya.',addTransaction:'＋ Tambah transaksi',balance:'Saldo akun',netChange:'Perubahan bersih',recentTransactions:'Transaksi terbaru',latestActivity:'Aktivitas terbaru di ruang kerja ini.',nap:'Capy sedang beristirahat.',firstTransaction:'Tambahkan transaksi pertama Anda.',viewHistory:'Lihat riwayat transaksi →'}
} as const;

export function trackingText(locale:Locale,key:keyof typeof messages.en){return messages[locale][key];}
