<script lang="ts">
 import {getContext,untrack} from 'svelte';
 import {AUTH_UI_CONTEXT,type AuthUiState} from '$lib/i18n/auth';
 import {Button} from '$lib/components/ui/button';import * as Card from '$lib/components/ui/card';import * as Field from '$lib/components/ui/field';import * as AlertDialog from '$lib/components/ui/alert-dialog';
 import {Input} from '$lib/components/ui/input';import ChoiceSelect from '$lib/components/forms/choice-select.svelte';
 import PageHeader from '$lib/components/shared/page-header.svelte';import LoadingScope from '$lib/components/shared/loading-scope.svelte';import ErrorState from '$lib/components/shared/error-state.svelte';import {formatDateTime} from '$lib/dates';
 const workspace=getContext<{selectedId:string;ready:boolean;revision?:number}>('capybudget-workspaces'),ui=getContext<AuthUiState>(AUTH_UI_CONTEXT);
 const copy=(en:string,id:string)=>ui.locale==='id'?id:en;
 type Member={userId:string;name:string;role:string;createdAt?:string};
 type Invite={id:string;email_snapshot:string;role:string;expiresAt:string;acceptedAt:string|null;revokedAt:string|null;emailState:string};
 type Confirmation={kind:'role'|'remove'|'transfer'|'cancel';ws:string;member?:Member;invitation?:Invite;nextRole?:string};
 let members:Member[]=$state([]),invites:Invite[]=$state([]),loading=$state(false),saving=$state(false),error=$state(''),notice=$state(''),email=$state(''),role=$state('viewer'),inviteUrl=$state(''),accessRole=$state('');
 let draftRoles:Record<string,string>=$state({}),confirmation:Confirmation|null=$state(null),checkedAt=$state(Date.now()),sequence=0;
 const isOwner=$derived(accessRole==='owner');
 const roles=$derived([{value:'accountant',label:copy('Accountant · manage finances','Akuntan · kelola keuangan')},{value:'staff',label:copy('Staff · prepare invoice drafts','Staf · siapkan draf invoice')},{value:'viewer',label:copy('Viewer · view only','Pembaca · hanya lihat')}]);
 const pendingCount=$derived(invites.filter(item=>invitationStatus(item)==='pending').length);
 function roleName(value:string){return value==='owner'?copy('Owner','Pemilik'):value==='accountant'?copy('Accountant','Akuntan'):value==='staff'?copy('Staff','Staf'):value==='viewer'?copy('Viewer','Pembaca'):copy('Unknown role','Peran tidak dikenal');}
 function roleDescription(value:string){
  if(value==='owner')return copy('Manages business finances, business settings, tax settings, payment connections, and team access. Can transfer ownership.','Mengelola keuangan bisnis, pengaturan bisnis, pajak, koneksi pembayaran, dan akses tim. Dapat mengalihkan kepemilikan.');
  if(value==='accountant')return copy('Manages financial records, payments, and reports, and can view the audit trail. Cannot manage team access, change business or tax settings, or manage payment connections.','Mengelola catatan keuangan, pembayaran, dan laporan, serta melihat riwayat audit. Tidak dapat mengelola akses tim, mengubah pengaturan bisnis atau pajak, atau mengelola koneksi pembayaran.');
  if(value==='staff')return copy('Creates and edits their own invoice drafts. Can view customers, vendors, and the product catalog. Cannot finalize or send invoices, record payments, or view accounts and reports.','Membuat dan mengedit draf invoice sendiri. Dapat melihat pelanggan, pemasok, dan katalog produk. Tidak dapat menerbitkan atau mengirim invoice, mencatat pembayaran, atau melihat akun dan laporan.');
  return copy('Views financial information and exports reports. Cannot change financial records or manage team access. The audit trail is limited to owners and accountants.','Melihat informasi keuangan dan mengekspor laporan. Tidak dapat mengubah catatan keuangan atau mengelola akses tim. Riwayat audit hanya untuk pemilik dan akuntan.');
 }
 function invitationStatus(item:Invite){return item.acceptedAt?'accepted':item.revokedAt?'cancelled':new Date(item.expiresAt).getTime()<=checkedAt?'expired':'pending';}
 function statusName(value:string){return value==='accepted'?copy('Invitation accepted','Undangan diterima'):value==='cancelled'?copy('Invitation cancelled','Undangan dibatalkan'):value==='expired'?copy('Invitation expired','Undangan kedaluwarsa'):copy('Waiting to join','Menunggu bergabung');}
 function delivery(item:Invite){
  if(item.emailState==='accepted')return copy('Email accepted by the mail service. Inbox delivery is not confirmed.','Email diterima oleh layanan email. Belum ada konfirmasi bahwa email masuk ke kotak masuk.');
  if(item.emailState==='failed')return copy('Email could not be sent. Create a new invitation to try again.','Email gagal dikirim. Buat undangan baru untuk mencoba lagi.');
  if(item.emailState==='uncertain')return copy('Email delivery is unconfirmed. Share the saved link or create a new invitation.','Pengiriman email belum terkonfirmasi. Bagikan tautan yang tersimpan atau buat undangan baru.');
  if(item.emailState==='not_requested')return copy('No email requested. Share the invitation link directly.','Tidak ada permintaan email. Bagikan tautan undangan secara langsung.');
  if(item.emailState==='sending')return copy('Sending the invitation email.','Sedang mengirim email undangan.');
  if(invitationStatus(item)!=='pending')return copy('This invitation is no longer active; email status does not change team access.','Undangan ini sudah tidak aktif; status email tidak mengubah akses tim.');
  return copy('Email is queued for delivery. Refresh to check its status.','Email dalam antrean pengiriman. Muat ulang untuk melihat statusnya.');
 }
 const endpoint=(ws:string)=>'/api/workspaces/'+ws;
 async function call(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,...(body===undefined?{}:{headers:{'content-type':'application/json'},body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw new Error(result.message??copy('Request failed.','Permintaan gagal.'));return result;}
 async function load(ws:string){const current=++sequence;loading=true;error='';try{const access=await call(endpoint(ws)+'/business-access');if(current!==sequence||ws!==workspace.selectedId)return;accessRole=access.role;if(access.role!=='owner'){members=[];invites=[];return;}const [roster,invitations]=await Promise.all([call(endpoint(ws)+'/members'),call(endpoint(ws)+'/invitations')]);if(current===sequence&&ws===workspace.selectedId){members=roster.items;invites=invitations.items;draftRoles={};checkedAt=Date.now();}}catch(e){if(current===sequence)error=e instanceof Error?e.message:String(e);}finally{if(current===sequence)loading=false;}}
 $effect(()=>{void workspace.revision;if(workspace.ready&&workspace.selectedId){const ws=workspace.selectedId;untrack(()=>{email='';role='viewer';inviteUrl='';notice='';accessRole='';members=[];invites=[];draftRoles={};confirmation=null;void load(ws);});}});
 async function mutate(path:string,method:string,body:unknown,message:string){if(saving||loading)return;const ws=workspace.selectedId;saving=true;error='';notice='';try{const result=await call(endpoint(ws)+path,method,body);if(ws!==workspace.selectedId)return;if(result.url){inviteUrl=result.url;email='';}await load(ws);if(ws===workspace.selectedId)notice=message;}catch(e){if(ws===workspace.selectedId)error=e instanceof Error?e.message:String(e);}finally{saving=false;}}
 function invite(event:SubmitEvent){event.preventDefault();void mutate('/invitations','POST',{email,role,locale:ui.locale},copy('Invitation created. Its email is queued; your teammate gets access after accepting it.','Undangan dibuat. Email dalam antrean; anggota mendapat akses setelah menerimanya.'));}
 function confirmAction(){const target=confirmation;if(!target||target.ws!==workspace.selectedId||saving||loading)return;confirmation=null;
  if(target.kind==='role'&&target.member)void mutate('/members/'+encodeURIComponent(target.member.userId),'PATCH',{role:target.nextRole},copy('Role updated for ','Peran diperbarui untuk ')+target.member.name+'.');
  else if(target.kind==='remove'&&target.member)void mutate('/members/'+encodeURIComponent(target.member.userId),'DELETE',undefined,copy('Business access removed for ','Akses bisnis dihapus untuk ')+target.member.name+'.');
  else if(target.kind==='transfer'&&target.member){inviteUrl='';void mutate('/members/transfer-owner','POST',{userId:target.member.userId,confirm:true},copy('Ownership transferred. Your role is now Accountant.','Kepemilikan dialihkan. Peran Anda sekarang Akuntan.'));}
  else if(target.kind==='cancel'&&target.invitation){inviteUrl='';void mutate('/invitations/'+target.invitation.id,'DELETE',undefined,copy('Invitation cancelled. Its link can no longer be used to join.','Undangan dibatalkan. Tautannya tidak dapat digunakan lagi untuk bergabung.'));}
 }
 async function copyLink(){const ws=workspace.selectedId;try{await navigator.clipboard.writeText(inviteUrl);if(ws===workspace.selectedId)notice=copy('Invitation link copied. Share it only with the invited person.','Tautan undangan disalin. Bagikan hanya kepada penerima undangan.');}catch{if(ws===workspace.selectedId)notice=copy('Select the link below and copy it manually.','Pilih tautan di bawah dan salin secara manual.');}}
 const confirmationTitle=$derived.by(()=>confirmation?.kind==='role'?copy('Change this person’s role?','Ubah peran anggota ini?'):confirmation?.kind==='remove'?copy('Remove business access?','Hapus akses bisnis?'):confirmation?.kind==='transfer'?copy('Transfer business ownership?','Alihkan kepemilikan bisnis?'):copy('Cancel this invitation?','Batalkan undangan ini?'));
</script>

<svelte:head><title>CapyBudget · {copy('Team access','Akses tim')}</title></svelte:head>
<LoadingScope active={loading||saving}/>
<PageHeader guidePath="/business/team" title={copy('Team access','Akses tim')} description={copy('See who can access this business, what they can do, and who is still waiting to join.','Lihat siapa yang memiliki akses bisnis, apa yang dapat mereka lakukan, dan siapa yang masih menunggu bergabung.')}/>
{#if error}<ErrorState title={copy('Could not complete the team request','Permintaan tim gagal diselesaikan')} message={error} onRetry={()=>load(workspace.selectedId)} retryLabel={copy('Reload team','Muat ulang tim')}/>{/if}
<div role="status" aria-live="polite" aria-atomic="true">{#if notice}<p class="mb-6 rounded-[14px] border border-border bg-muted p-4 text-sm leading-relaxed">{notice}</p>{/if}</div>
{#if accessRole}
 <div class="space-y-6">
  <Card.Root><Card.Header><Card.Title>{copy('Your access','Akses Anda')}</Card.Title><Card.Description>{copy('Access applies to this business workspace.','Akses berlaku untuk ruang kerja bisnis ini.')}</Card.Description></Card.Header><Card.Content class="space-y-3"><p class="font-semibold">{roleName(accessRole)}</p><p class="max-w-3xl text-sm leading-relaxed text-muted-foreground">{roleDescription(accessRole)}</p>{#if !isOwner}<p class="text-sm">{copy('Ask the business owner to invite teammates or change your role.','Minta pemilik bisnis untuk mengundang anggota atau mengubah peran Anda.')}</p>{/if}</Card.Content></Card.Root>
  <Card.Root><Card.Header><Card.Title>{copy('What each role can do','Apa yang dapat dilakukan setiap peran')}</Card.Title><Card.Description>{copy('Choose the access someone needs. You can change their role after they join.','Pilih akses yang dibutuhkan. Anda dapat mengubah peran setelah mereka bergabung.')}</Card.Description></Card.Header><Card.Content><dl class="grid gap-4 md:grid-cols-2">{#each ['owner','accountant','staff','viewer'] as name}<div class="space-y-2 rounded-[20px] border-2 border-border bg-muted/40 p-4"><dt class="font-semibold">{roleName(name)}</dt><dd class="text-sm leading-relaxed text-muted-foreground">{roleDescription(name)}</dd></div>{/each}</dl></Card.Content></Card.Root>
  {#if isOwner}
   <div class="grid gap-4 sm:grid-cols-2"><div class="rounded-[20px] border-2 border-border bg-muted/40 p-4"><p class="text-sm text-muted-foreground">{copy('Current members, including the owner','Anggota aktif, termasuk pemilik')}</p><p class="mt-2 text-2xl font-semibold tabular-nums">{members.length}</p></div><div class="rounded-[20px] border-2 border-border bg-muted/40 p-4"><p class="text-sm text-muted-foreground">{copy('Invitations waiting to be accepted','Undangan yang menunggu diterima')}</p><p class="mt-2 text-2xl font-semibold tabular-nums">{pendingCount}</p></div></div>
   <Card.Root><Card.Header><Card.Title>{copy('Invite a teammate','Undang anggota tim')}</Card.Title><Card.Description>{copy('1. Send an invitation. 2. They sign in or register with that email and verify it. 3. They accept to join this business. The link expires after 7 days.','1. Kirim undangan. 2. Penerima masuk atau mendaftar dengan email tersebut dan memverifikasinya. 3. Penerima menerima undangan untuk bergabung. Tautan berlaku selama 7 hari.')}</Card.Description></Card.Header><Card.Content class="space-y-6">
    <form onsubmit={invite} class="space-y-4"><div class="grid gap-4 md:grid-cols-2"><Field.Field><Field.FieldLabel for="invite-email">{copy('Teammate’s email','Email anggota')}</Field.FieldLabel><Input id="invite-email" type="email" autocomplete="email" bind:value={email} required maxlength={320} disabled={loading||saving} aria-describedby="invite-email-help"/><p id="invite-email-help" class="text-sm text-muted-foreground">{copy('They must use this exact email to accept the invitation.','Penerima harus menggunakan email ini untuk menerima undangan.')}</p></Field.Field><Field.Field><Field.FieldLabel for="invite-role">{copy('Access level','Tingkat akses')}</Field.FieldLabel><ChoiceSelect id="invite-role" bind:value={role} items={roles} disabled={loading||saving} aria-describedby="invite-role-help"/></Field.Field></div>
     <div id="invite-role-help" class="space-y-2 rounded-[14px] border border-border bg-muted/40 p-4" aria-live="polite"><p class="text-sm font-semibold">{roleName(role)}</p><p class="text-sm leading-relaxed text-muted-foreground">{roleDescription(role)}</p></div><Button type="submit" disabled={loading||saving||!email.trim()}>{copy('Send invitation','Kirim undangan')}</Button>
    </form>
    {#if inviteUrl}<div class="space-y-3 rounded-[20px] border-2 border-border p-4"><Field.Field><Field.FieldLabel for="invite-link">{copy('Invitation link','Tautan undangan')}</Field.FieldLabel><Input id="invite-link" readonly value={inviteUrl} onclick={event=>event.currentTarget.select()} aria-describedby="invite-link-help"/></Field.Field><p id="invite-link-help" class="text-sm leading-relaxed text-muted-foreground">{copy('The email is queued. You can also share this link with the invited person. Sending them a new invitation replaces their previous link.','Email dalam antrean. Anda juga dapat membagikan tautan ini kepada penerima. Mengirim undangan baru kepada orang yang sama mengganti tautan sebelumnya.')}</p><Button variant="outline" onclick={copyLink}>{copy('Copy invitation link','Salin tautan undangan')}</Button></div>{/if}
   </Card.Content></Card.Root>
   <Card.Root><Card.Header><div class="flex flex-wrap items-center justify-between gap-4"><Card.Title>{copy('Current members','Anggota aktif')}</Card.Title><Button variant="outline" disabled={saving||loading} onclick={()=>load(workspace.selectedId)}>{copy('Refresh status','Muat ulang status')}</Button></div><Card.Description>{copy('These people already have access. Changing a role changes their permissions; removing access keeps their existing business records.','Orang-orang ini sudah memiliki akses. Mengubah peran mengubah izin mereka; menghapus akses tetap menyimpan catatan bisnis yang sudah ada.')}</Card.Description></Card.Header><Card.Content><ul class="divide-y divide-border">{#each members as member(member.userId)}<li class="space-y-4 py-6 first:pt-0 last:pb-0"><div class="space-y-2"><h2 class="break-words text-base font-semibold">{member.name}</h2><p class="inline-flex rounded-full border border-border bg-muted px-3 py-1 text-sm font-semibold">{roleName(member.role)}</p><p class="max-w-3xl text-sm leading-relaxed text-muted-foreground">{roleDescription(member.role)}</p>{#if member.createdAt}<p class="text-sm text-muted-foreground">{copy('Joined: ','Bergabung: ')}{formatDateTime(member.createdAt,ui.locale)}</p>{/if}</div>
    {#if member.role!=='owner'}<div class="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-end"><Field.Field><Field.FieldLabel for={'member-role-'+member.userId}>{copy('Access level for ','Tingkat akses untuk ')+member.name}</Field.FieldLabel><ChoiceSelect id={'member-role-'+member.userId} value={draftRoles[member.userId]??member.role} items={roles} disabled={saving||loading} onValueChange={value=>{draftRoles[member.userId]=String(value);}}/></Field.Field><Button variant="outline" disabled={saving||loading||!draftRoles[member.userId]||draftRoles[member.userId]===member.role} onclick={()=>confirmation={kind:'role',ws:workspace.selectedId,member,nextRole:draftRoles[member.userId]}}>{copy('Save role','Simpan peran')}</Button><Button variant="outline" disabled={saving||loading} aria-label={copy('Remove business access for ','Hapus akses bisnis untuk ')+member.name} onclick={()=>confirmation={kind:'remove',ws:workspace.selectedId,member}}>{copy('Remove access','Hapus akses')}</Button></div>
     {#if draftRoles[member.userId]&&draftRoles[member.userId]!==member.role}<p class="text-sm text-muted-foreground">{copy('Not saved yet. New access: ','Belum disimpan. Akses baru: ')}{roleDescription(draftRoles[member.userId])}</p>{/if}
     <details class="rounded-[14px] border border-border"><summary class="min-h-11 cursor-pointer rounded-[14px] px-4 py-3 text-sm text-muted-foreground focus-visible:outline-2 focus-visible:outline-ring">{copy('Ownership options','Opsi kepemilikan')}</summary><div class="space-y-3 px-4 pb-4"><p class="text-sm leading-relaxed text-muted-foreground">{copy('Make this person the business owner. You will become an accountant and lose access to team management and owner settings.','Jadikan anggota ini pemilik bisnis. Anda akan menjadi akuntan dan kehilangan akses untuk mengelola tim serta pengaturan pemilik.')}</p><Button variant="outline" disabled={saving||loading} aria-label={copy('Transfer ownership to ','Alihkan kepemilikan kepada ')+member.name} onclick={()=>confirmation={kind:'transfer',ws:workspace.selectedId,member}}>{copy('Transfer ownership','Alihkan kepemilikan')}</Button></div></details>
    {:else}<p class="text-sm text-muted-foreground">{copy('The owner’s role changes only through an ownership transfer.','Peran pemilik hanya dapat diubah melalui pengalihan kepemilikan.')}</p>{/if}
   </li>{/each}</ul></Card.Content></Card.Root>
   <Card.Root><Card.Header><Card.Title>{copy('Invitation history','Riwayat undangan')}</Card.Title><Card.Description>{copy('An accepted invitation records that someone joined at that time. Check Current members for who has access now. Email delivery is shown separately. Showing the latest 100 invitations.','Undangan yang diterima mencatat bahwa seseorang bergabung pada saat itu. Lihat Anggota aktif untuk mengetahui siapa yang masih memiliki akses. Status pengiriman email ditampilkan terpisah. Menampilkan 100 undangan terakhir.')}</Card.Description></Card.Header><Card.Content>
    {#if !invites.length}<div class="space-y-2 rounded-[20px] border-2 border-border bg-muted/40 p-4"><p class="font-semibold">{copy('No invitations yet','Belum ada undangan')}</p><p class="text-sm text-muted-foreground">{copy('Use the invitation form above when you are ready to share this business.','Gunakan formulir undangan di atas saat Anda siap membagikan akses bisnis.')}</p></div>{/if}
    <ul class="divide-y divide-border">{#each invites as item(item.id)}{@const status=invitationStatus(item)}<li class="space-y-3 py-6 first:pt-0 last:pb-0"><div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0 space-y-2"><h2 class="break-all text-base font-semibold">{item.email_snapshot}</h2><p class="text-sm text-muted-foreground">{copy('Invited as: ','Diundang sebagai: ')}{roleName(item.role)}</p><p class="inline-flex rounded-full border border-border bg-muted px-3 py-1 text-sm font-semibold">{statusName(status)}</p></div>{#if status==='pending'}<Button variant="outline" disabled={saving||loading} aria-label={copy('Cancel invitation for ','Batalkan undangan untuk ')+item.email_snapshot} onclick={()=>confirmation={kind:'cancel',ws:workspace.selectedId,invitation:item}}>{copy('Cancel invitation','Batalkan undangan')}</Button>{/if}</div>
     <dl class="grid gap-3 rounded-[14px] border border-border bg-muted/40 p-4 sm:grid-cols-2"><div class="space-y-1"><dt class="text-sm font-semibold">{status==='accepted'?copy('Accepted on','Diterima pada'):status==='cancelled'?copy('Cancelled on','Dibatalkan pada'):copy('Link expires','Tautan kedaluwarsa')}</dt><dd class="text-sm text-muted-foreground">{formatDateTime(item.acceptedAt??item.revokedAt??item.expiresAt,ui.locale)}</dd></div><div class="space-y-1"><dt class="text-sm font-semibold">{copy('Invitation email','Email undangan')}</dt><dd class="text-sm leading-relaxed text-muted-foreground">{delivery(item)}</dd></div></dl>
     {#if status==='expired'||status==='cancelled'}<p class="text-sm text-muted-foreground">{copy('This link cannot be used to join. Create a new invitation above if access is still needed.','Tautan ini tidak dapat digunakan untuk bergabung. Buat undangan baru di atas jika akses masih diperlukan.')}</p>{/if}
    </li>{/each}</ul>
   </Card.Content></Card.Root>
  {/if}
 </div>
{/if}
<AlertDialog.Root open={!!confirmation} onOpenChange={open=>{if(!open&&!saving)confirmation=null;}}>
 <AlertDialog.Content class="max-h-[85dvh] overflow-y-auto sm:max-w-lg"><AlertDialog.Header><AlertDialog.Title>{confirmationTitle}</AlertDialog.Title><AlertDialog.Description>
  {#if confirmation?.kind==='role'}{copy('Change access for ','Ubah akses untuk ')}{confirmation.member?.name}{copy(' from ',' dari ')}{roleName(confirmation.member?.role??'')}{copy(' to ',' menjadi ')}{roleName(confirmation.nextRole??'')}. {roleDescription(confirmation.nextRole??'')}
  {:else if confirmation?.kind==='remove'}{confirmation.member?.name}{copy(' will lose access to this business. Their account and existing business records will remain. You can invite them again later.',' akan kehilangan akses ke bisnis ini. Akun dan catatan bisnis yang sudah ada tetap tersimpan. Anda dapat mengundangnya lagi nanti.')}
  {:else if confirmation?.kind==='transfer'}{copy('Make ','Jadikan ')}{confirmation.member?.name}{copy(' the owner of this business. You will become an accountant and will no longer manage team access, business settings, tax settings, or payment connections. Only the new owner can transfer ownership back to you.',' pemilik bisnis ini. Anda akan menjadi akuntan dan tidak lagi mengelola akses tim, pengaturan bisnis, pajak, atau koneksi pembayaran. Hanya pemilik baru yang dapat mengalihkan kepemilikan kembali kepada Anda.')}
  {:else}{copy('Cancel the invitation for ','Batalkan undangan untuk ')}{confirmation?.invitation?.email_snapshot}{copy('? Its link will stop working. You can create a new invitation later.','? Tautannya tidak akan berlaku lagi. Anda dapat membuat undangan baru nanti.')}{/if}
 </AlertDialog.Description></AlertDialog.Header><AlertDialog.Footer><AlertDialog.Cancel disabled={saving} onclick={()=>confirmation=null}>{copy('Keep as is','Biarkan tetap')}</AlertDialog.Cancel><Button disabled={saving||loading} onclick={confirmAction}>{confirmation?.kind==='transfer'?copy('Transfer ownership','Alihkan kepemilikan'):confirmation?.kind==='remove'?copy('Remove access','Hapus akses'):confirmation?.kind==='role'?copy('Confirm role change','Konfirmasi perubahan peran'):copy('Cancel invitation','Batalkan undangan')}</Button></AlertDialog.Footer></AlertDialog.Content>
</AlertDialog.Root>
